import {ensureVpageCreateSchema} from '../../../_vpage-create-schema.js';
import {currentUser} from '../../../_lib.js';
import {committedVpageMedia,ownedVpageMedia,reconcilePendingVpageMedia,reconcileVpageMediaActiveSet,validVpageMediaId} from '../../../_vpage-media.js';
import {deleteRemoteVpageMedia,VpageRemoteError} from '../../../_vpage-provisioning.js';

const missing=()=>new Response('Not found',{status:404,headers:{'cache-control':'private, no-store','x-content-type-options':'nosniff'}});
async function serve(ctx,head=false){
  const id=String(ctx.params?.id||'');if(!validVpageMediaId(id)||!ctx.env.FILES)return missing();
  let row=await committedVpageMedia(ctx.env,id);if(!row){const user=await currentUser(ctx,{includeCourseOwner:false});if(user){await ensureVpageCreateSchema(ctx.env);row=await ownedVpageMedia(ctx.env,id,user.id);if(!row)row=await ctx.env.DB.prepare("SELECT object_key,mime_type,file_size,content_hash FROM vpage_owner_assets WHERE id=? AND owner_id=? AND state='ready' LIMIT 1").bind(id,user.id).first()}}if(!row){await reconcilePendingVpageMedia(ctx.env,id,new URL(ctx.request.url).origin);await reconcileVpageMediaActiveSet(ctx.env,id);row=await committedVpageMedia(ctx.env,id)}if(!row)return missing();
  const object=head?await ctx.env.FILES.head(row.object_key):await ctx.env.FILES.get(row.object_key);if(!object||Number(object.size)!==Number(row.file_size)||object.customMetadata?.sha256!==row.content_hash||object.httpMetadata?.contentType!==row.mime_type)return missing();const headers=new Headers({'content-type':row.mime_type,'content-length':String(row.file_size),'cache-control':'private, no-store','x-content-type-options':'nosniff','cross-origin-resource-policy':'cross-origin'});if(object.httpEtag)headers.set('etag',object.httpEtag);return new Response(head?null:object.body,{status:200,headers});
}
export const onRequestGet=ctx=>serve(ctx,false);
export const onRequestHead=ctx=>serve(ctx,true);
export async function onRequestDelete(ctx){
  const id=String(ctx.params?.id||'');if(!validVpageMediaId(id))return missing();
  const user=await currentUser(ctx,{includeCourseOwner:false});if(!user)return new Response('Unauthorized',{status:401,headers:{'cache-control':'private, no-store'}});
  if(!ctx.env.FILES)return new Response('Media storage unavailable',{status:503,headers:{'cache-control':'private, no-store'}});
  await ensureVpageCreateSchema(ctx.env);
  const row=await ctx.env.DB.prepare('SELECT id,object_key,state FROM vpage_owner_assets WHERE id=? AND owner_id=? LIMIT 1').bind(id,user.id).first();if(!row)return missing();
  if(row.state==='deleted')return new Response(JSON.stringify({ok:true,id,replayed:true}),{headers:{'content-type':'application/json','cache-control':'private, no-store'}});
  if(row.state!=='deleting'){try{const used=await ctx.env.DB.prepare('SELECT 1 FROM vpage_create_draft_refs WHERE media_id=? LIMIT 1').bind(id).first();if(used)return new Response(JSON.stringify({error:'รูปนี้ยังถูกใช้ในร่าง กรุณาเอารูปออกและเซฟร่างก่อนลบ',code:'VPAGE_MEDIA_DRAFT_IN_USE'}),{status:409,headers:{'content-type':'application/json','cache-control':'private, no-store'}});const result=await ctx.env.DB.prepare("UPDATE vpage_owner_assets SET state='deleting',updated_at=CURRENT_TIMESTAMP WHERE id=? AND owner_id=? AND state IN ('pending','ready')").bind(id,user.id).run();if(!result.meta?.changes)return new Response(JSON.stringify({error:'รูปนี้กำลังถูกแก้ไข กรุณาลองใหม่'}),{status:409,headers:{'content-type':'application/json','cache-control':'private, no-store'}})}catch(error){const draftRace=String(error?.message||error).includes('vpage media in draft');return new Response(JSON.stringify({error:draftRace?'รูปนี้ยังถูกใช้ในร่าง กรุณาเอารูปออกและเซฟร่างก่อนลบ':'ตรวจสอบคลังรูปไม่สำเร็จ',code:draftRace?'VPAGE_MEDIA_DRAFT_IN_USE':'VPAGE_MEDIA_STORAGE_FAILED'}),{status:draftRace?409:503,headers:{'content-type':'application/json','cache-control':'private, no-store'}})}}
  try{await deleteRemoteVpageMedia(ctx.env,{userId:user.id,id})}catch(error){if(error instanceof VpageRemoteError&&error.status===404&&error.code==='VPAGE_MEDIA_NOT_FOUND'){/* already absent; finish local cleanup */}else{if(!error?.ambiguous&&row.state!=='deleting')await ctx.env.DB.prepare("UPDATE vpage_owner_assets SET state=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND owner_id=? AND state='deleting'").bind(row.state,id,user.id).run().catch(()=>{});return new Response(JSON.stringify({error:error instanceof VpageRemoteError?error.message:'ลบรูปไม่สำเร็จ',code:error?.code||'VPAGE_MEDIA_DELETE_FAILED'}),{status:Number(error?.status)||502,headers:{'content-type':'application/json','cache-control':'private, no-store'}})}}
  try{await ctx.env.FILES.delete(row.object_key);await ctx.env.DB.prepare("UPDATE vpage_owner_assets SET state='deleted',updated_at=CURRENT_TIMESTAMP WHERE id=? AND owner_id=? AND state='deleting'").bind(id,user.id).run();return new Response(JSON.stringify({ok:true,id,replayed:false}),{headers:{'content-type':'application/json','cache-control':'private, no-store'}})}catch{return new Response(JSON.stringify({error:'ต้องลบรูปใน VisionD อีกครั้ง',code:'VPAGE_MEDIA_LOCAL_DELETE_UNCERTAIN'}),{status:502,headers:{'content-type':'application/json','cache-control':'private, no-store'}})}
}
