import {json,requireBoss} from '../../../_lib.js';
import {ensureDatabase} from '../../../_schema.js';
import {encryptPartnerSecret,partnerEncryptionReady} from '../../../_partner_crypto.js';
import {cleanScopes,ensurePartnerSchema,newPartnerCredential,partnerSecretHash,PARTNER_SCOPES} from '../../../_partner_api.js';
const headers={'cache-control':'private, no-store'},clean=(v,n=180)=>String(v||'').trim().slice(0,n);
async function auth(ctx){await ensureDatabase(ctx.env);await ensurePartnerSchema(ctx.env);const value=await requireBoss(ctx);return value.error?{error:value.error}:value}
const domainValue=value=>{try{const url=new URL(String(value||''));return url.protocol==='https:'&&url.hostname&&url.pathname==='/'?url.origin:''}catch{return ''}};
export async function onRequestGet(ctx){const a=await auth(ctx);if(a.error)return a.error;const items=(await ctx.env.DB.prepare(`SELECT w.id,w.name,w.domain,w.status,w.scopes,w.client_id,w.secret_last4,w.created_at,w.updated_at,w.last_used_at,w.revoked_at,u.name created_by_name,(SELECT COUNT(*) FROM partner_api_audit x WHERE x.website_id=w.id) request_count FROM partner_websites w LEFT JOIN users u ON u.id=w.created_by ORDER BY w.created_at DESC`).all()).results||[];return json({encryption_ready:partnerEncryptionReady(ctx.env),available_scopes:PARTNER_SCOPES,items:items.map(item=>({...item,scopes:JSON.parse(item.scopes||'[]'),credential_display:`${item.client_id} / ••••${item.secret_last4}`}))},200,headers)}
export async function onRequestPost(ctx){const a=await auth(ctx);if(a.error)return a.error;if(!partnerEncryptionReady(ctx.env))return json({error:'ยังไม่ได้ตั้ง VISIOND_PARTNER_ENCRYPTION_KEY หรือ VISIOND_CHANNEL_ENCRYPTION_KEY ใน Cloudflare',code:'PARTNER_ENCRYPTION_NOT_CONFIGURED'},503,headers);const body=await ctx.request.json().catch(()=>({})),name=clean(body.name),domain=domainValue(body.domain),status=['draft','active','paused'].includes(body.status)?body.status:'draft',scopes=cleanScopes(body.scopes);if(name.length<2||!domain||!scopes.length)return json({error:'กรุณากรอกชื่อ, HTTPS Domain และเลือก Scope อย่างน้อย 1 รายการ'},400,headers);const id=`site_${crypto.randomUUID().replaceAll('-','')}`,credential=newPartnerCredential();try{await ctx.env.DB.prepare('INSERT INTO partner_websites(id,name,domain,status,scopes,client_id,secret_ciphertext,secret_hash,secret_last4,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,name,domain,status,JSON.stringify(scopes),credential.clientId,await encryptPartnerSecret(ctx.env,credential.secret),await partnerSecretHash(credential.clientId,credential.secret),credential.secret.slice(-4),a.user.id).run();return json({ok:true,item:{id,name,domain,status,scopes,client_id:credential.clientId},credential:{client_id:credential.clientId,client_secret:credential.secret,shown_once:true}},201,headers)}catch(error){return json({error:String(error).includes('UNIQUE')?'Domain นี้ถูกลงทะเบียนแล้ว':'สร้างเว็บไซต์คู่ค้าไม่สำเร็จ'},400,headers)}}
