import { json, requireAdmin } from '../../../../../_lib.js';
import { ensureDatabase } from '../../../../../_schema.js';
import { MAX_COURSE_VIDEO_BYTES } from '../../../../../_course_rules.js';

const extension=(name,type)=>String(name||'').split('.').pop()?.toLowerCase()||({"video/mp4":'mp4',"video/webm":'webm',"application/pdf":'pdf',"image/jpeg":'jpg',"image/png":'png'}[type]||'bin');
async function companyCourse(ctx){return ctx.env.DB.prepare("SELECT id FROM courses WHERE id=? AND owner_user_id IS NULL AND COALESCE(course_origin,'company')='company' AND course_type='online_course'").bind(ctx.params.id).first();}
async function syncCourseMinutes(env,courseId){await env.DB.prepare('UPDATE courses SET total_minutes=CAST((COALESCE((SELECT SUM(duration_seconds) FROM course_lessons WHERE course_id=?),0)+59)/60 AS INTEGER),updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(courseId,courseId).run();}

export async function onRequestPost(ctx){
  await ensureDatabase(ctx.env);const auth=await requireAdmin(ctx);if(auth.error)return auth.error;const course=await companyCourse(ctx);if(!course)return json({error:'คอร์ส Vision 5 ต้องจัดการบทเรียนผ่านหน้าของเจ้าของคอร์สเท่านั้น'},403);const lesson=await ctx.env.DB.prepare('SELECT * FROM course_lessons WHERE id=? AND course_id=?').bind(ctx.params.lessonId,course.id).first();if(!lesson)return json({error:'ไม่พบบทเรียน'},404);
  const form=await ctx.request.formData(),title=String(form.get('title')||'').trim(),episodeLabel=String(form.get('episode_label')||'').trim(),video=form.get('video'),pdf=form.get('pdf'),durationProvided=form.has('duration_minutes'),rawDuration=durationProvided?Number(form.get('duration_minutes')):Number(lesson.duration_seconds)/60,durationSeconds=Number.isFinite(rawDuration)&&rawDuration>=0&&rawDuration<=100000?Math.round(rawDuration*60):Number(lesson.duration_seconds)||0;if(!title)return json({error:'กรุณาใส่ชื่อบทเรียน'},400);if((episodeLabel&&!/^\d+(?:\.\d+)*$/.test(episodeLabel))||episodeLabel.length>20)return json({error:'เลข EP ใช้ตัวเลขและจุดเท่านั้น เช่น 1, 1.1 หรือ 1.2'},400);if(durationProvided&&(!Number.isFinite(rawDuration)||rawDuration<0||rawDuration>100000))return json({error:'ความยาว EP ไม่ถูกต้อง'},400);let videoKey=null,pdfKey=null;
  if(video?.size){if(!['video/mp4','video/webm'].includes(video.type)||video.size>MAX_COURSE_VIDEO_BYTES)return json({error:'คลิปต้องเป็น MP4 หรือ WEBM ไม่เกิน 2 GB'},400);videoKey=`course-${course.id}-video-${crypto.randomUUID()}.${extension(video.name,video.type)}`;await ctx.env.FILES.put(videoKey,video.stream(),{httpMetadata:{contentType:video.type}});}
  if(pdf?.size){if(!['application/pdf','image/jpeg','image/png'].includes(pdf.type)||pdf.size>100*1024*1024){if(videoKey)await ctx.env.FILES.delete(videoKey);return json({error:'เอกสารต้องเป็น PDF, JPEG หรือ PNG ไม่เกิน 100 MB'},400);}pdfKey=`course-${course.id}-document-${crypto.randomUUID()}.${extension(pdf.name,pdf.type)}`;try{await ctx.env.FILES.put(pdfKey,pdf.stream(),{httpMetadata:{contentType:pdf.type}})}catch(error){if(videoKey)await ctx.env.FILES.delete(videoKey);throw error}}
  try{await ctx.env.DB.prepare(`UPDATE course_lessons SET title=?,description=?,episode_label=?,duration_seconds=?,video_key=COALESCE(?,video_key),pdf_key=COALESCE(?,pdf_key),video_mime=COALESCE(?,video_mime),pdf_mime=COALESCE(?,pdf_mime),document_name=CASE WHEN ? IS NULL THEN document_name ELSE ? END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND course_id=?`).bind(title,String(form.get('description')||''),episodeLabel||null,durationSeconds,videoKey,pdfKey,videoKey?video.type:null,pdfKey?pdf.type:null,pdfKey,pdfKey?String(pdf.name||'document').slice(0,240):null,lesson.id,course.id).run();await syncCourseMinutes(ctx.env,course.id)}catch(error){if(videoKey)await ctx.env.FILES.delete(videoKey).catch(()=>{});if(pdfKey)await ctx.env.FILES.delete(pdfKey).catch(()=>{});return json({error:'บันทึกร่าง EP ไม่สำเร็จ'},500)}
  if(videoKey&&lesson.video_key)await ctx.env.FILES.delete(lesson.video_key).catch(()=>{});if(pdfKey&&lesson.pdf_key)await ctx.env.FILES.delete(lesson.pdf_key).catch(()=>{});return json({ok:true,id:lesson.id,status:(videoKey||lesson.video_key||pdfKey||lesson.pdf_key)?'ready':'draft'});
}

export async function onRequestDelete(ctx){await ensureDatabase(ctx.env);const auth=await requireAdmin(ctx);if(auth.error)return auth.error;const course=await companyCourse(ctx);if(!course)return json({error:'คอร์ส Vision 5 ต้องจัดการบทเรียนผ่านหน้าของเจ้าของคอร์สเท่านั้น'},403);const lesson=await ctx.env.DB.prepare('SELECT * FROM course_lessons WHERE id=? AND course_id=?').bind(ctx.params.lessonId,course.id).first();if(!lesson)return json({error:'ไม่พบบทเรียน'},404);try{await ctx.env.DB.prepare('DELETE FROM course_lessons WHERE id=? AND course_id=?').bind(lesson.id,course.id).run();await syncCourseMinutes(ctx.env,course.id)}catch(error){return json({error:'ลบบทเรียนไม่สำเร็จ กรุณาลองใหม่'},500)}if(lesson.video_key)await ctx.env.FILES.delete(lesson.video_key).catch(()=>{});if(lesson.pdf_key)await ctx.env.FILES.delete(lesson.pdf_key).catch(()=>{});return json({ok:true});}
