import {json,requireAdmin} from '../../../_lib.js';
import {ensureCatalogProducts} from '../../../_catalog.js';
import {ensureDatabase} from '../../../_schema.js';
const ext=(name,type)=>type==='image/png'?'png':type==='image/webp'?'webp':type==='application/zip'?'zip':name?.toLowerCase().endsWith('.zip')?'zip':type==='application/pdf'?'pdf':'jpg';
const validFile=(file,max,types)=>file&&typeof file.arrayBuffer==='function'&&file.size>0&&file.size<=max&&(types.includes(file.type)||(types.includes('application/zip')&&/\.zip$/i.test(file.name||''))||(types.includes('application/pdf')&&/\.pdf$/i.test(file.name||'')));

export async function onRequestGet(ctx){await ensureDatabase(ctx.env);const a=await requireAdmin(ctx);if(a.error)return a.error;await ensureCatalogProducts(ctx.env);const vision4=new URL(ctx.request.url).searchParams.get('queue')==='vision4',extra=vision4?"AND p.source='vision4' AND p.status='draft'":"AND NOT(p.source='vision4' AND p.status='draft')";const {results}=await ctx.env.DB.prepare(`SELECT p.*,(SELECT COUNT(*) FROM product_files own WHERE own.product_id=p.id)+(SELECT COUNT(*) FROM product_bundle_items b JOIN product_files bf ON bf.product_id=b.source_product_id WHERE b.bundle_product_id=p.id) file_count,(SELECT own.id FROM product_files own WHERE own.product_id=p.id ORDER BY own.id DESC LIMIT 1) latest_file_id,(SELECT own.mime_type FROM product_files own WHERE own.product_id=p.id ORDER BY own.id DESC LIMIT 1) latest_file_mime,(SELECT a.bundle_product_id FROM bundle_source_allocations a WHERE a.source_product_id=p.id) bundled_into_id,(SELECT bp.title FROM bundle_source_allocations a JOIN products bp ON bp.id=a.bundle_product_id WHERE a.source_product_id=p.id) bundled_into_title FROM products p WHERE p.deleted_at IS NULL AND COALESCE(p.product_kind,'product')='product' AND (p.slug='course-selling-rights' OR (p.category<>'resale-rights' AND NOT EXISTS(SELECT 1 FROM courses c WHERE c.product_id=p.id AND (c.owner_user_id IS NOT NULL OR c.course_origin='seller_rights' OR c.course_type='resale_rights')))) ${extra} ORDER BY p.id DESC`).all();return json({items:results})}

const bundleIds=form=>[...new Set(String(form.get('bundle_product_ids')||'').split(',').map(Number).filter(Number.isInteger))];
const bundleSourceCategory=category=>{const value=String(category||'');if(!/^set-[a-z0-9][a-z0-9-]{0,75}$/.test(value))throw new Error('กรุณาเลือกหมวดชุดรวมที่ถูกต้อง');const source=value.slice(4);if(!source||source.startsWith('set-')||source==='resale-rights')throw new Error('หมวดนี้ไม่สามารถสร้างชุดรวมได้');return source};
async function ensureBundleCategory(env,category,sourceCategory){const source=await env.DB.prepare('SELECT name FROM categories WHERE slug=? AND active=1').bind(sourceCategory).first();if(!source)throw new Error('ไม่พบหมวดต้นทางที่เปิดใช้งาน');await env.DB.prepare("INSERT OR IGNORE INTO categories(slug,name,parent_slug,file_type,active,sort_order) VALUES(?,?,NULL,'ชุด PDF',1,900)").bind(category,`ชุดรวม ${source.name||sourceCategory}`).run()}
async function validateBundle(env,form,category){const ids=bundleIds(form),size=Number(form.get('bundle_size')),previewCount=Number(form.get('bundle_preview_count'))||ids.length;if(form.get('bundle_mode')!=='1')return null;const promotion=category==='bundle-deals',sourceCategory=promotion?'':bundleSourceCategory(category);if(!Number.isInteger(size)||size<2||size>30||ids.length!==size)throw new Error(`กรุณาเลือกตะกร้าให้ครบ ${size||2} รายการ`);const marks=ids.map(()=>'?').join(','),categoryClause=promotion?"p.category IN ('worksheet','coloring','development-game')":'p.category=?',bindings=promotion?ids:[...ids,sourceCategory],{results}=await env.DB.prepare(`SELECT id,title,price,pages,cover_url,preview_urls FROM products p WHERE id IN (${marks}) AND status='published' AND deleted_at IS NULL AND ${categoryClause} AND COALESCE(product_kind,'product')='product' AND NOT EXISTS(SELECT 1 FROM courses c WHERE c.product_id=p.id AND (c.owner_user_id IS NOT NULL OR c.course_origin='seller_rights' OR c.course_type='resale_rights')) AND NOT EXISTS(SELECT 1 FROM bundle_source_allocations a WHERE a.source_product_id=p.id)`).bind(...bindings).all();if(results.length!==ids.length)throw new Error(promotion?'โปรยกชุดเลือกได้เฉพาะแบบฝึกหัด ระบายสี และเกมเสริมพัฒนาการที่พร้อมขาย':'มีตะกร้าต้นทางผิดหมวด ไม่พร้อมขาย หรือเคยรวมชุดแล้ว กรุณาเลือกใหม่');if(promotion){const target=await env.DB.prepare("SELECT slug FROM categories WHERE slug='bundle-deals' AND active=1").first();if(!target)throw new Error('หมวดโปรยกชุดยังไม่เปิดใช้งาน')}else await ensureBundleCategory(env,category,sourceCategory);const byId=new Map(results.map(item=>[Number(item.id),item])),ordered=ids.map(id=>byId.get(id)),allowed=new Set(ordered.flatMap(item=>{let extra=[];try{extra=JSON.parse(item.preview_urls||'[]')}catch{}return [item.cover_url,...(Array.isArray(extra)?extra:[])]}).filter(Boolean));let requested=[];try{requested=JSON.parse(String(form.get('bundle_preview_urls')||'[]'))}catch{}if(!Array.isArray(requested)||!requested.length)throw new Error('กรุณาตรวจและเลือกรูปตัวอย่างตะกร้ารวมอย่างน้อย 1 รูป');const previews=[...new Set(requested.map(String))].slice(0,Math.max(1,Math.min(previewCount,30)));if(previews.some(url=>!allowed.has(url)))throw new Error('รูปตัวอย่างต้องมาจากตะกร้าที่เลือกในชุดนี้เท่านั้น');return {ids,size,previews,normalPrice:ordered.reduce((sum,item)=>sum+Number(item.price||0),0),pages:ordered.reduce((sum,item)=>sum+Number(item.pages||0),0)}}
async function saveBundle(env,productId,bundle){if(!bundle)return;await env.DB.prepare('DELETE FROM product_bundle_items WHERE bundle_product_id=?').bind(productId).run();for(let index=0;index<bundle.ids.length;index++){await env.DB.prepare('INSERT INTO bundle_source_allocations(source_product_id,bundle_product_id) VALUES(?,?)').bind(bundle.ids[index],productId).run();await env.DB.prepare('INSERT INTO product_bundle_items(bundle_product_id,source_product_id,sort_order) VALUES(?,?,?)').bind(productId,bundle.ids[index],index).run()}const cover=bundle.previews[0]||'/assets/product-placeholder.svg';await env.DB.prepare('UPDATE products SET cover_url=?,preview_urls=?,pages=? WHERE id=?').bind(cover,JSON.stringify(bundle.previews),bundle.pages,productId).run()}

async function nextProductSlug(env,category,customPrefix=''){
  const prefix=customPrefix||`${category}-`,current=await env.DB.prepare('SELECT slug FROM products WHERE category=? AND slug LIKE ?').bind(category,`${prefix}%`).all(),history=await env.DB.prepare('SELECT old_slug slug FROM product_slug_history WHERE old_slug LIKE ?').bind(`${prefix}%`).all();
  let next=[...(current.results||[]),...(history.results||[])].reduce((max,row)=>Math.max(max,Number(String(row.slug||'').slice(prefix.length))||0),0)+1,slug='';
  do{slug=`${prefix}${String(next++).padStart(3,'0')}`}while(await env.DB.prepare('SELECT id FROM products WHERE slug=?').bind(slug).first());
  return slug;
}

export async function onRequestPost(ctx){await ensureDatabase(ctx.env);const a=await requireAdmin(ctx);if(a.error)return a.error;const form=await ctx.request.formData(),requestedSource=String(form.get('source')||''),paperDollSet=requestedSource==='paper_doll_set',submittedTitle=String(form.get('title')||'').trim(),price=Number(form.get('price_cents')),pages=Math.max(0,Math.floor(Number(form.get('pages'))||0)),category=paperDollSet?'paper-doll':String(form.get('category')||'').trim(),requestedFileType=String(form.get('file_type')||'PDF'),fileType=paperDollSet?'PDF':['PDF','ZIP','JPG/PNG','ชุดรวมหลายประเภท'].includes(requestedFileType)?requestedFileType:'PDF';if((!submittedTitle&&!paperDollSet)||!category)return json({error:'กรุณากรอกชื่อสินค้าและเลือกหมวดหมู่'},400);if(category==='resale-rights')return json({error:'ตะกร้าสิทธิ์ Vision 5 ต้องจัดการผ่านระบบ Vision 5 เท่านั้น'},403);if(!Number.isInteger(price)||price<0)return json({error:'ราคาไม่ถูกต้อง'},400);try{const bundle=await validateBundle(ctx.env,form,category),slug=await nextProductSlug(ctx.env,category,paperDollSet?'paper-doll-set-':''),setNumber=Number(slug.slice('paper-doll-set-'.length))||0,title=paperDollSet?`ตุ๊กตากระดาษชุดที่ ${setNumber}`:submittedTitle,duplicate=await ctx.env.DB.prepare('SELECT id,title FROM products WHERE lower(trim(title))=lower(trim(?)) AND deleted_at IS NULL LIMIT 1').bind(title).first();if(duplicate)return json({error:`ชื่อสินค้า “${duplicate.title}” มีอยู่แล้ว กรุณาใช้ชื่ออื่น`},409);const source=bundle?'bundle':paperDollSet?'paper_doll_set':requestedSource==='vision4'?'vision4':'admin',description=String(form.get('description')||'')||(bundle?`ชุดรวม ${bundle.size} ตะกร้า · ราคาปกติรวม ${(bundle.normalPrice/100).toFixed(2)} บาท · รวม ${bundle.pages} หน้า`:''),row=await ctx.env.DB.prepare(`INSERT INTO products(slug,title,short_description,description,price,cover_url,category,file_type,pages,status,source,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) RETURNING *`).bind(slug,title,String(form.get('short_description')||''),description,price,'/assets/product-placeholder.svg',category,fileType,bundle?bundle.pages:pages,paperDollSet?'draft':form.get('status')==='published'?'published':'draft',source).first();if(bundle)await saveBundle(ctx.env,row.id,bundle);else await saveUploads(ctx,row.id,form);const item=await ctx.env.DB.prepare('SELECT * FROM products WHERE id=?').bind(row.id).first();return json({item},201)}catch(error){return json({error:String(error).includes('UNIQUE')?'ตะกร้าบางใบถูกใช้สร้างชุดแล้ว หรือเลขสินค้าในหมวดนี้ชนกัน กรุณาโหลดใหม่':error.message||'เพิ่มสินค้าไม่สำเร็จ'},400)}}

async function saveUploads(ctx,id,form){const imageTypes=['image/jpeg','image/png','image/webp'],uploadImage=async(file,prefix)=>{if(!file||!file.size)return '';if(!validFile(file,5*1024*1024,imageTypes))throw new Error('รูปสินค้าแต่ละรูปต้องเป็น JPG, PNG หรือ WEBP ไม่เกิน 5 MB');const key=`${prefix}-${id}-${crypto.randomUUID()}.${ext(file.name,file.type)}`;await ctx.env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});return '/api/media/'+key},coverUrl=await uploadImage(form.get('cover'),'cover'),preview2=await uploadImage(form.get('preview_2'),'preview-2'),preview3=await uploadImage(form.get('preview_3'),'preview-3'),current=await ctx.env.DB.prepare('SELECT cover_url FROM products WHERE id=?').bind(id).first(),finalCover=coverUrl||current?.cover_url||'/assets/product-placeholder.svg',previews=[finalCover,preview2,preview3].filter(Boolean);await ctx.env.DB.prepare('UPDATE products SET cover_url=?,preview_urls=? WHERE id=?').bind(finalCover,JSON.stringify(previews),id).run();const file=form.get('product_file');if(file&&file.size){if(!validFile(file,100*1024*1024,['application/pdf','application/zip']))throw new Error('ไฟล์สินค้าต้องเป็น PDF หรือ ZIP ไม่เกิน 100 MB');const key=`product-${id}-${crypto.randomUUID()}.${ext(file.name,file.type)}`;await ctx.env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});await ctx.env.DB.prepare('INSERT INTO product_files(product_id,label,object_key,mime_type,file_size,version) VALUES(?,?,?,?,?,?)').bind(id,String(form.get('file_label')||'ไฟล์สินค้าฉบับเต็ม'),key,file.type,file.size,'1.0').run()}}
