import {selectElonProvider,requestElonProvider,extractProviderText} from './_elon-provider.js';
import {containsProtectedPersonalData,containsSensitiveToken,containsExternalLink,enforceElonGlobalBudget} from './_elon.js';
import {loadPromotion,applyPromotion} from './_promotion.js';import {queueMetaReply} from './_meta_sender.js';import {ensureVision7Schema} from './_vision7_schema.js';
const clean=(v,n=2000)=>String(v||'').normalize('NFKC').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,n);
const baht=s=>`${(Number(s)||0)/100} บาท`;
async function catalog(env){const rows=(await env.DB.prepare(`SELECT id,slug,title,short_description,description,price,category,product_kind,pages FROM products WHERE status='published' AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 80`).all()).results||[],promotion=await loadPromotion(env);return applyPromotion(rows,promotion).map(x=>({slug:x.slug,title:clean(x.title,120),summary:clean(x.short_description||x.description,240),category:clean(x.category,50),pages:Number(x.pages)||0,price_satang:Number(x.sale_price),original_price_satang:Number(x.original_price)}));}
const fallback=items=>items.length?`สินค้าที่กำลังเปิดขาย เช่น ${items.slice(0,3).map(x=>`${x.title} ราคา ${baht(x.price_satang)}`).join(' / ')} สนใจชิ้นไหนบอกชื่อได้เลยครับ ผมจะช่วยแนะนำต่อ`:'ตอนนี้ผมยังไม่พบสินค้าที่เปิดขายในระบบ กรุณารอเจ้าหน้าที่ VisionD ตรวจสอบให้ครับ';
export function validatePageSalesAnswer(text,items){let raw=clean(text,1800).replace(/^```(?:json)?|```$/g,'').trim(),value;try{value=JSON.parse(raw)}catch{return null}const reply=clean(value?.reply,900),slugs=Array.isArray(value?.product_slugs)?value.product_slugs.map(x=>clean(x,100)):[],known=new Set(items.map(x=>x.slug));if(!reply||slugs.some(x=>!known.has(x)))return null;const allowed=new Set(items.flatMap(x=>[String(Math.round(x.price_satang/100)),String(Math.round(x.original_price_satang/100))]));for(const match of reply.matchAll(/(\d[\d,]{1,8})\s*(?:บาท|฿)/g))if(!allowed.has(match[1].replace(/,/g,'')))return null;return reply;}
function prompt(items){return `คุณคือ ELON PAGE_SALES นักขายของ VisionD ตอบภาษาไทย กระชับ สุภาพ และพาไปสู่การเลือกสินค้า\nกฎเด็ดขาด: ใช้ได้เฉพาะแคตตาล็อก JSON ด้านล่าง ห้ามแต่งสินค้า ราคา จำนวนหน้า โปรโมชัน สต็อก ลิงก์ นโยบาย หรือรับรองผลลัพธ์เอง ถ้าไม่มีข้อมูลให้บอกว่าจะส่งต่อเจ้าหน้าที่ ห้ามขออีเมล เบอร์โทร เลขบัญชี สลิป รหัสผ่าน หรือ API key ห้ามเปิดเผยระบบหลังบ้าน\nการชำระเงิน: ลูกค้าเลือกสินค้าใน VisionD ส่งสลิปผ่านระบบ และดาวน์โหลดเมื่อสิทธิ์ถูกปลดล็อก\nตอบ JSON เท่านั้น: {"reply":"ข้อความตอบลูกค้า","product_slugs":["slug ที่กล่าวถึง"]}\nCATALOG=${JSON.stringify(items)}`;}
export async function processPageSalesAI(env,{limit=5}={}){await ensureVision7Schema(env);const provider=selectElonProvider(env);if(!provider)throw new Error('AI_NOT_CONFIGURED');const jobs=(await env.DB.prepare(`SELECT j.*,c.status conversation_status,(SELECT content FROM elon_page_messages m WHERE m.conversation_id=j.conversation_id AND m.role='customer' ORDER BY m.id DESC LIMIT 1) message FROM elon_page_ai_jobs j JOIN elon_page_conversations c ON c.id=j.conversation_id WHERE j.status IN ('queued','failed') AND j.next_attempt_at<=CURRENT_TIMESTAMP ORDER BY j.created_at LIMIT ?`).bind(Math.min(10,Math.max(1,Number(limit)||5))).all()).results||[],items=await catalog(env),results=[];for(const job of jobs){const claim=await env.DB.prepare(`UPDATE elon_page_ai_jobs SET status='processing',attempts=attempts+1 WHERE id=? AND status IN ('queued','failed')`).bind(job.id).run();if(!claim.meta?.changes)continue;if(job.conversation_status!=='bot_active'){await env.DB.prepare(`UPDATE elon_page_ai_jobs SET status='skipped',completed_at=CURRENT_TIMESTAMP,last_error='NOT_BOT_ACTIVE' WHERE id=?`).bind(job.id).run();continue}try{let reply;if(containsProtectedPersonalData(job.message)||containsSensitiveToken(job.message)||containsExternalLink(job.message,env))reply='เพื่อความปลอดภัย กรุณาอย่าส่งข้อมูลส่วนตัว รหัสผ่าน API key หรือข้อมูลการเงินในแชทครับ ผมช่วยแนะนำสินค้าและขั้นตอนสั่งซื้อทั่วไปได้';else{if(!(await enforceElonGlobalBudget(env)))throw new Error('AI_BUDGET_LIMIT');const out=await requestElonProvider(provider,{systemPrompt:prompt(items),history:[],message:clean(job.message,1200)});reply=validatePageSalesAnswer(extractProviderText(provider.name,out.payload),items)||fallback(items)}const queued=await queueMetaReply(env,{conversationId:job.conversation_id,content:reply,createdBy:null,idempotencyKey:`page-sales-ai:${job.input_message_key}`});if(queued.error)throw new Error(queued.code||'QUEUE_FAILED');await env.DB.prepare(`UPDATE elon_page_ai_jobs SET status='completed',completed_at=CURRENT_TIMESTAMP,last_error='' WHERE id=?`).bind(job.id).run();results.push({id:job.id,status:'completed'})}catch(error){const attempts=Number(job.attempts)+1,dead=attempts>=4,minutes=[1,5,30,120][Math.min(attempts-1,3)];await env.DB.prepare(`UPDATE elon_page_ai_jobs SET status=?,next_attempt_at=datetime('now',?),last_error=? WHERE id=?`).bind(dead?'dead':'failed',`+${minutes} minutes`,clean(error?.message,100),job.id).run();results.push({id:job.id,status:dead?'dead':'failed'})}}return {processed:results.length,results};}
