import {json,requireBoss} from '../../../../_lib.js';
import {ensureDatabase} from '../../../../_schema.js';
import {decryptPartnerSecret} from '../../../../_partner_crypto.js';
import {ensurePartnerWebhookSchema,processWebhookEvent} from '../../../../_partner_webhook.js';
import {maskedExternalId} from '../../../../_partner_sandbox.js';
const headers={'cache-control':'private, no-store'};
async function auth(ctx){await ensureDatabase(ctx.env);await ensurePartnerWebhookSchema(ctx.env);const value=await requireBoss(ctx);if(value.error)return{error:value.error};const website=await ctx.env.DB.prepare('SELECT id,name,status,client_id,secret_ciphertext,secret_last4 FROM partner_websites WHERE id=?').bind(ctx.params.id).first();return website?{user:value.user,website}:{error:json({error:'ไม่พบเว็บไซต์คู่ค้า'},404,headers)}}
const safeEvent=row=>({id:row.id,event_type:row.event_type,external_id_masked:maskedExternalId(row.external_id),idempotency_key_masked:maskedExternalId(row.idempotency_key),status:row.status,attempts:Number(row.attempts)||0,response_status:Number(row.response_status)||0,error_code:row.error_code||'',next_retry_at:row.next_retry_at,received_at:row.received_at,updated_at:row.updated_at});
export async function onRequestGet(ctx){const a=await auth(ctx);if(a.error)return a.error;const [events,logs]=await Promise.all([ctx.env.DB.prepare('SELECT * FROM partner_webhook_events WHERE website_id=? ORDER BY updated_at DESC LIMIT 100').bind(a.website.id).all(),ctx.env.DB.prepare('SELECT level,event_type,external_id_masked,message,response_status,created_at FROM partner_webhook_logs WHERE website_id=? ORDER BY created_at DESC LIMIT 100').bind(a.website.id).all()]);return json({website:{id:a.website.id,name:a.website.name,status:a.website.status,credential_display:`${maskedExternalId(a.website.client_id)} / ••••${a.website.secret_last4}`},callback_url:`${new URL(ctx.request.url).origin}/api/partner/v1/webhooks/events`,signature_contract:'v1=HMAC_SHA256(secret, timestamp + "." + raw_body)',events:(events.results||[]).map(safeEvent),logs:logs.results||[]},200,headers)}
export async function onRequestPost(ctx){const a=await auth(ctx);if(a.error)return a.error;const body=await ctx.request.json().catch(()=>({})),eventId=String(body.event_id||''),action=String(body.action||'');if(!eventId||!['retry','dead'].includes(action))return json({error:'WEBHOOK_ACTION_INVALID'},400,headers);const row=await ctx.env.DB.prepare('SELECT e.*,w.client_id FROM partner_webhook_events e JOIN partner_websites w ON w.id=e.website_id WHERE e.id=? AND e.website_id=?').bind(eventId,a.website.id).first();if(!row)return json({error:'ไม่พบ Event'},404,headers);if(action==='dead'){await ctx.env.DB.prepare("UPDATE partner_webhook_events SET status='dead',next_retry_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.id).run();return json({ok:true,status:'dead'},200,headers)}if(!['retry','dead'].includes(row.status))return json({error:'Event นี้ไม่อยู่ใน Retry หรือ Dead Letter'},409,headers);const result=await processWebhookEvent(ctx,row,await decryptPartnerSecret(ctx.env,a.website.secret_ciphertext));return json(result,result.ok?200:202,headers)}
