import {json,requireAdmin} from '../../../_lib.js';
import {clean,readToyImage,validateToyImageBuffer} from '../../../_toys_center.js';
const headers={'cache-control':'no-store'};
const base64=buffer=>{const bytes=new Uint8Array(buffer);let out='';for(let i=0;i<bytes.length;i+=8192)out+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(out)};
const imagePart=async file=>{const image=await readToyImage(file,'AI',{required:false});return image?{inlineData:{mimeType:image.type,data:base64(image.buffer)}}:null};
const storedImagePart=async(ctx,key)=>{const object=key?await ctx.env.FILES?.get(key):null;if(!object)return null;const image=validateToyImageBuffer(await object.arrayBuffer(),object.httpMetadata?.contentType||'image/jpeg','AI');return{inlineData:{mimeType:image.type,data:base64(image.buffer)}}};
const retainedCoverIndex=raw=>{const value=raw===null?'':String(raw);if(!/^(?:0|[1-9]\d*)$/.test(value))return-1;const index=Number(value);return Number.isSafeInteger(index)&&index<10?index:-1};
const parse=text=>{const raw=String(text||'').replace(/^```(?:json)?\s*|\s*```$/gi,'').trim();try{return JSON.parse(raw)}catch{return null}};
export async function onRequestPost(ctx){const auth=await requireAdmin(ctx);if(auth.error)return auth.error;const key=clean(ctx.env.GEMINI_API_KEY||ctx.env.GEMINI_API_KEY_2,500);if(!key)return json({error:'ยังไม่ได้เชื่อม Gemini API สำหรับช่วยกรอกข้อมูล'},503,headers);const form=await ctx.request.formData();let visiondPart=null,metaPart=null;try{visiondPart=await imagePart(form.get('image_1'));metaPart=await imagePart(form.get('image_2'))}catch(error){return json({error:String(error.message||error)},400,headers)}const rawProductId=form.get('product_id'),productId=Number(rawProductId);if(!visiondPart&&rawProductId!==null){if(!Number.isSafeInteger(productId)||productId<=0)return json({error:'รหัสสินค้าไม่ถูกต้อง'},400,headers);const coverIndex=retainedCoverIndex(form.get('visiond_cover_index'));if(coverIndex<0)return json({error:'รูปปก VisionD ไม่ถูกต้อง'},400,headers);const row=await ctx.env.DB.prepare('SELECT p.image_2_key,selected.image_key AS selected_image_key FROM toys_center_products p LEFT JOIN toys_center_product_images selected ON selected.product_id=p.id AND selected.position=? WHERE p.id=? LIMIT 1').bind(coverIndex,productId).first();if(!row)return json({error:'ไม่พบสินค้า'},404,headers);if(!row.selected_image_key)return json({error:'รูปปก VisionD ไม่ถูกต้อง'},400,headers);try{visiondPart=await storedImagePart(ctx,row.selected_image_key);if(!visiondPart)return json({error:'ไม่พบไฟล์รูปปก VisionD ที่เลือก'},400,headers);if(!metaPart&&row.image_2_key)metaPart=await storedImagePart(ctx,row.image_2_key)}catch(error){return json({error:String(error.message||error)},400,headers)}}const parts=[visiondPart,metaPart].filter(Boolean);if(!parts.length)return json({error:'กรุณาเลือกรูป 1 หรือรูป 2 ก่อนใช้ AI'},400,headers);const prompt=`วิเคราะห์สินค้าของสะสมจากรูปเพื่อช่วยผู้ขายกรอก Meta Catalog ภาษาไทย ตอบ JSON object เท่านั้น ห้าม markdown และห้ามเดาข้อมูลที่มองไม่เห็น ใช้คีย์: title,description,brand,google_product_category,fb_product_category,color,size,material,pattern,age_group,gender,product_tags โดย product_tags ต้องเป็น array ไม่เกิน 10 ค่า หากไม่มั่นใจ brand/category/size ให้เป็นสตริงว่าง รายละเอียดต้องบอกเฉพาะสิ่งที่เห็นและเตือนผู้ซื้อให้ตรวจสอบรูป ห้ามใส่ราคา จำนวน SKU slug หรือสถานะสินค้า`;
  const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent',{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt},...parts]}],generationConfig:{responseMimeType:'application/json',temperature:.1,maxOutputTokens:2048}})}),data=await response.json().catch(()=>({}));if(!response.ok)return json({error:response.status===429?'โควตา AI เต็ม กรุณาลองใหม่ภายหลัง':'AI วิเคราะห์รูปไม่สำเร็จ'},502,headers);const result=parse((data.candidates?.[0]?.content?.parts||[]).map(part=>part.text||'').join(''));if(!result)return json({error:'AI ตอบข้อมูลไม่ครบ กรุณาลองใหม่'},502,headers);const fields={};for(const name of['title','description','brand','google_product_category','fb_product_category','color','size','material','pattern','age_group','gender'])fields[name]=clean(result[name],name==='description'?9999:200);fields.product_tags=(Array.isArray(result.product_tags)?result.product_tags:[]).map(value=>clean(value,60)).filter(Boolean).slice(0,10).join(', ');return json({ok:true,fields,message:'AI ช่วยกรอกแล้ว กรุณาตรวจข้อมูลก่อนบันทึก'},200,headers)}
