import {json,requireAdmin} from '../../../_lib.js';
import {ensureToysCenterSchema,clean,slugify,publicProduct} from '../../../_toys_center.js';
const headers={'cache-control':'no-store'};
const imageTypes={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
async function auth(ctx){await ensureToysCenterSchema(ctx.env);const a=await requireAdmin(ctx);return a.error?{error:a.error}:a}
async function storeImage(env,file,slot){if(!(file instanceof File)||!file.size)throw new Error(`กรุณาแนบรูป ${slot}`);if(!imageTypes[file.type]||file.size>5*1024*1024)throw new Error(`รูป ${slot} ต้องเป็น JPG, PNG หรือ WEBP ไม่เกิน 5 MB`);const key=`toys-center/${crypto.randomUUID()}-${slot}.${imageTypes[file.type]}`;await env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});return key}
function fields(form){const price=Number(form.get('price'));return {metaId:clean(form.get('meta_id'),100),slug:slugify(form.get('slug')||form.get('meta_id')),title:clean(form.get('title'),200),description:clean(form.get('description'),9999),availability:form.get('availability')==='out of stock'?'out of stock':'in stock',condition:form.get('condition')==='new'?'new':'used',priceCents:Number.isFinite(price)&&price>=0?Math.round(price*100):-1,brand:clean(form.get('brand'),100),quantity:Math.max(0,Math.min(999999,Number(form.get('quantity'))||0)),status:form.get('status')==='published'?'published':'draft',google:clean(form.get('google_product_category'),200),facebook:clean(form.get('fb_product_category'),200),gtin:clean(form.get('gtin'),100),group:clean(form.get('item_group_id'),100),color:clean(form.get('color'),100),size:clean(form.get('size'),100),material:clean(form.get('material'),100),pattern:clean(form.get('pattern'),100),age:clean(form.get('age_group'),30),gender:clean(form.get('gender'),30),tags:JSON.stringify(clean(form.get('product_tags'),500).split(',').map(x=>x.trim()).filter(Boolean).slice(0,20))}}
export async function onRequestGet(ctx){const a=await auth(ctx);if(a.error)return a.error;const u=new URL(ctx.request.url),page=Math.max(1,Number(u.searchParams.get('page'))||1),limit=25,q=clean(u.searchParams.get('q'),100),like=`%${q}%`;const [settings,count,rows]=await Promise.all([ctx.env.DB.prepare('SELECT storefront_mode,updated_at FROM toys_center_settings WHERE id=1').first(),ctx.env.DB.prepare('SELECT COUNT(*) total FROM toys_center_products WHERE (?=\'\' OR title LIKE ? OR meta_id LIKE ?)').bind(q,like,like).first(),ctx.env.DB.prepare('SELECT * FROM toys_center_products WHERE (?=\'\' OR title LIKE ? OR meta_id LIKE ?) ORDER BY updated_at DESC,id DESC LIMIT ? OFFSET ?').bind(q,like,like,limit,(page-1)*limit).all()]);const origin=u.origin;return json({settings,items:(rows.results||[]).map(x=>publicProduct(x,origin)),pagination:{page,limit,total:Number(count?.total||0)}},200,headers)}
export async function onRequestPost(ctx){const a=await auth(ctx);if(a.error)return a.error;if(!ctx.env.FILES)return json({error:'ยังไม่ได้เชื่อมพื้นที่เก็บรูป FILES'},503,headers);const form=await ctx.request.formData(),f=fields(form);if(!f.metaId||!f.title||!f.description||!f.brand||f.priceCents<0)return json({error:'กรุณากรอก ID ชื่อ รายละเอียด ราคา และแบรนด์ให้ครบ'},400,headers);let image1='',image2='';try{image1=await storeImage(ctx.env,form.get('image_1'),1);image2=await storeImage(ctx.env,form.get('image_2'),2);const result=await ctx.env.DB.prepare(`INSERT INTO toys_center_products(meta_id,slug,title,description,availability,condition,price_cents,brand,quantity,image_1_key,image_2_key,google_product_category,fb_product_category,gtin,item_group_id,color,size,material,pattern,age_group,gender,product_tags,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(f.metaId,f.slug,f.title,f.description,f.availability,f.condition,f.priceCents,f.brand,f.quantity,image1,image2,f.google,f.facebook,f.gtin,f.group,f.color,f.size,f.material,f.pattern,f.age,f.gender,f.tags,f.status,a.user.id).run();return json({ok:true,id:result.meta.last_row_id,message:'เพิ่มสินค้า Toys Center สำเร็จ'},201,headers)}catch(error){if(image1)await ctx.env.FILES.delete(image1);if(image2)await ctx.env.FILES.delete(image2);return json({error:/unique/i.test(String(error))?'ID หรือ slug สินค้านี้มีอยู่แล้ว':String(error.message||error)},/unique/i.test(String(error))?409:400,headers)}}
export async function onRequestPatch(ctx){const a=await auth(ctx);if(a.error)return a.error;const body=await ctx.request.json().catch(()=>({})),mode=body.storefront_mode==='public'?'public':body.storefront_mode==='unlisted'?'unlisted':'';if(!mode)return json({error:'สถานะหน้าร้านไม่ถูกต้อง'},400,headers);await ctx.env.DB.prepare('UPDATE toys_center_settings SET storefront_mode=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=1').bind(mode,a.user.id).run();return json({ok:true,storefront_mode:mode,message:mode==='public'?'เปิดให้ค้นหาหน้าร้านแล้ว':'ซ่อนจากการค้นหาแล้ว แต่ฟีด Meta ยังใช้งานได้'},200,headers)}
