ALTER TABLE orders ADD COLUMN payment_account_type TEXT;
ALTER TABLE orders ADD COLUMN payment_bank_name TEXT;
ALTER TABLE orders ADD COLUMN payment_account_name TEXT;
ALTER TABLE orders ADD COLUMN payment_account_number TEXT;
ALTER TABLE orders ADD COLUMN slip_verification_status TEXT NOT NULL DEFAULT 'not_checked';
ALTER TABLE orders ADD COLUMN slip_verification_code TEXT;
ALTER TABLE orders ADD COLUMN slip_trans_ref TEXT;
ALTER TABLE orders ADD COLUMN slip_verified_at TEXT;
CREATE TABLE IF NOT EXISTS verified_slips (id INTEGER PRIMARY KEY AUTOINCREMENT,trans_ref TEXT NOT NULL UNIQUE,order_id INTEGER NOT NULL UNIQUE,provider TEXT NOT NULL DEFAULT 'easyslip',amount INTEGER NOT NULL,receiver_name TEXT,receiver_account TEXT,verified_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id));
CREATE UNIQUE INDEX IF NOT EXISTS idx_verified_slips_trans_ref ON verified_slips(trans_ref);
CREATE INDEX IF NOT EXISTS idx_orders_slip_verification ON orders(slip_verification_status,updated_at DESC);
