import {json} from '../../../../_lib.js';
import {ensureDatabase} from '../../../../_schema.js';
import {requireVision7User} from '../../../../_vision7_auth.js';
import {ensureVEasyRuntimeSchema} from '../../../../_veasy_runtime.js';
import {decryptChannelValue} from '../../../../_channel_crypto.js';

const headers={'cache-control':'no-store'},clean=(v,n=4900)=>String(v||'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().replace(/\s+/g,' ').slice(0,n);
async function context(ctx){await ensureDatabase(ctx.env);await ensureVEasyRuntimeSchema(ctx.env);const auth=await requireVision7User(ctx);if(auth.error)return {error:auth.error};const shop=await ctx.env.DB.prepare("SELECT id FROM veasy_shops WHERE id=? AND user_id=? AND status='active'").bind(ctx.params.shopId,auth.user.id).first();return shop?{shop}:{error:json({error:'ไม่พบร้านที่เป็นเจ้าของ',code:'VEASY_SHOP_NOT_OWNED'},404,headers)}}
async function linePush(token,to,text){const response=await fetch('https://api.line.me/v2/bot/message/push',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({to,messages:[{type:'text',text}]})});if(!response.ok)throw new Error(`LINE_PUSH_HTTP_${response.status}`)}
export async function onRequestGet(ctx){const value=await context(ctx);if(value.error)return value.error;const id=clean(new URL(ctx.request.url).searchParams.get('conversation_id'),160);if(id){const owned=await ctx.env.DB.prepare('SELECT id,display_name,platform FROM veasy_conversations WHERE shop_id=? AND id=?').bind(value.shop.id,id).first();if(!owned)return json({error:'ไม่พบบทสนทนานี้'},404,headers);const messages=(await ctx.env.DB.prepare('SELECT id,role,content,created_at FROM veasy_chat_messages WHERE shop_id=? AND conversation_id=? ORDER BY created_at ASC LIMIT 200').bind(value.shop.id,id).all()).results||[];const control=await ctx.env.DB.prepare('SELECT mode FROM veasy_conversation_controls WHERE shop_id=? AND conversation_id=?').bind(value.shop.id,id).first();return json({conversation:{...owned,mode:control?.mode||'bot'},messages},200,headers)}const rows=(await ctx.env.DB.prepare(`SELECT c.id,c.display_name,c.platform,c.updated_at,COALESCE(k.mode,'bot') mode,(SELECT content FROM veasy_chat_messages m WHERE m.shop_id=c.shop_id AND m.conversation_id=c.id ORDER BY m.created_at DESC LIMIT 1) last_message FROM veasy_conversations c LEFT JOIN veasy_conversation_controls k ON k.shop_id=c.shop_id AND k.conversation_id=c.id WHERE c.shop_id=? AND c.status='active' ORDER BY c.updated_at DESC LIMIT 100`).bind(value.shop.id).all()).results||[];return json({conversations:rows},200,headers)}
export async function onRequestPatch(ctx){const value=await context(ctx);if(value.error)return value.error;const body=await ctx.request.json().catch(()=>({})),id=clean(body.conversation_id,160),mode=body.mode==='human'?'human':body.mode==='bot'?'bot':'';if(!id||!mode)return json({error:'คำสั่งรับช่วงไม่ถูกต้อง'},400,headers);const result=await ctx.env.DB.prepare('UPDATE veasy_conversation_controls SET mode=?,updated_at=CURRENT_TIMESTAMP WHERE shop_id=? AND conversation_id=?').bind(mode,value.shop.id,id).run();if(!result.meta?.changes)return json({error:'ไม่พบบทสนทนานี้'},404,headers);return json({ok:true,mode},200,headers)}
export async function onRequestPost(ctx){const value=await context(ctx);if(value.error)return value.error;const body=await ctx.request.json().catch(()=>({})),id=clean(body.conversation_id,160),text=clean(body.text);if(!id||!text)return json({error:'กรุณาพิมพ์ข้อความ'},400,headers);const row=await ctx.env.DB.prepare(`SELECT c.platform,k.mode,k.target_ciphertext,x.token_ciphertext FROM veasy_conversations c JOIN veasy_conversation_controls k ON k.shop_id=c.shop_id AND k.conversation_id=c.id LEFT JOIN veasy_channel_credentials x ON x.shop_id=c.shop_id AND x.provider=c.platform WHERE c.shop_id=? AND c.id=?`).bind(value.shop.id,id).first();if(!row)return json({error:'ไม่พบบทสนทนานี้'},404,headers);if(row.mode!=='human')return json({error:'กด “เจ้าของร้านรับช่วง” ก่อนส่งข้อความ',code:'VEASY_HANDOFF_REQUIRED'},409,headers);if(row.platform!=='line')return json({error:'รุ่นนี้ส่งจากกล่องภายในได้เฉพาะ LINE'},409,headers);try{const [token,target]=await Promise.all([decryptChannelValue(ctx.env,row.token_ciphertext),decryptChannelValue(ctx.env,row.target_ciphertext)]);await linePush(token,target,text);await ctx.env.DB.prepare(`INSERT INTO veasy_chat_messages(id,shop_id,conversation_id,platform_message_id,role,content) VALUES(?,?,?,?, 'assistant',?)`).bind(crypto.randomUUID(),value.shop.id,id,`owner:${crypto.randomUUID()}`,text).run();return json({ok:true},200,headers)}catch(error){console.error('VEASY_OWNER_SEND_FAILED',{shopId:value.shop.id,conversationId:id,error:clean(error?.message,100)});return json({error:'ส่งข้อความ LINE ไม่สำเร็จ กรุณาลองใหม่',code:'VEASY_OWNER_SEND_FAILED'},502,headers)}}
