import {json,requireAdmin} from '../../../_lib.js';
const ext=(name,type)=>type==='image/png'?'png':type==='image/webp'?'webp':type==='application/zip'?'zip':name?.toLowerCase().endsWith('.zip')?'zip':type==='application/pdf'?'pdf':'jpg';
const validFile=(file,max,types)=>file&&typeof file.arrayBuffer==='function'&&file.size>0&&file.size<=max&&types.includes(file.type);

export async function onRequestGet(ctx){const a=await requireAdmin(ctx);if(a.error)return a.error;const item=await ctx.env.DB.prepare('SELECT * FROM products WHERE id=?').bind(ctx.params.id).first();if(!item)return json({error:'ไม่พบสินค้า'},404);const {results}=await ctx.env.DB.prepare('SELECT id,label,mime_type,file_size,version,created_at FROM product_files WHERE product_id=? ORDER BY id DESC').bind(item.id).all();return json({item,files:results.map(file=>({...file,file_name:`${item.slug||'product'}-${file.id}.${file.mime_type==='application/zip'?'zip':'pdf'}`}))})}

export async function onRequestPut(ctx){
  const a=await requireAdmin(ctx);if(a.error)return a.error;
  const old=await ctx.env.DB.prepare('SELECT * FROM products WHERE id=?').bind(ctx.params.id).first();if(!old)return json({error:'ไม่พบสินค้า'},404);
  const form=await ctx.request.formData();const title=String(form.get('title')||'').trim(),slug=String(form.get('slug')||'').trim().toLowerCase(),price=Number(form.get('price_cents'));
  if(!title||!slug)return json({error:'กรุณากรอกชื่อสินค้าและ Slug'},400);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))return json({error:'Slug ใช้ได้เฉพาะ a-z, 0-9 และขีดกลาง'},400);if(!Number.isInteger(price)||price<0)return json({error:'ราคาไม่ถูกต้อง'},400);
  try{
    await ctx.env.DB.prepare(`UPDATE products SET slug=?,title=?,short_description=?,description=?,price=?,category=?,file_type=?,status=?,source='admin',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(slug,title,String(form.get('short_description')||''),String(form.get('description')||''),price,String(form.get('category')||'dinosaur'),String(form.get('file_type')||'PDF'),form.get('status')==='published'?'published':'draft',old.id).run();
    let oldPreviews=[];try{oldPreviews=JSON.parse(old.preview_urls||'[]')}catch(error){oldPreviews=[]}if(!oldPreviews.length&&old.cover_url)oldPreviews=[old.cover_url];const imageTypes=['image/jpeg','image/png','image/webp'],uploadImage=async(file,prefix)=>{if(!file||!file.size)return '';if(!validFile(file,5*1024*1024,imageTypes))throw new Error('รูปสินค้าแต่ละรูปต้องเป็น JPG, PNG หรือ WEBP ไม่เกิน 5 MB');const key=`${prefix}-${old.id}-${crypto.randomUUID()}.${ext(file.name,file.type)}`;await ctx.env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});return '/api/media/'+key},newCover=await uploadImage(form.get('cover'),'cover'),newPreview2=await uploadImage(form.get('preview_2'),'preview-2'),newPreview3=await uploadImage(form.get('preview_3'),'preview-3'),finalCover=newCover||old.cover_url||'/assets/product-placeholder.svg',finalPreviews=[finalCover,newPreview2||oldPreviews[1],newPreview3||oldPreviews[2]].filter(Boolean);for(const [next,previous] of [[newCover,old.cover_url],[newPreview2,oldPreviews[1]],[newPreview3,oldPreviews[2]]])if(next&&previous?.startsWith('/api/media/')&&previous!==next)await ctx.env.FILES.delete(previous.slice('/api/media/'.length));await ctx.env.DB.prepare('UPDATE products SET cover_url=?,preview_urls=? WHERE id=?').bind(finalCover,JSON.stringify(finalPreviews),old.id).run();
    const file=form.get('product_file');if(file&&file.size){if(!validFile(file,100*1024*1024,['application/pdf','application/zip']))return json({error:'ไฟล์สินค้าต้องเป็น PDF หรือ ZIP ไม่เกิน 100 MB'},400);const key=`product-${old.id}-${crypto.randomUUID()}.${ext(file.name,file.type)}`;await ctx.env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});const current=await ctx.env.DB.prepare('SELECT COUNT(*) count FROM product_files WHERE product_id=?').bind(old.id).first();await ctx.env.DB.prepare('INSERT INTO product_files(product_id,label,object_key,mime_type,file_size,version) VALUES(?,?,?,?,?,?)').bind(old.id,String(form.get('file_label')||'ไฟล์สินค้าฉบับเต็ม'),key,file.type,file.size,`1.${Number(current.count)||0}`).run()}
    return json({item:await ctx.env.DB.prepare('SELECT * FROM products WHERE id=?').bind(old.id).first()});
  }catch(error){return json({error:String(error).includes('UNIQUE')?'Slug นี้ถูกใช้แล้ว':'บันทึกสินค้าไม่สำเร็จ'},400)}
}

export async function onRequestDelete(ctx){const a=await requireAdmin(ctx);if(a.error)return a.error;const item=await ctx.env.DB.prepare('SELECT * FROM products WHERE id=?').bind(ctx.params.id).first();if(!item)return json({error:'ไม่พบสินค้า'},404);const paid=await ctx.env.DB.prepare("SELECT 1 found FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.product_id=? AND o.status='paid' LIMIT 1").bind(item.id).first();if(paid)return json({error:'สินค้านี้มีรายการชำระเงินจริงแล้ว จึงลบไม่ได้'},409);const {results:files}=await ctx.env.DB.prepare('SELECT id,object_key FROM product_files WHERE product_id=?').bind(item.id).all();for(const file of files){await ctx.env.DB.prepare('DELETE FROM downloads WHERE product_file_id=?').bind(file.id).run();await ctx.env.FILES.delete(file.object_key)}const {results:orders}=await ctx.env.DB.prepare('SELECT DISTINCT order_id FROM order_items WHERE product_id=?').bind(item.id).all();await ctx.env.DB.prepare('DELETE FROM entitlements WHERE product_id=?').bind(item.id).run();await ctx.env.DB.prepare('DELETE FROM unlock_logs WHERE product_id=?').bind(item.id).run();await ctx.env.DB.prepare('DELETE FROM order_items WHERE product_id=?').bind(item.id).run();for(const row of orders){const remain=await ctx.env.DB.prepare('SELECT 1 found FROM order_items WHERE order_id=? LIMIT 1').bind(row.order_id).first();if(!remain){const order=await ctx.env.DB.prepare('SELECT slip_key FROM orders WHERE id=?').bind(row.order_id).first();if(order?.slip_key)await ctx.env.FILES.delete(order.slip_key);await ctx.env.DB.prepare('DELETE FROM orders WHERE id=?').bind(row.order_id).run()}}let previews=[];try{previews=JSON.parse(item.preview_urls||'[]')}catch(error){previews=[]}for(const url of new Set([item.cover_url,...previews]))if(url?.startsWith('/api/media/'))await ctx.env.FILES.delete(url.slice('/api/media/'.length));await ctx.env.DB.prepare('DELETE FROM product_files WHERE product_id=?').bind(item.id).run();await ctx.env.DB.prepare('DELETE FROM products WHERE id=?').bind(item.id).run();return json({ok:true,deleted_test_orders:orders.length})}
