import {json,requireAdmin} from '../../../_lib.js';
import {ensureCatalogProducts} from '../../../_catalog.js';
const ext=(name,type)=>type==='image/png'?'png':type==='image/webp'?'webp':type==='application/zip'?'zip':name?.toLowerCase().endsWith('.zip')?'zip':type==='application/pdf'?'pdf':'jpg';
const validFile=(file,max,types)=>file&&typeof file.arrayBuffer==='function'&&file.size>0&&file.size<=max&&types.includes(file.type);

export async function onRequestGet(ctx){const a=await requireAdmin(ctx);if(a.error)return a.error;await ensureCatalogProducts(ctx.env);const {results}=await ctx.env.DB.prepare(`SELECT p.*,COUNT(pf.id) file_count FROM products p LEFT JOIN product_files pf ON pf.product_id=p.id GROUP BY p.id ORDER BY p.id DESC`).all();return json({items:results})}

export async function onRequestPost(ctx){const a=await requireAdmin(ctx);if(a.error)return a.error;const form=await ctx.request.formData();const title=String(form.get('title')||'').trim(),slug=String(form.get('slug')||'').trim().toLowerCase(),price=Number(form.get('price_cents'));if(!title||!slug)return json({error:'กรุณากรอกชื่อสินค้าและ Slug'},400);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))return json({error:'Slug ใช้ได้เฉพาะ a-z, 0-9 และขีดกลาง'},400);if(!Number.isInteger(price)||price<0)return json({error:'ราคาไม่ถูกต้อง'},400);try{const row=await ctx.env.DB.prepare(`INSERT INTO products(slug,title,short_description,description,price,cover_url,category,status,source,updated_at) VALUES(?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) RETURNING *`).bind(slug,title,String(form.get('short_description')||''),String(form.get('description')||''),price,'/assets/product-placeholder.svg',String(form.get('category')||'digital-product'),form.get('status')==='published'?'published':'draft','admin').first();await saveUploads(ctx,row.id,form);const item=await ctx.env.DB.prepare('SELECT * FROM products WHERE id=?').bind(row.id).first();return json({item},201)}catch(error){return json({error:String(error).includes('UNIQUE')?'Slug นี้ถูกใช้แล้ว':'เพิ่มสินค้าไม่สำเร็จ'},400)}}

async function saveUploads(ctx,id,form){const cover=form.get('cover');if(cover&&cover.size){if(!validFile(cover,5*1024*1024,['image/jpeg','image/png','image/webp']))throw new Error('รูปปกต้องเป็น JPG, PNG หรือ WEBP ไม่เกิน 5 MB');const key=`cover-${id}-${crypto.randomUUID()}.${ext(cover.name,cover.type)}`;await ctx.env.FILES.put(key,await cover.arrayBuffer(),{httpMetadata:{contentType:cover.type}});await ctx.env.DB.prepare('UPDATE products SET cover_url=? WHERE id=?').bind('/api/media/'+key,id).run()}const file=form.get('product_file');if(file&&file.size){if(!validFile(file,100*1024*1024,['application/pdf','application/zip']))throw new Error('ไฟล์สินค้าต้องเป็น PDF หรือ ZIP ไม่เกิน 100 MB');const key=`product-${id}-${crypto.randomUUID()}.${ext(file.name,file.type)}`;await ctx.env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});await ctx.env.DB.prepare('INSERT INTO product_files(product_id,label,object_key,mime_type,file_size,version) VALUES(?,?,?,?,?,?)').bind(id,String(form.get('file_label')||'ไฟล์สินค้าฉบับเต็ม'),key,file.type,file.size,'1.0').run()}}
