import {json,requireAdmin} from '../../../_lib.js';
import {ensureCatalogProducts} from '../../../_catalog.js';
import {ensureDatabase} from '../../../_schema.js';
const ext=(name,type)=>type==='image/png'?'png':type==='image/webp'?'webp':type==='application/zip'?'zip':name?.toLowerCase().endsWith('.zip')?'zip':type==='application/pdf'?'pdf':'jpg';
const validFile=(file,max,types)=>file&&typeof file.arrayBuffer==='function'&&file.size>0&&file.size<=max&&(types.includes(file.type)||(types.includes('application/zip')&&/\.zip$/i.test(file.name||''))||(types.includes('application/pdf')&&/\.pdf$/i.test(file.name||'')));

export async function onRequestGet(ctx){await ensureDatabase(ctx.env);const a=await requireAdmin(ctx);if(a.error)return a.error;await ensureCatalogProducts(ctx.env);const vision4=new URL(ctx.request.url).searchParams.get('queue')==='vision4',extra=vision4?"AND p.source='vision4' AND p.status='draft'":"AND NOT(p.source='vision4' AND p.status='draft')";const {results}=await ctx.env.DB.prepare(`SELECT p.*,(SELECT COUNT(*) FROM product_files own WHERE own.product_id=p.id)+(SELECT COUNT(*) FROM product_bundle_items b JOIN product_files bf ON bf.product_id=b.source_product_id WHERE b.bundle_product_id=p.id) file_count,(SELECT own.id FROM product_files own WHERE own.product_id=p.id ORDER BY own.id DESC LIMIT 1) latest_file_id,(SELECT own.mime_type FROM product_files own WHERE own.product_id=p.id ORDER BY own.id DESC LIMIT 1) latest_file_mime FROM products p WHERE p.deleted_at IS NULL AND COALESCE(p.product_kind,'product')='product' AND p.category<>'resale-rights' AND NOT EXISTS(SELECT 1 FROM courses c WHERE c.product_id=p.id AND (c.owner_user_id IS NOT NULL OR c.course_origin='seller_rights' OR c.course_type='resale_rights')) ${extra} ORDER BY p.id DESC`).all();return json({items:results})}

const bundleIds=form=>[...new Set(String(form.get('bundle_product_ids')||'').split(',').map(Number).filter(Number.isInteger))];
async function validateBundle(env,form,category){const ids=bundleIds(form),size=Number(form.get('bundle_size'));if(form.get('bundle_mode')!=='1')return null;if(category!=='bundle-deals')throw new Error('หมวดโปรยกชุดต้องใช้ slug bundle-deals');if(![10,20,30,50].includes(size)||ids.length!==size)throw new Error(`กรุณาเลือกตะกร้าให้ครบ ${size||10} รายการ`);const marks=ids.map(()=>'?').join(','),{results}=await env.DB.prepare(`SELECT p.id,p.title,p.cover_url,p.pages,(SELECT COUNT(*) FROM product_files pf WHERE pf.product_id=p.id) file_count FROM products p WHERE id IN (${marks}) AND status='published' AND deleted_at IS NULL AND category NOT IN ('set-coloring','set-tattoo','bundle-deals','resale-rights') AND COALESCE(product_kind,'product')='product' AND NOT EXISTS(SELECT 1 FROM courses c WHERE c.product_id=p.id AND (c.owner_user_id IS NOT NULL OR c.course_origin='seller_rights' OR c.course_type='resale_rights'))`).bind(...ids).all();if(results.length!==ids.length)throw new Error('มีตะกร้าต้นทางที่ไม่พร้อมขาย กรุณาเลือกใหม่');const byId=new Map(results.map(item=>[Number(item.id),item])),items=ids.map(id=>byId.get(id)),previews=items.map(item=>item.cover_url).filter(Boolean),pages=items.reduce((sum,item)=>sum+(Number(item.pages)||0),0),files=items.reduce((sum,item)=>sum+(Number(item.file_count)||0),0),description=items.map((item,index)=>`${index+1}. ${item.title} (${Number(item.pages)||0} รูป)`).join('\n');return {ids,size,previews,items,pages,files,description}}
async function saveBundle(env,productId,bundle){if(!bundle)return;await env.DB.prepare('DELETE FROM product_bundle_items WHERE bundle_product_id=?').bind(productId).run();for(let index=0;index<bundle.ids.length;index++)await env.DB.prepare('INSERT INTO product_bundle_items(bundle_product_id,source_product_id,sort_order) VALUES(?,?,?)').bind(productId,bundle.ids[index],index).run();const cover=bundle.previews[0]||'/assets/product-placeholder.svg';await env.DB.prepare('UPDATE products SET cover_url=?,preview_urls=? WHERE id=?').bind(cover,JSON.stringify(bundle.previews),productId).run()}

async function nextProductSlug(env,category){
  const prefix=`${category}-`,current=await env.DB.prepare('SELECT slug FROM products WHERE category=? AND slug LIKE ?').bind(category,`${prefix}%`).all(),history=await env.DB.prepare('SELECT old_slug slug FROM product_slug_history WHERE old_slug LIKE ?').bind(`${prefix}%`).all();
  let next=[...(current.results||[]),...(history.results||[])].reduce((max,row)=>Math.max(max,Number(String(row.slug||'').slice(prefix.length))||0),0)+1,slug='';
  do{slug=`${prefix}${String(next++).padStart(3,'0')}`}while(await env.DB.prepare('SELECT id FROM products WHERE slug=?').bind(slug).first());
  return slug;
}

export async function onRequestPost(ctx){const a=await requireAdmin(ctx);if(a.error)return a.error;const form=await ctx.request.formData(),title=String(form.get('title')||'').trim(),price=Number(form.get('price_cents')),requestedPages=Math.max(0,Math.floor(Number(form.get('pages'))||0)),category=String(form.get('category')||'').trim();if(!title||!category)return json({error:'กรุณากรอกชื่อสินค้าและเลือกหมวดหมู่'},400);if(category==='resale-rights')return json({error:'ตะกร้าสิทธิ์ Vision 5 ต้องจัดการผ่านระบบ Vision 5 เท่านั้น'},403);if(!Number.isInteger(price)||price<0)return json({error:'ราคาไม่ถูกต้อง'},400);const duplicate=await ctx.env.DB.prepare('SELECT id,title FROM products WHERE lower(trim(title))=lower(trim(?)) AND deleted_at IS NULL LIMIT 1').bind(title).first();if(duplicate)return json({error:`ชื่อสินค้า “${duplicate.title}” มีอยู่แล้ว กรุณาใช้ชื่ออื่น`},409);try{const bundle=await validateBundle(ctx.env,form,category),slug=await nextProductSlug(ctx.env,category),source=bundle?'bundle':form.get('source')==='vision4'?'vision4':'admin',pages=bundle?bundle.pages:requestedPages,shortDescription=bundle?`โปรยกชุด ${bundle.size} ตะกร้า · ${bundle.files} ไฟล์ · ${bundle.pages} รูป`:String(form.get('short_description')||''),description=bundle?bundle.description:String(form.get('description')||''),row=await ctx.env.DB.prepare(`INSERT INTO products(slug,title,short_description,description,price,cover_url,category,file_type,pages,status,source,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) RETURNING *`).bind(slug,title,shortDescription,description,price,'/assets/product-placeholder.svg',category,bundle?'ชุดไฟล์ดิจิทัล':String(form.get('file_type')||'PDF'),pages,form.get('status')==='published'?'published':'draft',source).first();if(bundle)await saveBundle(ctx.env,row.id,bundle);else await saveUploads(ctx,row.id,form);const item=await ctx.env.DB.prepare('SELECT * FROM products WHERE id=?').bind(row.id).first();return json({item},201)}catch(error){return json({error:String(error).includes('UNIQUE')?'เลขสินค้าในหมวดนี้ชนกัน กรุณากดบันทึกอีกครั้ง':error.message||'เพิ่มสินค้าไม่สำเร็จ'},400)}}

async function saveUploads(ctx,id,form){const imageTypes=['image/jpeg','image/png','image/webp'],uploadImage=async(file,prefix)=>{if(!file||!file.size)return '';if(!validFile(file,5*1024*1024,imageTypes))throw new Error('รูปสินค้าแต่ละรูปต้องเป็น JPG, PNG หรือ WEBP ไม่เกิน 5 MB');const key=`${prefix}-${id}-${crypto.randomUUID()}.${ext(file.name,file.type)}`;await ctx.env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});return '/api/media/'+key},coverUrl=await uploadImage(form.get('cover'),'cover'),preview2=await uploadImage(form.get('preview_2'),'preview-2'),preview3=await uploadImage(form.get('preview_3'),'preview-3'),current=await ctx.env.DB.prepare('SELECT cover_url FROM products WHERE id=?').bind(id).first(),finalCover=coverUrl||current?.cover_url||'/assets/product-placeholder.svg',previews=[finalCover,preview2,preview3].filter(Boolean);await ctx.env.DB.prepare('UPDATE products SET cover_url=?,preview_urls=? WHERE id=?').bind(finalCover,JSON.stringify(previews),id).run();const file=form.get('product_file');if(file&&file.size){if(!validFile(file,100*1024*1024,['application/pdf','application/zip']))throw new Error('ไฟล์สินค้าต้องเป็น PDF หรือ ZIP ไม่เกิน 100 MB');const key=`product-${id}-${crypto.randomUUID()}.${ext(file.name,file.type)}`;await ctx.env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});await ctx.env.DB.prepare('INSERT INTO product_files(product_id,label,object_key,mime_type,file_size,version) VALUES(?,?,?,?,?,?)').bind(id,String(form.get('file_label')||'ไฟล์สินค้าฉบับเต็ม'),key,file.type,file.size,'1.0').run()}}
