import {json} from '../../../../../_lib.js';
import {ensureDatabase} from '../../../../../_schema.js';
import {requirePartnerScope} from '../../../../../_partner_api.js';
import {ensurePartnerCommerceClaimSchema} from '../../../../../_partner_commerce.js';
import {decryptPartnerData} from '../../../../../_partner_crypto.js';
import {cleanId} from '../../../../../_partner_sync.js';

const headers={'cache-control':'private, no-store'};
export async function onRequestGet(ctx){await ensureDatabase(ctx.env);await ensurePartnerCommerceClaimSchema(ctx.env);const auth=await requirePartnerScope(ctx,'commerce:read');if(auth.error)return auth.error;const externalId=cleanId(ctx.params.externalId);if(!externalId)return json({error:'EXTERNAL_ORDER_ID_INVALID',request_id:auth.requestId},400,headers);const order=await ctx.env.DB.prepare('SELECT id,external_order_id,status,currency,subtotal,discount,total,fulfilled_at,created_at,updated_at FROM partner_commerce_orders WHERE website_id=? AND external_order_id=? LIMIT 1').bind(auth.website.id,externalId).first();if(!order)return json({error:'COMMERCE_ORDER_NOT_FOUND',request_id:auth.requestId},404,headers);const items=(await ctx.env.DB.prepare('SELECT product_id,title,quantity,unit_price,line_total FROM partner_commerce_order_items WHERE order_id=? ORDER BY line_index LIMIT 100').bind(order.id).all()).results||[];let claim_url=null,claim_expires_at=null;if(order.status==='fulfilled'){const claim=await ctx.env.DB.prepare("SELECT token_ciphertext,expires_at FROM partner_commerce_claims WHERE order_id=? AND consumed_at IS NULL AND datetime(expires_at)>datetime('now') LIMIT 1").bind(order.id).first();if(claim)try{claim_url=`${new URL(ctx.request.url).origin}/partner-commerce-claim.html#token=${encodeURIComponent(await decryptPartnerData(ctx.env,claim.token_ciphertext))}`;claim_expires_at=claim.expires_at}catch{}}return json({order:{...order,item_count:items.length,items,entitlement_ready:order.status==='fulfilled',claim_url,claim_expires_at},request_id:auth.requestId},200,{...headers,'x-request-id':auth.requestId})}
