import {ensureDatabase} from '../_schema.js';
import {ensureSalesPageSchema} from '../_sales_pages.js';
import {loadPromotion,promotionPrice} from '../_promotion.js';
const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),safeJson=value=>JSON.stringify(value).replaceAll('<','\\u003c'),baseHeaders={'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=60','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'};
const parse=value=>{try{return JSON.parse(value||'{}')}catch{return{}}},origin=env=>String(env.APP_ORIGIN||'https://visiondonline.com').replace(/\/$/,'');
function shell({title,description='',canonical='',index=false,jsonLd=[],body,status=200}){const robots=index?'index,follow,max-image-preview:large':'noindex,nofollow',structured=jsonLd.map(item=>`<script type="application/ld+json">${safeJson(item)}</script>`).join('');return new Response(`<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="${robots}"><title>${escape(title)} | VisionD</title>${description?`<meta name="description" content="${escape(description)}">`:''}${canonical?`<link rel="canonical" href="${escape(canonical)}"><meta property="og:url" content="${escape(canonical)}">`:''}<meta property="og:type" content="website"><meta property="og:title" content="${escape(title)}">${description?`<meta property="og:description" content="${escape(description)}">`:''}${structured}<link rel="stylesheet" href="/sales-page-public.css?v=014476"><link rel="stylesheet" href="/visiond-button-system.css?v=014476"></head><body data-feature="SALES-PAGE-001" data-page-type="${index?'seo_automation':'ad_shortcut'}">${body}</body></html>`,{status,headers:{...baseHeaders,'x-robots-tag':robots}})}
export async function onRequestGet(ctx){
  await ensureDatabase(ctx.env);await ensureSalesPageSchema(ctx.env);
  let requestedSlug=String(ctx.params.slug||'');try{requestedSlug=decodeURIComponent(requestedSlug)}catch{}
  const page=await ctx.env.DB.prepare(`SELECT p.id,p.slug,p.title,p.page_type,p.content_json,p.revision_no,p.approved_revision_no,p.approved_at,p.robots_index,t.name template_name FROM sales_pages p JOIN sales_page_templates t ON t.id=p.template_id WHERE p.slug=? AND p.status='published' AND ((p.page_type='ad_shortcut' AND p.robots_index=0) OR (p.page_type='seo_automation' AND p.robots_index=1 AND p.approved_at IS NOT NULL AND p.approved_revision_no=p.revision_no))`).bind(requestedSlug).first();
  if(!page)return shell({title:'ไม่พบหน้าขาย',body:'<main class="notice"><h1>ไม่พบหน้านี้</h1><p>หน้าอาจยังไม่เผยแพร่ ถูกพัก หรือเก็บถาวร</p><a href="/digital-products.html">ดูสินค้าทั้งหมด</a></main>',status:404});
  const content=parse(page.content_json),rows=(await ctx.env.DB.prepare(`SELECT p.id,p.slug,p.title,p.short_description,p.description,p.price,p.cover_url,p.category,p.pages,p.product_kind,x.sort_order,c.name category_name FROM sales_page_products x JOIN products p ON p.id=x.product_id LEFT JOIN categories c ON c.slug=p.category WHERE x.page_id=? AND p.status='published' AND p.deleted_at IS NULL AND COALESCE(p.product_kind,'product')='product' ORDER BY x.sort_order`).bind(page.id).all()).results||[],promotion=await loadPromotion(ctx.env),products=rows.map(row=>promotionPrice(row,promotion)).map(row=>({id:row.id,slug:row.slug,title:row.title,summary:row.short_description||row.description||'',price:Number(row.sale_price),original_price:Number(row.original_price),promotion_percent:Number(row.promotion_percent)||0,cover_url:row.cover_url||'/assets/product-placeholder.svg',category:row.category,category_label:row.category_name||row.category,pages:Number(row.pages)||0,quantity:1}));
  if(!products.length)return shell({title:page.title,body:'<main class="notice"><h1>สินค้าหน้านี้ยังไม่พร้อมขาย</h1><p>กรุณากลับมาดูใหม่</p><a href="/digital-products.html">ดูสินค้าที่พร้อมขาย</a></main>',status:410});
  const cards=products.map(product=>`<article class="sale-product"><a href="/product.html?slug=${encodeURIComponent(product.slug)}"><img src="${escape(product.cover_url)}" alt="${escape(product.title)}" loading="lazy"></a><div><small>${escape(product.category_label)}</small><h2><a href="/product.html?slug=${encodeURIComponent(product.slug)}">${escape(product.title)}</a></h2><p>${escape(product.summary)}</p><p class="price">${product.promotion_percent?`<del>${(product.original_price/100).toLocaleString('th-TH')} บาท</del> `:''}<strong>${(product.price/100).toLocaleString('th-TH')} บาท</strong></p><div class="product-actions"><button data-add="${product.id}">เพิ่มตะกร้า</button><button data-buy="${product.id}">ซื้อทันที</button></div></div></article>`).join('');
  const dataScript=`<script type="application/json" id="salesPageData">${safeJson({page_id:page.id,page_slug:page.slug,revision_no:page.revision_no,products})}</script><script src="/sales-page-public.js?v=014476"></script>`;
  if(page.page_type==='ad_shortcut'){const body=`<header class="shortcut-head"><a href="/">VISIOND ONLINE</a><a href="/cart">รถเข็น <b data-cart-count>0</b></a></header><main><section class="shortcut-hero"><small>VISIOND AD SHORTCUT</small><h1>${escape(content.hero||page.title)}</h1><p>${escape(content.body||'เลือกสินค้าที่ต้องการและชำระเงินผ่านระบบ VisionD')}</p><button id="primaryCta">${escape(content.cta||'ซื้อเลย')}</button></section><section class="sale-products">${cards}</section><p id="saleState" role="status" aria-live="polite"></p></main>${dataScript}`;return shell({title:page.title,body})}
  const canonical=`${origin(ctx.env)}/s/${encodeURIComponent(page.slug)}`,paragraphs=String(content.body||'').split(/\n{2,}/).map(value=>value.trim()).filter(Boolean),faq=(Array.isArray(content.faq)?content.faq:[]).filter(item=>item?.question&&item?.answer),faqHtml=faq.map(item=>`<details><summary>${escape(item.question)}</summary><p>${escape(item.answer)}</p></details>`).join(''),jsonLd=[{'@context':'https://schema.org','@type':'WebPage',name:page.title,description:content.meta_description,url:canonical,inLanguage:'th-TH'},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'หน้าแรก',item:origin(ctx.env)},{'@type':'ListItem',position:2,name:'สินค้าดิจิทัล',item:`${origin(ctx.env)}/digital-products.html`},{'@type':'ListItem',position:3,name:page.title,item:canonical}]},{'@context':'https://schema.org','@type':'ItemList',itemListElement:products.map((product,index)=>({'@type':'ListItem',position:index+1,url:`${origin(ctx.env)}/product.html?slug=${encodeURIComponent(product.slug)}`,name:product.title}))}];if(faq.length)jsonLd.push({'@context':'https://schema.org','@type':'FAQPage',mainEntity:faq.map(item=>({'@type':'Question',name:item.question,acceptedAnswer:{'@type':'Answer',text:item.answer}}))});
  const body=`<header class="shortcut-head"><a href="/">VISIOND ONLINE</a><a href="/digital-products.html">สินค้าทั้งหมด</a><a href="/cart">รถเข็น <b data-cart-count>0</b></a></header><main class="seo-page"><nav aria-label="breadcrumb"><a href="/">หน้าแรก</a> › <a href="/digital-products.html">สินค้าดิจิทัล</a> › ${escape(page.title)}</nav><article><section class="shortcut-hero"><small>VISIOND DIGITAL GUIDE</small><h1>${escape(content.hero||page.title)}</h1><p>${escape(content.meta_description)}</p></section><section class="seo-content">${paragraphs.map((paragraph,index)=>`${index===1?`<h2>เลือก ${escape(content.keyword)} ให้เหมาะกับการใช้งาน</h2>`:''}<p>${escape(paragraph)}</p>`).join('')}</section><section aria-labelledby="relatedProducts"><h2 id="relatedProducts">สินค้า ${escape(content.keyword)} ที่เกี่ยวข้อง</h2><div class="sale-products">${cards}</div></section>${faq.length?`<section class="seo-faq"><h2>คำถามที่พบบ่อยเกี่ยวกับ ${escape(content.keyword)}</h2>${faqHtml}</section>`:''}<p id="saleState" role="status" aria-live="polite"></p></article></main>${dataScript}`;
  return shell({title:page.title,description:content.meta_description,canonical,index:true,jsonLd,body});
}
