import {json,sha256} from './_lib.js';
export const PARTNER_SCOPES=['products:read','customers:write','orders:write','commerce:read','commerce:write'];
const partnerSchemaReady=new WeakMap();
export async function ensurePartnerSchema(env){
  let ready=partnerSchemaReady.get(env.DB);if(ready)return ready;
  ready=(async()=>{
    try{const state=await env.DB.prepare("SELECT version FROM runtime_schema_state WHERE schema_key='core'").first();if(Number(state?.version)>=66)return true}catch(error){if(!/no such table[^]*runtime_schema_state/i.test(String(error?.message||error)))throw error}
    await env.DB.exec(`CREATE TABLE IF NOT EXISTS partner_websites (id TEXT PRIMARY KEY,name TEXT NOT NULL,domain TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','active','paused','revoked')),scopes TEXT NOT NULL DEFAULT '["products:read"]',client_id TEXT NOT NULL UNIQUE,secret_ciphertext TEXT NOT NULL,secret_hash TEXT NOT NULL,secret_last4 TEXT NOT NULL,created_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_used_at TEXT,revoked_at TEXT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL);CREATE INDEX IF NOT EXISTS idx_partner_websites_status ON partner_websites(status,updated_at DESC);CREATE TABLE IF NOT EXISTS partner_api_audit (id TEXT PRIMARY KEY,website_id TEXT,request_id TEXT NOT NULL UNIQUE,method TEXT NOT NULL,path TEXT NOT NULL,required_scope TEXT NOT NULL,response_status INTEGER NOT NULL,ip_hash TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(website_id) REFERENCES partner_websites(id) ON DELETE SET NULL);CREATE INDEX IF NOT EXISTS idx_partner_api_audit_website ON partner_api_audit(website_id,created_at DESC);`)
    return false;
  })().catch(error=>{partnerSchemaReady.delete(env.DB);throw error});partnerSchemaReady.set(env.DB,ready);return ready;
}
export const cleanScopes=value=>[...new Set((Array.isArray(value)?value:[]).map(String).filter(scope=>PARTNER_SCOPES.includes(scope)))];
export const newPartnerCredential=()=>({clientId:`vdw_${crypto.randomUUID().replaceAll('-','')}`,secret:`vds_${crypto.randomUUID().replaceAll('-','')}${crypto.randomUUID().replaceAll('-','')}`});
export const partnerSecretHash=(clientId,secret)=>sha256(`${clientId}:${secret}`);
function bearer(request){const value=request.headers.get('authorization')||'';return /^Bearer\s+\S+$/i.test(value)?value.replace(/^Bearer\s+/i,''):''}
function equalHash(a,b){a=String(a||'');b=String(b||'');if(a.length!==b.length)return false;let diff=0;for(let index=0;index<a.length;index++)diff|=a.charCodeAt(index)^b.charCodeAt(index);return diff===0}
async function audit(ctx,websiteId,scope,status){const requestId=ctx.request.headers.get('x-request-id')?.slice(0,100)||crypto.randomUUID(),ip=ctx.request.headers.get('cf-connecting-ip')||'';await ctx.env.DB.prepare('INSERT OR IGNORE INTO partner_api_audit(id,website_id,request_id,method,path,required_scope,response_status,ip_hash) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),websiteId||null,requestId,ctx.request.method,new URL(ctx.request.url).pathname,scope,status,ip?await sha256(`partner-ip:${ip}`):'').run().catch(()=>{});return requestId}
export async function requirePartnerScope(ctx,scope){await ensurePartnerSchema(ctx.env);const clientId=String(ctx.request.headers.get('x-visiond-client-id')||'').trim(),secret=bearer(ctx.request),row=clientId?await ctx.env.DB.prepare('SELECT id,name,domain,status,scopes,client_id,secret_hash FROM partner_websites WHERE client_id=?').bind(clientId).first():null;let status=401,code='PARTNER_CREDENTIAL_INVALID',scopes=[];try{scopes=JSON.parse(row?.scopes||'[]')}catch{scopes=[]}if(row&&secret&&equalHash(row.secret_hash,await partnerSecretHash(clientId,secret))){if(row.status!=='active'){status=403;code='PARTNER_WEBSITE_NOT_ACTIVE'}else if(!scopes.includes(scope)){status=403;code='PARTNER_SCOPE_DENIED'}else{await ctx.env.DB.prepare('UPDATE partner_websites SET last_used_at=CURRENT_TIMESTAMP WHERE id=?').bind(row.id).run();const requestId=await audit(ctx,row.id,scope,200);return {website:row,requestId}}}const requestId=await audit(ctx,row?.id,scope,status);return {error:json({error:code,request_id:requestId},status,{'cache-control':'no-store'})}}
