import {sha256} from './_lib.js';
import {ensurePartnerSchema} from './_partner_api.js';
import {ensurePartnerSyncSchema} from './_partner_sync.js';
export const SANDBOX_SCENARIOS=['customer','order','payment','cancellation','refund'];
export async function ensurePartnerSandboxSchema(env){await ensurePartnerSyncSchema(env);await env.DB.exec(`CREATE TABLE IF NOT EXISTS partner_sandbox_runs (id TEXT PRIMARY KEY,website_id TEXT NOT NULL,scenario TEXT NOT NULL CHECK(scenario IN ('customer','order','payment','cancellation','refund')),external_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,request_hash TEXT NOT NULL,request_summary TEXT NOT NULL,response_status INTEGER NOT NULL,response_summary TEXT NOT NULL,replayed INTEGER NOT NULL DEFAULT 0 CHECK(replayed IN (0,1)),created_by TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(website_id,idempotency_key),FOREIGN KEY(website_id) REFERENCES partner_websites(id) ON DELETE CASCADE,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT);CREATE INDEX IF NOT EXISTS idx_partner_sandbox_runs_site ON partner_sandbox_runs(website_id,created_at DESC);`)}
export async function ensurePartnerSandboxReady(env){if(await ensurePartnerSchema(env))return true;await ensurePartnerSandboxSchema(env);return false}
export const maskedExternalId=value=>{const text=String(value||'');return text.length<5?'••••':`${text.slice(0,3)}•••${text.slice(-2)}`};
export const sandboxPayload=({scenario,externalId})=>{const time=new Date().toISOString(),orderId=scenario==='customer'?null:externalId;switch(scenario){case'customer':return{external_customer_id:externalId,name:'[MASKED]',email:'[MASKED]',phone:'[MASKED]',status:'active',created_at:time};case'order':return{external_order_id:orderId,external_customer_id:'SANDBOX-CUSTOMER',status:'pending',payment_status:'unpaid',currency:'THB',subtotal:10000,discount:0,total:10000,items:[{external_product_id:'SANDBOX-PRODUCT',title:'[MASKED PRODUCT]',quantity:1,unit_price:10000,line_total:10000}],refunds:[],created_at:time,updated_at:time};case'payment':return{external_order_id:orderId,status:'paid',payment_status:'paid',currency:'THB',total:10000,updated_at:time};case'cancellation':return{external_order_id:orderId,status:'cancelled',payment_status:'unpaid',currency:'THB',total:10000,updated_at:time};case'refund':return{external_order_id:orderId,external_refund_id:`REF-${externalId}`,status:'refunded',payment_status:'refunded',currency:'THB',total:10000,refunded_amount:10000,updated_at:time};default:return null}};
export const sandboxHash=payload=>sha256(JSON.stringify(payload));
