import {sha256} from './_lib.js';
import {encryptPartnerData,decryptPartnerData} from './_partner_crypto.js';
import {ensurePartnerSyncSchema,cleanId,forbiddenDataPath,idempotencyKey,payloadHash} from './_partner_sync.js';
import {maskedExternalId} from './_partner_sandbox.js';
import {onRequestPost as syncCustomer} from './api/partner/v1/customers/sync.js';
import {onRequestPost as syncOrder} from './api/partner/v1/orders/sync.js';
const enc=new TextEncoder(),EVENTS=new Set(['customer','order','payment','cancellation','refund']);
export async function ensurePartnerWebhookSchema(env){await ensurePartnerSyncSchema(env);await env.DB.exec(`CREATE TABLE IF NOT EXISTS partner_webhook_events (id TEXT PRIMARY KEY,website_id TEXT NOT NULL,event_type TEXT NOT NULL,external_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,signature_hash TEXT NOT NULL,request_hash TEXT NOT NULL,payload_ciphertext TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','completed','retry','dead')),attempts INTEGER NOT NULL DEFAULT 0,response_status INTEGER NOT NULL DEFAULT 0,error_code TEXT NOT NULL DEFAULT '',next_retry_at TEXT,received_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,processed_at TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(website_id,idempotency_key),UNIQUE(website_id,signature_hash),FOREIGN KEY(website_id) REFERENCES partner_websites(id) ON DELETE CASCADE);CREATE INDEX IF NOT EXISTS idx_partner_webhook_queue ON partner_webhook_events(website_id,status,next_retry_at,updated_at DESC);CREATE TABLE IF NOT EXISTS partner_webhook_logs (id TEXT PRIMARY KEY,website_id TEXT NOT NULL,event_id TEXT,level TEXT NOT NULL,event_type TEXT NOT NULL,external_id_masked TEXT NOT NULL,message TEXT NOT NULL,response_status INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(website_id) REFERENCES partner_websites(id) ON DELETE CASCADE,FOREIGN KEY(event_id) REFERENCES partner_webhook_events(id) ON DELETE SET NULL);CREATE INDEX IF NOT EXISTS idx_partner_webhook_logs_site ON partner_webhook_logs(website_id,created_at DESC);`)}
const hex=bytes=>[...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,'0')).join('');
const equal=(a,b)=>{a=String(a||'');b=String(b||'');if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0};
export async function webhookSignature(secret,timestamp,raw){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return `v1=${hex(await crypto.subtle.sign('HMAC',key,enc.encode(`${timestamp}.${raw}`)))}`}
export function validWebhookTime(timestamp,now=Date.now()){const seconds=Number(timestamp);return Number.isInteger(seconds)&&Math.abs(Math.floor(now/1000)-seconds)<=300}
export async function verifyWebhook({secret,timestamp,raw,signature,now}){if(!validWebhookTime(timestamp,now))return'TIMESTAMP_INVALID';const expected=await webhookSignature(secret,timestamp,raw);return equal(expected,signature)?'':'SIGNATURE_INVALID'}
export function webhookEnvelope(body,request){const type=String(body?.type||''),data=body?.data,externalId=cleanId(body?.external_id),key=idempotencyKey(request);if(!EVENTS.has(type)||!data||typeof data!=='object'||Array.isArray(data)||!externalId||!key)return null;if(forbiddenDataPath(data))return null;return{type,data,externalId,key}}
export async function queueWebhook(env,{websiteId,envelope,signatureHash,requestHash}){const id=`pwh_${crypto.randomUUID().replaceAll('-','')}`,cipher=await encryptPartnerData(env,JSON.stringify(envelope));await env.DB.prepare('INSERT INTO partner_webhook_events(id,website_id,event_type,external_id,idempotency_key,signature_hash,request_hash,payload_ciphertext) VALUES(?,?,?,?,?,?,?,?)').bind(id,websiteId,envelope.type,envelope.externalId,envelope.key,signatureHash,requestHash,cipher).run();return id}
export async function readWebhookPayload(env,row){return JSON.parse(await decryptPartnerData(env,row.payload_ciphertext))}
export async function webhookLog(env,{websiteId,eventId,type,externalId,level='info',message,status=0}){await env.DB.prepare('INSERT INTO partner_webhook_logs(id,website_id,event_id,level,event_type,external_id_masked,message,response_status) VALUES(?,?,?,?,?,?,?,?)').bind(`pwl_${crypto.randomUUID().replaceAll('-','')}`,websiteId,eventId||null,level,type,maskedExternalId(externalId),String(message).slice(0,160),status).run()}
export const webhookSignatureHash=signature=>sha256(String(signature||''));
export const webhookRequestHash=envelope=>payloadHash({type:envelope.type,external_id:envelope.externalId,data:envelope.data});
export const retryDelayMinutes=attempt=>Math.min(60,2**Math.max(0,attempt));
export async function processWebhookEvent(ctx,row,secret){const envelope=await readWebhookPayload(ctx.env,row),handler=envelope.type==='customer'?syncCustomer:syncOrder,url=new URL(ctx.request.url),request=new Request(`${url.origin}/api/partner/v1/${envelope.type==='customer'?'customers':'orders'}/sync`,{method:'POST',headers:{'content-type':'application/json','x-visiond-client-id':row.client_id,authorization:`Bearer ${secret}`,'idempotency-key':envelope.key,'x-request-id':row.id},body:JSON.stringify(envelope.data)}),response=await handler({...ctx,request}),body=await response.clone().json().catch(()=>({})),attempts=Number(row.attempts||0)+1,ok=response.ok,status=ok?'completed':attempts>=5?'dead':'retry',delay=retryDelayMinutes(attempts);await ctx.env.DB.prepare(`UPDATE partner_webhook_events SET status=?,attempts=?,response_status=?,error_code=?,next_retry_at=${ok||status==='dead'?'NULL':`datetime('now','+${delay} minutes')`},processed_at=${ok?'CURRENT_TIMESTAMP':'processed_at'},updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(status,attempts,response.status,ok?'':String(body.error||'PROCESSING_FAILED').slice(0,100),row.id).run();await webhookLog(ctx.env,{websiteId:row.website_id,eventId:row.id,type:row.event_type,externalId:row.external_id,level:ok?'info':'error',message:ok?'ประมวลผลสำเร็จ':status==='dead'?'ย้ายไป Dead Letter':'เข้าคิว Retry',status:response.status});return{ok,status,response_status:response.status,error:ok?'':body.error||'PROCESSING_FAILED'}}
