const PREFIX='enc:v1:',AAD=new TextEncoder().encode('visiond:seller-slip-api-key:v1');
const secret=value=>String(value||'');
export const sellerTokenEncryptionConfigured=env=>secret(env?.VISION5_TOKEN_ENCRYPTION_KEY).length>=32;
export const isEncryptedSellerToken=value=>String(value||'').startsWith(PREFIX);
const bytesToBase64=bytes=>{let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary)};
const base64ToBytes=value=>Uint8Array.from(atob(value),char=>char.charCodeAt(0));
async function encryptionKey(env){const value=secret(env?.VISION5_TOKEN_ENCRYPTION_KEY);if(value.length<32){const error=new Error('TOKEN_ENCRYPTION_NOT_CONFIGURED');error.code='TOKEN_ENCRYPTION_NOT_CONFIGURED';throw error}const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function encryptSellerToken(env,token){const value=String(token||'');const iv=crypto.getRandomValues(new Uint8Array(12)),key=await encryptionKey(env),encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:AAD},key,new TextEncoder().encode(value));return `${PREFIX}${bytesToBase64(iv)}:${bytesToBase64(new Uint8Array(encrypted))}`}
export async function decryptSellerToken(env,stored){const value=String(stored||'');if(!value)return {token:'',legacy:false};if(!isEncryptedSellerToken(value))return {token:value,legacy:true};const parts=value.slice(PREFIX.length).split(':');if(parts.length!==2)throw new Error('TOKEN_CIPHERTEXT_INVALID');const key=await encryptionKey(env);try{const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(parts[0]),additionalData:AAD},key,base64ToBytes(parts[1]));return {token:new TextDecoder().decode(plain),legacy:false}}catch{throw new Error('TOKEN_DECRYPT_FAILED')}}
export function sellerTokenStatus(env,stored){const value=String(stored||''),encrypted=isEncryptedSellerToken(value),encryption_configured=sellerTokenEncryptionConfigured(env);return {configured:value.length>=20&&(!encrypted||encryption_configured),stored:Boolean(value),encrypted,encryption_configured,requires_configuration:encrypted&&!encryption_configured}}
export async function loadSellerToken(env,userId,{migrate=true}={}){const row=await env.DB.prepare('SELECT seller_slip_api_key FROM users WHERE id=?').bind(userId).first(),stored=String(row?.seller_slip_api_key||''),result=await decryptSellerToken(env,stored);if(result.legacy&&result.token&&migrate&&sellerTokenEncryptionConfigured(env)){const encrypted=await encryptSellerToken(env,result.token);await env.DB.prepare('UPDATE users SET seller_slip_api_key=?,seller_slip_api_updated_at=CURRENT_TIMESTAMP WHERE id=? AND seller_slip_api_key=?').bind(encrypted,userId,stored).run()}return result.token}
