import {sha256} from './_lib.js';
import {encryptChannelValue} from './_channel_crypto.js';
const clean=(value,max=1000)=>String(value??'').trim().slice(0,max),seconds=value=>Math.max(0,Number(value)||0),redirectDefault='https://visiondonline.com/api/tiktok-shop/callback';
export function tikTokShopOAuthConfig(env={}){const appKey=clean(env.TIKTOK_SHOP_APP_KEY,200),appSecret=clean(env.TIKTOK_SHOP_APP_SECRET,500),redirectUri=clean(env.TIKTOK_SHOP_REDIRECT_URI,1000)||redirectDefault;return {appKey,appSecret,redirectUri,configured:Boolean(appKey&&appSecret)}}
export async function createTikTokShopState(env,userId,channelId=''){const state=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),stateHash=await sha256(state);await env.DB.batch([env.DB.prepare("DELETE FROM tiktok_shop_oauth_states WHERE expires_at<=CURRENT_TIMESTAMP OR user_id=?").bind(userId),env.DB.prepare("INSERT INTO tiktok_shop_oauth_states(state_hash,user_id,channel_id,expires_at) VALUES(?,?,?,datetime('now','+10 minutes'))").bind(stateHash,userId,clean(channelId,80))]);return state}
export async function consumeTikTokShopState(env,state,userId){const stateHash=await sha256(clean(state,200)),row=await env.DB.prepare("SELECT state_hash,user_id,channel_id FROM tiktok_shop_oauth_states WHERE state_hash=? AND user_id=? AND expires_at>CURRENT_TIMESTAMP").bind(stateHash,userId).first();if(!row)return null;const deleted=await env.DB.prepare("DELETE FROM tiktok_shop_oauth_states WHERE state_hash=? AND user_id=?").bind(stateHash,userId).run();return deleted.meta?.changes===1?row:null}
export function tikTokShopCreatorAuthorizeUrl(config,state){const url=new URL('https://shop.tiktok.com/alliance/creator/auth');url.search=new URLSearchParams({app_key:config.appKey,state}).toString();return url.href}
export async function exchangeTikTokShopCode(config,code,fetchImpl=fetch){const url=new URL('https://auth.tiktok-shops.com/api/v2/token/get');url.search=new URLSearchParams({app_key:config.appKey,app_secret:config.appSecret,auth_code:clean(code,500),grant_type:'authorized_code'}).toString();const response=await fetchImpl(url,{headers:{accept:'application/json'}}),payload=await response.json().catch(()=>({})),data=payload.data||payload;if(!response.ok||Number(payload.code)!==0||!data.access_token)throw new Error(`TIKTOK_SHOP_TOKEN_${response.status}_${clean(payload.message||payload.msg||'FAILED',120)}`);if(Number(data.user_type)!==1)throw new Error('TIKTOK_SHOP_NOT_CREATOR');return data}
const isoAfter=value=>new Date(Date.now()+seconds(value)*1000).toISOString(),scopeText=value=>Array.isArray(value)?value.join(','):clean(value,2000);
export async function saveTikTokShopCreatorConnection(env,userId,channelId,token){const openId=clean(token.open_id,300);if(!openId)throw new Error('TIKTOK_SHOP_OPEN_ID_MISSING');const existing=await env.DB.prepare('SELECT id FROM tiktok_shop_creator_connections WHERE user_id=? AND open_id=?').bind(userId,openId).first(),id=existing?.id||crypto.randomUUID(),access=await encryptChannelValue(env,token.access_token),refresh=await encryptChannelValue(env,token.refresh_token);await env.DB.prepare(`INSERT INTO tiktok_shop_creator_connections(id,user_id,channel_id,open_id,access_token_ciphertext,refresh_token_ciphertext,scopes,access_expires_at,refresh_expires_at,user_type,status) VALUES(?,?,?,?,?,?,?,?,?,1,'active') ON CONFLICT(user_id,open_id) DO UPDATE SET channel_id=excluded.channel_id,access_token_ciphertext=excluded.access_token_ciphertext,refresh_token_ciphertext=excluded.refresh_token_ciphertext,scopes=excluded.scopes,access_expires_at=excluded.access_expires_at,refresh_expires_at=excluded.refresh_expires_at,user_type=1,status='active',updated_at=CURRENT_TIMESTAMP`).bind(id,userId,clean(channelId,80),openId,access,refresh,scopeText(token.granted_scopes),isoAfter(token.access_token_expire_in||token.expires_in),isoAfter(token.refresh_token_expire_in||token.refresh_expires_in)).run();return id}
