export async function ensureToysCenterSchema(env){
  await env.DB.exec("CREATE TABLE IF NOT EXISTS toys_center_settings (id INTEGER PRIMARY KEY CHECK(id=1),storefront_mode TEXT NOT NULL DEFAULT 'unlisted' CHECK(storefront_mode IN ('public','unlisted')),updated_by INTEGER,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS toys_center_products (id INTEGER PRIMARY KEY AUTOINCREMENT,meta_id TEXT NOT NULL UNIQUE,slug TEXT NOT NULL UNIQUE,title TEXT NOT NULL,description TEXT NOT NULL,availability TEXT NOT NULL DEFAULT 'in stock',condition TEXT NOT NULL DEFAULT 'used',price_cents INTEGER NOT NULL DEFAULT 0,cost_cents INTEGER CHECK(cost_cents IS NULL OR cost_cents>=0),currency TEXT NOT NULL DEFAULT 'THB',brand TEXT NOT NULL,product_line TEXT NOT NULL DEFAULT '' CHECK(length(product_line)<=120),series TEXT NOT NULL DEFAULT '' CHECK(length(series)<=120),quantity INTEGER NOT NULL DEFAULT 1,image_1_key TEXT NOT NULL,image_2_key TEXT NOT NULL,google_product_category TEXT NOT NULL DEFAULT '',fb_product_category TEXT NOT NULL DEFAULT '',gtin TEXT NOT NULL DEFAULT '',item_group_id TEXT NOT NULL DEFAULT '',color TEXT NOT NULL DEFAULT '',size TEXT NOT NULL DEFAULT '',material TEXT NOT NULL DEFAULT '',pattern TEXT NOT NULL DEFAULT '',age_group TEXT NOT NULL DEFAULT '',gender TEXT NOT NULL DEFAULT '',product_tags TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'draft',created_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS toys_center_product_images (id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL REFERENCES toys_center_products(id) ON DELETE CASCADE,position INTEGER NOT NULL CHECK(position BETWEEN 0 AND 9),image_key TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(product_id,position));INSERT OR IGNORE INTO toys_center_settings(id,storefront_mode) VALUES(1,'unlisted');INSERT OR IGNORE INTO toys_center_product_images(product_id,position,image_key) SELECT id,0,image_1_key FROM toys_center_products WHERE image_1_key<>'';CREATE INDEX IF NOT EXISTS idx_toys_center_status_updated ON toys_center_products(status,updated_at DESC,id DESC);CREATE INDEX IF NOT EXISTS idx_toys_center_product_images_product_position ON toys_center_product_images(product_id,position);");
}
export const clean=(value,max=9999)=>String(value??'').trim().slice(0,max);
const cleanProductMetadata=value=>String(value??'').normalize('NFKC').replace(/[\u0000-\u001f\u007f]+/g,' ').trim().replace(/\s+/g,' ').slice(0,120);
const optionalMoneyCents=value=>{const raw=String(value??'').trim();if(!raw)return null;if(!/^\d+(?:\.\d{1,2})?$/.test(raw))return-1;const cents=Math.round(Number(raw)*100);return Number.isSafeInteger(cents)&&cents>=0?cents:-1};
export const slugify=value=>clean(value,100).toLowerCase().replace(/[^a-z0-9ก-๙]+/g,'-').replace(/^-|-$/g,'')||`toy-${Date.now()}`;
const imageTypes={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
const imageMagic={
  'image/jpeg':bytes=>bytes.length>=3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff,
  'image/png':bytes=>bytes.length>=8&&[0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a].every((byte,index)=>bytes[index]===byte),
  'image/webp':bytes=>bytes.length>=12&&String.fromCharCode(...bytes.subarray(0,4))==='RIFF'&&String.fromCharCode(...bytes.subarray(8,12))==='WEBP'
};
const imageError=slot=>slot==='AI'?'รูปสำหรับ AI ต้องเป็น JPG, PNG หรือ WEBP ไม่เกิน 5 MB':`รูป ${slot} ต้องเป็น JPG, PNG หรือ WEBP ไม่เกิน 5 MB`;
export function validateToyImageBuffer(buffer,type,slot){type=String(type||'').toLowerCase();const bytes=new Uint8Array(buffer);if(!imageTypes[type]||!bytes.length||bytes.byteLength>5*1024*1024||!imageMagic[type](bytes))throw new Error(imageError(slot));return{buffer,type,extension:imageTypes[type]}}
export async function readToyImage(file,slot,{required=true}={}){if(!(file instanceof File)||!file.size){if(required)throw new Error(slot==='AI'?'กรุณาเลือกรูปสำหรับ AI':`กรุณาแนบรูป ${slot}`);return null}if(file.size>5*1024*1024)throw new Error(imageError(slot));return validateToyImageBuffer(await file.arrayBuffer(),file.type,slot)}
export async function putToyImage(env,image,slot){if(!image)return'';const key=`toys-center/${crypto.randomUUID()}-${slot}.${image.extension}`;await env.FILES.put(key,image.buffer,{httpMetadata:{contentType:image.type}});return key}
export async function putToyImages(ctx,images,slot='visiond'){
  const settled=await Promise.allSettled(images.map((image,index)=>putToyImage(ctx.env,image,`${slot}-${index+1}`)));
  const keys=settled.filter(result=>result.status==='fulfilled').map(result=>result.value).filter(Boolean);
  const failed=settled.find(result=>result.status==='rejected');
  if(failed){await cleanupToyImages(ctx,keys);throw failed.reason}
  return keys;
}
export async function cleanupToyImages(ctx,keys){
  const unique=[...new Set(keys.filter(Boolean))];if(!unique.length)return;
  const remove=async pending=>{const results=await Promise.allSettled(pending.map(key=>ctx.env.FILES.delete(key)));return pending.filter((_,index)=>results[index].status==='rejected')};
  const retry=async()=>{const failed=await remove(unique);if(failed.length){const remaining=await remove(failed);if(remaining.length)console.error('TOYS_CENTER_ORPHAN_CLEANUP_PENDING',remaining.join(','))}};
  if(ctx.waitUntil)ctx.waitUntil(retry());else await retry();
}
export async function storeToyImage(env,file,slot,{required=true}={}){return putToyImage(env,await readToyImage(file,slot,{required}),slot)}
export function resolveToyCoverIndex(form,count,currentIndex=0){const raw=form.get('visiond_cover_index'),fallback=Number.isInteger(currentIndex)&&currentIndex>=0&&currentIndex<count?currentIndex:0;if(raw===null)return fallback;const value=String(raw);if(!/^(?:0|[1-9]\d*)$/.test(value))return-1;const index=Number(value);return Number.isSafeInteger(index)&&index<count?index:-1}
export function toyProductFields(form){const price=Number(form.get('price'));return {metaId:clean(form.get('meta_id'),100),slug:slugify(form.get('slug')||form.get('meta_id')),title:clean(form.get('title'),200),description:clean(form.get('description'),9999),availability:form.get('availability')==='out of stock'?'out of stock':'in stock',condition:form.get('condition')==='new'?'new':'used',priceCents:Number.isFinite(price)&&price>=0?Math.round(price*100):-1,costCents:optionalMoneyCents(form.get('cost')),brand:clean(form.get('brand'),100),productLine:cleanProductMetadata(form.get('product_line')),series:cleanProductMetadata(form.get('series')),quantity:Math.max(0,Math.min(999999,Number(form.get('quantity'))||0)),status:form.get('status')==='published'?'published':'draft',google:clean(form.get('google_product_category'),200),facebook:clean(form.get('fb_product_category'),200),gtin:clean(form.get('gtin'),100),group:clean(form.get('item_group_id'),100),color:clean(form.get('color'),100),size:clean(form.get('size'),100),material:clean(form.get('material'),100),pattern:clean(form.get('pattern'),100),age:clean(form.get('age_group'),30),gender:clean(form.get('gender'),30),tags:JSON.stringify(clean(form.get('product_tags'),500).split(',').map(x=>x.trim()).filter(Boolean).slice(0,20))}}
export const mediaUrl=(origin,id,slot)=>`${origin}/api/toys-center/images/${encodeURIComponent(id)}/${slot}`;
export const galleryUrl=(origin,id,position,version='')=>`${origin}/api/toys-center/gallery/${encodeURIComponent(id)}/${position}${version?`?v=${encodeURIComponent(version)}`:''}`;
export function publicProduct(row,origin,{gallery=[],includeMeta=false,admin=false}={}){const primaryPosition=Number.isInteger(row.primary_image_position)?row.primary_image_position:0,images=(gallery.length?gallery:[{position:primaryPosition,id:row.primary_image_id}]).slice(0,10),costCents=row.cost_cents;const visiondImages=images.map(image=>galleryUrl(origin,row.id,image.position,image.id||row.updated_at||row.id));const product={...row,product_line:cleanProductMetadata(row.product_line),series:cleanProductMetadata(row.series),price:Number(row.price_cents)/100,visiond_image_urls:visiondImages,image_1_url:admin&&row.primary_image_id?`${origin}/api/admin/toys-center/${encodeURIComponent(row.id)}/images/${primaryPosition}?v=${row.primary_image_id}`:visiondImages[0]||'',link:`${origin}/toyscenter?product=${encodeURIComponent(row.slug)}`};delete product.cost;delete product.cost_cents;delete product.image_1_key;delete product.image_2_key;delete product.image_2_url;delete product.primary_image_id;delete product.primary_image_position;if(admin){product.cost=costCents==null?null:Number(costCents)/100;product.visiond_cover_index=primaryPosition}if(includeMeta)product.image_2_url=mediaUrl(origin,row.id,2);return product}
