export async function ensureToysCenterSchema(env){
  await env.DB.exec("CREATE TABLE IF NOT EXISTS toys_center_settings (id INTEGER PRIMARY KEY CHECK(id=1),storefront_mode TEXT NOT NULL DEFAULT 'unlisted' CHECK(storefront_mode IN ('public','unlisted')),updated_by INTEGER,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS toys_center_products (id INTEGER PRIMARY KEY AUTOINCREMENT,meta_id TEXT NOT NULL UNIQUE,slug TEXT NOT NULL UNIQUE,title TEXT NOT NULL,description TEXT NOT NULL,availability TEXT NOT NULL DEFAULT 'in stock',condition TEXT NOT NULL DEFAULT 'used',price_cents INTEGER NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'THB',brand TEXT NOT NULL,quantity INTEGER NOT NULL DEFAULT 1,image_1_key TEXT NOT NULL,image_2_key TEXT NOT NULL,google_product_category TEXT NOT NULL DEFAULT '',fb_product_category TEXT NOT NULL DEFAULT '',gtin TEXT NOT NULL DEFAULT '',item_group_id TEXT NOT NULL DEFAULT '',color TEXT NOT NULL DEFAULT '',size TEXT NOT NULL DEFAULT '',material TEXT NOT NULL DEFAULT '',pattern TEXT NOT NULL DEFAULT '',age_group TEXT NOT NULL DEFAULT '',gender TEXT NOT NULL DEFAULT '',product_tags TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'draft',created_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);INSERT OR IGNORE INTO toys_center_settings(id,storefront_mode) VALUES(1,'unlisted');CREATE INDEX IF NOT EXISTS idx_toys_center_status_updated ON toys_center_products(status,updated_at DESC,id DESC);");
}
export const clean=(value,max=9999)=>String(value??'').trim().slice(0,max);
export const slugify=value=>clean(value,100).toLowerCase().replace(/[^a-z0-9ก-๙]+/g,'-').replace(/^-|-$/g,'')||`toy-${Date.now()}`;
const imageTypes={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
export async function storeToyImage(env,file,slot,{required=true}={}){if(!(file instanceof File)||!file.size){if(required)throw new Error(`กรุณาแนบรูป ${slot}`);return''}if(!imageTypes[file.type]||file.size>5*1024*1024)throw new Error(`รูป ${slot} ต้องเป็น JPG, PNG หรือ WEBP ไม่เกิน 5 MB`);const key=`toys-center/${crypto.randomUUID()}-${slot}.${imageTypes[file.type]}`;await env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});return key}
export function toyProductFields(form){const price=Number(form.get('price'));return {metaId:clean(form.get('meta_id'),100),slug:slugify(form.get('slug')||form.get('meta_id')),title:clean(form.get('title'),200),description:clean(form.get('description'),9999),availability:form.get('availability')==='out of stock'?'out of stock':'in stock',condition:form.get('condition')==='new'?'new':'used',priceCents:Number.isFinite(price)&&price>=0?Math.round(price*100):-1,brand:clean(form.get('brand'),100),quantity:Math.max(0,Math.min(999999,Number(form.get('quantity'))||0)),status:form.get('status')==='published'?'published':'draft',google:clean(form.get('google_product_category'),200),facebook:clean(form.get('fb_product_category'),200),gtin:clean(form.get('gtin'),100),group:clean(form.get('item_group_id'),100),color:clean(form.get('color'),100),size:clean(form.get('size'),100),material:clean(form.get('material'),100),pattern:clean(form.get('pattern'),100),age:clean(form.get('age_group'),30),gender:clean(form.get('gender'),30),tags:JSON.stringify(clean(form.get('product_tags'),500).split(',').map(x=>x.trim()).filter(Boolean).slice(0,20))}}
export const mediaUrl=(origin,id,slot)=>`${origin}/api/toys-center/images/${encodeURIComponent(id)}/${slot}`;
export function publicProduct(row,origin){return {...row,price:Number(row.price_cents)/100,image_1_url:mediaUrl(origin,row.id,1),image_2_url:mediaUrl(origin,row.id,2),link:`${origin}/toyscenter?product=${encodeURIComponent(row.slug)}`}}
