const encoder=new TextEncoder(),xml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]));
let crcTable;
function crc32(bytes){if(!crcTable)crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0});let crc=0xffffffff;for(const byte of bytes)crc=crcTable[(crc^byte)&255]^(crc>>>8);return(crc^0xffffffff)>>>0}
const u16=(view,offset,value)=>view.setUint16(offset,value,true),u32=(view,offset,value)=>view.setUint32(offset,value,true);
export function buildVision13Epub({id,title,items}){const book=`<?xml version="1.0" encoding="utf-8"?><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" lang="th"><head><meta charset="utf-8"/><title>${xml(title)}</title><style>body{font-family:sans-serif;line-height:1.7;margin:8%}h1{color:#075b58}.item{margin:2rem 0;page-break-inside:avoid}.cite{font-size:.82rem;color:#456}</style></head><body><h1>${xml(title)}</h1><p>VisionD · ผลิตจาก Approval Snapshot ที่ผ่านการตรวจแล้ว</p>${items.map((item,index)=>`<section class="item"><h2>${index+1}</h2><p>${xml(item.canonical_text)}</p><p class="cite">อ้างอิง: ${item.citations.map(c=>`${xml(c.source_title)} หน้า ${Number(c.page)||0}`).join(' · ')}</p></section>`).join('')}</body></html>`;
  const files=[['mimetype','application/epub+zip'],['META-INF/container.xml','<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="EPUB/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>'],['EPUB/content.opf',`<?xml version="1.0" encoding="utf-8"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id" xml:lang="th"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="book-id">urn:uuid:${xml(id)}</dc:identifier><dc:title>${xml(title)}</dc:title><dc:language>th</dc:language></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/><item id="book" href="book.xhtml" media-type="application/xhtml+xml"/></manifest><spine><itemref idref="book"/></spine></package>`],['EPUB/nav.xhtml',`<?xml version="1.0" encoding="utf-8"?><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="th"><head><title>สารบัญ</title></head><body><nav epub:type="toc"><ol><li><a href="book.xhtml">${xml(title)}</a></li></ol></nav></body></html>`],['EPUB/book.xhtml',book]].map(([name,content])=>({name:encoder.encode(name),data:encoder.encode(content)}));
  const local=[],central=[];let offset=0;for(const file of files){const crc=crc32(file.data),head=new Uint8Array(30+file.name.length),view=new DataView(head.buffer);u32(view,0,0x04034b50);u16(view,4,20);u16(view,6,0x0800);u16(view,8,0);u32(view,14,crc);u32(view,18,file.data.length);u32(view,22,file.data.length);u16(view,26,file.name.length);head.set(file.name,30);local.push(head,file.data);const center=new Uint8Array(46+file.name.length),cv=new DataView(center.buffer);u32(cv,0,0x02014b50);u16(cv,4,20);u16(cv,6,20);u16(cv,8,0x0800);u32(cv,16,crc);u32(cv,20,file.data.length);u32(cv,24,file.data.length);u16(cv,28,file.name.length);u32(cv,42,offset);center.set(file.name,46);central.push(center);offset+=head.length+file.data.length}
  const centralSize=central.reduce((sum,value)=>sum+value.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);u32(ev,0,0x06054b50);u16(ev,8,files.length);u16(ev,10,files.length);u32(ev,12,centralSize);u32(ev,16,offset);const output=new Uint8Array(offset+centralSize+end.length);let cursor=0;for(const part of [...local,...central,end]){output.set(part,cursor);cursor+=part.length}return output}
export async function sha256(value){const bytes=value instanceof Uint8Array?value:encoder.encode(String(value)),digest=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
