import {ensureVEasyShopSchema} from './_veasy_shop.js';
export const WEBHOOK_PROVIDERS=new Set(['line','facebook','easyslip','generic']);
export const cleanWebhookProvider=value=>{const v=String(value||'').trim().toLowerCase();return WEBHOOK_PROVIDERS.has(v)?v:''};
const hex=bytes=>[...bytes].map(x=>x.toString(16).padStart(2,'0')).join('');
export const newWebhookPublicId=()=>`wh_${hex(crypto.getRandomValues(new Uint8Array(24)))}`;
export const webhookOrigin=env=>{try{const u=new URL(env.APP_ORIGIN||'https://visiondonline.com');return u.protocol==='https:'?u.origin:'https://visiondonline.com'}catch{return 'https://visiondonline.com'}};
export const webhookUrl=(env,provider,publicId)=>`${webhookOrigin(env)}/hooks/v1/${provider}/${publicId}`;
export async function ensureWebhookHubSchema(env){await ensureVEasyShopSchema(env);await env.DB.exec(`CREATE TABLE IF NOT EXISTS veasy_webhook_endpoints (id TEXT PRIMARY KEY,shop_id TEXT NOT NULL REFERENCES veasy_shops(id) ON DELETE CASCADE,provider TEXT NOT NULL CHECK(provider IN ('line','facebook','easyslip','generic')),public_id TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','active','paused','revoked')),adapter_state TEXT NOT NULL DEFAULT 'pending' CHECK(adapter_state IN ('pending','ready','error')),received_count INTEGER NOT NULL DEFAULT 0,failed_count INTEGER NOT NULL DEFAULT 0,last_event_at TEXT,created_by TEXT REFERENCES users(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,revoked_at TEXT);CREATE UNIQUE INDEX IF NOT EXISTS idx_webhook_shop_provider_live ON veasy_webhook_endpoints(shop_id,provider) WHERE status!='revoked';CREATE INDEX IF NOT EXISTS idx_webhook_endpoint_shop ON veasy_webhook_endpoints(shop_id,updated_at DESC);CREATE TABLE IF NOT EXISTS veasy_webhook_events (id TEXT PRIMARY KEY,endpoint_id TEXT NOT NULL REFERENCES veasy_webhook_endpoints(id) ON DELETE RESTRICT,request_id TEXT NOT NULL UNIQUE,external_event_id TEXT NOT NULL DEFAULT '',signature_status TEXT NOT NULL DEFAULT 'pending',processing_status TEXT NOT NULL DEFAULT 'received',event_type TEXT NOT NULL DEFAULT '',error_code TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_webhook_events_endpoint ON veasy_webhook_events(endpoint_id,created_at DESC);CREATE UNIQUE INDEX IF NOT EXISTS idx_webhook_line_event_dedupe ON veasy_webhook_events(endpoint_id,external_event_id) WHERE external_event_id!='';CREATE TABLE IF NOT EXISTS veasy_channel_credentials (shop_id TEXT NOT NULL REFERENCES veasy_shops(id) ON DELETE CASCADE,provider TEXT NOT NULL CHECK(provider IN ('line')),external_account_id TEXT NOT NULL DEFAULT '',secret_ciphertext TEXT NOT NULL,token_ciphertext TEXT NOT NULL,verified_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(shop_id,provider));`)}
export const projectWebhook=(env,row)=>({...row,webhook_url:webhookUrl(env,row.provider,row.public_id),accepting_events:row.status==='active'&&row.adapter_state==='ready'});
export async function createWebhook(env,{shopId,provider,actorId}){const id=crypto.randomUUID(),publicId=newWebhookPublicId();await env.DB.prepare(`INSERT INTO veasy_webhook_endpoints(id,shop_id,provider,public_id,created_by) VALUES(?,?,?,?,?)`).bind(id,shopId,provider,publicId,actorId).run();return env.DB.prepare('SELECT * FROM veasy_webhook_endpoints WHERE id=?').bind(id).first()}
export async function mutateWebhook(env,{id,shopId,action}){const current=await env.DB.prepare(`SELECT * FROM veasy_webhook_endpoints WHERE id=? AND (? IS NULL OR shop_id=?)`).bind(id,shopId,shopId).first();if(!current)return null;if(action==='pause'&&current.status!=='revoked')await env.DB.prepare(`UPDATE veasy_webhook_endpoints SET status='paused',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(id).run();else if(action==='resume'&&current.status==='paused')await env.DB.prepare(`UPDATE veasy_webhook_endpoints SET status=CASE WHEN adapter_state='ready' THEN 'active' ELSE 'draft' END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(id).run();else if(action==='revoke'&&current.status!=='revoked')await env.DB.prepare(`UPDATE veasy_webhook_endpoints SET status='revoked',revoked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(id).run();else if(action==='rotate'&&current.status!=='revoked'){const fresh={id:crypto.randomUUID(),publicId:newWebhookPublicId()};await env.DB.batch([env.DB.prepare(`UPDATE veasy_webhook_endpoints SET status='revoked',revoked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(id),env.DB.prepare(`INSERT INTO veasy_webhook_endpoints(id,shop_id,provider,public_id,created_by) VALUES(?,?,?,?,?)`).bind(fresh.id,current.shop_id,current.provider,fresh.publicId,current.created_by)]);return env.DB.prepare('SELECT * FROM veasy_webhook_endpoints WHERE id=?').bind(fresh.id).first()}else throw new Error('WEBHOOK_ACTION_INVALID');return env.DB.prepare('SELECT * FROM veasy_webhook_endpoints WHERE id=?').bind(id).first()}
