import {json,requireAdmin} from '../../_lib.js';
import {ensureDatabase} from '../../_schema.js';

const DATE_RE=/^\d{4}-\d{2}-\d{2}$/;
const CURSOR_RE=/^([0-9T: .+Z-]{10,40})\|(\d+)$/;
const clamp=(value,fallback,max)=>Math.min(max,Math.max(1,Number.parseInt(value,10)||fallback));
const validDate=value=>{if(!DATE_RE.test(value))return false;const [year,month,day]=value.split('-').map(Number),date=new Date(Date.UTC(year,month-1,day));return date.getUTCFullYear()===year&&date.getUTCMonth()===month-1&&date.getUTCDate()===day};
function queryOptions(url){const from=url.searchParams.get('from')||'',to=url.searchParams.get('to')||'',saleType=url.searchParams.get('sale_type')||'all',exporting=url.searchParams.get('export')==='1';if(from&&!validDate(from))return {error:'วันที่เริ่มต้นไม่ถูกต้อง'};if(to&&!validDate(to))return {error:'วันที่สิ้นสุดไม่ถูกต้อง'};if(from&&to&&from>to)return {error:'วันที่เริ่มต้นต้องไม่เกินวันที่สิ้นสุด'};if(!['all','slip_sale','manual'].includes(saleType))return {error:'ประเภทรายการไม่ถูกต้อง'};const rawCursor=url.searchParams.get('cursor')||'',cursor=rawCursor.match(CURSOR_RE),cursorId=cursor?Number(cursor[2]):null;if(rawCursor&&(!cursor||!Number.isSafeInteger(cursorId)||cursorId<1))return {error:'เคอร์เซอร์ไม่ถูกต้อง'};return {from,to,saleType,exporting,limit:clamp(url.searchParams.get('limit'),exporting?200:50,200),cursor:cursor?{paid_at:cursor[1],order_id:cursorId}:null}}
function filters(options,withCursor=false){const clauses=["o.status='paid'"],values=[];if(options.from){clauses.push("date(o.updated_at,'+7 hours')>=?");values.push(options.from)}if(options.to){clauses.push("date(o.updated_at,'+7 hours')<=?");values.push(options.to)}if(options.saleType==='manual')clauses.push("o.order_no LIKE 'VD-MANUAL-%'");if(options.saleType==='slip_sale')clauses.push("o.order_no NOT LIKE 'VD-MANUAL-%'");if(withCursor&&options.cursor){clauses.push('(o.updated_at<? OR (o.updated_at=? AND o.id<?))');values.push(options.cursor.paid_at,options.cursor.paid_at,options.cursor.order_id)}return {sql:clauses.join(' AND '),values}}
export async function onRequestGet(ctx){
  await ensureDatabase(ctx.env);const auth=await requireAdmin(ctx);if(auth.error)return auth.error;
  const options=queryOptions(new URL(ctx.request.url));if(options.error)return json({error:options.error},400);const pageFilter=filters(options,true);
  const page=await ctx.env.DB.prepare(`SELECT o.id order_id,o.order_no,o.user_id,o.sale_price_recorded,o.slip_key,o.admin_note,o.created_at,o.updated_at paid_at,u.name customer_name,u.email customer_email,u.phone customer_phone,CASE WHEN o.order_no LIKE 'VD-MANUAL-%' THEN 'manual' ELSE 'slip_sale' END sale_type,CASE WHEN o.course_owner_user_id IS NULL THEN 'visiond' ELSE 'seller_course' END revenue_channel,(SELECT actor_name FROM unlock_logs ul WHERE ul.order_id=o.id ORDER BY ul.id LIMIT 1) approved_by FROM orders o JOIN users u ON u.id=o.user_id WHERE ${pageFilter.sql} ORDER BY o.updated_at DESC,o.id DESC LIMIT ?`).bind(...pageFilter.values,options.limit+1).all();
  const orders=page.results||[],hasMore=orders.length>options.limit;if(hasMore)orders.pop();let items=[];
  if(orders.length){const ids=orders.map(order=>Number(order.order_id));const lines=(await ctx.env.DB.prepare(`SELECT oi.order_id,oi.product_id,COALESCE(oi.product_title,p.title,'สินค้าเดิม') product_title,oi.price unit_price,COUNT(*) quantity,SUM(oi.price) line_total FROM order_items oi LEFT JOIN products p ON p.id=oi.product_id WHERE oi.order_id IN (${ids.map(()=>'?').join(',')}) GROUP BY oi.order_id,oi.product_id,COALESCE(oi.product_title,p.title,'สินค้าเดิม'),oi.price ORDER BY MIN(oi.id)`).bind(...ids).all()).results||[];const byOrder=new Map();for(const line of lines){const list=byOrder.get(Number(line.order_id))||[];list.push(line);byOrder.set(Number(line.order_id),list)}for(const order of orders)for(const line of byOrder.get(Number(order.order_id))||[])items.push({...order,...line,slip_url:order.slip_key?`/api/admin/slip?key=${encodeURIComponent(order.slip_key)}`:null})}
  const last=orders.at(-1),response={items,pagination:{limit:options.limit,order_count:orders.length,has_more:hasMore,next_cursor:hasMore&&last?`${last.paid_at}|${last.order_id}`:null},export:{batch:options.exporting,max_limit:200}};
  if(!options.exporting){const allFilter=filters(options);response.summary=await ctx.env.DB.prepare(`SELECT COALESCE(SUM(CASE WHEN o.sale_price_recorded=0 THEN 0 ELSE oi.price END),0) total,COALESCE(SUM(CASE WHEN o.sale_price_recorded<>0 AND o.course_owner_user_id IS NULL THEN oi.price ELSE 0 END),0) visiond_total,COALESCE(SUM(CASE WHEN o.sale_price_recorded<>0 AND o.course_owner_user_id IS NOT NULL THEN oi.price ELSE 0 END),0) seller_course_total,COUNT(DISTINCT o.id) order_count,COUNT(oi.id) item_quantity,COUNT(DISTINCT CASE WHEN o.slip_key IS NOT NULL AND o.slip_key<>'' THEN o.id END) slip_count FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE ${allFilter.sql}`).bind(...allFilter.values).first();response.products=(await ctx.env.DB.prepare(`SELECT COALESCE(oi.product_title,p.title,'สินค้าเดิม') product_title,COUNT(oi.id) quantity,COALESCE(SUM(CASE WHEN o.sale_price_recorded=0 THEN 0 ELSE oi.price END),0) total FROM orders o JOIN order_items oi ON oi.order_id=o.id LEFT JOIN products p ON p.id=oi.product_id WHERE ${allFilter.sql} GROUP BY COALESCE(oi.product_title,p.title,'สินค้าเดิม') ORDER BY quantity DESC,total DESC LIMIT 8`).bind(...allFilter.values).all()).results||[]}
  return json(response);
}
