import {json,requireBoss} from '../../_lib.js';
import {ensureDatabase} from '../../_schema.js';
import {channelEncryptionReady,decryptChannelValue,encryptChannelValue} from '../../_channel_crypto.js';
import {ensureV12Schema} from '../../_v12_schema.js';
const headers={'cache-control':'private, no-store'},clean=(v,n=300)=>String(v||'').trim().slice(0,n);
async function auth(ctx){await ensureDatabase(ctx.env);await ensureV12Schema(ctx.env);const a=await requireBoss(ctx);return a.error?{error:a.error}:a}
export async function onRequestGet(ctx){const a=await auth(ctx);if(a.error)return a.error;const row=await ctx.env.DB.prepare("SELECT external_account_id,verified_at,updated_at FROM v12_channel_credentials WHERE provider='facebook'").first();return json({encryption_ready:channelEncryptionReady(ctx.env),facebook:{configured:Boolean(row),credential_display:row?'••••••••':'',external_account_id:row?.external_account_id||'',verified_at:row?.verified_at||null}},200,headers)}
export async function onRequestPut(ctx){const a=await auth(ctx);if(a.error)return a.error;if(!channelEncryptionReady(ctx.env))return json({error:'ระบบยังไม่ได้ตั้ง VISIOND_CHANNEL_ENCRYPTION_KEY ใน Cloudflare กรุณาตั้ง Secret แล้ว Redeploy',code:'CHANNEL_ENCRYPTION_NOT_CONFIGURED'},503,headers);const body=await ctx.request.json().catch(()=>({})),token=clean(body.page_access_token,800),pageId=clean(body.page_id,120);if(token.length<40||!/^\d{5,30}$/.test(pageId))return json({error:'Page ID หรือ Page Access Token ไม่ครบ กรุณาคัดลอกค่าเต็มจาก Meta',code:'FACEBOOK_CREDENTIAL_INCOMPLETE'},400,headers);try{const encrypted=await encryptChannelValue(ctx.env,token);await ctx.env.DB.prepare("INSERT INTO v12_channel_credentials(provider,external_account_id,token_ciphertext,verified_at) VALUES('facebook',?,?,NULL) ON CONFLICT(provider) DO UPDATE SET external_account_id=excluded.external_account_id,token_ciphertext=excluded.token_ciphertext,verified_at=NULL,updated_at=CURRENT_TIMESTAMP").bind(pageId,encrypted).run();return json({ok:true,credential_display:'••••••••'},200,headers)}catch(error){console.error('V12_FACEBOOK_SAVE_FAILED',{code:String(error?.message||'').slice(0,80)});return json({error:'บันทึกไม่สำเร็จ ระบบฐานข้อมูลหรือการเข้ารหัสยังไม่พร้อม',code:'V12_FACEBOOK_SAVE_FAILED'},500,headers)}}
export async function onRequestPost(ctx){const a=await auth(ctx);if(a.error)return a.error;const row=await ctx.env.DB.prepare("SELECT external_account_id,token_ciphertext FROM v12_channel_credentials WHERE provider='facebook'").first();if(!row)return json({error:'ยังไม่มีข้อมูลที่บันทึก กรุณากดบันทึกแบบเข้ารหัสก่อน',code:'FACEBOOK_CREDENTIAL_NOT_SAVED'},400,headers);try{const token=await decryptChannelValue(ctx.env,row.token_ciphertext),response=await fetch(`https://graph.facebook.com/me/messenger_profile?fields=get_started&access_token=${encodeURIComponent(token)}`),data=await response.json().catch(()=>({}));if(!response.ok){const code=Number(data?.error?.code||0),subcode=Number(data?.error?.error_subcode||0),type=clean(data?.error?.type,60),message=code===190?'Page Access Token ไม่ถูกต้อง หมดอายุ หรือสร้างจากแอปคนละตัว':code===10||code===200?'แอปหรือ Token ไม่มีสิทธิ์ pages_messaging สำหรับเพจนี้':code===4||code===17||code===32?'Meta จำกัดจำนวนคำขอชั่วคราว กรุณารอสักครู่':'Meta ปฏิเสธ Messenger API กรุณาตรวจ Token และ pages_messaging';return json({error:`${message} (Meta ${code||response.status}${subcode?`/${subcode}`:''})`,code:`FACEBOOK_GRAPH_${code||response.status}`,meta_error:{code:code||response.status,subcode,type}},400,headers)}await ctx.env.DB.prepare("UPDATE v12_channel_credentials SET verified_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE provider='facebook'").run();return json({ok:true,page:{id:row.external_account_id,name:'Facebook Page'},messenger_profile_ready:true},200,headers)}catch(error){console.error('V12_FACEBOOK_TEST_FAILED',{code:String(error?.message||'').slice(0,80)});return json({error:'ติดต่อ Meta ไม่สำเร็จ กรุณาลองใหม่',code:'V12_FACEBOOK_TEST_FAILED'},502,headers)}}
