import {json,requireBoss} from '../../_lib.js';
import {ensureDatabase} from '../../_schema.js';
import {veasyAiProviderStatus} from '../../_veasy_line_ai.js';

const headers={'cache-control':'private, no-store'};
async function context(ctx){await ensureDatabase(ctx.env);const auth=await requireBoss(ctx);if(auth.error)return{error:auth.error};const row=await ctx.env.DB.prepare(`SELECT c.shop_id,c.verified_at,c.secret_ciphertext,s.name shop_name,s.status shop_status,COALESCE(b.state,'stopped') state,b.last_error,b.updated_at FROM v12_channel_credentials c LEFT JOIN veasy_shops s ON s.id=c.shop_id LEFT JOIN veasy_bot_state b ON b.shop_id=c.shop_id WHERE c.provider='facebook'`).first();return{auth,row}}
const snapshot=(env,row)=>{const ai=veasyAiProviderStatus(env),blockers=[];if(!row?.shop_id)blockers.push('FACEBOOK_SHOP_NOT_CONFIGURED');if(!row?.verified_at||!row?.secret_ciphertext)blockers.push('FACEBOOK_WEBHOOK_NOT_READY');if(row?.shop_status!=='active')blockers.push('SHOP_INACTIVE');if(!ai.configured)blockers.push('AI_NOT_CONFIGURED');return{configured:Boolean(row?.shop_id),shop_id:row?.shop_id||'',shop_name:row?.shop_name||'',state:row?.state||'stopped',running:row?.state==='running',ready:blockers.length===0,blockers,last_error:row?.last_error||'',updated_at:row?.updated_at||null}};
export async function onRequestGet(ctx){const value=await context(ctx);if(value.error)return value.error;return json(snapshot(ctx.env,value.row),200,headers)}
export async function onRequestPatch(ctx){const value=await context(ctx);if(value.error)return value.error;const body=await ctx.request.json().catch(()=>({})),action=body.action==='start'?'start':body.action==='stop'?'stop':'';if(!action)return json({error:'คำสั่ง V12 ไม่ถูกต้อง',code:'V12_BOT_ACTION_INVALID'},400,headers);const current=snapshot(ctx.env,value.row);if(!current.configured)return json({error:'ยังไม่ได้ผูกร้านกับ Facebook Page',code:'V12_BOT_SHOP_NOT_CONFIGURED'},409,headers);if(action==='start'&&!current.ready)return json({error:'ยังเปิด V12 ไม่ได้ กรุณาตรวจ Facebook Webhook ร้าน และ AI Provider',code:'V12_BOT_NOT_READY',blockers:current.blockers},409,headers);const state=action==='start'?'running':'stopped';await ctx.env.DB.batch([ctx.env.DB.prepare(`INSERT INTO veasy_bot_state(shop_id,state,started_at,stopped_at,updated_by) VALUES(?,?,CASE WHEN ?='running' THEN CURRENT_TIMESTAMP END,CASE WHEN ?='stopped' THEN CURRENT_TIMESTAMP END,?) ON CONFLICT(shop_id) DO UPDATE SET state=excluded.state,handoff_platform='',started_at=CASE WHEN excluded.state='running' THEN CURRENT_TIMESTAMP ELSE veasy_bot_state.started_at END,stopped_at=CASE WHEN excluded.state='stopped' THEN CURRENT_TIMESTAMP ELSE veasy_bot_state.stopped_at END,last_error='',updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP`).bind(current.shop_id,state,state,state,value.auth.user.id),...(state==='stopped'?[ctx.env.DB.prepare('DELETE FROM veasy_conversation_leases WHERE shop_id=?').bind(current.shop_id),ctx.env.DB.prepare('DELETE FROM veasy_runtime_leases WHERE shop_id=?').bind(current.shop_id)]:[]),ctx.env.DB.prepare(`INSERT INTO veasy_audit_log(id,shop_id,actor_user_id,event_type,entity_type,entity_id,detail) VALUES(?,?,?,'bot_state_changed','bot',?,?)`).bind(crypto.randomUUID(),current.shop_id,value.auth.user.id,current.shop_id,JSON.stringify({action,state,source:'v12-connect'}))]);return json({...current,state,running:state==='running',last_error:'',updated_at:new Date().toISOString()},200,headers)}
// V12-CHANNEL-001 — Boss เปิด/ปิด V12 ทั้งร้านโดยใช้ bot state และ audit เดิม
