import {json,requireBoss} from '../../_lib.js';
import {ensureDatabase} from '../../_schema.js';
import {channelEncryptionReady,decryptChannelValue,encryptChannelValue} from '../../_channel_crypto.js';
import {ensureV12Schema} from '../../_v12_schema.js';
const headers={'cache-control':'private, no-store'},clean=(value,max=300)=>String(value||'').trim().slice(0,max);
async function auth(ctx){await ensureDatabase(ctx.env);await ensureV12Schema(ctx.env);const result=await requireBoss(ctx);return result.error?{error:result.error}:result}

export async function onRequestGet(ctx){const access=await auth(ctx);if(access.error)return access.error;const row=await ctx.env.DB.prepare("SELECT external_account_id,shop_id,token_ciphertext,verified_at,secret_ciphertext,verify_token_ciphertext,updated_at FROM v12_channel_credentials WHERE provider='facebook'").first(),shops=(await ctx.env.DB.prepare("SELECT id,name FROM veasy_shops WHERE status='active' ORDER BY name LIMIT 100").all()).results||[];return json({encryption_ready:channelEncryptionReady(ctx.env),shops,facebook:{configured:Boolean(row),token_saved:Boolean(row?.token_ciphertext),app_secret_saved:Boolean(row?.secret_ciphertext),external_account_id:row?.external_account_id||'',shop_id:row?.shop_id||'',verified_at:row?.verified_at||null,webhook_ready:Boolean(row?.secret_ciphertext&&row?.verify_token_ciphertext&&row?.shop_id),callback_url:'https://visiondonline.com/hooks/v12/facebook'}},200,headers)}

export async function onRequestPut(ctx){const access=await auth(ctx);if(access.error)return access.error;if(!channelEncryptionReady(ctx.env))return json({error:'ระบบยังไม่ได้ตั้ง VISIOND_CHANNEL_ENCRYPTION_KEY ใน Cloudflare กรุณาตั้ง Secret แล้ว Redeploy',code:'CHANNEL_ENCRYPTION_NOT_CONFIGURED'},503,headers);const body=await ctx.request.json().catch(()=>({})),token=clean(body.page_access_token,800),pageId=clean(body.page_id,120),appSecret=clean(body.app_secret,300),shopId=clean(body.shop_id,80),current=await ctx.env.DB.prepare("SELECT token_ciphertext,secret_ciphertext,verify_token_ciphertext FROM v12_channel_credentials WHERE provider='facebook'").first();if(!/^\d{5,30}$/.test(pageId)||!shopId||(!current?.token_ciphertext&&token.length<40)||(!current?.secret_ciphertext&&appSecret.length<20))return json({error:'กรุณากรอก Page ID เลือกร้าน และกรอกเฉพาะ Token หรือ App Secret ที่ยังไม่เคยบันทึก',code:'FACEBOOK_CREDENTIAL_INCOMPLETE'},400,headers);if((token&&token.length<40)||(appSecret&&appSecret.length<20))return json({error:'Token หรือ App Secret ใหม่สั้นผิดปกติ กรุณาตรวจค่าอีกครั้ง',code:'FACEBOOK_CREDENTIAL_INVALID'},400,headers);if(!await ctx.env.DB.prepare("SELECT id FROM veasy_shops WHERE id=? AND status='active'").bind(shopId).first())return json({error:'ไม่พบร้านที่เลือก'},400,headers);try{const verifyToken=current?.verify_token_ciphertext?'':`v12_${crypto.randomUUID().replaceAll('-','')}`,encrypted=await Promise.all([token?encryptChannelValue(ctx.env,token):null,appSecret?encryptChannelValue(ctx.env,appSecret):null,verifyToken?encryptChannelValue(ctx.env,verifyToken):null]),tokenCiphertext=encrypted[0]||current?.token_ciphertext,secretCiphertext=encrypted[1]||current?.secret_ciphertext,verifyCiphertext=encrypted[2]||current?.verify_token_ciphertext;await ctx.env.DB.prepare("INSERT INTO v12_channel_credentials(provider,external_account_id,token_ciphertext,shop_id,secret_ciphertext,verify_token_ciphertext,verified_at) VALUES('facebook',?,?,?,?,?,NULL) ON CONFLICT(provider) DO UPDATE SET external_account_id=excluded.external_account_id,token_ciphertext=excluded.token_ciphertext,shop_id=excluded.shop_id,secret_ciphertext=excluded.secret_ciphertext,verify_token_ciphertext=excluded.verify_token_ciphertext,verified_at=CASE WHEN v12_channel_credentials.token_ciphertext=excluded.token_ciphertext THEN v12_channel_credentials.verified_at ELSE NULL END,updated_at=CURRENT_TIMESTAMP").bind(pageId,tokenCiphertext,shopId,secretCiphertext,verifyCiphertext).run();return json({ok:true,token_saved:true,app_secret_saved:true,callback_url:'https://visiondonline.com/hooks/v12/facebook',verify_token:verifyToken||undefined},200,headers)}catch(error){console.error('V12_FACEBOOK_SAVE_FAILED',{code:String(error?.message||'').slice(0,80)});return json({error:'บันทึกไม่สำเร็จ ระบบฐานข้อมูลหรือการเข้ารหัสยังไม่พร้อม',code:'V12_FACEBOOK_SAVE_FAILED'},500,headers)}}

export async function onRequestPost(ctx){const access=await auth(ctx);if(access.error)return access.error;const row=await ctx.env.DB.prepare("SELECT external_account_id,token_ciphertext FROM v12_channel_credentials WHERE provider='facebook'").first();if(!row)return json({error:'ยังไม่มีข้อมูลที่บันทึก กรุณากดบันทึกแบบเข้ารหัสก่อน',code:'FACEBOOK_CREDENTIAL_NOT_SAVED'},400,headers);try{const token=await decryptChannelValue(ctx.env,row.token_ciphertext),response=await fetch(`https://graph.facebook.com/me/messenger_profile?fields=get_started&access_token=${encodeURIComponent(token)}`),data=await response.json().catch(()=>({}));if(!response.ok){const code=Number(data?.error?.code||0),subcode=Number(data?.error?.error_subcode||0),type=clean(data?.error?.type,60),message=code===190?'Page Access Token ไม่ถูกต้อง หมดอายุ หรือสร้างจากแอปคนละตัว':code===10||code===200?'แอปหรือ Token ไม่มีสิทธิ์ pages_messaging สำหรับเพจนี้':code===4||code===17||code===32?'Meta จำกัดจำนวนคำขอชั่วคราว กรุณารอสักครู่':'Meta ปฏิเสธ Messenger API กรุณาตรวจ Token และ pages_messaging';return json({error:`${message} (Meta ${code||response.status}${subcode?`/${subcode}`:''})`,code:`FACEBOOK_GRAPH_${code||response.status}`,meta_error:{code:code||response.status,subcode,type}},400,headers)}await ctx.env.DB.prepare("UPDATE v12_channel_credentials SET verified_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE provider='facebook'").run();return json({ok:true,page:{id:row.external_account_id,name:'Facebook Page'},messenger_profile_ready:true},200,headers)}catch(error){console.error('V12_FACEBOOK_TEST_FAILED',{code:String(error?.message||'').slice(0,80)});return json({error:'ติดต่อ Meta ไม่สำเร็จ กรุณาลองใหม่',code:'V12_FACEBOOK_TEST_FAILED'},502,headers)}}
// V12-CHANNEL-001 — จัดเก็บ credential แบบเข้ารหัสและทดสอบ Facebook Page
