import {sha256} from '../../_lib.js';
import {ensureDatabase} from '../../_schema.js';
import {decryptChannelValue,encryptChannelValue} from '../../_channel_crypto.js';
import {ensureV12Schema} from '../../_v12_schema.js';
const clean=(v,n=1000)=>String(v||'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().replace(/\s+/g,' ').slice(0,n),out=(body,status=200)=>new Response(typeof body==='string'?body:JSON.stringify(body),{status,headers:{'content-type':typeof body==='string'?'text/plain;charset=utf-8':'application/json','cache-control':'no-store'}});
async function credential(env){await ensureDatabase(env);await ensureV12Schema(env);return env.DB.prepare("SELECT shop_id,secret_ciphertext,verify_token_ciphertext,token_ciphertext FROM v12_channel_credentials WHERE provider='facebook' AND verified_at IS NOT NULL").first()}
async function signatureValid(secret,raw,signature){if(!/^sha256=[0-9a-f]{64}$/i.test(signature||''))return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']),bytes=Uint8Array.from(signature.slice(7).match(/.{2}/g),x=>parseInt(x,16));return crypto.subtle.verify('HMAC',key,bytes,new TextEncoder().encode(raw))}
export async function onRequestGet(ctx){const row=await credential(ctx.env);if(!row?.verify_token_ciphertext)return out('WEBHOOK_NOT_READY',503);const url=new URL(ctx.request.url),mode=url.searchParams.get('hub.mode'),token=url.searchParams.get('hub.verify_token'),challenge=url.searchParams.get('hub.challenge')||'';try{const expected=await decryptChannelValue(ctx.env,row.verify_token_ciphertext);return mode==='subscribe'&&token===expected?out(challenge):out('VERIFY_TOKEN_INVALID',403)}catch{return out('WEBHOOK_NOT_READY',503)}}
async function processMessage(env,row,event,token){const sender=clean(event?.sender?.id,180),mid=clean(event?.message?.mid,180);if(!sender||!mid)return;const conversationId=`facebook_${(await sha256(`${row.shop_id}:${sender}`)).slice(0,48)}`,claim=await env.DB.prepare("INSERT OR IGNORE INTO veasy_message_claims(shop_id,platform_message_id,conversation_id) VALUES(?,?,?)").bind(row.shop_id,mid,conversationId).run();if(!claim.meta?.changes)return;try{const profileResponse=await fetch(`https://graph.facebook.com/${encodeURIComponent(sender)}?fields=name,profile_pic&access_token=${encodeURIComponent(token)}`),profile=await profileResponse.json().catch(()=>({})),name=profileResponse.ok?clean(profile.name,120):'ลูกค้าจาก Facebook',picture=profileResponse.ok&&/^https:\/\//i.test(profile.profile_pic||'')?clean(profile.profile_pic,500):'',participantHash=await sha256(`facebook:${sender}`),target=await encryptChannelValue(env,sender),attachment=event?.message?.attachments?.find(x=>x?.type==='image'),mediaUrl=/^https:\/\//i.test(attachment?.payload?.url||'')?clean(attachment.payload.url,1000):'',text=clean(event?.message?.text,4900),messageType=mediaUrl?'image':'text',mediaMime=mediaUrl?'image/jpeg':'',content=text||(mediaUrl?'[รูปภาพ]':'[ข้อความ Facebook]');await env.DB.batch([env.DB.prepare(`INSERT INTO veasy_conversations(shop_id,id,platform,participant_hash,display_name,profile_url) VALUES(?,?,'facebook',?,?,?) ON CONFLICT(shop_id,id) DO UPDATE SET display_name=excluded.display_name,profile_url=CASE WHEN excluded.profile_url!='' THEN excluded.profile_url ELSE veasy_conversations.profile_url END,updated_at=CURRENT_TIMESTAMP`).bind(row.shop_id,conversationId,participantHash,name,picture),env.DB.prepare(`INSERT INTO veasy_conversation_controls(shop_id,conversation_id,mode,provider,target_ciphertext) VALUES(?,?,'human','facebook',?) ON CONFLICT(shop_id,conversation_id) DO UPDATE SET target_ciphertext=excluded.target_ciphertext,updated_at=CURRENT_TIMESTAMP`).bind(row.shop_id,conversationId,target),env.DB.prepare(`INSERT OR IGNORE INTO veasy_chat_messages(id,shop_id,conversation_id,platform_message_id,role,content,message_type,media_url,media_mime) VALUES(?,?,?,?, 'user',?,?,?,?)`).bind(crypto.randomUUID(),row.shop_id,conversationId,mid,content,messageType,mediaUrl,mediaMime),env.DB.prepare("UPDATE veasy_message_claims SET status='completed',completed_at=CURRENT_TIMESTAMP WHERE shop_id=? AND platform_message_id=?").bind(row.shop_id,mid)])}catch(error){await env.DB.prepare("UPDATE veasy_message_claims SET status='failed',completed_at=CURRENT_TIMESTAMP WHERE shop_id=? AND platform_message_id=?").bind(row.shop_id,mid).run().catch(()=>{});console.error('V12_FACEBOOK_WEBHOOK_MESSAGE_FAILED',{messageId:mid,error:clean(error?.message,80)})}}
export async function onRequestPost(ctx){const row=await credential(ctx.env);if(!row?.secret_ciphertext||!row?.shop_id)return out({error:'WEBHOOK_NOT_READY'},503);const raw=await ctx.request.text();try{const secret=await decryptChannelValue(ctx.env,row.secret_ciphertext);if(!await signatureValid(secret,raw,ctx.request.headers.get('x-hub-signature-256')))return out({error:'SIGNATURE_INVALID'},401);const payload=JSON.parse(raw),token=await decryptChannelValue(ctx.env,row.token_ciphertext),jobs=[];for(const entry of payload.entry||[])for(const event of entry.messaging||[])if(event?.message&&!event.message.is_echo)jobs.push(processMessage(ctx.env,row,event,token));ctx.waitUntil(Promise.all(jobs));return out({ok:true})}catch(error){console.error('V12_FACEBOOK_WEBHOOK_FAILED',{error:clean(error?.message,80)});return out({error:'WEBHOOK_PROCESS_FAILED'},400)}}
