import {json,requireBoss} from '../../../../_lib.js';
import {ensureDatabase} from '../../../../_schema.js';
import {decryptPartnerSecret} from '../../../../_partner_crypto.js';
import {buildPartnerAlerts,ensurePartnerHealthSchema} from '../../../../_partner_health.js';
import {processWebhookEvent} from '../../../../_partner_webhook.js';
import {maskedExternalId} from '../../../../_partner_sandbox.js';
const headers={'cache-control':'private, no-store'};
async function auth(ctx){await ensureDatabase(ctx.env);await ensurePartnerHealthSchema(ctx.env);const value=await requireBoss(ctx);if(value.error)return{error:value.error};const website=await ctx.env.DB.prepare('SELECT id,name,status,client_id,secret_ciphertext,secret_last4 FROM partner_websites WHERE id=?').bind(ctx.params.id).first();return website?{user:value.user,website}:{error:json({error:'ไม่พบเว็บไซต์คู่ค้า'},404,headers)}}
const safeEvent=row=>({id:row.id,event_type:row.event_type,external_id_masked:maskedExternalId(row.external_id),idempotency_key_masked:maskedExternalId(row.idempotency_key),status:row.status,attempts:Number(row.attempts)||0,response_status:Number(row.response_status)||0,duration_ms:Number(row.duration_ms)||0,error_code:row.error_code||'',next_retry_at:row.next_retry_at,received_at:row.received_at,updated_at:row.updated_at});
export async function onRequestGet(ctx){const a=await auth(ctx);if(a.error)return a.error;const [events,logs,stats,security]=await Promise.all([ctx.env.DB.prepare('SELECT * FROM partner_webhook_events WHERE website_id=? ORDER BY updated_at DESC LIMIT 100').bind(a.website.id).all(),ctx.env.DB.prepare('SELECT level,event_type,external_id_masked,message,response_status,created_at FROM partner_webhook_logs WHERE website_id=? ORDER BY created_at DESC LIMIT 100').bind(a.website.id).all(),ctx.env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN status='retry' THEN 1 ELSE 0 END) retry,SUM(CASE WHEN status='dead' THEN 1 ELSE 0 END) dead,COALESCE(ROUND(AVG(CASE WHEN duration_ms>0 THEN duration_ms END)),0) avg_duration_ms,COALESCE(MAX(duration_ms),0) max_duration_ms,MAX(received_at) latest_event_at FROM partner_webhook_events WHERE website_id=? AND received_at>=datetime('now','-24 hours')`).bind(a.website.id).first(),ctx.env.DB.prepare(`SELECT SUM(CASE WHEN message='SIGNATURE_INVALID' THEN 1 ELSE 0 END) signature_errors,SUM(CASE WHEN message='TIMESTAMP_INVALID' THEN 1 ELSE 0 END) timestamp_errors FROM partner_webhook_logs WHERE website_id=? AND created_at>=datetime('now','-24 hours')`).bind(a.website.id).first()]);const total=Number(stats?.total)||0,completed=Number(stats?.completed)||0,retry=Number(stats?.retry)||0,dead=Number(stats?.dead)||0,health={window_hours:24,total,completed,retry,dead,error_rate_percent:total?Number((((retry+dead)/total)*100).toFixed(2)):0,avg_duration_ms:Number(stats?.avg_duration_ms)||0,max_duration_ms:Number(stats?.max_duration_ms)||0,latest_event_at:stats?.latest_event_at||null,signature_errors:Number(security?.signature_errors)||0,timestamp_errors:Number(security?.timestamp_errors)||0};return json({website:{id:a.website.id,name:a.website.name,status:a.website.status,credential_display:`${maskedExternalId(a.website.client_id)} / ••••${a.website.secret_last4}`},callback_url:`${new URL(ctx.request.url).origin}/api/partner/v1/webhooks/events`,signature_contract:'v1=HMAC_SHA256(secret, timestamp + "." + raw_body)',health,alerts:buildPartnerAlerts({signatureErrors:health.signature_errors,timestampErrors:health.timestamp_errors,retry,dead}),events:(events.results||[]).map(safeEvent),logs:logs.results||[]},200,headers)}
export async function onRequestPost(ctx){const a=await auth(ctx);if(a.error)return a.error;const body=await ctx.request.json().catch(()=>({})),eventId=String(body.event_id||''),action=String(body.action||'');if(!eventId||!['retry','dead'].includes(action))return json({error:'WEBHOOK_ACTION_INVALID'},400,headers);const row=await ctx.env.DB.prepare('SELECT e.*,w.client_id FROM partner_webhook_events e JOIN partner_websites w ON w.id=e.website_id WHERE e.id=? AND e.website_id=?').bind(eventId,a.website.id).first();if(!row)return json({error:'ไม่พบ Event'},404,headers);if(action==='dead'){await ctx.env.DB.prepare("UPDATE partner_webhook_events SET status='dead',next_retry_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.id).run();return json({ok:true,status:'dead'},200,headers)}if(!['retry','dead'].includes(row.status))return json({error:'Event นี้ไม่อยู่ใน Retry หรือ Dead Letter'},409,headers);const result=await processWebhookEvent(ctx,row,await decryptPartnerSecret(ctx.env,a.website.secret_ciphertext));return json(result,result.ok?200:202,headers)}
