import {json,requireUser} from '../../../../_lib.js';
import {ensureDatabase} from '../../../../_schema.js';
const safeExt=name=>{const x=String(name||'').split('.').pop()?.toLowerCase().replace(/[^a-z0-9]/g,'');return x?.slice(0,12)||'bin'};
async function ownedLesson(ctx,user){return ctx.env.DB.prepare("SELECT l.*,c.edit_expires_at,c.product_id,c.license_entitlement_id FROM course_lessons l JOIN courses c ON c.id=l.course_id JOIN products p ON p.id=c.product_id WHERE l.id=? AND l.course_id=? AND c.owner_user_id=? AND c.course_origin='seller_rights' AND p.deleted_at IS NULL").bind(ctx.params.lessonId,ctx.params.id,user.id).first()}
async function locked(ctx){return Boolean(await ctx.env.DB.prepare("SELECT id FROM orders WHERE seller_course_id=? AND status IN ('pending_review','paid') LIMIT 1").bind(ctx.params.id).first())}
const expired=lesson=>lesson.edit_expires_at&&Date.parse(lesson.edit_expires_at)<=Date.now();

export async function onRequestPut(ctx){
  await ensureDatabase(ctx.env);const auth=await requireUser(ctx);if(auth.error)return auth.error;const lesson=await ownedLesson(ctx,auth.user);if(!lesson)return json({error:'ไม่พบ EP'},404);
  if(await locked(ctx))return json({error:'หลังมียอดขาย เปลี่ยนแปลงเนื้อหาทั้งหมดไม่ได้ หากแก้ข้อผิดพลาดภายในต้องติดต่อ VisionD เท่านั้น'},409);if(expired(lesson))return json({error:'หมดระยะเวลาแก้ไข 30 วันแล้ว'},403);
  const form=await ctx.request.formData(),title=String(form.get('title')||'').trim().slice(0,200),description=String(form.get('description')||'').slice(0,5000),duration=Number(form.get('duration_seconds')||0),video=form.get('video'),documents=form.getAll('documents').filter(x=>x instanceof File&&x.size);
  if(!title)return json({error:'กรุณาใส่ชื่อ EP'},400);if(!Number.isInteger(duration)||duration<0||duration>86400)return json({error:'ระยะเวลาต้องเป็นวินาทีจำนวนเต็ม 0–86,400'},400);
  if(video?.size&&(!['video/mp4','video/webm'].includes(video.type)||video.size>200*1024*1024))return json({error:'คลิปต้องเป็น MP4 หรือ WEBM ไม่เกิน 200 MB'},400);if(documents.some(file=>file.size>200*1024*1024))return json({error:'ไฟล์ประกอบแต่ละไฟล์ต้องไม่เกิน 200 MB'},400);
  if(documents.length>20)return json({error:'แนบไฟล์ประกอบได้ไม่เกิน 20 ไฟล์ต่อครั้ง'},400);
  let newVideo=null,uploaded=[];try{
    if(video?.size){newVideo=`seller-course-${lesson.course_id}-video-${crypto.randomUUID()}.${safeExt(video.name)}`;await ctx.env.FILES.put(newVideo,video.stream(),{httpMetadata:{contentType:video.type}})}
    const current=await ctx.env.DB.prepare('SELECT COALESCE(MAX(sort_order),0) n FROM course_lesson_files WHERE lesson_id=?').bind(lesson.id).first(),statements=[ctx.env.DB.prepare(`UPDATE course_lessons SET title=?,description=?,duration_seconds=?,video_key=CASE WHEN ? IS NULL THEN video_key ELSE ? END,video_mime=CASE WHEN ? IS NULL THEN video_mime ELSE ? END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND course_id=?`).bind(title,description,duration,newVideo,newVideo,newVideo,video?.type||null,lesson.id,lesson.course_id)];
    for(let i=0;i<documents.length;i++){const file=documents[i],key=`seller-course-${lesson.course_id}-file-${crypto.randomUUID()}.${safeExt(file.name)}`;await ctx.env.FILES.put(key,file.stream(),{httpMetadata:{contentType:file.type||'application/octet-stream'}});uploaded.push(key);statements.push(ctx.env.DB.prepare('INSERT INTO course_lesson_files(lesson_id,object_key,file_name,mime_type,file_size,sort_order) VALUES(?,?,?,?,?,?)').bind(lesson.id,key,String(file.name||`file-${i+1}`).slice(0,240),file.type||'application/octet-stream',file.size,Number(current.n)+(i+1)*10))}
    statements.push(ctx.env.DB.prepare("UPDATE courses SET total_minutes=(SELECT CAST(COALESCE(SUM(duration_seconds),0)/60 AS INTEGER) FROM course_lessons WHERE course_id=?),review_status=CASE WHEN license_entitlement_id IS NULL THEN 'draft' ELSE 'pending' END,submitted_at=CASE WHEN license_entitlement_id IS NULL THEN submitted_at ELSE CURRENT_TIMESTAMP END,active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(lesson.course_id,lesson.course_id));statements.push(ctx.env.DB.prepare("UPDATE products SET status='draft',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(lesson.product_id));await ctx.env.DB.batch(statements);
    if(newVideo&&lesson.video_key)await ctx.env.FILES.delete(lesson.video_key).catch(()=>{});return json({ok:true,id:lesson.id,file_count:documents.length,message:'บันทึกข้อมูล EP แล้ว'});
  }catch(error){if(newVideo)await ctx.env.FILES.delete(newVideo).catch(()=>{});for(const key of uploaded)await ctx.env.FILES.delete(key).catch(()=>{});return json({error:'บันทึก EP ไม่สำเร็จ กรุณาลองใหม่'},500)}
}

export async function onRequestDelete(ctx){await ensureDatabase(ctx.env);const auth=await requireUser(ctx);if(auth.error)return auth.error;const lesson=await ownedLesson(ctx,auth.user);if(!lesson)return json({error:'ไม่พบ EP'},404);if(await locked(ctx))return json({error:'หลังส่งสลิปหรือมียอดขายแล้ว เปลี่ยนแปลงเนื้อหาไม่ได้ หากแก้ข้อผิดพลาดภายในต้องติดต่อ VisionD เท่านั้น'},409);if(expired(lesson))return json({error:'หมดระยะเวลาแก้ไข 30 วันแล้ว'},403);const count=await ctx.env.DB.prepare('SELECT COUNT(*) n FROM course_lessons WHERE course_id=?').bind(lesson.course_id).first();if(Number(count?.n)<=1)return json({error:'คอร์สต้องมีอย่างน้อย 1 EP แก้ข้อมูล EP นี้แทนการลบ'},409);const files=await ctx.env.DB.prepare('SELECT object_key FROM course_lesson_files WHERE lesson_id=?').bind(lesson.id).all();const bound=lesson.license_entitlement_id!==null;await ctx.env.DB.batch([ctx.env.DB.prepare('DELETE FROM course_lessons WHERE id=?').bind(lesson.id),ctx.env.DB.prepare("UPDATE courses SET expected_episodes=(SELECT COUNT(*) FROM course_lessons WHERE course_id=?),total_minutes=(SELECT CAST(COALESCE(SUM(duration_seconds),0)/60 AS INTEGER) FROM course_lessons WHERE course_id=?),review_status=?,submitted_at=CASE WHEN ?=1 THEN CURRENT_TIMESTAMP ELSE submitted_at END,active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(ctx.params.id,ctx.params.id,bound?'pending':'draft',bound?1:0,ctx.params.id),ctx.env.DB.prepare("UPDATE products SET pages=(SELECT COUNT(*) FROM course_lessons WHERE course_id=?),status='draft',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(ctx.params.id,lesson.product_id)]);if(lesson.video_key)await ctx.env.FILES.delete(lesson.video_key).catch(()=>{});if(lesson.pdf_key)await ctx.env.FILES.delete(lesson.pdf_key).catch(()=>{});for(const file of files.results||[])await ctx.env.FILES.delete(file.object_key).catch(()=>{});return json({ok:true,message:bound?'ลบ EP แล้วและส่งให้ Boss ตรวจซ้ำ':'ลบ EP และไฟล์ทั้งหมดแล้ว'})}
