(function installVisionDThaiMartContent(scope){
  'use strict';
  if(scope!==scope.top)return;
  const Core=scope.VisionDThaiMartCore,Config=scope.VisionDThaiMartSelectors;
  if(!Core||!Config)throw new Error('VisionD Thai Mart extension dependencies are missing');
  let generation=0,activeController=null;
  const normalize=value=>String(value??'').replace(/\s+/g,' ').trim();
  const exactText=value=>String(value??'').replace(/\r\n?/g,'\n');
  const isVisible=element=>{if(!(element instanceof Element)||element.hidden)return false;const style=getComputedStyle(element),rect=element.getBoundingClientRect();return style.display!=='none'&&style.visibility!=='hidden'&&style.opacity!=='0'&&rect.width>0&&rect.height>0};
  const unique=items=>[...new Set(items.filter(Boolean))];
  const fieldResult=(field,status,extra={})=>({field,status,...extra});
  const failure=(code,message,fields=[],details={})=>({ok:false,code,message,fields,details});
  const targetPage=()=>location.protocol==='https:'&&location.host===Config.target.host&&location.pathname===Config.target.path;
  const guard=(job,...elements)=>{if(job.signal.aborted||job.id!==generation||job.href!==location.href||!targetPage()||elements.some(element=>element&&(!element.isConnected||!isVisible(element))))throw new DOMException('Stale Thai Mart fill generation','AbortError')};

  function exactVisible(selector,root=document){return unique([...root.querySelectorAll(selector)].filter(element=>isVisible(element)&&!element.disabled))}
  function textNodes(labels,root=document){const wanted=new Set(labels.map(normalize));return [...root.querySelectorAll('label,legend,span,div,p,strong,h1,h2,h3')].filter(node=>isVisible(node)&&wanted.has(normalize(node.textContent)))}
  function scopedControl(labels,selector){
    const matches=[];
    for(const label of textNodes(labels)){
      if(label.matches('label')&&label.control?.matches(selector)&&isVisible(label.control))matches.push(label.control);
      let current=label;
      for(let depth=0;current&&depth<7;depth++,current=current.parentElement){const controls=exactVisible(selector,current);if(controls.length===1){matches.push(controls[0]);break}}
    }
    const controls=unique(matches);return controls.length===1?{ok:true,element:controls[0]}:{ok:false,count:controls.length};
  }
  function galleryContext(input){
    let current=input.parentElement;
    for(let depth=0;current&&depth<8&&!current.matches('form,main,body,html');depth++,current=current.parentElement){
      const text=normalize(current.textContent),hasLabel=textNodes(Config.gallery.sectionLabels,current).length>0,excluded=Config.gallery.excludedSectionText.some(term=>text.includes(term));
      if(excluded&&!hasLabel)return null;
      if(hasLabel&&!excluded)return current;
    }
    return null;
  }
  function locateGallery(){
    const candidates=exactVisible('input[type="file"][multiple]').filter(input=>{const accept=String(input.accept||input.getAttribute('accept')||'');return Config.gallery.allowedAccept.test(accept)&&!/pdf|video/i.test(accept)}).map(element=>({element,context:galleryContext(element)})).filter(item=>item.context);
    return candidates.length===1?{ok:true,...candidates[0]}:{ok:false,count:candidates.length};
  }
  function locateCategory(){return scopedControl(Config.category.labels,'select,[role="combobox"]')}
  function locateForm(){
    const controls={};for(const[key,selector]of Object.entries(Config.fields)){const items=exactVisible(selector);controls[key]=items.length===1?{ok:true,element:items[0]}:{ok:false,count:items.length}}
    const description=scopedControl(Config.description.labels,Config.description.selector),category=locateCategory(),gallery=locateGallery();
    return{controls,description,category,gallery,evidence:Object.values(controls).filter(item=>item.ok).length+Number(description.ok)+Number(category.ok)+Number(gallery.ok)};
  }
  function requiredDrift(located){const fields=[];for(const[key,result]of Object.entries(located.controls))if(!result.ok)fields.push(fieldResult(key,'selector_drift',{matches:result.count}));for(const key of['description','category','gallery'])if(!located[key].ok)fields.push(fieldResult(key,'selector_drift',{matches:located[key].count}));return fields}
  function assertCurrent(job,located){
    const elements=[...Object.values(located.controls).map(item=>item.element),located.description.element,located.category.element,located.gallery.element,located.gallery.context];guard(job,...elements);
    const current=locateForm();for(const key of Object.keys(located.controls))if(!current.controls[key].ok||current.controls[key].element!==located.controls[key].element)throw new DOMException('Thai Mart field identity changed','AbortError');
    if(!current.description.ok||current.description.element!==located.description.element||!current.category.ok||current.category.element!==located.category.element||!current.gallery.ok||current.gallery.element!==located.gallery.element||current.gallery.context!==located.gallery.context)throw new DOMException('Thai Mart form identity changed','AbortError');
  }
  function waitForForm(job,timeout=5000){const immediate=locateForm();if(immediate.evidence>=8)return Promise.resolve(immediate);return new Promise(resolve=>{let settled=false;const finish=result=>{if(settled)return;settled=true;observer.disconnect();clearTimeout(timer);job.signal.removeEventListener('abort',aborted);resolve(result)};const observer=new MutationObserver(()=>{const found=locateForm();if(found.evidence>=8)finish(found)}),timer=setTimeout(()=>finish(locateForm()),timeout),aborted=()=>finish({evidence:0,aborted:true});observer.observe(document.documentElement,{childList:true,subtree:true});job.signal.addEventListener('abort',aborted,{once:true})})}

  function runtimeMessage(payload){return new Promise(resolve=>chrome.runtime.sendMessage(payload,response=>{if(chrome.runtime.lastError)return resolve({ok:false,code:'extension_message'});resolve(response||{ok:false,code:'extension_message'})}))}
  const getState=()=>runtimeMessage({type:'VISIOND_THAIMART_GET_FILL_STATE'}),setState=state=>runtimeMessage({type:'VISIOND_THAIMART_SET_FILL_STATE',state});
  const decode=value=>{const binary=atob(value),bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);return bytes};
  function fetchImage(image,productId,job){return new Promise(resolve=>{guard(job);const port=chrome.runtime.connect({name:'visiond-thaimart-image-fetch'}),chunks=[];let meta=null,total=0,done=false;const finish=value=>{if(done)return;done=true;clearTimeout(timer);job.signal.removeEventListener('abort',abort);try{port.disconnect()}catch{}resolve(value)},abort=()=>finish({ok:false,code:'stale_generation'}),timer=setTimeout(()=>finish({ok:false,code:'image_timeout'}),15000);job.signal.addEventListener('abort',abort,{once:true});port.onDisconnect.addListener(()=>{if(!done)finish({ok:false,code:'worker_disconnected'})});port.onMessage.addListener(message=>{if(!message?.ok)return finish(message||{ok:false,code:'image_download'});if(message.type==='start'){meta=message;return}if(message.type==='chunk'){const bytes=decode(message.data);total+=bytes.length;if(total>10*1024*1024)return finish({ok:false,code:'image_too_large'});chunks.push(bytes);return}if(message.type==='end'){if(!meta||total!==meta.size)return finish({ok:false,code:'image_transfer'});finish({ok:true,mime:meta.mime,extension:meta.extension,chunks,size:total})}});port.postMessage({type:'fetch',url:image.url,productId})})}
  async function prepareImages(images,productId,job){const files=[];let aggregate=0;for(let index=0;index<images.length;index++){guard(job);const response=await fetchImage(images[index],productId,job);guard(job);if(!response.ok)return failure(response.code||'image_download',`ดาวน์โหลดรูปที่ ${index+1} ไม่สำเร็จ`,[],{index,response});aggregate+=response.size;if(aggregate>90*1024*1024)return failure('image_aggregate','ขนาดรูปรวมเกินขอบเขต 90 MiB');const name=index===0?`visiond-cover-01.${response.extension}`:`visiond-image-${String(index+1).padStart(2,'0')}.${response.extension}`;files.push(new File(response.chunks,name,{type:response.mime,lastModified:Date.now()}))}return{ok:true,files,aggregate}}
  function assignFiles(input,files){const transfer=new DataTransfer();files.forEach(file=>transfer.items.add(file));input.files=transfer.files;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}
  function galleryCounter(input,context){const matches=[...normalize(context?.textContent).matchAll(/(?:^|\D)(\d+)\s*\/\s*9(?:\D|$)/g)].map(match=>Number(match[1])),current=Math.max(Number(input.files?.length||0),...(matches.length?matches:[0]));return{current,capacity:Config.gallery.capacity}}
  function uploadErrors(scope){const failureText=/(?:ไม่สำเร็จ|ล้มเหลว|ผิดพลาด|ไม่สามารถ|เกิน|failed|error|invalid)/i,uploadText=/(?:อัปโหลด|รูปสินค้า|รูปภาพ|รูป|upload|image)/i;return unique([...scope.querySelectorAll('[role="alert"],[aria-live="assertive"],.error,[class*="error" i]')].filter(isVisible).map(element=>normalize(element.textContent)).filter(text=>failureText.test(text)&&uploadText.test(text)))}
  function waitForFiles(input,context,errorScope,expected,job,baselineErrors=[],timeout=8000){return new Promise(resolve=>{let settled=false,stableTimer=null;const finish=value=>{if(settled)return;settled=true;observer.disconnect();clearTimeout(timer);clearTimeout(stableTimer);job.signal.removeEventListener('abort',aborted);resolve(value)},errorsNow=()=>uploadErrors(errorScope).filter(error=>!baselineErrors.includes(error)),inspect=()=>{const errors=errorsNow(),counter=galleryCounter(input,context);if(errors.length)return finish({observed:false,error:'image_upload_error',errors,...counter});if(counter.current>expected)return finish({observed:false,error:'image_count_conflict',...counter});if(counter.current===expected){if(!stableTimer)stableTimer=setTimeout(()=>{const delayed=errorsNow(),latest=galleryCounter(input,context);if(delayed.length)return finish({observed:false,error:'image_upload_error',errors:delayed,...latest});if(latest.current!==expected)return finish({observed:false,error:'image_count_conflict',...latest});finish({observed:true,...latest})},600)}else if(stableTimer){clearTimeout(stableTimer);stableTimer=null}},observer=new MutationObserver(inspect),timer=setTimeout(()=>finish({observed:false,...galleryCounter(input,context)}),timeout),aborted=()=>finish({observed:false,aborted:true});observer.observe(errorScope,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['class','hidden','style','aria-hidden']});job.signal.addEventListener('abort',aborted,{once:true});inspect()})}

  function nativeSet(control,value){const text=String(value);if(control.isContentEditable){control.textContent=text;control.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}));control.dispatchEvent(new Event('change',{bubbles:true}));return}const prototype=control instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:control instanceof HTMLSelectElement?HTMLSelectElement.prototype:HTMLInputElement.prototype,setter=Object.getOwnPropertyDescriptor(prototype,'value')?.set;if(!setter)throw new Error('control_setter_missing');setter.call(control,text);control.dispatchEvent(new Event('input',{bubbles:true}));control.dispatchEvent(new Event('change',{bubbles:true}));control.dispatchEvent(new FocusEvent('blur',{bubbles:true}))}
  const readValue=control=>control.isContentEditable?control.textContent:control.value;
  async function setAndVerify(control,value,job,{multiline=false}={}){guard(job,control);nativeSet(control,value);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));guard(job,control);const actual=multiline?exactText(readValue(control)):String(readValue(control)),expected=multiline?exactText(value):String(value);if(actual!==expected)throw new Error('readback_mismatch')}
  function nearestInteractive(element){return element.closest('button,input,a[href],[role="button"]')}
  function nonSubmittingClickTarget(element){const interactive=nearestInteractive(element);if(!interactive)return true;if(interactive instanceof HTMLAnchorElement)return false;if(interactive instanceof HTMLButtonElement)return interactive.type==='button';if(interactive instanceof HTMLInputElement)return['button','checkbox','radio'].includes(interactive.type);return interactive===element&&interactive.getAttribute('role')==='button'&&!interactive.closest('form')}
  function allowedCategoryControl(control){if(control instanceof HTMLSelectElement)return true;if(control.getAttribute('role')!=='combobox')return false;if(control instanceof HTMLButtonElement)return control.type==='button';if(control instanceof HTMLInputElement)return['text','search'].includes(control.type)&&nonSubmittingClickTarget(control);return nonSubmittingClickTarget(control)}
  function clickAllowedCategory(element,kind,root){if(kind==='control'){if(!allowedCategoryControl(element))throw new Error('category_control_not_allowlisted')}else if(!root?.contains(element)||!['option','treeitem','menuitem'].includes(element.getAttribute('role'))||!['DIV','LI','SPAN'].includes(element.tagName)||!nonSubmittingClickTarget(element))throw new Error('category_option_not_allowlisted');element.click()}
  async function categoryRoot(control,job){const id=control.getAttribute('aria-controls');if(id){const root=document.getElementById(id);if(root&&isVisible(root))return root}const before=new Set(exactVisible('[role="dialog"],[role="listbox"],[role="menu"],[role="tree"]'));clickAllowedCategory(control,'control');const deadline=Date.now()+3000;while(Date.now()<deadline){guard(job,control);const roots=exactVisible('[role="dialog"],[role="listbox"],[role="menu"],[role="tree"]').filter(root=>!before.has(root));if(roots.length===1)return roots[0];if(roots.length>1)throw new Error('category_root_ambiguous');await new Promise(resolve=>setTimeout(resolve,50))}throw new Error('category_root_missing')}
  const categoryReadback=control=>normalize(control instanceof HTMLSelectElement?control.selectedOptions[0]?.textContent:control.value||control.textContent||control.getAttribute('aria-label'));
  async function selectCategory(control,path,job){const joined=path.join(' > '),read=()=>categoryReadback(control);if(read()===joined)return;if(control instanceof HTMLSelectElement){const options=[...control.options].filter(option=>normalize(option.textContent)===joined);if(options.length!==1)throw new Error('category_option_missing');await setAndVerify(control,options[0].value,job);if(read()!==joined)throw new Error('category_readback');return}const root=await categoryRoot(control,job);for(const segment of path){const deadline=Date.now()+3000;let option=null;while(Date.now()<deadline){guard(job,control,root);const options=exactVisible('[role="option"],[role="treeitem"],[role="menuitem"]',root).filter(item=>normalize(item.textContent)===normalize(segment));if(options.length===1){option=options[0];break}if(options.length>1)throw new Error('category_option_ambiguous');await new Promise(resolve=>setTimeout(resolve,50))}if(!option)throw new Error('category_option_missing');clickAllowedCategory(option,'option',root)}await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));guard(job,control);if(read()!==joined)throw new Error('category_readback')}
  const isBlankValue=(value,{multiline=false}={})=>(multiline?exactText(value):String(value??'')).trim()==='';
  function existingFieldConflicts(located,values){
    const conflicts=[];
    for(const key of['name','sku','price','stock','weight','width','length','height']){const current=String(readValue(located.controls[key].element));if(!isBlankValue(current)&&current!==String(values[key]))conflicts.push(fieldResult(key,'conflict',{current_value_present:true}))}
    const description=exactText(readValue(located.description.element));if(!isBlankValue(description,{multiline:true})&&description!==exactText(values.description))conflicts.push(fieldResult('description','conflict',{current_value_present:true}));
    const category=categoryReadback(located.category.element),expectedCategory=Core.CATEGORY_PATH.join(' > ');if(category&&category!==expectedCategory)conflicts.push(fieldResult('category','conflict',{current_value_present:true}));
    return conflicts;
  }
  function valuesMatch(located,values){return readValue(located.controls.name.element)===values.name&&exactText(readValue(located.description.element))===exactText(values.description)&&readValue(located.controls.sku.element)===values.sku&&readValue(located.controls.price.element)===values.price&&readValue(located.controls.stock.element)===values.stock&&readValue(located.controls.weight.element)===values.weight&&readValue(located.controls.width.element)===values.width&&readValue(located.controls.length.element)===values.length&&readValue(located.controls.height.element)===values.height&&categoryReadback(located.category.element)===Core.CATEGORY_PATH.join(' > ')}

  async function fillThaiMart(handoff,initial,job,state){
    const drift=requiredDrift(initial);if(drift.length)return failure('selector_drift','ไม่พบช่อง Thai Mart แบบเอกลักษณ์',drift);
    assertCurrent(job,initial);const images=handoff.product.images,counter=galleryCounter(initial.gallery.element,initial.gallery.context);if(images.length>counter.capacity)return failure('image_capacity',`Thai Mart รับได้ ${counter.capacity} รูป แต่ JSON มี ${images.length} รูป`,[fieldResult('images','blocked',{payload_count:images.length,platform_capacity:counter.capacity})]);
    const fingerprint=Core.handoffFingerprint(handoff),prior=state?.state,values=Core.fieldValues(handoff);
    if(prior&&prior.fingerprint!==fingerprint)return failure('changed_payload_conflict','ฟอร์มนี้เคยกรอกด้วย JSON คนละสินค้า กรุณาเปิดหน้าสร้างสินค้าใหม่');
    const conflicts=existingFieldConflicts(initial,values);
    if(counter.current>0){if(prior?.fingerprint===fingerprint&&prior.status==='files_selected'&&counter.current===images.length&&valuesMatch(initial,values))return{ok:true,code:'thaimart_unchanged',page:'thaimart',message:'ข้อมูลและไฟล์รูปชุดนี้ตรงกับ JSON เดิม จึงไม่กรอกซ้ำ',fields:[fieldResult('images','unchanged',{count:counter.current,confirmation:'input_files_observed'})]};if(conflicts.length)return failure('existing_field_conflict','พบข้อมูลฉบับร่างเดิมที่ไม่ตรงกับ JSON จึงไม่เขียนทับอัตโนมัติ',conflicts);return failure('existing_media_conflict','พบรูปหรือข้อมูลเดิมที่ไม่ตรงกับสถานะ handoff จึงไม่เขียนทับอัตโนมัติ',[fieldResult('images','conflict',{current:counter.current})])}
    if(conflicts.length)return failure('existing_field_conflict','พบข้อมูลฉบับร่างเดิมที่ไม่ตรงกับ JSON จึงไม่เขียนทับอัตโนมัติ',conflicts);
    const prepared=await prepareImages(images,handoff.product.visiond_product_id,job);if(!prepared.ok)return prepared;assertCurrent(job,initial);
    const pending=await setState({fingerprint,status:'pending',count:images.length});if(!pending.ok)return failure('state_unavailable','บันทึกสถานะ idempotency ไม่สำเร็จ จึงยังไม่แตะฟอร์ม Thai Mart');
    try{await selectCategory(initial.category.element,handoff.product.category_path,job)}catch(error){return failure('selector_drift','Thai Mart ไม่ยืนยันหมวดหมู่แบบปลอดภัย',[],{reason:error.message})}
    let located=locateForm(),afterCategoryDrift=requiredDrift(located);if(afterCategoryDrift.length)return failure('selector_drift','ช่อง Thai Mart เปลี่ยนหลังเลือกหมวดหมู่',afterCategoryDrift);guard(job);
    const errorScope=located.gallery.element.closest('main')||located.gallery.element.closest('form')||located.gallery.context.parentElement||located.gallery.context,baselineErrors=uploadErrors(errorScope);if(baselineErrors.length)return failure('image_upload_error','พบข้อผิดพลาดรูปบน Thai Mart ก่อนเริ่ม',[fieldResult('images','blocked',{errors:baselineErrors})]);
    assertCurrent(job,located);assignFiles(located.gallery.element,prepared.files);const confirmation=await waitForFiles(located.gallery.element,located.gallery.context,errorScope,images.length,job,baselineErrors);guard(job);
    if(!confirmation.observed){await setState({fingerprint,status:'partial',count:confirmation.current||0,expected:images.length,error:confirmation.error||null});return failure(confirmation.error||'image_selection_unconfirmed',confirmation.error==='image_upload_error'?'Thai Mart แสดงข้อผิดพลาดหลังเลือกไฟล์รูป':'Thai Mart ไม่ยืนยันจำนวนไฟล์รูปตาม JSON',[fieldResult('images','partial',{observed_count:confirmation.current||0,expected_count:images.length,errors:confirmation.errors||[]})])}
    located=locateForm();const postMediaDrift=requiredDrift(located);if(postMediaDrift.length)return failure('selector_drift','ช่อง Thai Mart เปลี่ยนหลังเลือกไฟล์รูป',postMediaDrift);
    try{for(const key of['name','sku','price','stock','weight','width','length','height']){assertCurrent(job,located);await setAndVerify(located.controls[key].element,values[key],job)}assertCurrent(job,located);await setAndVerify(located.description.element,values.description,job,{multiline:true})}catch(error){await setState({fingerprint,status:'partial',count:images.length});return failure('readback_mismatch','Thai Mart ไม่ยืนยันค่าหลังกรอกแบบ exact readback',[],{reason:error.message})}
    const completed=await setState({fingerprint,status:'files_selected',count:images.length,confirmation:'input_files_observed'});if(!completed.ok)return failure('state_unavailable','เลือกไฟล์และกรอกข้อมูลแล้ว แต่บันทึกสถานะ idempotency ไม่สำเร็จ',[fieldResult('images','files_selected',{count:images.length})]);
    return{ok:true,code:'thaimart_filled',page:'thaimart',message:'เลือกไฟล์รูปและกรอกข้อมูล Thai Mart แล้ว โปรดตรวจทุกช่องและกดบันทึกด้วยตนเอง',fields:[fieldResult('category','confirmed'),fieldResult('images','files_selected',{count:images.length,confirmation:'input_files_observed'}),...['name','description','sku','price','stock','weight','width','length','height'].map(key=>fieldResult(key,'confirmed'))],final_submit_automated:false};
  }
  async function runFill(raw,job){if(!targetPage())return failure('page_mismatch','เปิด https://seller.thaimart.com/products/create ก่อน');const checked=Core.validateHandoff(raw);if(!checked.ok)return failure('invalid_handoff','JSON Thai Mart ไม่ผ่านการตรวจสอบ',[],{errors:checked.errors});const located=await waitForForm(job);guard(job);if(located.evidence<8)return failure('page_mismatch','ไม่พบฟอร์มสร้างสินค้า Thai Mart ที่รองรับภายในเวลาที่กำหนด');const state=await getState();guard(job);if(!state.ok)return failure('state_unavailable','อ่านสถานะ idempotency ของแท็บนี้ไม่สำเร็จ จึงยกเลิกก่อนกรอก');return fillThaiMart(checked.value,located,job,state)}
  function startFill(raw){activeController?.abort();activeController=new AbortController();const job={id:++generation,href:location.href,signal:activeController.signal};return runFill(raw,job).catch(error=>error?.name==='AbortError'?failure('stale_generation','หน้าถูกเปลี่ยนระหว่างกรอก จึงยกเลิกงานเก่า'):failure('unexpected',String(error?.message||error)))}
  chrome.runtime.onMessage.addListener((request,_sender,sendResponse)=>{if(request?.type==='VISIOND_THAIMART_PING'){sendResponse({ok:true,target:targetPage()});return false}if(request?.type!=='VISIOND_THAIMART_FILL_CURRENT')return false;startFill(request.handoff).then(sendResponse);return true});
  scope.VisionDThaiMartContentTest=Object.freeze({startFill,locateForm,locateGallery,galleryCounter,allowedCategoryControl,existingFieldConflicts});
})(globalThis);
