import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const [version,index,admin,page,ui,create,update,roadmap]=await Promise.all([read('VERSION.txt'),read('public/index.html'),read('public/admin.html'),read('public/v12-connect.html'),read('public/admin.js'),read('functions/api/admin/products/index.js'),read('functions/api/admin/products/[id].js'),read('VISIOND-ROADMAP.md')]);
assert.equal(version.trim(),'v0.14.206');assert.match(index,/WEB v0\.14\.206/);assert.match(admin,/ADMIN v0\.14\.206/);assert.match(admin,/admin\.js\?v=014206/);assert.match(page,/v0\.14\.206/);
for(const token of ['eligibleCategories','set-${esc(category.slug)}','bundleSourceCategory','currentSourceCategory','productCategorySelect.options[0]?.value','p.source === "bundle"'])assert.ok(ui.includes(token),`frontend coverage missing ${token}`);
assert.ok(!ui.includes("'<option value=\"set-coloring\">คละแบบระบายสี</option><option value=\"set-tattoo\">คละแบบรอยสัก</option>'"));
for(const source of [create,update]){assert.match(source,/\^set-\[a-z0-9\]/);assert.ok(source.includes('INSERT OR IGNORE INTO categories'));assert.ok(source.includes("sourceCategory"));}assert.ok(update.includes('DELETE FROM bundle_source_allocations WHERE bundle_product_id=?'));
assert.match(roadmap,/Dynamic Bundle Categories/);
console.log('v0.14.206 dynamic bundle categories and events: PASS');
