import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const [api,menu,css,catalog,register,ledger]=await Promise.all([read('functions/api/products/index.js'),read('public/mobile-storefront.js'),read('public/mobile-storefront.css'),read('public/catalog-sync.js'),read('public/register.html'),read('patch-ledgers/v0.14.173.json')]);
assert.doesNotMatch(api,/purgeExpiredTrash/);
assert.doesNotMatch(api,/analytics_daily|page_views/);
assert.match(api,/catalog_counts/);
assert.match(api,/max-age=30/);
assert.match(menu,/pageshow/);
assert.match(menu,/mobile-nav-backdrop.*remove/);
assert.match(css,/body\.mobile-nav-open \.mobile-nav-backdrop:not\(\[hidden\]\)/);
assert.match(register,/mobile-storefront\.(?:css|js)\?v=014173/);
assert.match(catalog,/โปรยกชุด/);
assert.match(catalog,/VISIOND_CATALOG_COUNT_MISMATCH/);
assert.equal(JSON.parse(ledger).version,'0.14.173');
console.log('v0.14.173 catalog/mobile contract: PASS');
