import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('public/index.html','utf8');
const css=fs.readFileSync('public/home-modern-ai.css','utf8');
assert.equal(fs.readFileSync('VERSION.txt','utf8').trim(),'v0.14.144');
assert.match(html,/home-vlearning-preview/);
assert.match(html,/vlearning-home-preview-v014144\.png/);
assert.match(html,/href="#courses">ดูคอร์สที่เปิดเรียน/);
assert.doesNotMatch(html,/home-hero-dual|home-hero-digital/);
assert.doesNotMatch(css,/home-hero-dual|home-hero-digital/);
assert.ok(fs.statSync('public/assets/vlearning-home-preview-v014144.png').size>100000);
assert.match(html,/WEB v0\.14\.144/);
assert.match(fs.readFileSync('public/admin.html','utf8'),/ADMIN v0\.14\.144/);
console.log('v0.14.144 V-Learning preview checks passed');
