import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=path=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.292');
const source=read('public/course-draft-first-ep.js');
const review=read('functions/api/admin/course-seller-reviews/[id].js');
const catalog=read('functions/api/courses/index.js');
assert.match(source,/submit\.textContent='ส่งตรวจ'/);
assert.match(source,/async function submitForReview\(courseId\)/);
assert.ok(source.includes('/publish`'), 'must call the existing publish API');
assert.ok(source.indexOf('await uploadEpisode(')<source.indexOf('await submitForReview(createdCourseId)'), 'all EP uploads must finish before review submission');
assert.match(source,/confirm_permanent:true/);
assert.ok(source.includes('ลองส่งตรวจอีกครั้ง'));
assert.ok(!source.includes("submit.textContent='บันทึกตะกร้าคอร์สพร้อม EP'"));
assert.match(review,/c\.course_plan/);
assert.match(review,/partner=course\.course_plan==='partner'/);
assert.match(review,/productStatus:'published'/);
assert.match(review,/active=1/);
assert.match(catalog,/c\.active=1 AND p\.status='published'/);
console.log('v0.14.292 direct course review submission: PASS');
