import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {ensureV12SalesAssistantSchema} from '../functions/api/admin/v12-sales-assistant.js';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const [version,index,admin,page,ui,api]=await Promise.all([read('VERSION.txt'),read('public/index.html'),read('public/admin.html'),read('public/v12-connect.html'),read('public/v12-sales-assistant.js'),read('functions/api/admin/v12-sales-assistant.js')]);
assert.match(version.trim(),/^v0\.14\.(248|249)$/);
assert.match(index,/WEB v0\.14\.(248|249)/);assert.match(admin,/ADMIN v0\.14\.(248|249)/);assert.match(page,/v0\.14\.(248|249)/);
assert.ok(api.includes('ensureV12SalesAssistantSchema(ctx.env)'));
assert.ok(api.includes('CREATE TABLE IF NOT EXISTS v12_lead_insights'));
assert.ok(api.includes('วิเคราะห์บทสนทนาไม่สำเร็จ (${code})'));
assert.ok(ui.includes('HTTP ${response.status}'));
assert.ok(ui.includes('ติดต่อระบบวิเคราะห์ไม่สำเร็จ'));
let sql='';
await ensureV12SalesAssistantSchema({DB:{exec:async value=>{sql=value}}});
assert.match(sql,/CREATE TABLE IF NOT EXISTS v12_lead_insights/);
assert.match(sql,/CREATE INDEX IF NOT EXISTS idx_v12_lead_insights_stage/);
console.log('v0.14.248 V12 sales assistant production schema recovery: PASS');
