import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=file=>fs.readFileSync(file,'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.85');
const payment=read('functions/_payment.js'),settings=read('functions/api/admin/payment-settings.js');
const create=read('functions/api/orders/index.js'),slip=read('functions/api/orders/[id]/slip.js');
const approve=read('functions/api/admin/orders/[id]/approve.js'),reject=read('functions/api/admin/orders/[id]/reject.js');
const orders=read('functions/api/admin/orders.js'),admin=read('public/admin.js'),rights=read('public/course-rights-product.js');
assert.match(payment,/vision5_rights_auto_verify/);
assert.match(settings,/auth\.user\.role==='boss'/);
assert.match(settings,/vision5_rights_easyslip_toggled/);
assert.match(create,/if\(payment\.vision5_rights_auto_verify\)/);
assert.match(slip,/VISION5_RIGHTS_MANUAL_MODE/);
assert.match(slip,/กำลังรอ Boss ตรวจและอนุมัติสิทธิ์/);
assert.match(orders,/boss_can_review_rights/);
assert.match(approve,/a\.user\.role!=='boss'/);
assert.match(approve,/slip_verification_status!=='manual'/);
assert.match(approve,/b\.confirmed!==true/);
assert.match(approve,/boss_rights_slip_approval/);
assert.match(approve,/ออเดอร์นี้ถูกดำเนินการแล้ว จึงไม่เพิ่มเครดิตซ้ำ/);
assert.match(reject,/เฉพาะ Boss ปฏิเสธสลิปตะกร้าสิทธิ์ได้/);
assert.match(reject,/!note/);
assert.match(admin,/Boss อนุมัติและเพิ่มเครดิต/);
assert.match(admin,/confirmed: rights/);
assert.match(rights,/rights-payment-mode/);
const ledger=JSON.parse(read('requirements-ledger.json'));
assert.equal(ledger.requirements.find(x=>x.id==='EC-V5-RIGHTS-SLIP-001')?.status,'DONE-VERIFIED');
console.log('v0.14.85 Vision 5 rights EasySlip switch and Boss fallback checks passed');
