import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import assert from'node:assert/strict';const root=new URL('../',import.meta.url),r=p=>fs.readFileSync(new URL(p,root),'utf8');
assert.equal(r('VERSION.txt').trim(),'v0.14.382');assert.match(r('public/index.html'),/WEB v0\.14\.382/);assert.match(r('public/admin.html'),/ADMIN v0\.14\.382/);
const map=r('FEATURE-MAP.md'),home=r('public/index.html'),dashboard=r('public/dashboard.html'),badge=r('public/course-owner-badge.js'),card=r('public/course-owner-dashboard.js'),api=r('functions/api/course-seller/index.js');
for(const x of['COURSE-OWNER-ENTRY-001','`PARTIAL`','active homepage badge','dormant dashboard credit card','ไม่พบ HTML หรือ JS ที่โหลด','async','ไม่อ้าง global dedupe','NAV-SHELL-001','MEMBER-HUB-001','COURSE-BASKET-001'])assert.ok(map.includes(x),x);
assert.match(home,/id="navMember"/);assert.match(home,/src="\/course-owner-badge\.js\?v=014304"/);assert.match(dashboard,/id="dashIdentity"/);
assert.equal((badge.match(/dataset\.feature='COURSE-OWNER-ENTRY-001'/g)||[]).length,2);assert.match(badge,/fetch\('\/api\/auth\/me',\{cache:'no-store'\}\)/);assert.match(badge,/!user\?\.is_course_owner/);assert.match(badge,/href='\/course-center'/);assert.match(badge,/homeMember\.querySelector\('\.course-owner-badge'\)/);
assert.equal((card.match(/dataset\.feature='COURSE-OWNER-ENTRY-001'/g)||[]).length,1);assert.match(card,/fetch\('\/api\/course-seller',\{cache:'no-store'\}\)/);assert.match(card,/credit_balance/);assert.match(card,/balance>0/);assert.match(card,/\/course-center\?create=1/);assert.match(card,/course-selling-rights/);assert.match(api,/requireUser/);assert.match(api,/credit_balance: licenses\.filter\(\(x\) => x\.available\)\.length/);
const publicDir=fileURLToPath(new URL('public/',root)),loaders=fs.readdirSync(publicDir).filter(name=>/\.(?:html|js)$/.test(name)&&name!=='course-owner-dashboard.js').map(name=>fs.readFileSync(path.join(publicDir,name),'utf8')).join('\n');assert.doesNotMatch(loaders,/course-owner-dashboard\.js/);
console.log('PASS v0.14.382 Course Owner Entry PARTIAL Feature Map');
