import fs from 'node:fs';import assert from 'node:assert/strict';
const read=path=>fs.readFileSync(path,'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.77');
const bindings=read('wrangler.toml.example');assert.match(bindings,/binding = "ELON_WEB_DB"/);assert.match(bindings,/binding = "ELON_V7_DB"/);
const boundary=read('functions/_elon_databases.js');assert.match(boundary,/if\(!env\.ELON_WEB_DB\)throw/);assert.match(boundary,/if\(!env\.ELON_V7_DB\)throw/);assert.doesNotMatch(boundary,/env\.DB\s*\|\||\?\?\s*env\.DB/);
const store=read('functions/_elon-member-store.js');assert.match(store,/elonWebDb\(env\)/);assert.doesNotMatch(store,/env\.DB/);assert.match(store,/`ew_\$\{crypto\.randomUUID\(\)\}`/);
for(const file of ['functions/api/elon/chat.js','functions/api/elon/clear.js','functions/api/elon/conversations.js'])assert.match(read(file),/ensureElonWebSchema/);
const core=read('functions/_schema.js');assert.doesNotMatch(core,/CREATE TABLE IF NOT EXISTS elon_(?:conversations|messages|rate_limits|usage_limits)/);
const webMigration=read('elon-web-migrations/0001_elon_web_isolated.sql'),v7Migration=read('elon-v7-migrations/0001_elon_v7_boundary.sql');assert.match(webMigration,/elon_web_conversations/);assert.doesNotMatch(webMigration,/elon_v7_/);assert.match(v7Migration,/elon_v7_/);assert.doesNotMatch(v7Migration,/elon_web_/);
assert.equal(JSON.parse(read('requirements-ledger.json')).requirements.find(item=>item.id==='EC-ELON-DB-001')?.status,'DONE-VERIFIED');
console.log('v0.14.77 ELON database hard split passed');
