import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=(file)=>fs.readFileSync(new URL(`../${file}`,import.meta.url),'utf8');
const version=read('VERSION.txt'),html=read('public/course-center.html'),center=read('public/course-center.js'),seller=read('public/course-seller.js'),all=html+center+seller;
assert.match(version,/v0\.14\.278/);
assert.match(center,/ซื้อสิทธิ์ 499 บาท/);
assert.match(center,/ใช้ 1 เครดิตต่อ 1 คอร์ส · เงินเข้าผู้สอนโดยตรง/);
assert.match(center,/ไม่จำกัดคอร์สและ EP/);
assert.match(center,/เงินเข้า VisionD · ระบบตรวจสลิปและแบ่งรายได้อัตโนมัติ/);
assert.match(center,/ผู้สอน 50% \/ VisionD 50%/);
assert.match(seller,/function showCurrentCourseEditAction\(course\)/);
assert.match(seller,/currentCourseEditAction/);
assert.match(seller,/course-basket-edit\.html\?id=/);
assert.match(seller,/แก้ไขข้อมูลตะกร้าคอร์สนี้/);
assert.match(seller,/showCurrentCourseEditAction\(course\)/);
assert.doesNotMatch(all,/เลือกเข้าแบบ 1, 2 หรือ 3|เลือกสร้างคอร์สแบบ 1, 2 หรือ 3|เริ่มขายฟรี|เข้าแบบ 3/);
console.log('v0.14.278 focused tests: PASS');
