import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const src=readFileSync('public/tiktok-analyzer.js','utf8'),html=readFileSync('public/tiktok-analyzer.html','utf8'),css=readFileSync('public/tiktok-analyzer.css','utf8');
const cut=(a,b)=>src.slice(src.indexOf(a),src.indexOf(b,src.indexOf(a)));
const nodes=new Map(),make=()=>({hidden:true,dataset:{},value:'',textContent:'',innerHTML:'',classList:{add(){},remove(){},toggle(){}},querySelector:()=>null,querySelectorAll:()=>[],removeAttribute(){},insertAdjacentHTML(){},scrollIntoView(){}}),$=s=>{if(s==='[data-field="direction"]')return null;if(!nodes.has(s))nodes.set(s,make());return nodes.get(s)};
const form=new Proxy(make(),{get:(t,k)=>k in t?t[k]:(t[k]=make())});
const pending=new Map(),state={selected:null,connectionLoadSeq:0},s={$,form,state,document:{body:make()},URL,encodeURIComponent,renderChannels(){},resetMarketplaceView(){},upgradeLegacyProductLinkCells(){},escapeHtml:x=>String(x??''),arrayValue:x=>Array.isArray(x)?x:[],textValue:x=>String(x||''),normalizeProductName:x=>String(x||''),typeLabels:{},api:url=>new Promise(r=>pending.set(new URL(url,'https://fixture.invalid').searchParams.get('channel_id'),r))};
vm.createContext(s);vm.runInContext(cut('function createTikTokChannelOwnership','const $ =')+'\nconst channelOwnership=createTikTokChannelOwnership(()=>state.selected);'+cut('function clearChannelOwnedView()','async function refreshOwnedInventory')+'\n'+cut('async function selectChannel(id, context)','function newChannel()')+'\n'+cut('function list(values, render)','const renderResultBase = renderResult;')+`\nfunction stampChannelOwnedActions(root,c){root.dataset.channelOwner=c.channelId}this.choose=id=>{state.selected=id;const c=channelOwnership.begin(id);clearChannelOwnedView();return selectChannel(id,c)};`,s);
const payload=id=>({channel:{id,name:id},products:[],runs:id==='A'?[{result:{summary:'Saved A only'}}]:[]});
for(const id of ['A','B','C','A']){const p=s.choose(id);pending.get(id)(payload(id));await p;assert.equal($('#result').hidden,false,id+' scaffold visible');assert.equal($('#result').dataset.channelOwner,id);assert.equal($('[data-field="summary"]').textContent,id==='A'?'Saved A only':'ยังไม่มีสรุป');if(id!=='A'){assert.match($('[data-list="ai-recommendations"]').innerHTML,/ยังไม่มีข้อมูลพอ/);assert.match($('[data-list="plan"]').innerHTML,/ยังไม่มีข้อมูลพอ/)}}
const late=s.choose('A'),current=s.choose('B');pending.get('B')(payload('B'));await current;pending.get('A')(payload('A'));await late;assert.equal($('#result').dataset.channelOwner,'B');assert.equal($('[data-field="summary"]').textContent,'ยังไม่มีสรุป');
assert.match(html,/id="manualCForm"/);assert.match(html,/id="analyzeAiRecommendations"/);assert.match(css,/\.workspace-output\.shop-connected #angelInventory\{display:none!important\}/,'legacy duplicate inventory remains hidden');
console.log('PASS v89 actual selection/render A→emptyB/C→A and lateA guard; truthful scaffold/controls/Shop CSS preserved');
