import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=file=>fs.readFileSync(new URL(`../${file}`,import.meta.url),'utf8');
const api=read('functions/api/admin/daily-tasks.js'),html=read('public/daily-tasks.html'),js=read('public/daily-tasks.js'),css=read('public/daily-tasks.css'),migration=read('migrations/0069_daily_personal_tasks.sql'),admin=read('public/admin.html');
for(const label of ['ลง Zippo','ทำแคตตาล็อก','Toyskub','ทำสินค้าดิจิทัล','ยิงแอด','บอท TikTok','ขายของ','กิจกรรมอื่นๆ'])assert.ok(api.includes(label),`missing default: ${label}`);
assert.ok(api.includes('requireAdmin(ctx)'),'API must require admin');
assert.ok((api.match(/auth\.user\.id/g)||[]).length>=6,'all mutations and reads must scope by current user');
assert.ok(api.includes('user_id=? AND task_date=?'),'queries must scope account and date');
assert.ok(api.includes('AND is_custom=1'),'delete/custom lookup must reject default tasks');
assert.match(migration,/UNIQUE\(user_id,task_date,task_key\)/);
assert.match(migration,/VALUES\('core',69\)/);
assert.ok(html.includes('<table class="daily-table">'),'daily work must render as a table');
assert.ok(html.includes('data-feature="DAILY-TASKS-001"'));
assert.ok(admin.includes('/daily-tasks.html'));
assert.ok(css.includes('.daily-table tr.is-incomplete td')&&css.includes('#fff1f2'),'incomplete tasks must be red');
assert.ok(js.includes("strong.textContent=task.label"),'custom labels must render as text, not HTML');
assert.ok(js.includes("action:'toggle'")&&js.includes("action:'add'"));
assert.equal(read('VERSION.txt').trim(),'v0.14.421');
assert.ok(read('public/index.html').includes('WEB v0.14.421'));
assert.ok(admin.includes('ADMIN v0.14.421'));
console.log('PASS v0.14.421 daily personal tasks');
