import fs from 'node:fs';
import assert from 'node:assert/strict';
import { COURSE_PLANS, courseRevenue } from '../functions/_course_plans.js';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.333');
assert.match(read('public/index.html'),/WEB v0\.14\.333/);
assert.match(read('public/admin.html'),/ADMIN v0\.14\.333/);
assert.equal(COURSE_PLANS.partner.apiFee,0);
assert.deepEqual(courseRevenue('partner',100000),{teacher:50000,visiond:50000,apiFee:0});
assert.deepEqual(courseRevenue('partner',99999),{teacher:49999,visiond:50000,apiFee:0});
const sales=read('functions/api/course-seller/sales.js'),index=read('functions/api/course-seller/index.js'),ui=read('public/course-center.js'),html=read('public/course-center.html');
assert.match(sales,/CAST\(o\.total \/ 2 AS INTEGER\)/);
assert.doesNotMatch(sales,/THEN o\.teacher_revenue/);
assert.match(sales,/next_clear_date/);
assert.match(sales,/clear_day: 1/);
assert.match(index,/CAST\(o\.total \/ 2 AS INTEGER\)/);
assert.match(index,/THEN 0 ELSE o\.course_api_fee/);
assert.match(ui,/ไม่หักค่า API/);
assert.match(ui,/เคลียร์ทุกวันที่ 1/);
assert.match(html,/เคลียร์ยอดทุกวันที่ 1/);
console.log('PASS v0.14.333 partner revenue has no API deduction and dashboard shows day-1 cycle');
