import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=(file)=>fs.readFileSync(new URL(`../${file}`,import.meta.url),'utf8');
const version=read('VERSION.txt'),seller=read('public/course-seller.js'),html=read('public/course-seller.html');
assert.equal(version.trim(),'v0.14.279');
assert.match(seller,/const licenseList = document\.querySelector\("#licenseList"\)/);
assert.match(seller,/createCourseBasket = document\.querySelector\("#createCourseBasket"\)/);
assert.match(seller,/if \(licenseList\) licenseList\.innerHTML/);
assert.match(seller,/licenseList\?\.querySelectorAll/);
assert.match(seller,/if \(createCourseBasket\) createCourseBasket\.hidden = true/);
assert.match(seller,/startCourseForm\.disabled = !state \|\| credit < 1/);
assert.match(seller,/credit > 0\s*\? "เริ่มกรอกข้อมูลคอร์ส"/);
assert.match(seller,/sellerCourseForm\.querySelector\('button\[type="submit"\]'\)\.disabled=plan==="rights"&&credit<1/);
assert.match(html,/id="licenseList">กำลังโหลด/);
assert.match(html,/id="createCourseBasket"/);
console.log('v0.14.279 course type 1 creation path: PASS');
