import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';

import './test-v020141-vsport-project-delete.mjs';
import './test-v020141-vsport-project-delete-browser.mjs';

const root=new URL('../',import.meta.url),read=relative=>readFile(new URL(relative,root)),text=async relative=>(await read(relative)).toString('utf8'),sha256=async relative=>createHash('sha256').update(await read(relative)).digest('hex').toUpperCase();
const [version,home,admin,html,css,client,foundation,api,featureMap,packageText,migration111,migration115]=await Promise.all(['VERSION.txt','public/index.html','public/admin.html','public/vsport.html','public/vsport.css','public/vsport.js','functions/_vsport.js','functions/api/admin/vsport.js','FEATURE-MAP.md','package.json','migrations/0111_vsport.sql','migrations/0115_vsport_project_delete.sql'].map(text));
assert.equal(version.trim(),'v0.20.141');assert.match(home,/WEB v0\.20\.141/);assert.match(admin,/ADMIN v0\.20\.141/);assert.match(html,/src="\/vsport\.js\?v=020141"/);assert.doesNotMatch(html,/vsport\.js\?v=020140/);
assert.match(client,/vds-btn vds-btn--danger','ลบ'/);assert.match(client,/Idempotency-Key/);assert.match(client,/expected_title/);assert.match(client,/projectListVersion/);assert.match(client,/deletedProjectIds/);assert.match(client,/cleanupKeyBase='visiond_vsport_delete_cleanup_v1'/);assert.match(client,/cleanupLockKeyBase='visiond_vsport_delete_cleanup_lock_v1'/);assert.match(client,/CLEANUP_REPLAY_DELAYS=\[250,5000,30000\]/);assert.match(client,/rememberPendingCleanup\(candidate,\{ifAbsent:true\}\)/,'confirmed intent is persisted before its first request');assert.match(client,/navigator\.locks\?\.request/);assert.match(client,/withStorageCleanupLock/);assert.match(client,/currentPendingCleanup\(record\)/);assert.match(client,/isAuthoritativeCleanupTerminal/);assert.match(client,/cleanup_pending===false/);assert.match(client,/result\.cleanup_pending===true\?'pending':'malformed'/);assert.match(api,/export async function onRequestDelete/);assert.match(api,/CLEANUP_LIMIT=24/);assert.match(api,/exactObjectCleanup/);assert.match(api,/reason='orphan_guard'/);assert.doesNotMatch(api,/FILES\.(?:list|delete)\([^)]*vsport\//);
assert.match(migration115,/CREATE TABLE IF NOT EXISTS vsport_project_deletions/);assert.match(migration115,/CREATE TABLE IF NOT EXISTS vsport_object_cleanup_jobs/);assert.match(migration115,/idx_vsport_cleanup_state_due/);assert.match(migration115,/idx_vsport_candidates_project_ingest/);assert.match(featureMap,/owner-scoped project delete/);
assert.equal(await sha256('functions/_vsport.js'),'F14100C24027793FB9AD65CA1BB2D0779FAE5A53B7FE65C14E4258A828D1F180','v0.20.140 discovery helper remains byte-identical');assert.equal(await sha256('public/vsport.css'),'262CE0A73E4044B3F2FEABBD4DE65C5C98D635EDFD44AAABFEF2B395111A0EFC','V Sport CSS remains byte-identical');assert.equal(await sha256('functions/api/admin/vsport-assets/[id].js'),'6BEF06AD1B137C56707D6F01CE0F86777CB79D8D6EFF108C763F9C07EAB4A434','asset route remains byte-identical');assert.equal(await sha256('migrations/0111_vsport.sql'),'0AD1F2DA8B5833615BAE8967A7953CB75F83CE9ABEBAC12E5F1E4CEC2321A59D','authoritative cascade schema remains byte-identical');
const packageJson=JSON.parse(packageText);assert.equal(packageJson.scripts['test:v020141'],'node scripts/test-v020141.mjs && npm run test:v020140');
const liveGraph=await Promise.all(['public/live-center.html','public/live-center.js','public/live-package-open.html','public/live-package-open.js','public/live-package-ai-host.js','public/live-package-player.js'].map(text));assert.ok(liveGraph.every(source=>source.includes('?v=020138')),'unrelated Live Center cache graph remains v0.20.138');assert.equal(liveGraph.some(source=>source.includes('?v=020141')),false);
const ledger=JSON.parse(await text('patch-ledgers/v0.20.141.json'));assert.equal(ledger.version,'v0.20.141');assert.equal(ledger.feature,'VSPORT-001');assert.equal(ledger.files.length,32);for(const required of ['functions/api/admin/vsport.js','migrations/0115_vsport_project_delete.sql','public/vsport.js','public/vsport.html','scripts/test-v020141-vsport-project-delete.mjs','scripts/test-v020141-vsport-project-delete-browser.mjs','scripts/test-v020141.mjs'])assert.ok(ledger.files.includes(required),required);for(const forbidden of ['functions/_vsport.js','functions/api/admin/vsport-assets/[id].js','public/vsport.css','migrations/0111_vsport.sql'])assert.equal(ledger.files.includes(forbidden),false,`${forbidden} stays outside task scope`);
assert.match(migration111,/FOREIGN KEY\(project_id\) REFERENCES vsport_projects\(id\) ON DELETE CASCADE/);assert.match(css,/@media\(max-width:640px\)/);assert.match(foundation,/export function bangkokNewsWindow/);
console.log('v0.20.141 V Sport project delete control release checks passed');
