import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fixture,route,helper,secret,owner} from './test-browser-launcher-transport.mjs';
import {launcherRoute} from '../functions/_browser_launcher.js';
const migration=await readFile('migrations/0099_browser_launcher_pair_code.sql','utf8');
const env=()=>{const e=fixture();e.DB.raw.exec(migration);return e};
const stage=(e,code='AABBCCDDEEFF',id=helper)=>route(e,'pair-stage',{helper_id:id,owner_hash:owner,port:53179,secret,pair_code:code},'',true);
const prepare=(e,code='AABBCCDDEEFF',session='main')=>route(e,'pair-prepare-code',{pair_code:code},session);
const confirm=(e,p,session='main')=>route(e,'pair-confirm',{pair_id:p.pair_id,pair_code:p.pair_code,confirm_nonce:p.confirm_nonce,replace_id:p.replace_id},session);
const list=(e,after='',session='main')=>launcherRoute({env:e,params:{action:'helpers'},request:new Request('https://visiondonline.com/api/launcher/helpers'+(after?'?after='+after:''),{headers:{cookie:'vd_session='+session}})});
let n=0;async function test(name,fn){await fn();console.log('PASS v75 '+name);n++}
await test('code-only enrollment blocks legacy-ID bypass and requires original session/explicit confirmation',async()=>{const e=env();assert.equal((await stage(e)).status,200);assert.equal((await route(e,'pair-prepare',{pair_id:helper})).status,409);const p=await(await prepare(e)).json();assert.equal(p.pair_id,helper);assert.equal((await prepare(e,'AABBCCDDEEFF','other')).status,409);assert.equal((await confirm(e,p,'other')).status,409);assert.equal((await confirm(e,p)).status,200);assert.equal((await confirm(e,p)).status,409);assert.equal((await stage(e,'112233445566')).status,200);assert.equal(e.DB.raw.prepare('SELECT status,pair_code FROM browser_launcher_helpers').get().status,'active');});
await test('same code retry retains expiry/nonce; rotation invalidates previous prepared approval',async()=>{const e=env();await stage(e);const p=await(await prepare(e)).json(),expiry=e.DB.raw.prepare('SELECT expires_at FROM browser_launcher_helpers').get().expires_at;assert.equal((await stage(e)).status,200);assert.equal(e.DB.raw.prepare('SELECT expires_at FROM browser_launcher_helpers').get().expires_at,expiry);assert.equal((await(await prepare(e)).json()).confirm_nonce,p.confirm_nonce);assert.equal((await stage(e,'112233445566')).status,200);assert.equal((await confirm(e,p)).status,409);assert.equal((await prepare(e)).status,409);const next=await(await prepare(e,'112233445566')).json();assert.notEqual(next.confirm_nonce,p.confirm_nonce);assert.equal((await confirm(e,next)).status,200)});
await test('expired attempts require fresh code and final authorization rolls back',async()=>{for(const mutation of ["DELETE FROM sessions WHERE id='main'","UPDATE users SET role='user' WHERE id=1","UPDATE browser_launcher_helpers SET pair_code='112233445566'","UPDATE browser_launcher_helpers SET expires_at=datetime('now','-1 second')"]){const e=env();await stage(e);const p=await(await prepare(e)).json();e.DB.beforeBatch=()=>e.DB.raw.exec(mutation);assert.notEqual((await confirm(e,p)).status,200);assert.notEqual(e.DB.raw.prepare('SELECT status FROM browser_launcher_helpers').get().status,'active')}const e=env();await stage(e);e.DB.raw.exec("UPDATE browser_launcher_helpers SET expires_at=datetime('now','-1 second')");assert.equal((await stage(e)).status,409);assert.equal((await prepare(e)).status,409);assert.equal((await stage(e,'112233445566')).status,200)});
await test('code collisions reject and exact lookup uses index',async()=>{const e=env();await stage(e);await stage(e,'AABBCCDDEEFF',crypto.randomUUID());assert.equal((await prepare(e)).status,409);const plan=e.DB.raw.prepare("EXPLAIN QUERY PLAN SELECT id FROM browser_launcher_helpers WHERE pair_code='AABBCCDDEEFF' AND status IN ('staged','prepared') AND expires_at>CURRENT_TIMESTAMP ORDER BY status,expires_at,id LIMIT 2").all();assert.ok(plan.some(p=>p.detail.includes('idx_launcher_pair_code')));});
await test('owner list is bounded keyset with sentinel and no foreign rows',async()=>{const e=env();await stage(e);const row=e.DB.raw.prepare('SELECT * FROM browser_launcher_helpers').get();e.DB.raw.exec('DELETE FROM browser_launcher_helpers');const ids=Array.from({length:26},()=>crypto.randomUUID()).sort();for(const id of ids)e.DB.raw.prepare("INSERT INTO browser_launcher_helpers(id,user_id,owner_hash,port,secret_cipher,key_version,status,pair_code,expires_at) VALUES(?,1,?,53179,?,1,'active','AABBCCDDEEFF',datetime('now','+1 day'))").run(id,owner,row.secret_cipher);const response=await list(e),a=await response.json();assert.match(response.headers.get('cache-control'),/no-store/);assert.equal(a.items.length,24);assert.equal(a.has_more,true);const b=await(await list(e,a.next_cursor)).json();assert.equal(b.has_more,false);assert.deepEqual([...a.items,...b.items].map(x=>x.id),ids);assert.equal((await(await list(e,'','other')).json()).items.length,0);});
console.log('v75 backend cases: '+n);
await test('concurrent code guesses are bounded by atomic IP/account counters',async()=>{const e=env();const responses=await Promise.all(Array.from({length:24},()=>prepare(e,'000000000000')));assert.equal(responses.filter(r=>r.status===409).length,10);assert.equal(responses.filter(r=>r.status===429).length,14);assert.equal(e.DB.raw.prepare('SELECT count(*) n FROM browser_launcher_helpers').get().n,0)});
await test('competing sessions admit one prepare and legacy read cannot win after rotation',async()=>{const e=env();await stage(e);const r=await Promise.all([prepare(e),prepare(e,'AABBCCDDEEFF','other')]);assert.equal(r.filter(x=>x.status===200).length,1);assert.equal(r.filter(x=>x.status===409).length,1);const f=env();await stage(f,'12ABCDEF');const original=f.DB.prepare.bind(f.DB);let changed=false;f.DB.prepare=sql=>{const q=original(sql);if(sql.startsWith('UPDATE browser_launcher_helpers SET user_id=')){const run=q.run;q.run=async()=>{if(!changed){changed=true;f.DB.raw.exec("UPDATE browser_launcher_helpers SET pair_code='112233445566'")}return run.call(q)}}return q};assert.equal((await route(f,'pair-prepare',{pair_id:helper})).status,409)});
