import assert from 'node:assert/strict';import fs from 'node:fs';
const style=fs.readFileSync('public/style.css','utf8'),home=fs.readFileSync('public/home-modern-ai.css','utf8'),member=fs.readFileSync('public/member-modern-ai.css','utf8'),courseCss=fs.readFileSync('public/course-modern-ai.css','utf8'),courseBase=fs.readFileSync('public/course.css','utf8'),courses=fs.readFileSync('public/courses.js','utf8'),mine=fs.readFileSync('public/my-courses.js','utf8'),learn=fs.readFileSync('public/learn.js','utf8'),seller=fs.readFileSync('public/course-seller.html','utf8');
assert.match(style,/background:linear-gradient\(180deg,#0ABAB5 0%,#42CEC9 22%,#DDF7F5 56%,#F7FEFD 100%\)/);assert.doesNotMatch(home,/body\{background:/);assert.doesNotMatch(member,/\.dashboard-shell\{background:/);assert.doesNotMatch(courseCss,/\.course-hero,.page-hero\{background:/);
assert.match(courseBase,/course-modern-ai\.css\?v=01495/);
for(const contract of ['/api/courses','data-platform','data-buy','completed_lessons','lesson_count'])assert.ok(courses.includes(contract),`courses ${contract}`);
for(const contract of ['owned','access_blocked','payment','verified','pending','learn.html?course='])assert.ok(mine.includes(contract),`mine ${contract}`);
for(const contract of ['/progress','position_seconds','completedCount','data-percent','resume_lesson_id','saveRetry'])assert.ok(learn.includes(contract),`learn ${contract}`);
for(const id of ['createCourseBasket','sellerCourseForm','sellerLessonForm','publishForm','paymentProfileForm','slipApiForm','salesRows','slipIssueRows'])assert.ok(seller.includes(id),`seller ${id}`);
for(const rule of ['min-height:44px','focus-visible','max-width:760px','prefers-reduced-motion','--vd-primary-soft'])assert.ok(courseCss.includes(rule),`css ${rule}`);assert.equal((courseCss.match(/{/g)||[]).length,(courseCss.match(/}/g)||[]).length);
console.log('v0.14.95 Legacy gradient preserved and course journey adopted');
