import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=file=>readFileSync(new URL(`../${file}`,import.meta.url),'utf8');
const schema=read('functions/_schema.js'),migration=read('migrations/0037_global_test_user.sql'),register=read('functions/api/auth/register.js'),endpoint=read('functions/api/admin/users/test-user.js'),usersApi=read('functions/api/admin/users.js'),admin=read('public/admin.js'),review=read('functions/api/admin/course-seller-reviews/[id].js'),payment=read('functions/api/course-seller/payment-profile.js');
assert.equal(read('VERSION.txt').trim(),'v0.14.125');
assert.match(schema,/is_test_user/);assert.match(migration,/vision5_test_account=1/);assert.match(migration,/รัฐสิทธิ ดำรงรถการ/);
assert.match(register,/duplicateName/);assert.match(register,/ชื่อ–นามสกุลนี้มีบัญชีอยู่แล้ว/);
assert.match(endpoint,/requireBoss/);assert.match(endpoint,/is_test_user,vision5_test_account/);assert.match(endpoint,/รัฐสิทธิ ดำรงรถการ/);assert.match(endpoint,/Username หรืออีเมลนี้ถูกใช้แล้ว/);
assert.match(usersApi,/u\.is_test_user/);assert.match(admin,/createTestUser/);assert.match(admin,/\+ สร้างยูสเทส/);assert.match(admin,/test-user-badge/);
assert.match(review,/mark_test_user/);assert.match(review,/name=CASE WHEN/);
assert.match(payment,/acceptedNames/);assert.match(payment,/รัฐสิทธิ์ ดำรงรถการ/);
console.log('v0.14.125 global test-user identity checks passed');
