import assert from "node:assert/strict";
import fs from "node:fs";
const read=file=>fs.readFileSync(file,"utf8"),legacy=read("public/course-seller.html"),center=read("public/course-center.html");
assert.equal(read("VERSION.txt").trim(),"v0.14.268");
assert.match(legacy,/id="sellerActionRequired"[\s\S]*?hidden/);
assert.match(legacy,/id="customerSalesPanel" class="seller-card" hidden/);
assert.match(legacy,/id="pendingSlipPanel" class="seller-card" hidden/);
assert.doesNotMatch(legacy,/href="#sellerActionRequired"/);
for(const id of ["myCoursesPanel","customerSalesPanel","pendingSlipPanel"])assert.match(center,new RegExp(`id="${id}"[^>]*hidden`));
console.log("v0.14.268 temporary course-center surface cleanup: PASS");
