import assert from "node:assert/strict";
import fs from "node:fs";
const read = (file) => fs.readFileSync(new URL(`../${file}`, import.meta.url), "utf8");
const client = read("public/tiktok-analyzer.js"), css = read("public/tiktok-analyzer.css"), html = read("public/tiktok-analyzer.html");
assert.doesNotMatch(client, /ดูสินค้า GMV โตสูง|เรียงตามเกรด|showcaseGrowthSort|showcaseGradeSort|showcaseSort/);
assert.doesNotMatch(css, /\.showcase-sort/);
assert.match(client, /gradeRank\(a\) - gradeRank\(b\)/);
assert.match(client, /GMV เทียบ 7 วันล่าสุดกับ 7 วันก่อนหน้า/);
assert.match(html, /tiktok-analyzer\.js\?v=02047/);
assert.equal(read("VERSION.txt").trim(), "v0.20.47");
console.log("Showcase obsolete sort controls removal regression: PASS");
