import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const read = (path) => readFile(new URL(path, root), 'utf8');

const [provider, client, page, css, version] = await Promise.all([
  read('functions/_tiktok_analyzer.js'),
  read('public/tiktok-analyzer.js'),
  read('public/tiktok-analyzer.html'),
  read('public/tiktok-analyzer.css'),
  read('VERSION.txt'),
]);
const endpoint = await read('functions/api/admin/tiktok-analyzer/index.js');
const [shopEndpoint, shopApi] = await Promise.all([read('functions/api/admin/tiktok-connections/index.js'), read('functions/_tiktok_shop_api.js')]);

assert.match(provider, /สินค้าเกรด A และ B เป็นสินค้าที่ต้องทำคอนเทนต์ลงต่อเนื่อง/);
assert.match(provider, /เลื่อน B เป็น A เมื่อมีหลักฐานว่ายอดขาย วิว และทราฟฟิกดีขึ้นอย่างต่อเนื่อง/);
assert.match(provider, /สินค้า A ผลงานลดลงแต่ยังขายได้บ้างให้ลดเป็น B/);
assert.match(provider, /สินค้า A วิวหรือทราฟฟิกไม่ดีพร้อมขายไม่ได้ ให้ลดเป็น F/);
assert.match(provider, /ห้ามเลื่อนหรือลดเกรดจากความรู้สึก ข้อมูลเพียงครั้งเดียว หรือคลิปเดียว/);
assert.match(provider, /A=ขายได้อย่างน้อย 7 ชิ้นต่อ 7 วัน/);
assert.match(provider, /B=ขายได้ 4-6 ชิ้นต่อ 7 วัน/);
assert.match(provider, /C=ขายได้ 1-3 ชิ้นต่อ 7 วัน/);
assert.match(provider, /F=ขายได้ 0 ชิ้นต่อ 7 วัน/);
assert.match(provider, /A เมื่อขายได้อย่างน้อย 30 ชิ้นใน 30 วัน/);
assert.match(provider, /B เมื่อขายได้ 16-29 ชิ้นใน 30 วัน/);
assert.match(provider, /C เมื่อขายได้ 0-15 ชิ้นใน 30 วัน/);
assert.match(provider, /สินค้าที่ไม่ปรากฏในรูปห้ามสรุปว่าเป็นยอด 0 หรือ F/);
assert.match(provider, /orders>=30\?'A':orders>=16\?'B':'C'/);
assert.match(provider, /correctTextGrade/);
assert.match(client, /renderResultTextGradeBase/);
assert.match(provider, /ห้ามคาดคะเนเป็นยอดต่อสัปดาห์/);
assert.match(provider, /ให้ใช้แทนกฎ C แบบ 72 ชั่วโมงก่อนหน้า/);
assert.match(provider, /30 สินค้าหลัก \+ 10 สินค้าแนะนำเกรด E/);
assert.match(provider, /ใส่ A ได้สูงสุด 20 รายการ/);
assert.match(provider, /กัน C ไว้ 5 รายการ/);
assert.match(provider, /ใช้ B เติมจำนวนที่เหลือให้ครบ 30/);
assert.match(provider, /หากยังไม่มีทั้งสินค้า A และ B ให้ใช้ C ทั้ง 30 รายการ/);
assert.match(provider, /ห้ามนำ D หรือ F เข้า 30 สินค้าหลัก/);
assert.match(provider, /ห้ามสร้างชื่อสินค้าซ้ำหรือชื่อปลอม/);
assert.match(provider, /สินค้า C สำหรับทดลองอาจคัดมาจากสินค้า C เดิม/);
assert.match(provider, /สินค้า D ที่ถึงจังหวะกระแส ฤดูกาล หรือโปรโมชั่น/);
assert.match(provider, /สินค้า E ที่ผู้ใช้เลือกนำมาทดลอง/);
assert.match(provider, /ต้องเปลี่ยน product_type ของรายการนั้นเป็น C/);
assert.match(provider, /ห้ามให้สินค้าเดียวกันซ้ำอยู่ใน D หรือ E/);
assert.match(provider, /ต้องหาสินค้า E แนะนำอื่นที่ไม่ซ้ำเติมให้กลุ่ม E ยังคงครบ 10 รายการ/);
assert.match(provider, /สินค้า C เป็นสินค้าเทส ให้ตรวจหลักฐานใหม่เมื่อครบ 3 วัน/);
assert.match(provider, /สินค้า A และ B ให้ประเมินผลตามยอดขายย้อนหลัง 7 วัน/);
assert.match(provider, /ห้ามใช้ข้อมูลก่อนถึงวันตรวจมาตัดสินว่าเป็นผลครบช่วง/);
assert.match(provider, /เมื่อมีข้อมูล TikTok หรือ TikTok Shop API ให้ใช้ข้อมูล API เป็นหลัก/);
assert.match(provider, /ไม่บังคับผู้ใช้แนบรูปใหม่/);
assert.match(provider, /รูปแนบเป็นทางสำรองก่อน API ได้รับอนุญาต/);
assert.match(provider, /ห้ามลบข้อมูลสินค้า F แม้ไม่ผ่าน/);
assert.match(provider, /สินค้านี้เคยทดสอบแล้ว เคยเป็น F และกำลังเริ่มรอบ C ใหม่/);
assert.match(provider, /ห้ามซ่อนผลรอบเก่า/);
assert.match(provider, /review_started_at TEXT,next_review_at TEXT,review_cycle_days INTEGER/);
assert.match(provider, /CREATE TABLE IF NOT EXISTS tiktok_product_events/);
assert.match(provider, /idx_tiktok_product_events_channel/);
assert.match(client, /A:'≥ 7 ชิ้น\/สัปดาห์'/);
assert.match(client, /B:'4–6 ชิ้น\/สัปดาห์'/);
assert.match(client, /C:'1–3 ชิ้น\/สัปดาห์'/);
assert.match(client, /F:'0 ชิ้น\/สัปดาห์ · คัดออก'/);
assert.match(page, /เกณฑ์รูป 30 วัน: A ≥ 30 ชิ้น · B 16–29 ชิ้น · C 0–15 ชิ้น/);
assert.match(page, /เพิ่มหรือลบสินค้าใน Showcase ของช่องนี้ ส่วนการจัดเกรดทำในลิสต์คัดสินค้า/);
assert.match(page, /เพิ่มใน Showcase/);
assert.match(page, /ลบสินค้าที่เลือกออกจาก Showcase/);
assert.doesNotMatch(client, /class="shop-grade"/);
assert.doesNotMatch(client, /class="grade-guide"/);
assert.match(shopEndpoint, /action==='shop_add'/);
assert.match(shopEndpoint, /action==='shop_remove'/);
assert.match(shopApi, /export async function addTikTokShopShowcaseProducts/);
assert.match(provider, /inventory_status TEXT NOT NULL DEFAULT 'analyzed'/);
assert.match(endpoint, /action==='set_product_inventory'/);
assert.match(endpoint, /already_exists:true/);
assert.match(endpoint, /\['kept','discarded'\]\.includes\(status\)/);
assert.match(endpoint, /inventory_status=excluded\.inventory_status/);
assert.match(endpoint, /r\.created_at attachment_date/);
assert.match(endpoint, /cycle=type==='C'\?3:\['A','B'\]\.includes\(type\)\?7:0/);
assert.match(endpoint, /datetime\('now',\?\)/);
assert.match(endpoint, /result\.daily_product_list/);
assert.match(endpoint, /kind:'daily_ranking'/);
assert.match(endpoint, /SELECT id,product_name,event_type,product_type,inventory_status,detail,source_run_id,event_at FROM tiktok_product_events/);
assert.match(endpoint, /event_type,product_type,inventory_status,detail/);
assert.match(endpoint, /eventProducts=new Set/);
assert.match(endpoint, /shopApiConnection/);
assert.match(endpoint, /หรือเชื่อม TikTok Shop API/);
assert.match(endpoint, /orders_last_7_days/);
assert.match(endpoint, /action==='fail_c_product'/);
assert.match(endpoint, /ปุ่มไม่ผ่านใช้ได้เฉพาะสินค้า C/);
assert.match(endpoint, /SET product_type='F',inventory_status='discarded'/);
assert.match(endpoint, /next_review_at=NULL,review_cycle_days=0,review_status='failed'/);
assert.match(endpoint, /'manual_fail','F','discarded'/);
assert.match(endpoint, /action==='retest_f_product'/);
assert.match(endpoint, /action==='set_product_c'/);
assert.match(endpoint, /'manual_c','C','kept'/);
assert.match(endpoint, /ทดสอบใหม่ได้เฉพาะสินค้า F/);
assert.match(endpoint, /SET product_type='C',inventory_status='kept'/);
assert.match(endpoint, /next_review_at=datetime\('now','\+3 days'\)/);
assert.match(endpoint, /'manual_retest','C','kept'/);
assert.match(endpoint, /ประวัติสินค้า F ของช่องที่ต้องเก็บไว้และแจ้งเตือน/);
assert.match(client, /ลิสต์คัดสินค้า/);
assert.match(client, /data-inventory="kept"/);
assert.match(client, /data-inventory="discarded"/);
assert.match(client, /อยู่ในลิสต์คัดสินค้าแล้ว ไม่ได้เพิ่มซ้ำ/);
assert.match(client, /อยู่ในประวัติคัดออกแล้ว ไม่ได้เพิ่มซ้ำ/);
assert.match(client, /button\.dataset\.setC=productName/);
assert.doesNotMatch(client, />เลือกเป็น C<\/button>/);
assert.match(client, /button\.dataset\.retestF=name;button\.textContent='ทดสอบใหม่เป็น C'/);
assert.match(client, /async function setProductC/);
assert.match(client, /manualCForm/);
assert.match(page, /ใส่ชื่อสินค้าเต็ม/);
assert.match(page, /เพิ่มเป็น C/);
assert.match(client, /ประวัติสินค้าที่คัดออก/);
assert.match(client, /รอบตรวจสินค้า A\/B\/C/);
assert.match(client, /C ตรวจรอบ 3 วัน หรือกดไม่ผ่านได้ทันที · A และ B ตรวจทุก 7 วัน/);
assert.match(client, /review-reminder\$\{due\?' overdue':''\}/);
assert.match(client, /ตรวจอัตโนมัติจาก TikTok Shop API · ไม่ต้องแนบรูปใหม่/);
assert.match(client, /API ยังไม่พร้อม · แนบรูปใหม่เมื่อถึงรอบตรวจ/);
assert.match(client, /data-fail-c=/);
assert.match(client, /ไม่ผ่าน → F/);
assert.match(client, /async function failCProduct/);
assert.match(client, /manual_fail:'กดไม่ผ่าน'/);
assert.match(client, /data-retest-f/);
assert.match(client, /ทดสอบใหม่เป็น C/);
assert.match(client, /เคยทดสอบแล้ว · กำลังทดสอบใหม่/);
assert.match(client, /async function retestFProduct/);
assert.match(client, /เวลาและเหตุการณ์/);
assert.match(client, /timeline-event/);
assert.match(client, /product_events/);
assert.match(page, /ลิสต์คัดสินค้า/);
assert.doesNotMatch(page, /ลิสต์สินค้าถาวร/);
assert.match(page, /A สูงสุด 20 · C จำนวน 5 · B เติมให้ครบ 30/);
assert.match(page, /ถ้ายังไม่มี A และ B ให้เป็น C ทั้ง 30/);
assert.match(page, /C สามารถคัดจาก D หรือ E มาทดลองได้และต้องเปลี่ยนเกรดเป็น C/);
assert.match(page, /id="productReviewSchedule"/);
assert.match(page, /หาก API พร้อมสามารถวิเคราะห์โดยไม่แนบรูป/);
assert.match(page, /กำหนดเป็น C ได้ทันที/);
assert.match(page, /เฉพาะสินค้า F ที่เคยคัดออกเท่านั้นจึงมีปุ่ม “ทดสอบใหม่เป็น C”/);
assert.match(client, /function showToast/);
assert.match(client, /เก็บ “\$\{productName\}” สำเร็จ/);
assert.match(css, /\.action-toast\.visible/);
assert.equal(version.trim(), 'v0.14.556');

console.log('v0.14.556 visible inventory notifications checks passed');
