import fs from 'node:fs';
import assert from 'node:assert/strict';
import {autoSeoDraft,seoQuality} from '../functions/_sales_pages.js';
const read=file=>fs.readFileSync(new URL(`../${file}`,import.meta.url),'utf8');
const helper=read('functions/_sales_pages.js'),generate=read('functions/api/admin/sales-pages/generate.js'),detail=read('functions/api/admin/sales-pages/[id].js'),renderer=read('functions/s/[slug].js'),sitemap=read('functions/sitemap.xml.js'),html=read('public/sales-page-center.html'),ui=read('public/sales-page-center.js');
const middleware=read('functions/_middleware.js');
assert.equal(read('VERSION.txt').trim(),'v0.14.476');
assert.match(read('public/index.html'),/WEB v0\.14\.476/);assert.match(read('public/admin.html'),/ADMIN v0\.14\.476/);
for(const token of ['autoSeoDraft','seoQuality','meta_description','faq'])assert.ok(helper.includes(token),token);
for(const token of ['requireAdmin','published','Keyword หรือ Slug นี้มีหน้า Auto SEO อยู่แล้ว','สร้างร่าง Auto SEO'])assert.ok(generate.includes(token),token);
assert.match(detail,/หน้า SEO ยังไม่ผ่านเกณฑ์/);assert.match(detail,/approved_revision_no/);assert.match(detail,/Keyword หรือ Slug นี้ซ้ำ/);
for(const token of ["page_type='seo_automation'",'approved_revision_no=p.revision_no','canonical','FAQPage','BreadcrumbList','ItemList','index,follow'])assert.ok(renderer.includes(token),token);
assert.match(renderer,/decodeURIComponent\(requestedSlug\)/);
for(const token of ["page_type='seo_automation'","status='published'",'robots_index=1','approved_revision_no=revision_no','application/xml'])assert.ok(sitemap.includes(token),token);
assert.match(middleware,/url\.pathname==='\/sitemap\.xml'\?await renderSitemap\(ctx\)/);
for(const token of ['สร้าง Auto SEO จากสินค้าที่เลือก','Meta description','FAQ','seoQuality'])assert.ok(html.includes(token),token);
for(const token of ['/api/admin/sales-pages/generate','faqFromText','เปิดหน้า SEO จริง','renderQuality'])assert.ok(ui.includes(token),token);
const draft=autoSeoDraft([{id:1,title:'แบบฝึกหัดคณิตศาสตร์อนุบาล',slug:'math',category:'worksheet',category_name:'แบบฝึกหัด'}]);
assert.equal(seoQuality({title:draft.title,slug:draft.slug,content:draft.content,productCount:1}).ok,true);
assert.equal(seoQuality({title:'สั้น',slug:'x',content:{},productCount:0}).ok,false);
console.log('PASS v0.14.476 Auto SEO generation, quality gate, renderer and sitemap');
