import fs from 'node:fs';
import assert from 'node:assert/strict';
import {ensureV12Schema} from '../functions/_v12_schema.js';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.404');
assert.match(read('public/index.html'),/WEB v0\.14\.404/);
assert.match(read('public/admin.html'),/ADMIN v0\.14\.404/);
assert.match(read('public/v12-connect.html'),/v0\.14\.404/);
const calls=[];
const DB={prepare(sql){calls.push(sql);if(/PRAGMA|CREATE|ALTER/i.test(sql))throw new Error('V12_SCHEMA_HOT_PATH_DDL');return{first:async()=>({version:66})}}};
assert.equal(await ensureV12Schema({DB}),true);
assert.equal(await ensureV12Schema({DB}),true);
assert.deepEqual(calls,["SELECT version FROM runtime_schema_state WHERE schema_key='core'"],'V12 schema must share one persistent probe per isolate');
const schema=read('functions/_v12_schema.js');
assert.match(schema,/v12SchemaReady=new WeakMap/);
assert.match(schema,/Number\(state\?\.version\)>=66/);
assert.match(schema,/no such table[^]*runtime_schema_state/,'legacy database fallback must remain');
assert.match(schema,/ensureVEasyRuntimeSchema/,'legacy bootstrap must remain behind readiness guard');
assert.match(read('FEATURE-MAP.md'),/Schema hot path:[\s\S]*?persistent readiness marker/);
console.log('PASS v0.14.404 V12 runtime schema guard');
