import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.123');
const html=read('public/course-seller.html'),ui=read('public/course-seller.js'),payment=read('functions/api/course-seller/payment-profile.js'),slipApi=read('functions/api/course-seller/slip-api.js'),slip=read('functions/api/orders/[id]/slip.js'),publish=read('functions/api/course-seller/[id]/publish.js'),schema=read('functions/_schema.js');
assert.match(html,/QR รับเงิน \(ไม่บังคับ\)/);
assert.doesNotMatch(html,/name="payment_qr"[^>]+required/);
for(const bank of ['กสิกรไทย','กรุงไทย','กรุงเทพ','ไทยพาณิชย์','กรุงศรีอยุธยา','ทหารไทยธนชาต','ออมสิน','ธ\.ก\.ส\.','ธอส\.','เกียรตินาคินภัทร','CIMB Thai','UOB','LH Bank','ไทยเครดิต','ธนาคารอิสลาม'])assert.match(html,new RegExp(bank));
assert.match(payment,/banks\.has\(bank\)/);
assert.match(payment,/qr instanceof File&&qr\.size/);
assert.match(html,/เปิดการตรวจสลิปอัตโนมัติ/);
assert.match(slipApi,/seller_slip_auto_verify=0/);
assert.match(slipApi,/seller_slip_auto_verify=1/);
assert.match(publish,/seller_slip_auto_verify/);
assert.match(slip,/VISION5_TEST_ACCOUNT_BOSS_REVIEW/);
assert.match(schema,/vision5_test_account/);
assert.match(schema,/seller_slip_auto_verify/);
assert.match(ui,/เครดิตคงเหลือ/);
assert.match(ui,/ใช้สร้างตะกร้าแล้ว/);
assert.doesNotMatch(ui,/แต้ม/);
assert.match(html,/header-shell\.css\?v=014123/);
assert.match(html,/shared-nav\.js\?v=014123/);
console.log('v0.14.123 Vision 5 settings and credit UI: PASS');
