import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {decryptPartnerSecret,encryptPartnerSecret,partnerEncryptionReady} from '../functions/_partner_crypto.js';
import {cleanScopes,newPartnerCredential,partnerSecretHash} from '../functions/_partner_api.js';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const [version,index,admin,v12,page,ui,cryptoSource,core,registry,update,rotate,products,migration,protocol,roadmap]=await Promise.all(['VERSION.txt','public/index.html','public/admin.html','public/v12-connect.html','public/partner-api.html','public/partner-api.js','functions/_partner_crypto.js','functions/_partner_api.js','functions/api/admin/partner-websites/index.js','functions/api/admin/partner-websites/[id].js','functions/api/admin/partner-websites/[id]/credential.js','functions/api/partner/v1/products/index.js','migrations/0046_partner_api_foundation.sql','VISIOND-PARTNER-API-PROTOCOL.md','VISIOND-ROADMAP.md'].map(read));
assert.equal(version.trim(),'v0.14.215');assert.match(index,/WEB v0\.14\.215/);assert.match(admin,/ADMIN v0\.14\.215/);assert.match(v12,/v0\.14\.215/);assert.match(page,/v0\.14\.215/);assert.match(admin,/href="\/partner-api\.html"[\s\S]*ศูนย์ควบคุม[\s\S]*เว็บพาร์ทเนอร์/);assert.match(page,/ศูนย์ควบคุมเว็บพาร์ทเนอร์/);assert.match(page,/visiond-button-system\.css\?v=014215/);assert.match(page,/visiond-button-system\.js\?v=014215/);
const env={VISIOND_PARTNER_ENCRYPTION_KEY:'test-only-partner-key-32-bytes-minimum-12345'},secret='test_secret_not_production';assert.equal(partnerEncryptionReady(env),true);const ciphertext=await encryptPartnerSecret(env,secret);assert.match(ciphertext,/^vdpa1:/);assert.notEqual(ciphertext.includes(secret),true);assert.equal(await decryptPartnerSecret(env,ciphertext),secret);
const credential=newPartnerCredential();assert.match(credential.clientId,/^vdw_[a-f0-9]{32}$/);assert.match(credential.secret,/^vds_[a-f0-9]{64}$/);assert.equal((await partnerSecretHash(credential.clientId,credential.secret)).length,64);assert.deepEqual(cleanScopes(['products:read','products:write','products:read']),['products:read']);
for(const token of['AES-GCM','visiond-partner-credentials-v1','PARTNER_ENCRYPTION_NOT_CONFIGURED'])assert.ok(cryptoSource.includes(token),token);
for(const token of['products:read','partner_api_audit','x-visiond-client-id','Authorization'.toLowerCase(),'equalHash'])assert.ok((core+products).toLowerCase().includes(token.toLowerCase()),token);
for(const source of[registry,update,rotate])assert.match(source,/requireBoss/);assert.match(registry,/shown_once:true/);assert.match(rotate,/shown_once:true/);
for(const token of["p.status='published'","p.deleted_at IS NULL","p.category<>'resale-rights'",'price_currency'])assert.ok(products.includes(token),token);assert.doesNotMatch(products,/product_files|object_key|account_number/);
for(const token of['partner_websites','secret_ciphertext','secret_hash','partner_api_audit','request_id'])assert.ok(migration.includes(token),token);
for(const token of['Credential แสดงครั้งเดียว','ออก Credential ใหม่','products:read'])assert.ok((page+ui).includes(token),token);
assert.match(protocol,/ห้ามเชื่อมฐานข้อมูล VisionD โดยตรง/);assert.match(roadmap,/Partner API Phase 1 Foundation/);
console.log('v0.14.215 Partner API phase 1 registry encrypted credential scope and read-only catalog: PASS');
