import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const api = fs.readFileSync('functions/api/admin/work-notes/presentation.js', 'utf8');
const expand = fs.readFileSync('functions/api/admin/work-notes/expand.js', 'utf8');
const client = fs.readFileSync('public/work-notes.js', 'utf8');
const html = fs.readFileSync('public/work-notes.html', 'utf8');
assert.match(api, /bullets\":\[\{\"text\"/);
assert.match(api, /value\.attachment_numbers/);
assert.match(api, /text\.matchAll\(\/\\\[รูป/);
assert.match(api, /const missing = \[\]/);
assert.match(api, /รูปประกอบตามโน้ต/);
assert.doesNotMatch(api, /attachment_numbers:[\s\S]{0,250}slice\(0, 2\)/);
assert.match(expand, /ป้ายรูปต้องอยู่บรรทัดเดียวกับข้อความ/);
assert.match(client, /คลิกเพื่อดูใหญ่/);
assert.match(client, /hyperlink:\{slide:detailSlideByNumber\.get\(number\)/);
assert.match(client, /กลับไปข้อความที่กำกับรูปนี้/);
assert.match(client, /function imageBox/);
assert.match(html, /work-notes\.js\?v=014620/);

const bundle = fs.readFileSync('public/vendor/pptxgen.min.js', 'utf8');
const context = { console, navigator: { userAgent: 'node' }, document: { createElement: () => ({ getContext: () => ({}) }) }, Blob, TextEncoder, TextDecoder, setTimeout, clearTimeout };
context.window = context; context.self = context; vm.createContext(context); vm.runInContext(bundle, context);
const pptx = new context.PptxGenJS(); pptx.layout = 'LAYOUT_WIDE';
pptx.addSlide().addText('หน้าปก', { x: 1, y: 1, w: 5, h: 1 });
const contentSlide = pptx.addSlide();
contentSlide.addText('ข้อความบรรทัดที่กำกับรูป 1', { x: 1, y: 1, w: 6, h: 1 });
contentSlide.addImage({ data: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lZzpcwAAAABJRU5ErkJggg==', x: 8, y: 1, w: 2, h: 2, hyperlink: { slide: 3, tooltip: 'เปิดรูป 1 ขนาดใหญ่' } });
const detailSlide = pptx.addSlide();
detailSlide.addText('รูป 1 ขนาดใหญ่', { x: 1, y: .5, w: 6, h: 1 });
detailSlide.addText('กลับ', { x: 1, y: 6, w: 2, h: .5, hyperlink: { slide: 2 } });
const bytes = await pptx.write({ outputType: 'arraybuffer' });
const zip = await context.JSZip.loadAsync(bytes);
const contentXml = await zip.file('ppt/slides/slide2.xml').async('string');
const contentRels = await zip.file('ppt/slides/_rels/slide2.xml.rels').async('string');
const detailRels = await zip.file('ppt/slides/_rels/slide3.xml.rels').async('string');
assert.match(contentXml, /ข้อความบรรทัดที่กำกับรูป 1/);
assert.match(contentXml, /ppaction:\/\/hlinksldjump/);
assert.match(contentRels, /Target="slide3\.xml"/);
assert.match(detailRels, /Target="slide2\.xml"/);
console.log('v0.14.620 image-to-line mapping and large-image navigation test passed');
