import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=file=>readFileSync(new URL(`../${file}`,import.meta.url),'utf8');
const html=read('public/course-seller.html');
const seller=read('public/course-seller.js');
const dates=read('public/course-license-dates.js');
const css=read('public/course-seller.css');
const payment=read('functions/api/course-seller/payment-profile.js');
assert.equal(read('VERSION.txt').trim(),'v0.14.124');
assert.equal((html.match(/id="vision5CreditSummary"/g)||[]).length,1,'credit summary must have one owner');
assert.doesNotMatch(dates,/summary\.innerHTML|summary=document\.createElement/,'date decorator must not create a second credit summary');
assert.match(dates,/querySelectorAll\('\.credit-summary'\).*remove/,'stale duplicate cleanup is required');
assert.match(html,/ตะกร้าคอร์สของฉัน/);
assert.match(html,/<h1>สร้างตะกร้าคอร์ส<\/h1>/);
assert.doesNotMatch(html,/สร้างตะกร้าคอร์สของฉัน<\/h1>|สร้างตะกร้าคอร์สMy/);
assert.match(seller,/seller-course-card/);
assert.match(seller,/แก้ข้อมูลคอร์ส/);
assert.match(css,/seller-course-grid/);
assert.match(html,/บันทึกแล้วแก้ไขได้เมื่อต้องการ/);
assert.match(seller,/editPaymentProfile/);
assert.match(payment,/newKey\|\|oldKey/,'an omitted QR must preserve the previous QR');
assert.doesNotMatch(payment,/seller_payment_status!='unset'|seller_payment_status!==?'unset'/);
console.log('v0.14.124 Vision 5 credit deduplication and basket catalog checks passed');
