import fs from 'node:fs';
import assert from 'node:assert/strict';
const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
assert.equal(read('VERSION.txt').trim(), 'v0.14.326');
assert.match(read('public/index.html'), /WEB v0\.14\.326/);
assert.match(read('public/admin.html'), /ADMIN v0\.14\.326/);
const page = read('public/v12-connect.html');
assert.match(page, /v0\.14\.326/);
assert.doesNotMatch(page, /014247/);
for (const id of ['V12-CHANNEL-001','V12-INBOX-001','V12-BROADCAST-001','V12-SALES-AI-001']) assert.match(read('FEATURE-MAP.md'), new RegExp(id));
assert.match(read('functions/hooks/v12/facebook.js'), /x-hub-signature-256/);
assert.match(read('functions/api/admin/v12-channel.js'), /encrypt/i);
assert.match(read('functions/api/admin/v12-broadcast.js'), /v12_broadcast_deliveries/);
assert.match(read('functions/api/admin/v12-sales-assistant.js'), /v12_lead_insights/);
console.log('PASS v0.14.326 V12 Feature Map');
