import assert from 'node:assert/strict';
import fs from 'node:fs';
import {salesPageContent,salesPageProductIds,salesPageSlug} from '../functions/_sales_pages.js';
const read=file=>fs.readFileSync(file,'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.234');
const migration=read('migrations/0061_sales_page_center.sql'),schema=read('functions/_sales_pages.js'),list=read('functions/api/admin/sales-pages/index.js'),item=read('functions/api/admin/sales-pages/[id].js'),admin=read('public/admin.html'),html=read('public/sales-page-center.html'),ui=read('public/sales-page-center.js'),css=read('public/sales-page-center.css'),protocol=read('VISIOND-SALES-PAGE-PROTOCOL.md');
for(const token of['sales_page_templates','sales_pages','sales_page_products','sales_page_revisions','UNIQUE(page_id,revision_no)'])assert.ok(migration.includes(token),token);
for(const token of['ad_shortcut','seo_automation','robots_index','approved_revision_no'])assert.ok(schema.includes(token),token);
assert.equal(salesPageSlug(' แบบ ฝึกหัด @ 2026 '),'แบบ-ฝึกหัด-2026');
assert.deepEqual(salesPageProductIds([2,'2',3,0,-1,'x']),[2,3]);
assert.equal(salesPageContent({hero:' a ',extra:'secret'}).hero,'a');
for(const token of['requireAdmin','permissions','can_approve',"status:'draft',robots_index:false"])assert.ok(list.includes(token),token);
for(const token of["a.user.role!=='boss'",'SEO Automation ต้องผ่านการอนุมัติ Revision ปัจจุบันก่อนเผยแพร่',"page_type='seo_automation' THEN 1 ELSE 0",'approval_reset:true'])assert.ok(item.includes(token),token);
assert.match(admin,/href="\/sales-page-center\.html"/);
for(const token of['Ad Shortcut Page','SEO Automation Page','Preview มือถือ','ประวัติ Revision','v0.14.234'])assert.ok(html.includes(token),token);
for(const token of['srcdoc','selectedProducts'])assert.ok(ui.includes(token),token);
assert.ok(html.includes('data-action="submit_review"'),'submit_review');
assert.ok(item.includes('robots_index'),'robots_index');
assert.match(css,/@media\(max-width:850px\)/);
for(const token of['Ad Shortcut','noindex','SEO Automation','Boss','Revision'])assert.ok(protocol.includes(token),token);
console.log('v0.14.234 Sales Page Center phase 1 templates products unique slug revisions mobile preview and permission gates: PASS');
