import assert from'node:assert/strict';
import fs from'node:fs';
import{partnerDelivery}from'../functions/_partner_delivery.js';
import{DatabaseSync}from'node:sqlite';
import{onRequestGet as catalogHandler}from'../functions/api/partner/v1/products/index.js';
import{onRequestGet as detailHandler}from'../functions/api/partner/v1/products/[id].js';
import{partnerSecretHash}from'../functions/_partner_api.js';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const catalog=read('functions/api/partner/v1/products/index.js'),detail=read('functions/api/partner/v1/products/[id].js'),protocol=read('VISIOND-PARTNER-API-PROTOCOL.md');
assert.equal(read('VERSION.txt').trim(),'v0.14.412');
assert.match(read('public/index.html'),/WEB v0\.14\.412/);assert.match(read('public/admin.html'),/ADMIN v0\.14\.412/);
const single=partnerDelivery({file_type:'PDF',pages:40,delivery_file_count:2,delivery_total_size:4096,delivery_bundle_item_count:0});
assert.deepEqual({...single,access_note:undefined},{method:'visiond_claim',content_type:'digital_download',package_type:'single',file_format:'PDF',file_count:2,page_count:40,total_size_bytes:4096,bundle_item_count:0,access_note:undefined});
const bundle=partnerDelivery({file_type:'ชุด PDF',pages:80,delivery_file_count:3,delivery_total_size:8192,delivery_bundle_item_count:2},[{id:7,title:'ชุดที่ 1',file_type:'PDF',file_count:1,pages:30}]);
assert.equal(bundle.package_type,'bundle');assert.deepEqual(bundle.items,[{id:7,title:'ชุดที่ 1',file_format:'PDF',file_count:1,page_count:30}]);
for(const source of[catalog,detail]){assert.match(source,/partnerDelivery/);assert.doesNotMatch(source,/object_key|download_token/)}
assert.match(catalog,/WITH selected AS/);assert.match(catalog,/JOIN selected p/);assert.match(catalog,/limit\+1/);assert.match(detail,/LIMIT 30/);assert.match(detail,/delivery_bundle_item_count/);
for(const token of['visiond_claim','file_count','total_size_bytes','ห้ามคืน object key'])assert.ok(protocol.includes(token),token);
const sqlite=new DatabaseSync(':memory:');sqlite.exec(`CREATE TABLE runtime_schema_state(schema_key TEXT PRIMARY KEY,version INTEGER);INSERT INTO runtime_schema_state VALUES('core',68);CREATE TABLE partner_websites(id TEXT PRIMARY KEY,name TEXT,domain TEXT,status TEXT,scopes TEXT,client_id TEXT,secret_hash TEXT,last_used_at TEXT);CREATE TABLE partner_api_audit(id TEXT PRIMARY KEY,website_id TEXT,request_id TEXT UNIQUE,method TEXT,path TEXT,required_scope TEXT,response_status INTEGER,ip_hash TEXT);CREATE TABLE products(id INTEGER PRIMARY KEY,slug TEXT,title TEXT,short_description TEXT,description TEXT,price INTEGER,cover_url TEXT,preview_urls TEXT,category TEXT,file_type TEXT,pages INTEGER,product_kind TEXT,status TEXT,deleted_at TEXT,updated_at TEXT);CREATE TABLE product_files(id INTEGER PRIMARY KEY,product_id INTEGER,label TEXT,object_key TEXT,mime_type TEXT,file_size INTEGER);CREATE TABLE product_bundle_items(bundle_product_id INTEGER,source_product_id INTEGER,sort_order INTEGER);`);
class Statement{constructor(sql){this.sql=sql;this.args=[]}bind(...args){this.args=args;return this}async first(){return sqlite.prepare(this.sql).get(...this.args)}async all(){return{results:sqlite.prepare(this.sql).all(...this.args)}}async run(){const out=sqlite.prepare(this.sql).run(...this.args);return{meta:{changes:Number(out.changes)}}}}
const DB={prepare:sql=>new Statement(sql)},secret='vds_delivery_test_secret';sqlite.prepare('INSERT INTO partner_websites VALUES(?,?,?,?,?,?,?,NULL)').run('site','Web2','https://web2.invalid','active','["products:read"]','vdw_delivery',await partnerSecretHash('vdw_delivery',secret));
sqlite.prepare("INSERT INTO products VALUES(1,'single','Single','','',100,'/cover.jpg','[]','worksheet','PDF',10,'product','published',NULL,CURRENT_TIMESTAMP),(2,'source','Source','','',200,'/source.jpg','[]','worksheet','PDF',20,'product','published',NULL,CURRENT_TIMESTAMP),(3,'bundle','Bundle','','',250,'/bundle.jpg','[]','bundle-deals','ชุด PDF',30,'product','published',NULL,CURRENT_TIMESTAMP)").run();sqlite.prepare("INSERT INTO product_files VALUES(11,1,'Single file','private/single.pdf','application/pdf',1000),(12,2,'Source file','private/source.pdf','application/pdf',2000)").run();sqlite.prepare('INSERT INTO product_bundle_items VALUES(3,2,0)').run();
const headers={'x-visiond-client-id':'vdw_delivery',authorization:`Bearer ${secret}`,'x-request-id':'delivery-test'};const context=(path,params={})=>({env:{DB},params,request:new Request(`https://visiondonline.com${path}`,{headers})});
const catalogResponse=await catalogHandler(context('/api/partner/v1/products?limit=100')),catalogBody=await catalogResponse.json();assert.equal(catalogResponse.status,200);assert.equal(catalogBody.items.length,3);assert.equal(catalogBody.items[0].delivery.file_count,1);assert.equal(catalogBody.items[2].delivery.package_type,'bundle');assert.equal(catalogBody.items[2].delivery.total_size_bytes,2000);
const detailResponse=await detailHandler(context('/api/partner/v1/products/3',{id:'3'})),detailBody=await detailResponse.json();assert.equal(detailResponse.status,200);assert.deepEqual(detailBody.item.delivery.items,[{id:2,title:'Source',file_format:'PDF',file_count:1,page_count:20}]);assert.doesNotMatch(JSON.stringify(detailBody),/private\/|object_key|download_token/);
console.log('PASS v0.14.412 Partner Product Delivery Contract');
