import assert from'node:assert/strict';import vm from'node:vm';import{readFileSync}from'node:fs';import{createHash}from'node:crypto';import{createServer}from'node:http';import{fixture}from'./test-v02072.mjs';
const html=readFileSync('public/launcher-setup.html','utf8'),script=readFileSync('public/launcher-setup.js','utf8'),analyzer=readFileSync('public/tiktok-analyzer.js','utf8'),css=readFileSync('public/launcher-pages.css','utf8');
const path='/downloads/visiond-helper/0.20.78/VisionD-Helper-Setup.exe',manifest=JSON.parse(readFileSync('public/downloads/visiond-helper/0.20.78/release.json'));
assert.match(html,/>ดาวน์โหลด Helper สำหรับ Windows<\/a>/);assert.match(html,/<a id="download"[^>]*download="VisionD-Helper-Setup-0.20.78.exe"/);assert.doesNotMatch(html.match(/<a id="download"[^>]*>/)[0],/href=|target=/);assert.match(analyzer,/link.href='\/launcher-setup'/);assert.doesNotMatch(analyzer,/href="\/launcher-setup"[^>]*target=/);assert.match(css,/input\[type=text\],select\{width:100%/);
const tick=()=>new Promise(r=>setImmediate(r));
function browser(data){const nodes=new Map(),events={},calls=[];const node=id=>{if(!nodes.has(id))nodes.set(id,{value:id==='setup-state'?'new':'',events:{},addEventListener(k,f){this.events[k]=f},removeAttribute(){}});return nodes.get(id)};let timer;vm.runInNewContext(script,{AbortController,document:{getElementById:node},setTimeout:f=>{timer=f;return f},clearTimeout(){},fetch:async(url,options)=>{calls.push({url,options});return{ok:true,json:async()=>data}},window:{open(){assert.fail('setup must not auto-open any native/browser window')}},location:{assign(){assert.fail('setup must not auto-navigate')}}});return{node,calls,timeout:()=>timer()}}
for(const valid of [false,true]){const f=browser({...manifest,executable:{...manifest.executable,sha256:valid?manifest.executable.sha256:'a'.repeat(64)}});await tick();assert.equal(f.node('download').href,valid?path:undefined);if(valid){assert.equal(f.calls.length,1);f.node('download').events.click({preventDefault(){assert.fail('verified download blocked')}});assert.match(f.node('download-status').textContent,/เบราว์เซอร์/);assert.match(f.node('download-status').textContent,/ยังไม่ได้ติดตั้งอัตโนมัติ/);assert.equal(f.calls.length,1,'real anchor navigation, no operator/blob download');for(const[state,expected]of [['new',/Run/],['outdated',/อัปเดต/],['not-running',/อย่าผูกซ้ำ/],['repair',/เฉพาะเมื่อ Helper แจ้ง/],['paired',/ไม่ต้องผูกซ้ำ/]]){f.node('setup-state').value=state;f.node('setup-state').events.change();assert.match(f.node('setup-guidance').textContent,expected)}}}
// Test the actual versioned attachment bytes and configured response headers via isolated HTTP.
const headers=readFileSync('public/_headers','utf8'),block=headers.split(path+'\n')[1]?.split('\n\n')[0]||headers.split(path+'\r\n')[1]?.split('\r\n\r\n')[0];assert.ok(block);const values=Object.fromEntries(block.trim().split(/\r?\n/).map(l=>{const i=l.indexOf(':');return[l.slice(0,i).trim(),l.slice(i+1).trim()]}));assert.equal(values['Content-Type'],'application/octet-stream');assert.match(values['Content-Disposition'],/attachment; filename="VisionD-Helper-Setup-0.20.78.exe"/);assert.equal(values['X-Content-Type-Options'],'nosniff');const bytes=readFileSync('public'+path);const server=createServer((req,res)=>{if(req.url!==path){res.writeHead(404).end();return}res.writeHead(200,values);res.end(bytes)});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const response=await fetch('http://127.0.0.1:'+server.address().port+path);assert.equal(response.status,200);assert.equal(createHash('sha256').update(Buffer.from(await response.arrayBuffer())).digest('hex'),manifest.executable.sha256);assert.match(response.headers.get('content-disposition'),/attachment/)}finally{await new Promise(r=>server.close(r))}
// Registered-but-offline helper must expose recovery at the exact failed clicked control.
{const f=fixture(),children=[],node={dataset:{},appendChild:n=>children.push(n),set textContent(v){this.text=v;children.length=0},get textContent(){return this.text}},control={parentElement:{querySelector:()=>node},setAttribute(){},removeAttribute(){}};f.s.document={createElement:tag=>({tag,dataset:{},addEventListener(){}})};const running=f.s.run('shop',control);await tick();for(let i=0;i<8;i++){f.reply(f.pending[i],{status:'pending'});await tick();if(i<7){f.timers.shift()();await tick()}}assert.equal(await running,false);assert.ok(children.some(n=>n.href==='/launcher-setup'&&n.textContent.includes('ดาวน์โหลด')));assert.equal(f.s.requests.size,1);const check=f.s.run('shop',control);await tick();f.reply(f.pending[8],{status:'pending'});await check;assert.equal(f.opened.length,1);assert.equal(f.s.requests.size,1);assert.equal(children.some(n=>n.href==='/launcher-setup'),false,'healthy pending refresh removes contextual recovery');}
console.log('PASS v77 same-browser guided states, pinned real attachment link/HTTP/hash/headers, no auto-install, adjacent offline recovery without duplicate command');
