import assert from 'node:assert/strict';import {mkdtempSync,rmSync,readFileSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{execFileSync}from'node:child_process';
import {fixture,route,helper,secret,owner}from'./test-browser-launcher-transport.mjs';
import {launcherMac,launcherCanonical}from'../functions/_browser_launcher_crypto.js';import{sha256}from'../functions/_lib.js';
const e=fixture(),code='AABBCCDDEEFF',newId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
await route(e,'pair-stage',{helper_id:helper,owner_hash:owner,port:53179,secret,pair_code:'12ABCDEF'},'',true);const p=await(await route(e,'pair-prepare',{pair_id:helper})).json();await route(e,'pair-confirm',{pair_id:helper,pair_code:p.pair_code,confirm_nonce:p.confirm_nonce,replace_id:''});
const stage={helper_id:newId,owner_hash:owner,port:53180,secret,pair_code:code,replaces_helper_id:helper};assert.equal((await route(e,'pair-stage',stage,'',true)).status,200);assert.equal((await route(e,'pair-prepare-code',{pair_code:code},'other')).status,409,'other account cannot activate without replacing old owner');const prepared=await(await route(e,'pair-prepare-code',{pair_code:code})).json();assert.equal(prepared.replace_id,helper);assert.equal((await route(e,'pair-confirm',{pair_id:newId,pair_code:code,confirm_nonce:prepared.confirm_nonce,replace_id:''})).status,409);assert.equal(e.DB.raw.prepare('SELECT status FROM browser_launcher_helpers WHERE id=?').get(helper).status,'active');assert.equal((await route(e,'pair-confirm',{pair_id:newId,pair_code:code,confirm_nonce:prepared.confirm_nonce,replace_id:helper})).status,200);assert.equal(e.DB.raw.prepare('SELECT status FROM browser_launcher_helpers WHERE id=?').get(helper).status,'revoked');assert.equal(e.DB.raw.prepare('SELECT replaces_helper_id FROM browser_launcher_helpers WHERE id=?').get(newId).replaces_helper_id,helper);
assert.equal((await route(e,'pair-confirm',{pair_id:newId,pair_code:code,confirm_nonce:prepared.confirm_nonce,replace_id:helper})).status,409);
console.log('PASS v76 exact original-helper/current-owner replacement, no-confirm old active, one-use final activation/revocation');
const challenge=await(await route(e,'challenge',{helper_id:newId,command_id:newId,purpose:'pair-state'},'',true)).json();const stateBody={helper_id:newId,key_version:1,command_id:newId,nonce:challenge.nonce,expires_at:challenge.expires_at,payload:'',mac:await launcherMac(secret,launcherCanonical('pair-state',newId,1,newId,challenge.nonce,challenge.expires_at,await sha256('')))};const state=await(await route(e,'pair-state',stateBody,'',true)).json();assert.equal(state.paired,true);assert.equal(state.helper_id,newId);assert.equal(state.replaces_helper_id,helper);assert.deepEqual(await(await route(e,'pair-state',stateBody,'',true)).json(),state,'lost-response proof retry preserves committed candidate');assert.equal((await route(e,'pair-state',{...stateBody,mac:'00'.repeat(32)},'',true)).status,403);assert.ok(e.DB.raw.prepare('EXPLAIN QUERY PLAN SELECT id FROM browser_launcher_helpers WHERE id=? AND user_id=? AND status=?').all(helper,1,'active').some(r=>r.detail.includes('SEARCH')));console.log('PASS signed exact replacement proof is authenticated/idempotent and old-helper lookup uses primary-key index');
const work=mkdtempSync(join(tmpdir(),'visiond-orphan-harness-'));try{const exe=join(work,'OrphanPortHarness.exe');execFileSync(join(process.env.WINDIR||'C:\\Windows','Microsoft.NET','Framework64','v4.0.30319','csc.exe'),['/nologo','/target:exe','/main:OrphanPortHarness','/r:System.Security.dll','/r:System.Web.Extensions.dll','/r:System.Windows.Forms.dll','/r:System.Drawing.dll','/r:System.Management.dll','/out:'+exe,'tools\\browser-launcher\\Launcher.cs','tools\\browser-launcher\\Setup.cs','scripts\\fixtures\\OrphanPortHarness.cs'],{stdio:'inherit'});console.log(execFileSync(exe,[],{encoding:'utf8',timeout:20000}).trim());}finally{rmSync(work,{recursive:true,force:true})}
const native=readFileSync('tools/browser-launcher/Launcher.cs','utf8'),setup=readFileSync('tools/browser-launcher/Setup.cs','utf8');assert.match(native,/AwaitRepairConfirmation\(confirmed/);assert.match(setup,/LocalHelper.HasRepairCandidate\(\)\|\|\(!LocalHelper.AwaitingRepairStart\(\)/);assert.match(setup,/status.Text=NeedsRepair\?/);assert.match(setup,/LocalHelper.CompleteRepairStartup\(\)/);assert.doesNotMatch(native.slice(native.indexOf('internal static bool RepairPort'),native.indexOf('private static Dictionary<string,object> Signed')),/Process.Start|https:\/\//);
