import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {alignCategoryText,onRequestPost} from '../functions/api/admin/products/bulk-category.js';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const [version,index,admin,v12,ui,api,roadmap]=await Promise.all([read('VERSION.txt'),read('public/index.html'),read('public/admin.html'),read('public/v12-connect.html'),read('public/admin.js'),read('functions/api/admin/products/bulk-category.js'),read('VISIOND-ROADMAP.md')]);
assert.equal(version.trim(),'v0.14.208');assert.match(index,/WEB v0\.14\.208/);assert.match(admin,/ADMIN v0\.14\.208/);assert.match(admin,/admin\.js\?v=014208/);assert.match(v12,/v0\.14\.208/);
assert.match(admin,/id="newBundleButton"[\s\S]*id="bulkMoveCategoryButton"/);assert.match(admin,/id="bulkMoveCategoryDialog"/);
for(const token of ['openBulkMoveCategory','moveSelectedProductsCategory','/api/admin/products/bulk-category','confirmed:true','bulkSelectedProducts.clear()'])assert.ok(ui.includes(token),token);
for(const token of ['requireAdmin','product_slug_history','NUMERIC_PRODUCT_ID_UNCHANGED','bundle_source_allocations','ctx.env.DB.batch','อยู่หมวดปลายทางแล้ว','Slug ใหม่ชนกับสินค้าอื่น'])assert.ok(api.includes(token),token);
assert.equal(alignCategoryText('ชุดรอยสัก 1','tattoo',{slug:'coloring',name:'ระบายสี'},true),'ระบายสี ชุดรอยสัก 1');
assert.equal(alignCategoryText('แบบรอยสักชุด 1',{slug:'tattoo',name:'รอยสัก'},{slug:'coloring',name:'ระบายสี'},true),'แบบระบายสีชุด 1');
const denied=await onRequestPost({request:new Request('https://test/api/admin/products/bulk-category',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}),env:{}});assert.equal(denied.status,401);
assert.match(roadmap,/Bulk Product Category Move/);console.log('v0.14.208 bulk category move frontend/backend events: PASS');
