import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('public/index.html','utf8');
const css=fs.readFileSync('public/home-modern-ai.css','utf8');
const catalog=fs.readFileSync('public/catalog-sync.js','utf8');
assert.match(html,/visiond-design-system\.css\?v=01489/);
assert.match(html,/home-modern-ai\.css\?v=01490/);
assert.match(html,/<body class="home-page home-ai-commerce">/);
for(const id of ['courseOwnerAddCart','courseOwnerPrice','courseOwnerOriginalPrice','courseOwnerCover','homeProductSearch','clearHomeProductSearch','homeProductSearchCount'])assert.match(html,new RegExp(`id="${id}"`),`missing ${id}`);
for(const hook of ['class="vd-grid"','catalog-sync.js','home-course-rights.js','meta-pixel.js','elon-chat.css','mobile-storefront.css','data-cart-count'])assert.ok(html.includes(hook),`missing ${hook}`);
for(const section of ['home-ai-hero','course-owner-feature','showcase-section','vd-catalog-wrap','digital-categories-section','tattoo-seo-section','home-contact-section'])assert.ok(html.includes(section),`missing ${section}`);
for(const semantic of ['vds-card--hero','vds-card--feature','vds-card--information','vds-btn--promotion','vds-btn--primary','vds-btn--secondary','vds-btn--tonal'])assert.ok(html.includes(semantic),`missing ${semantic}`);
assert.match(html,/<label class="home-search-label" for="homeProductSearch">/);
for(const link of ['/digital-products.html','/courses.html','course-selling-rights','category=tattoo','category=coloring','category=worksheet','category=development-game','https://lin.ee/','https://m.me/'])assert.ok(html.includes(link),`missing ${link}`);
for(const seo of ['rel="canonical"','application/ld+json','og:title','twitter:card'])assert.ok(html.includes(seo),`missing ${seo}`);
assert.match(catalog,/classList\.add\("vds-card", "vds-card--product"\)/);
assert.match(catalog,/data-add-cart/);assert.match(catalog,/itemCount >= 30/);assert.match(catalog,/course-selling-rights/);assert.match(catalog,/promotion_percent/);
for(const check of ['focus-visible','prefers-reduced-motion','max-width:420px','min-height:44px','--vd-ai-midnight'])assert.ok(css.includes(check),`missing ${check}`);
assert.equal((css.match(/{/g)||[]).length,(css.match(/}/g)||[]).length);
console.log('v0.14.90 Storefront Home Modern AI adoption passed');
