import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const [version,index,admin,v12,ui,api,roadmap]=await Promise.all(['VERSION.txt','public/index.html','public/admin.html','public/v12-connect.html','public/admin.js','functions/api/admin/products/bulk-category.js','VISIOND-ROADMAP.md'].map(read));
assert.equal(version.trim(),'v0.14.214');assert.match(index,/WEB v0\.14\.214/);assert.match(admin,/ADMIN v0\.14\.214/);assert.match(v12,/v0\.14\.214/);assert.match(admin,/admin\.js\?v=014214/);
assert.doesNotMatch(admin,/id="bulkMoveCategoryButton"[^>]*disabled/);
for(const token of["moveButton.disabled=false","productSearchInput.scrollIntoView","productSearchInput.focus()","ย้ายหมวดหรือลบ","ย้ายหมวด ${count} ตะกร้า"])assert.ok(ui.includes(token),token);
for(const token of['requireAdmin','confirmed','UPDATE products SET slug='])assert.ok(api.includes(token),token);
assert.match(roadmap,/Bulk Category Move Button Guidance/);
console.log('v0.14.214 bulk category move button selection guidance: PASS');
