import assert from 'node:assert/strict';
import fs from 'node:fs';
import {encryptAccountVaultValue,decryptAccountVaultValue} from '../functions/_account_vault_crypto.js';
const read=file=>fs.readFileSync(new URL('../'+file,import.meta.url),'utf8');
const html=read('public/account-vault.html');
const indexApi=read('functions/api/admin/account-vault/index.js');
const itemApi=read('functions/api/admin/account-vault/[id].js');
const cryptoSource=read('functions/_account_vault_crypto.js');
const legacyMigration=read('migrations/0076_account_vault.sql');
const socialMigration=read('migrations/0108_account_vault_social_hint.sql');
const admin=read('public/admin.html');
assert.equal(read('VERSION.txt').trim(),'v0.20.119');
assert.match(html,/บัญชีโซเชียล/);
assert.doesNotMatch(html,/name="password"|name="login_id"/);
for(const token of['record_kind','encryption_context','password_hint_ciphertext','idx_admin_account_vault_owner_kind_id'])assert.ok(socialMigration.includes(token),token);
for(const source of[indexApi,itemApi]){assert.match(source,/requireBoss/);assert.doesNotMatch(source,/requireAdmin|CREATE TABLE/)}
assert.match(cryptoSource,/AES-GCM/);
assert.match(cryptoSource,/ACCOUNT_VAULT_ENCRYPTION_KEY/);
assert.match(legacyMigration,/password_ciphertext/);
assert.equal((admin.match(/ACCOUNT-VAULT-001/g)||[]).length,1);
const env={ACCOUNT_VAULT_ENCRYPTION_KEY:'test-key-that-is-at-least-thirty-two-characters'};
const cipher=await encryptAccountVaultValue(env,'legacy-secret','7:password');
assert.equal(await decryptAccountVaultValue(env,cipher,'7:password'),'legacy-secret');
await assert.rejects(()=>decryptAccountVaultValue(env,cipher,'social:7:password-hint'));
console.log('PASS legacy account-vault AES-GCM compatibility and v0.20.119 social-hint isolation');
