import assert from "node:assert/strict";import fs from "node:fs";import {execFileSync} from "node:child_process";
const read=p=>fs.readFileSync(p,"utf8"),theme=read("public/frontend-theme.css"),promo=read("public/promo-banner.js"),cart=read("public/cart.js"),headers=read("public/_headers"),stamp=read("VERSION.txt").trim().replace(/\D/g,"");
const pages=["index.html","digital-products.html","product.html","cart.html","courses.html","bots.html","blog.html","about.html","contact.html","login.html","register.html","forgot-password.html","reset-password.html","privacy.html","terms.html","course-rights-terms.html","account.html","dashboard.html","my-courses.html","learn.html","my-programs.html","course-seller.html","course-basket-edit.html","blog/how-to-choose-tattoo-design.html","blog/popular-tattoo-styles.html","blog/tattoo-design-pdf-for-artists.html"];
for(const page of pages){const html=read(`public/${page}`);assert.ok(html.includes("vd-frontend"),page);const versions=[...html.matchAll(/\?v=(\d+)/g)].map(x=>x[1]),pageStamp=versions[0];assert.ok(pageStamp&&Number(pageStamp)>=14102&&Number(pageStamp)<=Number(stamp),`${page}: invalid cache stamp ${pageStamp}`);assert.ok(html.includes(`/frontend-theme.css?v=${pageStamp}`),page);assert.ok(versions.every(x=>x===pageStamp),`${page}: ${[...new Set(versions)]}`)}
for(const token of ["linear-gradient(180deg,#74d8d2",".vd-card-actions a",".vd-card-actions button",".boss-mobile-launch",".topbar.mobile-nav-ready","background:var(--vf-tiffany)!important","background:#fff!important"])assert.ok(theme.includes(token),token);
for(const dark of ["background:#0a5b57","background:#172127","background:var(--vd-ai-midnight)"])assert.ok(!theme.includes(dark),dark);
assert.ok(promo.includes("?motion=${Date.now()}"));assert.ok(cart.includes("?motion=${Date.now()}"));for(const kind of ["/*.css","/*.js","/assets/*.gif"])assert.ok(headers.includes(kind),kind);
const identify=execFileSync("identify",["-format","%n %T\\n","public/assets/visiond-bundle-promo.gif"],{encoding:"utf8"}),verbose=execFileSync("identify",["-verbose","public/assets/visiond-bundle-promo.gif"],{encoding:"utf8"});assert.equal(identify.trim().split("\n").length,4);assert.ok(identify.includes("4 100"));assert.ok(identify.includes("4 130"));assert.match(verbose,/Iterations: 0/);
assert.ok(Number(read("VERSION.txt").trim().split(".").at(-1))>=102);console.log("v0.14.102 canonical frontend theme cache and animated promo passed");
