import fs from 'node:fs';
import assert from 'node:assert/strict';
import {ELON_KNOWLEDGE,elonSalesSearchTerms,elonSystemPrompt} from '../functions/_elon.js';
const read=path=>fs.readFileSync(path,'utf8');
assert.ok(Number(read('VERSION.txt').trim().split('.').pop())>=75);
const tattooTerms=elonSalesSearchTerms('ชั้นสนรอยสัก');
assert.ok(tattooTerms.includes('รอยสัก'));
assert.ok(tattooTerms.includes('แบบสัก'));
assert.ok(tattooTerms.includes('tattoo'));
for(const step of ['สินค้าดิจิทัล','ดูสินค้า','ซื้อสินค้านี้','ใส่รถเข็น','ชำระเงิน','สินค้าของฉัน','ดาวน์โหลด'])assert.match(ELON_KNOWLEDGE,new RegExp(step));
const prompt=elonSystemPrompt({authenticated:true,can_use_seller_vision5:false},{path:'/',title:'หน้าแรก'},{catalog_categories:[{slug:'tattoo',name:'แบบรอยสัก',product_count:30}],matching_products:[{slug:'tattoo-001',title:'แบบรอยสักชุดที่ 1',price_baht:39}]});
assert.match(prompt,/แบบรอยสัก/);
assert.match(prompt,/tattoo-001/);
const core=read('functions/_elon.js'),chat=read('functions/api/elon/chat.js');
assert.match(core,/catalog_categories/);
assert.match(core,/matching_products/);
assert.match(core,/COUNT\(\*\) product_count/);
assert.match(chat,/elonPublicSalesContext\(ctx\.env,pageContext,message\)/);
assert.equal(JSON.parse(read('requirements-ledger.json')).requirements.find(item=>item.id==='EC-ELON-002')?.status,'DONE-VERIFIED');
console.log('v0.14.75 ELON catalog and navigation hotfix passed');
