import assert from'node:assert/strict';
import {readFile} from'node:fs/promises';
import fs from'node:fs';
import http from'node:http';
import path from'node:path';
import {createRequire} from'node:module';
import {fileURLToPath} from'node:url';
import {DatabaseSync} from'node:sqlite';
import {balanceStories,buildTimeline,extractImageUrls,imageDimensions,isSafeRemoteUrl,newsRssUrl,parseNewsRss,storyFingerprint} from'../functions/_vsport.js';
import {planTimeline} from'../public/vsport.js';

const root=new URL('../',import.meta.url),read=path=>readFile(new URL(path,root),'utf8');
const [migration,api,assetApi,html,css,client,admin,home,featureMap,version]=await Promise.all(['migrations/0111_vsport.sql','functions/api/admin/vsport.js','functions/api/admin/vsport-assets/[id].js','public/vsport.html','public/vsport.css','public/vsport.js','public/admin.html','public/index.html','FEATURE-MAP.md','VERSION.txt'].map(read));

const visibleVersion=version.trim();assert.ok(['v0.20.122','v0.20.123','v0.20.124','v0.20.125'].includes(visibleVersion));assert.ok(home.includes(`WEB ${visibleVersion}`));assert.ok(admin.includes(`ADMIN ${visibleVersion}`));assert.match(admin,/href="\/vsport\.html"[^>]+data-feature="VSPORT-001"/);assert.match(html,/data-feature="VSPORT-001"/);assert.match(html,/name="scopeMode" value="specific_team"/);assert.match(html,/name="scopeMode" value="all_teams_for_day"/);assert.match(html,/id="targetSeconds"/);assert.match(html,/id="silentVideoFile"/);assert.match(html,/id="mergeAudioFile"/);assert.match(html,/id="thumbFocusText"/);assert.match(html,/id="thumbFocusAsset"/);assert.equal((html.match(/data-layout="(?:split|stack|spotlight)"/g)||[]).length,3);assert.doesNotMatch(css,/(?:^|})\.vds-btn(?:--[a-z-]+)?\s*\{/, 'page CSS must not redefine canonical buttons');for(const button of html.matchAll(/<button\b([^>]*)>/g)){assert.match(button[1],/class="[^"]*vds-btn/);assert.match(button[1],/type="(?:button|submit)"/)}
for(const token of ['.decode()','localStorage','MediaRecorder','captureStream','requestKey','inflight','CACHE_MS','viewerScope=','recoverQueue','recoverServerJobs','VIDEO_DURATION_MISMATCH','story-group','thumbnail_focus_asset_id','media.currentTime=1e101','fallbackSeconds:measuredElapsed','queueBusy','JOB_LEASE_MS'])assert.ok(client.includes(token),token);assert.match(client,/fetch\('\/api\/auth\/me'/);assert.match(client,/queueStorageKey=.*viewerScope/);assert.match(api,/requireAdmin/);assert.match(assetApi,/requireAdmin/);assert.match(api,/private, no-store/);assert.match(assetApi,/private, no-store/);assert.match(api,/LIMIT 25/g);assert.match(api,/safeFollowFetch/);assert.match(api,/redirect:'manual'/);assert.match(api,/state='ingesting'.*state IN \('candidate','failed'\)/s);assert.match(api,/jobs_project/);assert.match(api,/JOB_LEASE_MS=120000/);assert.match(api,/status=\?.*updated_at=\?/s);assert.match(migration,/UNIQUE INDEX IF NOT EXISTS idx_vsport_assets_candidate_unique/);assert.match(featureMap,/## VSPORT-001/);

const item=(headline,publisher,date='Thu, 18 Sep 2026 10:00:00 GMT')=>`<item><title><![CDATA[${headline}]]></title><link>https://news.google.com/articles/${encodeURIComponent(headline)}</link><pubDate>${date}</pubDate><description><![CDATA[<p>รายละเอียด ${headline}</p>]]></description><source url="https://example.com">${publisher}</source></item>`;
const rss=`<rss><channel>${item('Liverpool win transfer race','World Sport')}${item('Liverpool manager update','Daily Ball')}${item('Liverpool player returns','Global FC')}${item('Liverpool fourth story','Extra Sport')}${item('Arsenal announce signing','London News')}${item('Arsenal injury update','Football Wire')}${item('Old Liverpool story','Old News','Wed, 17 Sep 2026 10:00:00 GMT')}</channel></rss>`;
const all=parseNewsRss(rss,{newsDate:'2026-09-18',scopeMode:'all_teams_for_day'});assert.equal(all.length,5);assert.equal(all.filter(story=>story.team_name==='Liverpool FC').length,3,'all-team balance caps one group at three');assert.equal(new Set(all.map(story=>story.fingerprint)).size,all.length);const specific=parseNewsRss(rss,{newsDate:'2026-09-18',scopeMode:'specific_team',teamName:'Liverpool FC'});assert.equal(specific.length,4);assert.ok(specific.every(story=>story.team_name==='Liverpool FC'));assert.match(newsRssUrl('2026-09-18','specific_team','Liverpool FC'),/after%3A2026-09-18/);assert.equal(storyFingerprint(all[0]),storyFingerprint({...all[0]}));assert.equal(balanceStories([{team_name:'A',id:1},{team_name:'A',id:2},{team_name:'B',id:3}],{limit:3,maxPerTeam:2}).map(x=>x.id).join(','),'1,3,2');
assert.equal(isSafeRemoteUrl('https://images.example.com/a.jpg'),true);assert.equal(isSafeRemoteUrl('https://[2606:4700:4700::1111]/x'),true);for(const url of ['http://example.com/a.jpg','https://localhost/a','https://127.0.0.1/a','https://10.0.0.2/a','https://172.20.0.1/a','https://192.168.1.1/a','https://[fc00::1]/x','https://[fdff::1]/x','https://[fe80::1]/x','https://[febf::1]/x','https://[::]/x','https://[::1]/x','https://[ff02::1]/x','https://[::ffff:127.0.0.1]/x','https://[::ffff:192.168.1.1]/x'])assert.equal(isSafeRemoteUrl(url),false,url);assert.deepEqual(extractImageUrls('<meta property="og:image" content="/hero.jpg"><img src="https://cdn.example.com/one.png">','https://news.example.com/story'),['https://news.example.com/hero.jpg','https://cdn.example.com/one.png']);
const png=new Uint8Array(24);png.set([0x89,0x50,0x4e,0x47],0);new DataView(png.buffer).setUint32(16,1280);new DataView(png.buffer).setUint32(20,720);assert.deepEqual(imageDimensions(png,'image/png'),{width:1280,height:720});const timeline=buildTimeline([1,2,3],10.001);assert.equal(timeline[0].start_seconds,0);assert.equal(timeline.at(-1).end_seconds,10.001);assert.ok(timeline.every((row,index)=>row.duration_seconds>0&&(index===0||row.start_seconds===timeline[index-1].end_seconds)));assert.deepEqual(planTimeline([1,2,3],10.001),timeline);

const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE users(id INTEGER PRIMARY KEY);INSERT INTO users(id) VALUES(1);');db.exec(migration);const addProject=db.prepare("INSERT INTO vsport_projects(owner_id,title,news_date,scope_mode,target_minutes,updated_at) VALUES(1,?,'2026-09-18','all_teams_for_day',30,?)");for(let i=1;i<=61;i++)addProject.run(`Project ${i}`,`2026-09-${String(1+Math.floor(i/5)).padStart(2,'0')} 10:${String(i%60).padStart(2,'0')}:00`);let cursor=null,ids=[];do{const sql=cursor?'SELECT id,updated_at FROM vsport_projects WHERE owner_id=? AND (updated_at<? OR (updated_at=? AND id<?)) ORDER BY updated_at DESC,id DESC LIMIT ?':'SELECT id,updated_at FROM vsport_projects WHERE owner_id=? ORDER BY updated_at DESC,id DESC LIMIT ?',args=cursor?[1,cursor.at,cursor.at,cursor.id,25]:[1,25],rows=db.prepare(sql).all(...args),page=rows.slice(0,24);ids.push(...page.map(row=>row.id));cursor=rows.length>24?{at:page.at(-1).updated_at,id:page.at(-1).id}:null;const detail=db.prepare(`EXPLAIN QUERY PLAN ${sql}`).all(...args).map(row=>row.detail).join(' | ');assert.match(detail,/idx_vsport_projects_owner_updated/);assert.doesNotMatch(detail,/TEMP B-TREE/)}while(cursor);assert.equal(ids.length,61);assert.equal(new Set(ids).size,61,'project keyset has no duplicates or gaps');
const projectId=ids[0],insertStory=db.prepare("INSERT INTO vsport_stories(project_id,headline,team_name,publisher,source_url,published_at,retrieved_at,fingerprint,sort_order) VALUES(?,?,'A','P','https://example.com','2026-09-18','2026-09-18',?,?)");for(let i=1;i<=61;i++)insertStory.run(projectId,`H${i}`,`f${i}`,i);let after=0,storyIds=[];do{const rows=db.prepare('SELECT id FROM vsport_stories WHERE project_id=? AND id>? ORDER BY id LIMIT 25').all(projectId,after),page=rows.slice(0,24);storyIds.push(...page.map(row=>row.id));after=rows.length>24?page.at(-1).id:0;if(!after)break}while(true);assert.equal(storyIds.length,61);assert.equal(new Set(storyIds).size,61,'story keyset has no duplicates or gaps');
for(const [sql,args,index]of[["SELECT id FROM vsport_stories WHERE project_id=? AND id>? ORDER BY id LIMIT 25",[projectId,0],'idx_vsport_stories_project_id'],["SELECT id FROM vsport_image_candidates WHERE project_id=? AND id>? ORDER BY id LIMIT 25",[projectId,0],'idx_vsport_candidates_project_id'],["SELECT id FROM vsport_assets WHERE project_id=? AND id>? ORDER BY id LIMIT 25",[projectId,0],'idx_vsport_assets_project_id'],["SELECT id FROM vsport_assets WHERE id=? AND owner_id=?",[1,1],'idx_vsport_assets_owner_id'],["SELECT id FROM vsport_jobs WHERE project_id=? AND owner_id=? ORDER BY updated_at DESC,id LIMIT 24",[projectId,1],'idx_vsport_jobs_owner_project_updated']]){const detail=db.prepare(`EXPLAIN QUERY PLAN ${sql}`).all(...args).map(row=>row.detail).join(' | ');assert.match(detail,new RegExp(`${index}|INTEGER PRIMARY KEY`),detail);assert.doesNotMatch(detail,/TEMP B-TREE/,detail)}
db.prepare("INSERT INTO vsport_jobs(id,owner_id,project_id,job_type,idempotency_key,status,checkpoint,updated_at) VALUES('stale',1,?,'discover','stable-key','running','fetch_news','2026-09-18 00:00:00')").run(projectId);const stale=db.prepare("SELECT id,status,updated_at FROM vsport_jobs WHERE id='stale'").get(),claim=db.prepare("UPDATE vsport_jobs SET status='queued',checkpoint=?,error_text='',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status=? AND updated_at=?");assert.equal(claim.run('recovered_after_stale_lease',stale.id,stale.status,stale.updated_at).changes,1,'first stale lease recovery wins');assert.equal(claim.run('recovered_after_stale_lease',stale.id,stale.status,stale.updated_at).changes,0,'stale lease recovery is compare-and-set');db.close();

const require=createRequire(import.meta.url);let chromium;for(const candidate of[process.env.PLAYWRIGHT_PACKAGE,'C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright','playwright'].filter(Boolean)){try{({chromium}=require(candidate));break}catch{}}assert.ok(chromium,'Playwright Chromium is required');
const publicRoot=path.join(path.dirname(fileURLToPath(import.meta.url)),'..','public'),fixtureProject={id:9,title:'ข่าวฟุตบอลวันนี้',news_date:'2026-09-18',scope_mode:'all_teams_for_day',team_name:'',target_minutes:30,target_seconds:1800,status:'media_review',narration_script:'บททดสอบ',thumbnail_headline:'ข่าวเด่นวันนี้',thumbnail_subheadline:'ครบทุกประเด็น',thumbnail_focus_text:'Liverpool',thumbnail_focus_asset_id:31,thumbnail_palette:'red-yellow',thumbnail_layout:'split'},fixtureProject2={...fixtureProject,id:10,title:'ข่าวฟุตบอลวันนี้ 2',thumbnail_focus_asset_id:32},fixtureStories=[{id:11,headline:'Liverpool story',summary:'สรุปหนึ่ง',team_name:'Liverpool FC',publisher:'World Sport',source_url:'https://example.com/liverpool',published_at:'2026-09-18T10:00:00Z',retrieved_at:'2026-09-18T11:00:00Z',selected:1,sort_order:0},{id:12,headline:'Arsenal story',summary:'สรุปสอง',team_name:'Arsenal',publisher:'London Ball',source_url:'https://example.com/arsenal',published_at:'2026-09-18T09:00:00Z',retrieved_at:'2026-09-18T11:00:00Z',selected:1,sort_order:10}],fixtureAsset={id:31,story_id:11,candidate_id:21,source_url:'https://cdn.example.com/photo.png',source_page_url:'https://example.com/liverpool',publisher:'World Sport',mime_type:'image/png',file_size:100,width:1280,height:720,created_at:'2026-09-18',preview_url:'/api/admin/vsport-assets/31'},fixtureAsset2={...fixtureAsset,id:32,candidate_id:22,preview_url:'/api/admin/vsport-assets/32'};
const send=(response,data,status=200)=>{response.statusCode=status;response.setHeader('content-type','application/json; charset=utf-8');response.end(JSON.stringify(data))};
const server=http.createServer((request,response)=>{const url=new URL(request.url,'http://127.0.0.1');if(url.pathname==='/api/auth/me')return send(response,{user:{id:7,role:'admin'}});if(url.pathname==='/api/admin/vsport'&&url.searchParams.has('jobs_project'))return send(response,{jobs:[]});if(url.pathname==='/api/admin/vsport'&&['9','10'].includes(url.searchParams.get('id'))){const second=url.searchParams.get('id')==='10';return send(response,{project:second?fixtureProject2:fixtureProject,stories:fixtureStories,candidates:[],assets:[second?fixtureAsset2:fixtureAsset],story_pagination:{limit:24,has_more:false,next_cursor:null},media_pagination:{candidates:{limit:24,has_more:false},assets:{limit:24,has_more:false}}})}if(url.pathname==='/api/admin/vsport')return send(response,{items:[fixtureProject,fixtureProject2],pagination:{limit:24,has_more:false,next_cursor:null}});if(['/api/admin/vsport-assets/31','/api/admin/vsport-assets/32'].includes(url.pathname)){response.setHeader('content-type','image/svg+xml');return response.end('<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><rect width="1280" height="720" fill="#0abab5"/></svg>')}const relative=url.pathname==='/'?'/vsport.html':url.pathname,local=path.resolve(publicRoot,`.${relative}`);if(!local.startsWith(publicRoot)||!fs.existsSync(local)){response.statusCode=404;return response.end('not found')}const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};response.setHeader('content-type',types[path.extname(local)]||'application/octet-stream');response.end(fs.readFileSync(local))});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});
try{
  const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(()=>localStorage.setItem('visiond_vsport_render_queue_v1:7:admin',JSON.stringify([{id:'recover',projectId:9,title:'งานที่ค้าง',seconds:1800,status:'active'}])));
  await page.goto(`${base}/vsport.html`);
  await page.getByRole('button',{name:'เปิดทำต่อ'}).first().click();
  await page.waitForSelector('#workspace:not([hidden])');
  assert.equal(await page.locator('.story-group').count(),2,'all-team stories render in team groups');
  assert.equal(await page.locator('#thumbFocusAsset option').count(),2,'thumbnail exposes automatic and selected image focus');
  assert.equal(await page.locator('#renderQueue').textContent().then(text=>text.includes('paused')),true,'active queue recovers as paused');
  assert.equal(await page.getByRole('button',{name:'ลองใหม่'}).count(),1);

  await page.getByRole('button',{name:'ลองใหม่'}).click();
  await page.getByRole('button',{name:'ข้ามงานนี้'}).click();
  await page.waitForFunction(()=>document.querySelector('#assetList')?.textContent.includes('พร้อมใช้ในไทม์ไลน์'));
  await page.locator('#targetSeconds').fill('1');
  await page.locator('#planTimeline').click();
  assert.match(await page.locator('#mediaStatus').textContent(),/จบที่ 1\.000 วินาที/);
  await page.locator('#enqueueRender').click();
  await page.locator('#startQueue').click();
  await page.waitForFunction(()=>document.querySelector('#renderStatus')?.textContent.includes('เรนเดอร์สำเร็จ'),null,{timeout:15000});
  assert.match(await page.locator('#renderQueue').textContent(),/completed/,'one-second MediaRecorder output must finalize the queue');
  assert.equal(await page.locator('#silentOutput a[download]').count(),1,'successful render exposes a download');

  await page.getByRole('button',{name:'ยืนยันเสร็จและนำออก'}).click();
  await page.locator('#enqueueRender').click();
  await page.waitForFunction(()=>document.querySelectorAll('#renderQueue .queue-row').length===1);
  await page.locator('.project-row').filter({hasText:'ข่าวฟุตบอลวันนี้ 2'}).getByRole('button',{name:'เปิดทำต่อ'}).click();
  await page.waitForFunction(()=>document.querySelector('#workspaceTitle')?.textContent==='ข่าวฟุตบอลวันนี้ 2');
  await page.locator('#targetSeconds').fill('1');
  await page.locator('#planTimeline').click();
  await page.locator('#enqueueRender').click();
  await page.waitForFunction(()=>document.querySelectorAll('#renderQueue .queue-row').length===2);
  assert.equal(await page.locator('#renderQueue .queue-row').count(),2,'two projects can wait in the persisted queue');
  await page.evaluate(()=>Object.defineProperty(HTMLMediaElement.prototype,'duration',{configurable:true,get:()=>Infinity}));
  await page.evaluate(()=>{document.querySelector('#renderProgress').value=0});
  await page.locator('#startQueue').click();
  await page.waitForFunction(()=>Number(document.querySelector('#renderProgress')?.value)>=100&&document.querySelector('#renderQueue')?.textContent.includes('active'),null,{timeout:15000});
  await page.locator('.project-row').filter({hasText:'ข่าวฟุตบอลวันนี้ 2'}).getByRole('button',{name:'เปิดทำต่อ'}).click();
  assert.equal(await page.locator('#workspaceTitle').textContent(),'ข่าวฟุตบอลวันนี้','manual project switching is blocked through render finalization');
  await page.locator('#startQueue').click();
  await page.waitForFunction(()=>{const text=document.querySelector('#renderQueue')?.textContent||'';return text.includes('completed')&&text.includes('queued')},null,{timeout:15000});
  assert.equal((await page.locator('#renderQueue').textContent()).includes('active'),false,'second job cannot start during first job finalization');
  await page.locator('#startQueue').click();
  await page.waitForFunction(()=>document.querySelector('#workspaceTitle')?.textContent==='ข่าวฟุตบอลวันนี้ 2'&&[...document.querySelectorAll('#renderQueue .queue-row')].filter(row=>row.textContent.includes('completed')).length===2,null,{timeout:15000});
  assert.equal(await page.locator('#silentOutput a[download]').count(),1,'cross-project render waits for image decode and completes');
  assert.equal(errors.length,0,errors.join('\n'));

  const mobile=await browser.newPage({viewport:{width:390,height:844}});
  await mobile.goto(`${base}/vsport.html`);
  await mobile.getByRole('button',{name:'เปิดทำต่อ'}).first().click();
  await mobile.waitForSelector('#workspace:not([hidden])');
  assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth),390,'mobile page must not overflow');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
console.log('PASS v0.20.122 vSport sourced workflow, Tha1 pagination/indexes, stable image gate, exact timeline, scoped resumable jobs/queue, browser desktop/mobile, render/merge and thumbnail focus contracts');
