import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=file=>fs.readFileSync(file,'utf8');
const html=read('public/course-seller.html');
const ui=read('public/course-seller.js');
const css=read('public/course-seller.css');
const create=read('functions/api/course-seller/index.js');
const publish=read('functions/api/course-seller/[id]/publish.js');
const review=read('functions/api/admin/course-seller-reviews/[id].js');
assert.match(ui,/data-v5-step="credit"><span>1/);
assert.match(ui,/data-v5-step="draft"><span>2/);
assert.match(ui,/data-v5-step="ep"><span>3/);
assert.match(ui,/data-v5-step="setup"><span>4/);
assert.match(ui,/data-v5-step="bind"><span>5/);
assert.match(html,/1 เครดิตสร้าง(?:ร่าง)?ตะกร้าคอร์สได้ 1 ใบ/);
assert.match(html,/1280 × 720 px/);
assert.match(create,/credit_required: true/);
assert.match(create,/UPDATE course_right_credits SET active=0/);
assert.match(create,/credit_used: 1/);
assert.doesNotMatch(publish,/UPDATE course_right_credits SET active=0/);
assert.match(publish,/ไม่หักเครดิตซ้ำ/);
assert.match(review,/UPDATE course_right_credits SET active=1,used_at=NULL,used_course_id=NULL/);
assert.match(review,/credit_refunded:1/);
assert.match(css,/seller-priority-card.*display:none!important/);
assert.match(css,/#salesRows/);
assert.match(css,/#slipIssueRows/);
console.log('v0.14.87 Vision 5 rights-first five-step flow passed');
