import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
const [version,index,admin,ui,css]=await Promise.all(['VERSION.txt','public/index.html','public/admin.html','public/course-seller.js','public/course-seller.css'].map(read));
assert.equal(version.trim(),'v0.14.253');
assert.match(index,/WEB v0\.14\.253/);assert.match(admin,/ADMIN v0\.14\.253/);
for(const token of['data-course-plan="rights"','data-course-plan="free"','data-course-plan="partner"','openCoursePlan(button.dataset.coursePlan)','createCourseBasket.onclick = () => openCoursePlan("rights")'])assert.ok(ui.includes(token),token);
assert.ok(ui.indexOf('data-course-plan="rights"')<ui.indexOf('data-course-plan="free"'));assert.ok(ui.indexOf('data-course-plan="free"')<ui.indexOf('data-course-plan="partner"'));
for(const token of['ยืนยันสร้างแบบ 1','ยืนยันสร้างแบบ 2','ยืนยันสร้างแบบ 3'])assert.ok(ui.includes(token),token);
assert.match(css,/\.vision5-credit-grid > button/);assert.match(css,/cursor: pointer/);
console.log('v0.14.253 clickable course plans 1/2/3: PASS');
