import {json,requireUser} from '../../_lib.js';
import {ensureDatabase} from '../../_schema.js';
const canEdit=course=>!course.edit_expires_at||Date.parse(course.edit_expires_at)>Date.now(),slugTags=new Set(['Shopee','TikTok','Lazada','Kalodata','YouTube','Gemini','Grok','ChatGPT','Facebook','Canva','อื่น ๆ']);
const ext=file=>file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';
async function owned(ctx,user){return ctx.env.DB.prepare(`SELECT c.*,p.title,p.short_description,p.description,p.price,p.cover_url,p.slug FROM courses c JOIN products p ON p.id=c.product_id WHERE c.id=? AND c.owner_user_id=? AND c.course_origin='seller_rights' AND p.deleted_at IS NULL`).bind(ctx.params.id,user.id).first()}
async function hasPaidSale(ctx,courseId){return Boolean(await ctx.env.DB.prepare("SELECT id FROM orders WHERE seller_course_id=? AND status='paid' LIMIT 1").bind(courseId).first())}
export async function onRequestGet(ctx){await ensureDatabase(ctx.env);const auth=await requireUser(ctx);if(auth.error)return auth.error;const course=await owned(ctx,auth.user);if(!course)return json({error:'ไม่พบคอร์ส'},404);return json({item:course,editable:canEdit(course),content_locked:await hasPaidSale(ctx,course.id)},200,{'cache-control':'no-store'})}
export async function onRequestPut(ctx){
  await ensureDatabase(ctx.env);const auth=await requireUser(ctx);if(auth.error)return auth.error;const course=await owned(ctx,auth.user);if(!course)return json({error:'ไม่พบคอร์ส'},404);
  const form=await ctx.request.formData(),price=Math.round(Number(form.get('price_baht'))*100),contact=String(form.get('contact_info')||'').trim().slice(0,200);
  if(await hasPaidSale(ctx,course.id)){if(!Number.isFinite(price)||price<0)return json({error:'กรุณาระบุราคาขาย'},400);await ctx.env.DB.batch([ctx.env.DB.prepare('UPDATE products SET price=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(price,course.product_id),ctx.env.DB.prepare('UPDATE courses SET contact_info=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(contact,course.id)]);return json({ok:true,content_locked:true,message:'บันทึกข้อมูลการขายแล้ว หลังมียอดขายเปลี่ยนแปลงเนื้อหาทั้งหมดไม่ได้ หากแก้ข้อผิดพลาดภายในต้องติดต่อ VisionD เท่านั้น'})}
  if(!canEdit(course))return json({error:'หมดระยะเวลาแก้ไข 30 วันแล้ว'},403);
  const title=String(form.get('title')||'').trim(),teacher=String(form.get('teacher_name')||'').trim(),description=String(form.get('description')||'').trim(),episodes=Math.min(200,Math.max(1,Number(form.get('expected_episodes'))||1));if(!title||!teacher||!description||!Number.isFinite(price)||price<0)return json({error:'กรุณากรอกข้อมูลให้ครบ'},400);
  const tags=[...new Set(form.getAll('platform_tags').map(String).filter(x=>slugTags.has(x)))],other=String(form.get('platform_other')||'').trim().slice(0,60);if(tags.includes('อื่น ๆ')&&other)tags.push(other);if(!tags.length)return json({error:'กรุณาเลือกหัวข้อที่สอน'},400);
  let coverUrl=course.cover_url,newKey;const cover=form.get('cover');if(cover instanceof File&&cover.size){if(!['image/jpeg','image/png','image/webp'].includes(cover.type)||cover.size>8*1024*1024)return json({error:'รูปปกต้องเป็น JPG, PNG หรือ WEBP ไม่เกิน 8 MB'},400);newKey=`seller-course-cover-${crypto.randomUUID()}.${ext(cover)}`;await ctx.env.FILES.put(newKey,await cover.arrayBuffer(),{httpMetadata:{contentType:cover.type}});coverUrl='/api/media/'+newKey}
  await ctx.env.DB.batch([ctx.env.DB.prepare(`UPDATE products SET title=?,short_description=?,description=?,price=?,cover_url=?,preview_urls=?,status='draft',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(title,String(form.get('short_description')||''),description,price,coverUrl,JSON.stringify([coverUrl]),course.product_id),ctx.env.DB.prepare(`UPDATE courses SET teacher_name=?,contact_info=?,platform_tags=?,learner_level=?,expected_episodes=?,review_status=CASE WHEN license_entitlement_id IS NULL THEN 'draft' ELSE 'pending' END,review_note='',submitted_at=CASE WHEN license_entitlement_id IS NULL THEN NULL ELSE CURRENT_TIMESTAMP END,active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(teacher,contact,JSON.stringify(tags),['beginner','intermediate','advanced','all'].includes(String(form.get('learner_level')))?String(form.get('learner_level')):'beginner',episodes,course.id)]);if(newKey&&course.cover_url?.startsWith('/api/media/'))await ctx.env.FILES.delete(course.cover_url.slice('/api/media/'.length));return json({ok:true,message:'บันทึกแล้ว หากคอร์สผูกตะกร้า ระบบส่งให้ Boss ตรวจซ้ำอัตโนมัติ'})
}
export async function onRequestDelete(ctx){await ensureDatabase(ctx.env);const auth=await requireUser(ctx);if(auth.error)return auth.error;const course=await owned(ctx,auth.user);if(!course)return json({error:'ไม่พบคอร์ส'},404);if(await hasPaidSale(ctx,course.id))return json({error:'หลังมียอดขาย เปลี่ยนแปลงเนื้อหาทั้งหมดไม่ได้ หากแก้ข้อผิดพลาดภายในต้องติดต่อ VisionD เท่านั้น'},409);await ctx.env.DB.prepare("UPDATE products SET deleted_at=CURRENT_TIMESTAMP,deleted_prev_status=status,status='draft',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(course.product_id).run();return json({ok:true,message:'ลบคอร์สแล้ว เครดิตไม่ถูกคืน'})}
