import {json,requireUser} from '../../_lib.js';
import {ensureDatabase} from '../../_schema.js';
const imageTypes=['image/jpeg','image/png','image/webp'];
const ext=(name,type)=>String(name||'').split('.').pop()?.toLowerCase()||({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[type]||'bin');
const slugify=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9ก-๙]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||`course-${Date.now()}`;
const expiry=(start,days)=>{if(Number(days)===0)return null;return new Date(new Date(start).getTime()+Number(days)*86400000).toISOString()};
const editable=c=>!c.edit_expires_at||Date.parse(c.edit_expires_at)>Date.now();
async function putImage(env,file,prefix,max=8*1024*1024){if(!(file instanceof File)||!file.size)return null;if(!imageTypes.includes(file.type)||file.size>max)throw new Error('IMAGE_INVALID');const key=`${prefix}-${crypto.randomUUID()}.${ext(file.name,file.type)}`;await env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});return key}
export async function onRequestGet(ctx){
  await ensureDatabase(ctx.env);const auth=await requireUser(ctx);if(auth.error)return auth.error;
  const profile=await ctx.env.DB.prepare(`SELECT seller_bank_name bank_name,seller_account_name account_name,seller_account_number account_number,seller_payment_status status,seller_payment_submitted_at submitted_at,seller_payment_verified_at verified_at FROM users WHERE id=?`).bind(auth.user.id).first();
  const legacy=await ctx.env.DB.prepare(`SELECT e.id entitlement_id,e.granted_at,p.title license_title,c.license_edit_days,owned.id bound_course_id,op.title bound_course_title,owned.edit_expires_at,op.status bound_status FROM entitlements e JOIN products p ON p.id=e.product_id JOIN courses c ON c.product_id=p.id AND c.course_type='resale_rights' LEFT JOIN courses owned ON owned.license_entitlement_id=e.id LEFT JOIN products op ON op.id=owned.product_id WHERE e.user_id=? AND e.active=1 ORDER BY e.id DESC`).bind(auth.user.id).all();
  const credits=await ctx.env.DB.prepare(`SELECT cr.id credit_id,cr.active,cr.used_at,cr.granted_at,p.title license_title,c.license_edit_days,owned.id bound_course_id,op.title bound_course_title,owned.edit_expires_at,op.status bound_status FROM course_right_credits cr JOIN products p ON p.id=cr.product_id JOIN courses c ON c.product_id=p.id AND c.course_type='resale_rights' LEFT JOIN courses owned ON owned.license_entitlement_id=(0-cr.id) LEFT JOIN products op ON op.id=owned.product_id WHERE cr.user_id=? ORDER BY cr.id DESC`).bind(auth.user.id).all();
  const licenses=[...(legacy.results||[])];for(const x of credits.results||[]){x.entitlement_id=`credit-${x.credit_id}`;x.credit=1;licenses.push(x)}
  licenses.forEach(x=>{x.purchased_at=x.granted_at;x.available=x.credit?Boolean(x.active)&&!x.bound_course_id:!x.bound_course_id;x.expires_at=x.bound_course_id?x.edit_expires_at:null;x.editable=x.available||editable(x);x.credit_used=x.credit&&!x.active});licenses.sort((a,b)=>String(b.granted_at).localeCompare(String(a.granted_at)));
  const courses=await ctx.env.DB.prepare(`SELECT c.id,p.slug,p.title,p.short_description,p.description,p.price,p.cover_url,p.status,c.teacher_name,c.contact_info,c.platform_tags,c.learner_level,c.expected_episodes,c.review_status,c.review_note,c.payment_bank_name,c.payment_account_name,c.payment_account_number,c.edit_expires_at,c.license_edit_days,COALESCE((SELECT SUM(o.total) FROM orders o WHERE o.seller_course_id=c.id AND o.status='paid'),0) paid_total,COALESCE((SELECT COUNT(*) FROM orders o WHERE o.seller_course_id=c.id AND o.status='paid'),0) paid_orders FROM courses c JOIN products p ON p.id=c.product_id WHERE c.owner_user_id=? AND p.deleted_at IS NULL ORDER BY c.id DESC`).bind(auth.user.id).all();
  const sales=await ctx.env.DB.prepare(`SELECT o.order_no,o.total,o.updated_at,c.id course_id,p.title course_title FROM orders o JOIN courses c ON c.id=o.seller_course_id JOIN products p ON p.id=c.product_id WHERE o.course_owner_user_id=? AND o.status='paid' ORDER BY o.updated_at DESC LIMIT 200`).bind(auth.user.id).all();
  const totals=(sales.results||[]).reduce((a,x)=>{a.amount+=Number(x.total)||0;a.orders++;return a},{amount:0,orders:0});
  return json({payment_profile:profile,licenses,courses:courses.results||[],sales:sales.results||[],totals,credit_balance:(credits.results||[]).filter(x=>x.active&&!x.bound_course_id).length,credit_used:(credits.results||[]).filter(x=>!x.active).length},200,{'cache-control':'no-store'});
}
export async function onRequestPost(ctx){
  await ensureDatabase(ctx.env);const auth=await requireUser(ctx);if(auth.error)return auth.error;
  const form=await ctx.request.formData(),token=String(form.get('license_entitlement_id')||''),isCredit=token.startsWith('credit-'),licenseId=Number(isCredit?token.slice(7):token),bindingId=isCredit?-licenseId:licenseId;
  const title=String(form.get('title')||'').trim(),teacher=String(form.get('teacher_name')||'').trim(),description=String(form.get('description')||'').trim(),price=Math.round(Number(form.get('price_baht'))*100),episodes=Math.min(200,Math.max(1,Number(form.get('expected_episodes'))||1));
  if(!title||!teacher||!description||!Number.isFinite(price)||price<0)return json({error:'กรุณากรอกชื่อคอร์ส ชื่อผู้สอน รายละเอียด และราคาให้ครบ'},400);
  const owner=await ctx.env.DB.prepare(`SELECT seller_bank_name,seller_account_name,seller_account_number,seller_payment_qr_url,seller_payment_status FROM users WHERE id=?`).bind(auth.user.id).first();
  if(!owner||owner.seller_payment_status==='unset')return json({error:'กรุณาตั้งค่าบัญชีรับเงินก่อนสร้างตะกร้าคอร์ส',payment_profile_required:true},409);
  if(owner.seller_payment_status==='rejected')return json({error:'บัญชีรับเงินไม่ผ่านการตรวจ กรุณาติดต่อ VisionD หลังไมค์'},409);
  const license=isCredit?await ctx.env.DB.prepare(`SELECT cr.id,c.license_edit_days FROM course_right_credits cr JOIN courses c ON c.product_id=cr.product_id AND c.course_type='resale_rights' WHERE cr.id=? AND cr.user_id=? AND cr.active=1 AND cr.used_course_id IS NULL`).bind(licenseId,auth.user.id).first():await ctx.env.DB.prepare(`SELECT e.id,c.license_edit_days FROM entitlements e JOIN courses c ON c.product_id=e.product_id AND c.course_type='resale_rights' WHERE e.id=? AND e.user_id=? AND e.active=1`).bind(licenseId,auth.user.id).first();
  if(!license)return json({error:'ต้องซื้อสิทธิ์ลงขายคอร์สออนไลน์ก่อน จึงจะสร้างตะกร้าคอร์สได้',credit_required:true},403);
  if(await ctx.env.DB.prepare('SELECT id FROM courses WHERE license_entitlement_id=?').bind(bindingId).first())return json({error:'เครดิตสิทธิ์นี้ถูกใช้แล้ว'},409);
  const cover=form.get('cover');let coverKey;try{coverKey=await putImage(ctx.env,cover,'seller-course-cover')}catch{return json({error:'รูปปกต้องเป็น JPG, PNG หรือ WEBP ไม่เกิน 8 MB'},400)}if(!coverKey)return json({error:'กรุณาแนบรูปปกคอร์ส'},400);
  const allowed=new Set(['Shopee','TikTok','Lazada','Kalodata','YouTube','Gemini','Grok','ChatGPT','Facebook','Canva','อื่น ๆ']),tags=[...new Set(form.getAll('platform_tags').map(String).filter(x=>allowed.has(x)))],other=String(form.get('platform_other')||'').trim().slice(0,60);if(tags.includes('อื่น ๆ')&&other)tags.push(other);if(!tags.length){await ctx.env.FILES.delete(coverKey);return json({error:'กรุณาเลือกแพลตฟอร์มหรือหัวข้อที่สอนอย่างน้อย 1 รายการ'},400)}
  let slug=slugify(title),n=1;while(await ctx.env.DB.prepare('SELECT id FROM products WHERE slug=?').bind(slug).first())slug=`${slugify(title)}-${++n}`;const coverUrl='/api/media/'+coverKey;
  const product=await ctx.env.DB.prepare(`INSERT INTO products(slug,title,short_description,description,price,cover_url,preview_urls,category,file_type,pages,status,source,product_kind) VALUES(?,?,?,?,?,?,?,'online-course','คอร์สออนไลน์',?,'draft','course-seller','course')`).bind(slug,title,String(form.get('short_description')||''),description,price,coverUrl,JSON.stringify([coverUrl]),episodes).run();
  const now=new Date().toISOString(),editExpires=expiry(now,license.license_edit_days);let courseId;
  try{const course=await ctx.env.DB.prepare(`INSERT INTO courses(product_id,subtitle,teacher_name,active,course_type,license_edit_days,owner_user_id,license_entitlement_id,edit_expires_at,contact_info,payment_bank_name,payment_account_name,payment_account_number,payment_qr_url,platform_tags,learner_level,expected_episodes,review_status,submitted_at,course_origin) VALUES(?,?,?,0,'online_course',?,?,?,?,?,?,?,?,?,?,?,?,'pending',CURRENT_TIMESTAMP,'seller_rights')`).bind(product.meta.last_row_id,String(form.get('short_description')||''),teacher,license.license_edit_days,auth.user.id,bindingId,editExpires,String(form.get('contact_info')||''),owner.seller_bank_name,owner.seller_account_name,owner.seller_account_number,`/api/course-seller/payment-qr/${bindingId}`,JSON.stringify(tags),['beginner','intermediate','advanced','all'].includes(String(form.get('learner_level')))?String(form.get('learner_level')):'beginner',episodes).run();courseId=course.meta.last_row_id}catch(error){await ctx.env.DB.prepare('DELETE FROM products WHERE id=?').bind(product.meta.last_row_id).run();await ctx.env.FILES.delete(coverKey);return json({error:'สร้างตะกร้าคอร์สไม่สำเร็จ เครดิตยังไม่ถูกหัก'},409)}
  if(isCredit){const used=await ctx.env.DB.prepare('UPDATE course_right_credits SET active=0,used_at=CURRENT_TIMESTAMP,used_course_id=? WHERE id=? AND user_id=? AND active=1 AND used_course_id IS NULL').bind(courseId,licenseId,auth.user.id).run();if(!used.meta.changes){await ctx.env.DB.prepare('DELETE FROM products WHERE id=?').bind(product.meta.last_row_id).run();await ctx.env.FILES.delete(coverKey);return json({error:'เครดิตถูกใช้ไปแล้ว ตะกร้าไม่ได้ถูกสร้าง'},409)}}
  return json({ok:true,id:courseId,slug,review_status:'pending',message:'สร้างตะกร้าร่างแล้ว กรุณารอ Boss ตรวจสอบ'},201);
}
