import{json}from'../../../_lib.js';import{requireVxUser}from'../../../_vx_access.js';
const headers={'cache-control':'private, no-store'},date=value=>/^\d{4}-\d{2}-\d{2}$/.test(String(value||''))?String(value):'',clean=(value,max=40)=>String(value||'').trim().slice(0,max);
async function ready(env){await env.DB.batch([env.DB.prepare(`CREATE TABLE IF NOT EXISTS tiktok_commission_cards(id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,date_from TEXT NOT NULL,date_to TEXT NOT NULL,currency TEXT NOT NULL,basis TEXT NOT NULL,data_fingerprint TEXT NOT NULL,page_number INTEGER NOT NULL,page_count INTEGER NOT NULL,object_key TEXT NOT NULL UNIQUE,file_size INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,UNIQUE(user_id,date_from,date_to,currency,basis,data_fingerprint,page_number))`),env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_tiktok_commission_cards_range ON tiktok_commission_cards(user_id,date_from,date_to,currency,basis,created_at DESC)')])}
const items=rows=>(rows||[]).map(row=>({id:row.id,page_number:Number(row.page_number),page_count:Number(row.page_count),url:`/api/admin/tiktok-commission-cards/${encodeURIComponent(row.id)}`}));
async function cached(env,userId,x){const rows=(await env.DB.prepare('SELECT id,page_number,page_count FROM tiktok_commission_cards WHERE user_id=? AND date_from=? AND date_to=? AND currency=? AND basis=? AND data_fingerprint=? ORDER BY page_number').bind(userId,x.from,x.to,x.currency,x.basis,x.fingerprint).all()).results||[];return rows.length&&rows.length===Number(rows[0].page_count)?items(rows):[]}
function fields(source){return{from:date(source.get('from')),to:date(source.get('to')),currency:clean(source.get('currency'),8).toUpperCase(),basis:clean(source.get('basis'),40),fingerprint:clean(source.get('fingerprint'),64).toLowerCase()}}
function valid(x){return x.from&&x.to&&x.from<=x.to&&/^[A-Z]{3,8}$/.test(x.currency)&&/^[a-z_]{1,40}$/.test(x.basis)&&/^[a-f0-9]{64}$/.test(x.fingerprint)}
export async function onRequestGet(ctx){const auth=await requireVxUser(ctx);if(auth.error)return auth.error;await ready(ctx.env);const x=fields(new URL(ctx.request.url).searchParams);if(!valid(x))return json({error:'คีย์ช่วงวันที่ของรูปไม่ถูกต้อง'},400,headers);return json({ok:true,cache_key:`${x.from}:${x.to}`,items:await cached(ctx.env,auth.user.id,x)},200,headers)}
export async function onRequestPost(ctx){const auth=await requireVxUser(ctx);if(auth.error)return auth.error;if(!ctx.env.FILES)return json({error:'ยังไม่ได้เชื่อมคลังรูป'},503,headers);await ready(ctx.env);const form=await ctx.request.formData(),x=fields(form);if(!valid(x))return json({error:'คีย์ช่วงวันที่ของรูปไม่ถูกต้อง'},400,headers);const existing=await cached(ctx.env,auth.user.id,x);if(existing.length)return json({ok:true,cached:true,items:existing},200,headers);const files=form.getAll('image');if(!files.length||files.length>50||files.some(file=>!(file instanceof File)||file.type!=='image/png'||!file.size||file.size>5*1024*1024))return json({error:'รูปต้องเป็น PNG ไม่เกิน 5 MB และไม่เกิน 50 รูปต่อชุด'},400,headers);const uploaded=[];try{for(let index=0;index<files.length;index++){const file=files[index],id=crypto.randomUUID(),key=`tiktok-commission-cards/${auth.user.id}/${x.from}_${x.to}/${x.fingerprint}/${id}.png`;await ctx.env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:'image/png'}});uploaded.push({id,key,page:index+1});await ctx.env.DB.prepare('INSERT INTO tiktok_commission_cards(id,user_id,date_from,date_to,currency,basis,data_fingerprint,page_number,page_count,object_key,file_size) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(id,auth.user.id,x.from,x.to,x.currency,x.basis,x.fingerprint,index+1,files.length,key,file.size).run()}}catch(error){for(const item of uploaded){await ctx.env.DB.prepare('DELETE FROM tiktok_commission_cards WHERE id=?').bind(item.id).run().catch(()=>{});await ctx.env.FILES.delete(item.key).catch(()=>{})}return json({error:'บันทึกชุดรูปไม่สำเร็จ'},500,headers)}const stale=(await ctx.env.DB.prepare('SELECT object_key FROM tiktok_commission_cards WHERE user_id=? AND date_from=? AND date_to=? AND currency=? AND basis=? AND data_fingerprint<>?').bind(auth.user.id,x.from,x.to,x.currency,x.basis,x.fingerprint).all()).results||[];if(stale.length){await ctx.env.DB.prepare('DELETE FROM tiktok_commission_cards WHERE user_id=? AND date_from=? AND date_to=? AND currency=? AND basis=? AND data_fingerprint<>?').bind(auth.user.id,x.from,x.to,x.currency,x.basis,x.fingerprint).run();for(const item of stale)await ctx.env.FILES.delete(item.object_key).catch(()=>{})}return json({ok:true,cached:false,items:items(uploaded.map(item=>({id:item.id,page_number:item.page,page_count:files.length})))},201,headers)}
