import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const read=path=>readFile(path,'utf8');
assert.equal((await read('VERSION.txt')).trim(),'v0.14.157');
assert.match(await read('public/index.html'),/WEB v0\.14\.157/);
assert.match(await read('public/admin.html'),/ADMIN v0\.14\.157/);
const api=await read('functions/api/admin/course-integrity.js');
assert.match(api,/WITH paid AS/);assert.match(api,/rights AS/);
assert.match(api,/WITH bought AS/);assert.match(api,/logged AS/);
assert.doesNotMatch(api,/\(SELECT COUNT\(\*\) FROM orders o WHERE o\.seller_course_id=c\.id/);
assert.match(api,/LIMIT 200/);assert.match(api,/requireAdmin/);
assert.doesNotMatch(api,/onRequestPost|onRequestPut|onRequestDelete/);
assert.match(api,/event_case_ready:healthy&&paid>0/);
console.log('v0.14.157 fast read-only Integrity queries: PASS');
