import fs from 'node:fs';
const read=(path)=>fs.readFileSync(path,'utf8'),assert=(ok,message)=>{if(!ok)throw new Error(message)};
assert(read('VERSION.txt').trim()==='v0.14.133','VERSION must be v0.14.133');
const html=read('public/course-basket-edit.html'),css=read('public/course-seller.css'),js=read('public/course-basket-edit.js');
for(const hook of ['course-basket-form','course-basket-title','course-basket-teacher','course-basket-summary'])assert(html.includes(hook),`missing ${hook}`);
assert(css.includes('grid-row: 1 / span 3')&&css.includes('.course-basket-form .course-basket-title'),'desktop course form layout not fixed');
assert(css.includes('grid-row: auto'),'mobile course form layout not reset');
assert(html.includes('เผยแพร่และรอตรวจสอบ')&&js.includes('เผยแพร่แล้ว · รอตรวจสอบ'),'publish wording not updated');
assert(html.includes('name="title" required'),'course title field changed or removed');
assert(css.includes('.seller-lesson-editor[hidden]')&&css.includes('display: none !important'),'hidden EP editor can be overridden by grid CSS');
assert(js.includes('function openEpisodeEditor')&&js.includes('episodeForm.removeAttribute("hidden")')&&js.includes('episodeForm.elements.title.focus'),'edit EP button does not open and focus populated form');
console.log('v0.14.133 course basket form layout checks passed');
