import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=file=>fs.readFileSync(file,'utf8');
const html=read('public/admin.html');
const css=read('public/admin-navigation.css');
const ui=read('public/admin.js');
assert.match(html,/class="admin-menu-board"/);
assert.match(html,/class="admin-all-grid"/);
assert.doesNotMatch(html,/<details class="admin-more-nav">/);
for(const tab of ['overview','sales','promotion','categories','users','settings','elon','health','trash'])assert.match(html,new RegExp(`data-admin-tab="${tab}"`));
assert.match(html,/class="admin-more-link" href="\/course-integrity.html"/);
assert.match(html,/danger-link boss-only-danger/);
assert.match(css,/grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);
assert.match(css,/min-height:104px/);
assert.match(css,/admin-all-grid>button\.active/);
assert.match(css,/@media\(max-width:520px\).*admin-all-grid/s);
assert.match(ui,/querySelectorAll\("\[data-admin-tab\]"\)/);
console.log('v0.14.88 large always-visible admin menu passed');
