import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read = path => readFile(path, 'utf8');
assert.equal((await read('VERSION.txt')).trim(), 'v0.14.156');
assert.match(await read('public/index.html'), /WEB v0\.14\.156/);
assert.match(await read('public/admin.html'), /ADMIN v0\.14\.156/);
const api = await read('functions/api/admin/course-integrity.js');
const html = await read('public/course-integrity.html');
const ui = await read('public/course-integrity.js');
assert.match(api, /requireAdmin/);
assert.doesNotMatch(api, /onRequestPost|onRequestPut|onRequestDelete/);
assert.match(api, /owner_username/);
assert.match(api, /vision5_test_account/);
assert.match(api, /paid>0/);
assert.match(api, /review_status===['"]approved['"]/);
assert.match(api, /product_status===['"]published['"]/);
assert.match(api, /event_case_ready/);
assert.match(api, /sample_account:String\(x\.owner_username/);
assert.match(html, /id="eventCaseSummary"[^>]*aria-live="polite"/);
assert.match(html, /course-integrity\.js\?v=014156/);
assert.match(ui, /0=0=0 ยังไม่นับว่าผ่าน/);
assert.match(ui, /Event Case · user1/);
assert.match(ui, /มีออเดอร์ paid \+ หลักฐานสลิป \+ สิทธิ์เรียน/);
console.log('v0.14.156 read-only production Event Case gate: PASS');
