import {json,requireAdmin} from '../../../_lib.js';
import {ensureDatabase} from '../../../_schema.js';
async function lessonValidation(env,courseId,expected){
  const rows=await env.DB.prepare(`SELECT l.id,l.title,l.sort_order,
    CASE WHEN l.video_key IS NOT NULL OR l.pdf_key IS NOT NULL OR EXISTS(SELECT 1 FROM course_lesson_files f WHERE f.lesson_id=l.id) THEN 1 ELSE 0 END has_media
    FROM course_lessons l WHERE l.course_id=? ORDER BY l.sort_order,l.id`).bind(courseId).all();
  const lessons=(rows.results||[]).filter(lesson=>String(lesson.title||'').trim()&&Number(lesson.has_media)),required=1,missing=lessons.length?[]:[1];
  return {complete:lessons.length>=required,actual:lessons.length,required,missing};
}
async function courseTransition(env,{courseId,productId,from,to,courseSet,courseBindings=[],productStatus}){
  const fromList=Array.isArray(from)?from:[from],marks=fromList.map(()=>'?').join(',');
  const results=await env.DB.batch([
    env.DB.prepare(`UPDATE courses SET ${courseSet},updated_at=CURRENT_TIMESTAMP WHERE id=? AND product_id=? AND course_origin='seller_rights' AND course_plan='partner' AND review_status IN (${marks})`).bind(...courseBindings,courseId,productId,...fromList),
    env.DB.prepare(`UPDATE products SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND EXISTS(SELECT 1 FROM courses c WHERE c.id=? AND c.product_id=products.id AND c.course_origin='seller_rights' AND c.course_plan='partner' AND c.review_status=?)`).bind(productStatus,productId,courseId,to)
  ]);
  return Number(results?.[0]?.meta?.changes||0)===1&&Number(results?.[1]?.meta?.changes||0)===1;
}
export async function onRequestPost(ctx){
  await ensureDatabase(ctx.env);const auth=await requireAdmin(ctx);if(auth.error)return auth.error;if(auth.user.role!=='boss')return json({error:'เฉพาะ Boss อนุมัติได้'},403);
  const body=await ctx.request.json().catch(()=>({})),action=String(body.action||''),id=Number(ctx.params.id);
  if(['mark_test_account','unmark_test_account','mark_test_user','unmark_test_user'].includes(action)){const value=action.startsWith('mark_')?1:0;const changed=await ctx.env.DB.prepare("UPDATE users SET is_test_user=?,vision5_test_account=?,name=CASE WHEN ?=1 THEN 'รัฐสิทธิ ดำรงรถการ' ELSE name END WHERE id=?").bind(value,value,value,id).run();return changed.meta.changes?json({ok:true,message:value?'ตั้งเป็นยูสเทสแล้ว · ใช้ชื่อกลางและสลิปต้องให้ Boss อนุมัติ':'ยกเลิกสถานะยูสเทสแล้ว'}):json({error:'ไม่พบยูสเซอร์'},404)}
  if(action==='approve_profile'){const changed=await ctx.env.DB.prepare("UPDATE users SET seller_payment_status='approved',seller_payment_verified_at=CURRENT_TIMESTAMP,seller_payment_verified_by=? WHERE id=? AND seller_payment_status='pending'").bind(auth.user.id,id).run();return changed.meta.changes?json({ok:true}):json({error:'ไม่พบบัญชีที่รอตรวจ'},404)}
  if(action==='reject_profile'){const changed=await ctx.env.DB.prepare("UPDATE users SET seller_payment_status='rejected',seller_payment_verified_at=CURRENT_TIMESTAMP,seller_payment_verified_by=? WHERE id=? AND seller_payment_status='pending'").bind(auth.user.id,id).run();return changed.meta.changes?json({ok:true}):json({error:'ไม่พบบัญชีที่รอตรวจ'},404)}
  if(action==='reset_profile'){const user=await ctx.env.DB.prepare('SELECT seller_payment_qr_url FROM users WHERE id=?').bind(id).first();if(!user)return json({error:'ไม่พบยูสเซอร์'},404);await ctx.env.DB.prepare("UPDATE users SET seller_bank_name='',seller_account_name='',seller_account_number='',seller_payment_qr_url='',seller_payment_status='unset',seller_payment_submitted_at=NULL,seller_payment_verified_at=NULL,seller_payment_verified_by=NULL WHERE id=?").bind(id).run();if(user.seller_payment_qr_url)await ctx.env.FILES.delete(user.seller_payment_qr_url);return json({ok:true})}
  const course=await ctx.env.DB.prepare(`SELECT c.id,c.product_id,c.review_status,c.owner_user_id,c.license_entitlement_id,c.basket_binding_locked,c.submitted_at,c.expected_episodes,c.course_plan FROM courses c WHERE c.id=? AND c.course_type='online_course' AND c.course_origin='seller_rights' AND c.course_plan='partner'`).bind(id).first();if(!course)return json({error:'ไม่พบคอร์สพาร์ตเนอร์ในคิวตรวจ'},404);
  if(action==='approve_course'){if(!course.submitted_at||course.review_status!=='pending')return json({error:'เจ้าของคอร์สพาร์ตเนอร์ยังไม่ได้ส่งตรวจ'},409);const validation=await lessonValidation(ctx.env,id,course.expected_episodes);if(!validation.complete){const detail=validation.missing.length?` EP ที่ยังไม่พร้อม: ${validation.missing.join(', ')}`:'';return json({error:`อนุมัติไม่ได้ บทเรียนยังไม่ครบ (${validation.actual}/${validation.required} EP)${detail}`,lesson_validation:validation},409)}const changed=await courseTransition(ctx.env,{courseId:id,productId:course.product_id,from:'pending',to:'approved',courseSet:"review_status='approved',review_note='',approved_at=CURRENT_TIMESTAMP,approved_by=?,active=1",courseBindings:[auth.user.id],productStatus:'published'});if(!changed)return json({error:'สถานะคอร์สถูกเปลี่ยนไปแล้ว กรุณาโหลดรายการใหม่'},409);return json({ok:true,message:'อนุมัติแล้ว คอร์สพาร์ตเนอร์ถูกเผยแพร่ในแคตตาล็อกคอร์ส'})}
  if(action==='request_changes'){const changed=await courseTransition(ctx.env,{courseId:id,productId:course.product_id,from:'pending',to:'changes_requested',courseSet:"review_status='changes_requested',review_note=?,active=0",courseBindings:[String(body.note||'กรุณาแก้ไขข้อมูลคอร์สพาร์ตเนอร์').trim().slice(0,500)],productStatus:'draft'});if(!changed)return json({error:'คอร์สไม่ได้อยู่ในสถานะรอตรวจ หรือมีผู้ตรวจดำเนินการแล้ว'},409);return json({ok:true})}
  if(action==='reject_course'){const note=String(body.note||'คอร์สพาร์ตเนอร์ไม่ผ่านการตรวจ').trim().slice(0,500),changed=await courseTransition(ctx.env,{courseId:id,productId:course.product_id,from:'pending',to:'rejected',courseSet:"review_status='rejected',review_note=?,active=0,submitted_at=NULL",courseBindings:[note],productStatus:'draft'});if(!changed)return json({error:'คอร์สไม่ได้อยู่ในสถานะรอตรวจ หรือมีผู้ตรวจดำเนินการแล้ว'},409);return json({ok:true,message:'ไม่อนุมัติคอร์สพาร์ตเนอร์และส่งกลับเป็นร่างแล้ว'})}
  if(action==='suspend_course'){const reason=String(body.note||'ระงับเนื่องจากฝ่าฝืนกฎห้ามเปลี่ยนเนื้อหาหลังมียอดขาย').trim().slice(0,500),changed=await courseTransition(ctx.env,{courseId:id,productId:course.product_id,from:'approved',to:'suspended',courseSet:"review_status='suspended',review_note=?,active=0",courseBindings:[reason],productStatus:'draft'});if(!changed)return json({error:'ระงับได้เฉพาะคอร์สที่กำลังเผยแพร่ หรือสถานะถูกเปลี่ยนไปแล้ว'},409);return json({ok:true,message:'ระงับการขายและการเข้าถึงของผู้เรียนแล้ว'})}
  if(action==='restore_course'){const changed=await courseTransition(ctx.env,{courseId:id,productId:course.product_id,from:'suspended',to:'approved',courseSet:"review_status='approved',review_note='',active=1",productStatus:'published'});if(!changed)return json({error:'คอร์สไม่ได้ถูกระงับ หรือสถานะถูกเปลี่ยนไปแล้ว'},409);return json({ok:true,message:'คืนสถานะคอร์สพาร์ตเนอร์แล้ว'})}
  return json({error:'คำสั่งไม่ถูกต้อง'},400);
}
