import {json,requireAdmin} from '../../../_lib.js';
import {ensureDatabase} from '../../../_schema.js';
async function lessonValidation(env,courseId,expected){
  const rows=await env.DB.prepare(`SELECT l.id,l.title,l.sort_order,
    CASE WHEN l.video_key IS NOT NULL OR l.pdf_key IS NOT NULL OR EXISTS(SELECT 1 FROM course_lesson_files f WHERE f.lesson_id=l.id) THEN 1 ELSE 0 END has_media
    FROM course_lessons l WHERE l.course_id=? ORDER BY l.sort_order,l.id`).bind(courseId).all();
  const lessons=rows.results||[],required=Math.max(1,Number(expected)||1),missing=[];
  for(let index=0;index<lessons.length;index++)if(!String(lessons[index].title||'').trim()||!Number(lessons[index].has_media))missing.push(index+1);
  if(lessons.length<required)for(let index=lessons.length;index<required;index++)missing.push(index+1);
  return {complete:lessons.length===required&&!missing.length,actual:lessons.length,required,missing:[...new Set(missing)]};
}
export async function onRequestPost(ctx){
  await ensureDatabase(ctx.env);const auth=await requireAdmin(ctx);if(auth.error)return auth.error;if(auth.user.role!=='boss')return json({error:'เฉพาะ Boss อนุมัติได้'},403);
  const body=await ctx.request.json().catch(()=>({})),action=String(body.action||''),id=Number(ctx.params.id);
  if(action==='approve_profile'){const changed=await ctx.env.DB.prepare("UPDATE users SET seller_payment_status='approved',seller_payment_verified_at=CURRENT_TIMESTAMP,seller_payment_verified_by=? WHERE id=? AND seller_payment_status='pending'").bind(auth.user.id,id).run();return changed.meta.changes?json({ok:true}):json({error:'ไม่พบบัญชีที่รอตรวจ'},404)}
  if(action==='reject_profile'){const changed=await ctx.env.DB.prepare("UPDATE users SET seller_payment_status='rejected',seller_payment_verified_at=CURRENT_TIMESTAMP,seller_payment_verified_by=? WHERE id=? AND seller_payment_status='pending'").bind(auth.user.id,id).run();return changed.meta.changes?json({ok:true}):json({error:'ไม่พบบัญชีที่รอตรวจ'},404)}
  if(action==='reset_profile'){const user=await ctx.env.DB.prepare('SELECT seller_payment_qr_url FROM users WHERE id=?').bind(id).first();if(!user)return json({error:'ไม่พบยูสเซอร์'},404);await ctx.env.DB.prepare("UPDATE users SET seller_bank_name='',seller_account_name='',seller_account_number='',seller_payment_qr_url='',seller_payment_status='unset',seller_payment_submitted_at=NULL,seller_payment_verified_at=NULL,seller_payment_verified_by=NULL WHERE id=?").bind(id).run();if(user.seller_payment_qr_url)await ctx.env.FILES.delete(user.seller_payment_qr_url);return json({ok:true})}
  const course=await ctx.env.DB.prepare(`SELECT c.id,c.product_id,c.review_status,c.owner_user_id,c.license_entitlement_id,c.basket_binding_locked,c.submitted_at,c.expected_episodes,u.seller_payment_status FROM courses c JOIN users u ON u.id=c.owner_user_id WHERE c.id=? AND c.course_type='online_course'`).bind(id).first();if(!course)return json({error:'ไม่พบตะกร้าคอร์ส'},404);
  if(action==='approve_course'){if(course.license_entitlement_id===null||!course.basket_binding_locked||!course.submitted_at||course.review_status!=='pending')return json({error:'เจ้าของคอร์สยังไม่ได้กดเผยแพร่และผูกตะกร้า VisionD ไม่มีสิทธิ์นำคอร์สขึ้นขายเอง'},409);if(course.seller_payment_status!=='approved')return json({error:'ต้องอนุมัติบัญชีรับเงินของเจ้าของคอร์สก่อน'},409);const validation=await lessonValidation(ctx.env,id,course.expected_episodes);if(!validation.complete){const detail=validation.missing.length?` EP ที่ยังไม่พร้อม: ${validation.missing.join(', ')}`:'';return json({error:`อนุมัติไม่ได้ บทเรียนยังไม่ครบ (${validation.actual}/${validation.required} EP)${detail}`,lesson_validation:validation},409)}await ctx.env.DB.batch([ctx.env.DB.prepare("UPDATE courses SET review_status='approved',review_note='',approved_at=CURRENT_TIMESTAMP,approved_by=?,active=1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND review_status='pending'").bind(auth.user.id,id),ctx.env.DB.prepare("UPDATE products SET status='published',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(course.product_id)]);return json({ok:true,message:'อนุมัติตามคำขอเผยแพร่ของเจ้าของคอร์สแล้ว'})}
  if(action==='request_changes'){await ctx.env.DB.batch([ctx.env.DB.prepare("UPDATE courses SET review_status='changes_requested',review_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(String(body.note||'กรุณาแก้ไขข้อมูลตะกร้าคอร์ส'),id),ctx.env.DB.prepare("UPDATE products SET status='draft',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(course.product_id)]);return json({ok:true})}
  if(action==='suspend_course'){const reason=String(body.note||'ระงับเนื่องจากฝ่าฝืนกฎห้ามเปลี่ยนเนื้อหาหลังมียอดขาย').trim().slice(0,500);await ctx.env.DB.batch([ctx.env.DB.prepare("UPDATE courses SET review_status='suspended',review_note=?,active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(reason,id),ctx.env.DB.prepare("UPDATE products SET status='draft',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(course.product_id)]);return json({ok:true,message:'ระงับตะกร้าจากการขายใหม่ทันทีแล้ว'})}
  if(action==='restore_course'){await ctx.env.DB.batch([ctx.env.DB.prepare("UPDATE courses SET review_status='approved',review_note='',active=1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND review_status='suspended'").bind(id),ctx.env.DB.prepare("UPDATE products SET status='published',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(course.product_id)]);return json({ok:true,message:'คืนสถานะตะกร้าแล้ว'})}
  if(action==='delete_course'){await ctx.env.DB.prepare("UPDATE products SET deleted_at=CURRENT_TIMESTAMP,deleted_prev_status=status,status='draft',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(course.product_id).run();return json({ok:true,message:'ลบตะกร้าคอร์สแล้ว เครดิตไม่ถูกคืน'})}
  return json({error:'คำสั่งไม่ถูกต้อง'},400);
}
