import {json,requireAdmin} from '../../../_lib.js';
const headers={'cache-control':'private, no-store'},clean=(value,max)=>String(value??'').trim().slice(0,max);
async function ready(ctx){const auth=await requireAdmin(ctx);if(auth.error)return auth;await ctx.env.DB.prepare("CREATE TABLE IF NOT EXISTS admin_work_notes(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,content TEXT NOT NULL,created_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();await ctx.env.DB.prepare("CREATE TABLE IF NOT EXISTS admin_work_note_attachments(id INTEGER PRIMARY KEY AUTOINCREMENT,note_id INTEGER NOT NULL,object_key TEXT NOT NULL UNIQUE,file_name TEXT NOT NULL,mime_type TEXT NOT NULL,file_size INTEGER NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(note_id) REFERENCES admin_work_notes(id) ON DELETE CASCADE)").run();return auth}
const cursor=value=>{const raw=String(value||''),split=raw.lastIndexOf('|');return split>0?{at:raw.slice(0,split),id:Number(raw.slice(split+1))}:null};
async function list(ctx){const params=new URL(ctx.request.url).searchParams,limit=Math.min(24,Math.max(1,Number(params.get('limit'))||24)),after=cursor(params.get('cursor')),where=[],bindings=[];if(after){where.push('(updated_at<? OR (updated_at=? AND id<?))');bindings.push(after.at,after.at,after.id)}const rows=(await ctx.env.DB.prepare(`SELECT id,title,content,created_at,updated_at FROM admin_work_notes${where.length?' WHERE '+where.join(' AND '):''} ORDER BY updated_at DESC,id DESC LIMIT ?`).bind(...bindings,limit+1).all()).results||[],items=rows.slice(0,limit),ids=items.map(item=>item.id),files=ids.length?(await ctx.env.DB.prepare(`SELECT id,note_id,file_name,mime_type,file_size FROM admin_work_note_attachments WHERE note_id IN (${ids.map(()=>'?').join(',')}) ORDER BY note_id,sort_order,id`).bind(...ids).all()).results||[]:[];for(const item of items)item.attachments=files.filter(file=>Number(file.note_id)===Number(item.id)).map(file=>({...file,url:`/api/admin/work-notes/${file.id}`}));const last=items.at(-1);return{items,pagination:{limit,has_more:rows.length>limit,next_cursor:rows.length>limit&&last?`${last.updated_at}|${last.id}`:null}}}
export async function onRequestGet(ctx){const auth=await ready(ctx);if(auth.error)return auth.error;return json(await list(ctx),200,headers)}
export async function onRequestPost(ctx){const auth=await ready(ctx);if(auth.error)return auth.error;const body=await ctx.request.json().catch(()=>({})),title=clean(body.title,160),content=clean(body.content,30000);if(!title||!content)return json({error:'กรุณากรอกหัวข้อและเนื้อหาโน้ต'},400,headers);const result=await ctx.env.DB.prepare('INSERT INTO admin_work_notes(title,content,created_by) VALUES(?,?,?) RETURNING id').bind(title,content,auth.user.id).first();return json({ok:true,id:result.id,...await list(ctx)},201,headers)}
export async function onRequestPatch(ctx){const auth=await ready(ctx);if(auth.error)return auth.error;const body=await ctx.request.json().catch(()=>({})),id=Number(body.id),title=clean(body.title,160),content=clean(body.content,30000);if(!Number.isInteger(id)||id<1||!title||!content)return json({error:'ข้อมูลโน้ตไม่ถูกต้อง'},400,headers);const result=await ctx.env.DB.prepare('UPDATE admin_work_notes SET title=?,content=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(title,content,id).run();if(!Number(result.meta?.changes))return json({error:'ไม่พบโน้ตนี้'},404,headers);return json({ok:true,...await list(ctx)},200,headers)}
export async function onRequestDelete(ctx){const auth=await ready(ctx);if(auth.error)return auth.error;const body=await ctx.request.json().catch(()=>({})),id=Number(body.id);if(!Number.isInteger(id)||id<1)return json({error:'รหัสโน้ตไม่ถูกต้อง'},400,headers);const files=(await ctx.env.DB.prepare('SELECT object_key FROM admin_work_note_attachments WHERE note_id=?').bind(id).all()).results||[],result=await ctx.env.DB.prepare('DELETE FROM admin_work_notes WHERE id=?').bind(id).run();if(!Number(result.meta?.changes))return json({error:'ไม่พบโน้ตนี้'},404,headers);for(const file of files)await ctx.env.FILES?.delete(file.object_key).catch(()=>{});return json({ok:true,...await list(ctx)},200,headers)}
