import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import vm from'node:vm';import{fileURLToPath}from'node:url';import{makeHandoff,clone}from'./fixture.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),sandbox={URL,structuredClone,TextEncoder,TextDecoder};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(root,'src/core.js'),'utf8'),sandbox);const core=sandbox.VisionDShopeeCore,realm=value=>vm.runInContext(`JSON.parse(${JSON.stringify(JSON.stringify(value))})`,sandbox);
const valid=makeHandoff(3);let result=core.validateHandoff(realm(valid));assert.equal(result.ok,true,JSON.stringify(result.errors));assert.deepEqual({...core.page2FieldValues(realm(valid))},{brand:'VisionD',description:'บรรทัดหนึ่ง\r\nบรรทัดสอง \\ ทดสอบ',price:'1850',stock:'3',weight:'0.5',width:'12',length:'20',height:'8'});
const extreme=makeHandoff(1);extreme.product.page_2.sales.price_minor=Number.MAX_SAFE_INTEGER-1;extreme.product.page_2.shipping.weight_g=Number.MAX_SAFE_INTEGER;extreme.product.page_2.shipping.width_mm=Number.MAX_SAFE_INTEGER;const exact=core.page2FieldValues(realm(extreme));assert.equal(exact.price,'90071992547409.9');assert.equal(exact.weight,'9007199254740.991');assert.equal(exact.width,'900719925474099.1');
const collisionA=makeHandoff(1),collisionB=makeHandoff(1);collisionA.product.page_2.description='ชน 1bweath1p8xga8iyd8xx';collisionB.product.page_2.description='ชน jp90e21dfacmh5z1ehb';assert.notEqual(core.handoffFingerprint(realm(collisionA)),core.handoffFingerprint(realm(collisionB)),'known FNV collision must remain distinct');const reorder=value=>Array.isArray(value)?value.map(reorder):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).reverse().map(([key,entry])=>[key,reorder(entry)])):value;assert.equal(core.handoffFingerprint(realm(valid)),core.handoffFingerprint(realm(reorder(valid))),'object key order must not change identity');
const invalid=[];const add=(code,mutate)=>{const value=clone(valid);mutate(value);invalid.push([code,value])};
add('wrong_schema',v=>v.schema='other');add('wrong_version',v=>v.version=2);add('incomplete',v=>{v.validation.complete=false;v.validation.missing=['page_1.gtin']});add('title_too_long',v=>v.product.page_1.name='ก'.repeat(121));add('private_field',v=>v.product.page_2.cost_cents=1);add('unexpected_shape',v=>v.product.extra=true);add('cover_order',v=>{v.product.page_1.images[0].cover=false;v.product.page_1.images[1].cover=true});add('duplicate_image',v=>v.product.page_1.images[1].url=v.product.page_1.images[0].url);add('duplicate_image_identity',v=>v.product.page_1.images[1].url='https://visiondonline.com/api/toys-center/gallery/7/0?v=999');add('invalid_image_route',v=>v.product.page_1.images[0].url='https://visiondonline.com/api/toys-center/gallery/007/0?v=100');add('invalid_image_route',v=>v.product.page_1.images[0].url='https://visiondonline.com/api/toys-center/gallery/7/00?v=100');add('invalid_image_route',v=>v.product.page_1.images[0].url='https://visiondonline.com/api/toys-center/gallery/8/0?v=100');add('invalid_image_route',v=>v.product.page_1.images[0].url+='&x=1');add('untrusted_image_origin',v=>v.product.page_1.images[0].url='https://evil.test/api/toys-center/gallery/7/0?v=100');add('unsupported_currency',v=>v.product.page_2.sales.currency='USD');add('wrong_category',v=>v.product.page_2.category_path[2]='เดา');add('invalid_value',v=>v.product.page_2.shipping.width_mm=1.5);
for(const[code,value]of invalid){result=core.validateHandoff(realm(value));assert.equal(result.ok,false,code);assert.ok(result.errors.some(error=>error.code===code||code==='unexpected_shape'&&error.code==='private_field'),`${code}: ${JSON.stringify(result.errors)}`)}
const ten=makeHandoff(10);assert.equal(core.validateHandoff(realm(ten)).ok,true,'v1 remains valid at max10; live page capacity is separate');
const proto=vm.runInContext(`JSON.parse(${JSON.stringify(JSON.stringify(valid).replace('"name":','"__proto__":{"polluted":true},"name":'))})`,sandbox);result=core.validateHandoff(proto);assert.equal(result.ok,false);assert.ok(result.errors.some(error=>error.code==='prototype_field'));
let deep={};for(let index=0;index<40;index++)deep={nested:deep};result=core.validateHandoff(realm(deep));assert.equal(result.ok,false);assert.ok(result.errors.some(error=>error.code==='structure_limit'||error.code==='unexpected_shape'));
console.log('PASS core strict v1 allowlist, Thai/Unicode, units, privacy, URL binding, title120 and max10');
