import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import vm from'node:vm';import{fileURLToPath}from'node:url';import{makeThaiMartHandoff,clone}from'./fixture.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),sandbox={URL,structuredClone};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(root,'src/thaimart-core.js'),'utf8'),sandbox);const core=sandbox.VisionDThaiMartCore,realm=value=>vm.runInContext(`JSON.parse(${JSON.stringify(JSON.stringify(value))})`,sandbox),valid=makeThaiMartHandoff(3);
let result=core.validateHandoff(realm(valid));assert.equal(result.ok,true,JSON.stringify(result.errors));assert.deepEqual({...core.fieldValues(realm(valid))},{name:valid.product.name,description:valid.product.description,sku:'TOY-007',price:'1850',stock:'0',weight:'500',width:'12',length:'20',height:'8'});
assert.equal(core.validateHandoff(realm({...clone(valid),product:{...clone(valid).product,sku:''}})).ok,true,'optional SKU is exact empty string');assert.equal(core.validateHandoff(realm({...clone(valid),product:{...clone(valid).product,shipping:{weight_g:500,dimensions_cm:null}}})).ok,true,'dimensions are explicitly null when absent');assert.equal(core.validateHandoff(realm({...clone(valid),product:{...clone(valid).product,sales:{currency:'THB',price_thb:1,stock:0}}})).ok,true,'zero stock is valid');
const invalid=[],add=(code,mutate)=>{const value=clone(valid);mutate(value);invalid.push([code,value])};add('wrong_schema',v=>v.schema='visiond.shopee-product-handoff');add('wrong_platform',v=>v.platform='shopee');add('unexpected_shape',v=>v.extra=true);add('unexpected_shape',v=>v.product.extra=true);add('unexpected_shape',v=>v.product.sales.extra=true);add('unexpected_shape',v=>v.product.shipping.extra=true);add('unexpected_shape',v=>v.product.shipping.dimensions_cm.depth_cm=1);add('private_field',v=>v.product.cost_cents=1);add('invalid_name',v=>v.product.name='สั้น');add('invalid_description',v=>v.product.description='');add('invalid_sku',v=>v.product.sku=null);add('invalid_sku',v=>v.product.sku='x'.repeat(101));add('invalid_image_count',v=>v.product.images=makeThaiMartHandoff(10).product.images);add('cover_order',v=>{v.product.images[0].cover=false;v.product.images[1].cover=true});add('duplicate_image_identity',v=>v.product.images[1].url='https://visiondonline.com/api/toys-center/gallery/7/0?v=999');add('wrong_category',v=>v.product.category_path[2]='อื่นๆ');add('invalid_price',v=>v.product.sales.price_thb=1.5);add('invalid_stock',v=>v.product.sales.stock=-1);add('invalid_weight',v=>v.product.shipping.weight_g=50001);add('unexpected_shape',v=>v.product.shipping.dimensions_cm={width_cm:1,length_cm:1});add('invalid_dimensions',v=>v.product.shipping.dimensions_cm.width_cm=151);add('invalid_dimensions_sum',v=>v.product.shipping.dimensions_cm={width_cm:100,length_cm:100,height_cm:100});
for(const[code,value]of invalid){result=core.validateHandoff(realm(value));assert.equal(result.ok,false,code);assert.ok(result.errors.some(error=>error.code===code||code==='unexpected_shape'&&error.code==='private_field'),`${code}: ${JSON.stringify(result.errors)}`)}
const collisionA=clone(valid),collisionB=clone(valid);collisionA.product.description='ชน 1bweath1p8xga8iyd8xx';collisionB.product.description='ชน jp90e21dfacmh5z1ehb';assert.notEqual(core.handoffFingerprint(realm(collisionA)),core.handoffFingerprint(realm(collisionB)));const reorder=value=>Array.isArray(value)?value.map(reorder):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).reverse().map(([key,entry])=>[key,reorder(entry)])):value;assert.equal(core.handoffFingerprint(realm(valid)),core.handoffFingerprint(realm(reorder(valid))));
const proto=vm.runInContext(`JSON.parse(${JSON.stringify(JSON.stringify(valid).replace('"name":','"__proto__":{"polluted":true},"name":'))})`,sandbox);assert.ok(core.validateHandoff(proto).errors.some(error=>error.code==='prototype_field'));
console.log('PASS Thai Mart strict recursive v1 allowlist, zero stock, empty SKU, dimensions null/full, privacy and canonical identity');
