import {json,requireUser} from '../../_lib.js';
import {ensureVpageCreateSchema} from '../../_vpage-create-schema.js';
import {ensureDatabase} from '../../_schema.js';

const headers={'cache-control':'private, no-store'};
const mediaId=value=>{if(!value)return'';const match=String(value).match(/^https:\/\/smartlinkpage\.com\/media\/(vpm_[a-f0-9]{32})$/);return match?.[1]||null};
const text=(value,max)=>typeof value==='string'&&value.length<=max;
const fields={product_image_url:2048,background_image_url:2048,detail_text:4000,youtube_url:2048,text_size:16,text_style:16,text_font:16,text_color:7,background_color:7};
function validDraft(item){
  if(!item||typeof item!=='object'||Array.isArray(item)||!text(item.display_name,120)||!text(item.domain_id,120)||!text(item.slug,50)||![1,2].includes(item.active_set)||!Array.isArray(item.content_sets)||item.content_sets.length!==2)return false;
  const refs=[];
  for(const [index,set] of item.content_sets.entries()){
    if(!set||set.set_no!==index+1||Object.entries(fields).some(([key,max])=>!text(set[key],max)))return false;
    for(const value of [set.product_image_url,set.background_image_url]){const id=mediaId(value);if(id===null)return false;if(id)refs.push(id)}
    for(const kind of ['product_items','contact_items']){
      const rows=set[kind];if(!Array.isArray(rows)||rows.length>3)return false;
      for(const row of rows){if(!row||!text(row.destination_url,2048)||!text(row.image_url,2048)||kind==='contact_items'&&!['facebook','line'].includes(row.contact_type))return false;const id=mediaId(row.image_url);if(id===null)return false;if(id)refs.push(id)}
    }
  }
  return [...new Set(refs)];
}
async function readBounded(request){const reader=request.body?.getReader?.();if(!reader)throw new Error('empty');const chunks=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>65536){await reader.cancel().catch(()=>{});throw new Error('large')}chunks.push(value)}}finally{reader.releaseLock()}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes))}
const authFor=async ctx=>{await ensureDatabase(ctx.env);const auth=await requireUser(ctx,{includeCourseOwner:false});if(!auth.error)await ensureVpageCreateSchema(ctx.env);return auth};
export async function onRequestGet(ctx){const auth=await authFor(ctx);if(auth.error)return auth.error;const row=await ctx.env.DB.prepare('SELECT draft_json,revision,updated_at FROM vpage_create_drafts WHERE owner_id=?').bind(auth.user.id).first();return json({item:row?JSON.parse(row.draft_json):null,revision:Number(row?.revision||0),updated_at:row?.updated_at||null},200,headers)}
export async function onRequestPut(ctx){const auth=await authFor(ctx);if(auth.error)return auth.error;if(!/^application\/json(?:;|$)/i.test(ctx.request.headers.get('content-type')||''))return json({error:'ส่งข้อมูลร่างเป็น JSON'},415,headers);let body;try{body=await readBounded(ctx.request)}catch{return json({error:'ข้อมูลร่างไม่ถูกต้องหรือใหญ่เกิน 64 KiB'},413,headers)}const revision=body?.expected_revision,draft=body?.draft,refs=validDraft(draft);if(!Number.isSafeInteger(revision)||revision<0||refs===false)return json({error:'ข้อมูลร่างไม่ถูกต้อง'},400,headers);const raw=JSON.stringify(draft);if(raw.length>65536)return json({error:'ข้อมูลร่างใหญ่เกินกำหนด'},413,headers);
  if(refs.length){const marks=refs.map(()=>'?').join(','),rows=(await ctx.env.DB.prepare(`SELECT id FROM vpage_owner_assets WHERE owner_id=? AND state='ready' AND id IN (${marks}) LIMIT 16`).bind(auth.user.id,...refs).all()).results||[];if(rows.length!==refs.length)return json({error:'รูปในร่างไม่พร้อมใช้หรือไม่ใช่ของคุณ'},409,headers)}
  const guard=crypto.randomUUID();try{const statements=[ctx.env.DB.prepare("INSERT INTO vpage_draft_transition_guards(token) VALUES(CASE WHEN (?=0 AND NOT EXISTS(SELECT 1 FROM vpage_create_drafts WHERE owner_id=?)) OR EXISTS(SELECT 1 FROM vpage_create_drafts WHERE owner_id=? AND revision=?) THEN ? ELSE NULL END)").bind(revision,auth.user.id,auth.user.id,revision,guard),revision===0?ctx.env.DB.prepare('INSERT INTO vpage_create_drafts(owner_id,draft_json,revision) VALUES(?,?,1)').bind(auth.user.id,raw):ctx.env.DB.prepare('UPDATE vpage_create_drafts SET draft_json=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE owner_id=? AND revision=?').bind(raw,auth.user.id,revision),ctx.env.DB.prepare('DELETE FROM vpage_create_draft_refs WHERE owner_id=?').bind(auth.user.id),...refs.map(id=>ctx.env.DB.prepare('INSERT INTO vpage_create_draft_refs(owner_id,media_id) VALUES(?,?)').bind(auth.user.id,id)),ctx.env.DB.prepare('DELETE FROM vpage_draft_transition_guards WHERE token=?').bind(guard)];await ctx.env.DB.batch(statements)}catch{const existing=await ctx.env.DB.prepare('SELECT draft_json,revision FROM vpage_create_drafts WHERE owner_id=?').bind(auth.user.id).first();if(existing?.draft_json===raw&&Number(existing.revision)===revision+1)return json({saved:true,revision:Number(existing.revision),replayed:true},200,headers);return json({error:'ร่างถูกแก้ในอีกแท็บ หรือรูปในร่างไม่พร้อม กรุณารีโหลดก่อนบันทึก',code:'VPAGE_DRAFT_CONFLICT'},409,headers)}return json({saved:true,revision:revision+1},200,headers)}
export async function onRequestDelete(ctx){const auth=await authFor(ctx);if(auth.error)return auth.error;let body;try{body=await readBounded(ctx.request)}catch{return json({error:'ข้อมูลคำขอไม่ถูกต้อง'},400,headers)}if(!Number.isSafeInteger(body?.expected_revision)||body.expected_revision<0)return json({error:'revision ไม่ถูกต้อง'},400,headers);const result=await ctx.env.DB.prepare('DELETE FROM vpage_create_drafts WHERE owner_id=? AND revision=?').bind(auth.user.id,body.expected_revision).run();return json({deleted:Boolean(result.meta?.changes)},200,headers)}
