import test from'node:test';import assert from'node:assert/strict';import crypto from'node:crypto';
import{readConfig,readiness,runCollector,signedRequest}from'../src/collector.js';

const configured=(overrides={})=>readConfig({VISIOND_INGEST_URL:'https://visiondonline.com/api/internal/tiktok-commission-snapshots',VISIOND_STATUS_URL:'https://visiondonline.com/api/internal/tiktok-commission-collector-status',VISIOND_D1_BREAKER_URL:'https://visiondonline.com/api/internal/d1-quota-breaker',TIKTOK_COMMISSION_COLLECTOR_SECRET:'x'.repeat(32),TIKTOK_COMMISSION_SOURCE_ADAPTER:'affiliate-center',TIKTOK_COMMISSION_ACCOUNTS_JSON:'[{"connection_id":"c1","session_secret_name":"session-c1"}]',...overrides});
const openProbe=()=>({ok:true,status:200,json:async()=>({quota_breaker:{auto_closed:false,control_available:true}})});

test('empty placeholder config is safely disabled',async()=>{const config=readConfig({TIKTOK_COMMISSION_ACCOUNTS_JSON:'[]'});assert.equal(readiness(config).ready,false);let called=false;const result=await runCollector(config,{fetchImpl:async()=>{called=true}});assert.equal(result.status,503);assert.equal(called,false)});
test('configured collector probes breaker, signs and sends authoritative rows',async()=>{const secret='x'.repeat(32),now=1788724800000,config=configured();let request,probes=0;const result=await runCollector(config,{now,readRows:async()=>[{day:'2026-09-06',currency:'THB',amount:123.45,status:'actual'}],fetchImpl:async(url,init)=>{if(url===config.breakerUrl){probes++;return openProbe()}request={url,init};return{ok:true,status:200,json:async()=>({stored:1})}}});assert.equal(probes,1);assert.equal(result.results[0].stored,1);const expected=crypto.createHmac('sha256',secret).update(`${now}.${request.init.body}`).digest('hex');assert.equal(request.init.headers['x-visiond-signature'],expected)});
test('signature is deterministic',()=>{const signed=signedRequest({connection_id:'c1',rows:[]},'s'.repeat(32),123);assert.equal(signed.timestamp,'123');assert.equal(signed.signature.length,64)});
test('reader retries then reports reconnect required without ingesting fake rows',async()=>{const config=configured({VISIOND_INGEST_URL:'https://x/ingest',VISIOND_STATUS_URL:'https://x/status',VISIOND_D1_BREAKER_URL:'https://x/breaker',TIKTOK_COMMISSION_MAX_ATTEMPTS:'2'});let reads=0,ingests=0,statuses=[];const result=await runCollector(config,{readRows:async()=>{reads++;throw new Error('SESSION_LOGIN_REQUIRED')},fetchImpl:async(url,init)=>{if(url.endsWith('/breaker'))return openProbe();if(url.endsWith('/ingest'))ingests++;else statuses.push(JSON.parse(init.body).status);return{ok:true,status:200,json:async()=>({})}}});assert.equal(reads,2);assert.equal(ingests,0);assert.deepEqual(statuses,['connecting','reconnect_required']);assert.match(result.results[0].error,/SESSION_LOGIN_REQUIRED/)});
test('closed, malformed or unavailable breaker prevents provider read',async()=>{const config=configured();let reads=0;const readRows=async()=>{reads++;return[]};let result=await runCollector(config,{readRows,fetchImpl:async()=>({ok:true,status:200,json:async()=>({quota_breaker:{auto_closed:true,control_available:true}})})});assert.equal(result.skipped,true);assert.equal(reads,0);result=await runCollector(config,{readRows,fetchImpl:async()=>({ok:true,status:200,json:async()=>({})})});assert.equal(result.error,'d1_quota_control_unavailable');assert.equal(reads,0);result=await runCollector(config,{readRows,fetchImpl:async()=>{throw new Error('offline')}});assert.equal(result.error,'d1_quota_control_unavailable');assert.equal(reads,0)});
