import {json} from '../../../_lib.js';
import {requireVxUser} from '../../../_vx_access.js';
import {ensureDatabase} from '../../../_schema.js';
import {analyzeTikTok,ensureTikTokAnalyzerSchema,selectTikTokProvider} from '../../../_tiktok_analyzer.js';
import {tikTokCapabilities,tikTokVisibleProfile} from '../../../_tiktok_oauth.js';
import {requireD1DataFetchAvailable} from '../../../_d1_quota_breaker.js';

const headers={'cache-control':'private, no-store'};
const text=(value,max=2000)=>String(value||'').trim().slice(0,max);
const parse=value=>{try{return JSON.parse(value||'{}')}catch{return{}}};
const ext=type=>type==='image/png'?'png':type==='image/webp'?'webp':'jpg';
const channelView=row=>({...tikTokVisibleProfile({...row,scopes:row.tiktok_scopes}),tiktok_connected:tikTokCapabilities(row.tiktok_scopes).basic,analysis_count:Number(row.analysis_count||0),latest_result:parse(row.latest_result)});
const base64=buffer=>{const bytes=new Uint8Array(buffer);let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary)};
const safeUrl=value=>{try{const url=new URL(String(value||''));return ['http:','https:'].includes(url.protocol)?url.href.slice(0,1000):''}catch{return''}};
const productType=(value,fallback='B')=>/^[A-F]$/.test(String(value||'').toUpperCase())?String(value).toUpperCase():fallback;
const productKey=value=>String(value||'').normalize('NFKC').toLocaleLowerCase().replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/[^\p{L}\p{N}]+/gu,'').trim();
const findMatchingProduct=(db,channelId,name)=>db.prepare('SELECT id,name,inventory_status,product_type FROM tiktok_channel_products WHERE id=COALESCE((SELECT id FROM tiktok_channel_products WHERE channel_id=? AND name_key=? LIMIT 1),(SELECT id FROM tiktok_channel_products WHERE channel_id=? AND name=? COLLATE NOCASE LIMIT 1))').bind(channelId,productKey(name),channelId,name).first();
const PAGE_SIZE=24;
const pageLimit=value=>Math.min(PAGE_SIZE,Math.max(1,Number(value)||PAGE_SIZE));
const pageCursor=value=>{const raw=String(value||''),split=raw.lastIndexOf('|');return split>0?{at:raw.slice(0,split),id:raw.slice(split+1)}:null};
const pageResult=(rows,limit,atKey)=>{const hasMore=rows.length>limit,items=rows.slice(0,limit),last=items.at(-1);return{items,pagination:{limit,has_more:hasMore,next_cursor:hasMore&&last?`${last[atKey]}|${last.id}`:null}}};
async function inventoryPage(db,channelId,params,resource='inventory'){
  const limit=pageLimit(params.get('limit')),productCursor=pageCursor(params.get('product_cursor')),eventCursor=pageCursor(params.get('event_cursor')),productBindings=[channelId],eventBindings=[channelId],productWhere=['p.channel_id=?'],eventWhere=['channel_id=?'];
  if(productCursor){productWhere.push('(p.last_seen_at<? OR (p.last_seen_at=? AND p.id<?))');productBindings.push(productCursor.at,productCursor.at,productCursor.id)}
  if(eventCursor){eventWhere.push('(event_at<? OR (event_at=? AND id<?))');eventBindings.push(eventCursor.at,eventCursor.at,eventCursor.id)}
  const productRequest=resource==='inventory'||resource==='products',eventRequest=resource==='inventory'||resource==='events';
  const [productRows,eventRows,countRows]=await Promise.all([
    productRequest?db.prepare(`SELECT p.id,p.name,p.product_url,p.product_type,p.source_kind,p.customer_gender,p.customer_age_range,p.score,p.evidence,p.source_run_id,p.inventory_status,p.decided_at,p.review_started_at,p.next_review_at,p.review_cycle_days,p.review_status,p.first_seen_at,p.last_seen_at,r.created_at attachment_date FROM tiktok_channel_products p LEFT JOIN tiktok_analysis_runs r ON r.id=p.source_run_id WHERE ${productWhere.join(' AND ')} ORDER BY p.last_seen_at DESC,p.id DESC LIMIT ?`).bind(...productBindings,limit+1).all():Promise.resolve({results:[]}),
    eventRequest?db.prepare(`SELECT id,product_name,event_type,product_type,inventory_status,detail,source_run_id,event_at FROM tiktok_product_events WHERE ${eventWhere.join(' AND ')} ORDER BY event_at DESC,id DESC LIMIT ?`).bind(...eventBindings,limit+1).all():Promise.resolve({results:[]}),
    productRequest?db.prepare("SELECT inventory_status,COUNT(*) total FROM tiktok_channel_products WHERE channel_id=? GROUP BY inventory_status").bind(channelId).all():Promise.resolve({results:[]}),
  ]);
  const products=pageResult(productRows.results||[],limit,'last_seen_at'),events=pageResult(eventRows.results||[],limit,'event_at'),counts={all:0,kept:0,discarded:0,analyzed:0};
  for(const row of countRows.results||[]){const count=Number(row.total)||0;counts.all+=count;if(Object.hasOwn(counts,row.inventory_status))counts[row.inventory_status]=count}
  return{...(productRequest?{products:products.items,inventory_counts:counts}:{}),...(eventRequest?{product_events:events.items}:{}),pagination:{...(productRequest?{products:products.pagination}:{}),...(eventRequest?{events:events.pagination}:{})}}
}

export async function onRequestGet(ctx){
  await ensureDatabase(ctx.env);await ensureTikTokAnalyzerSchema(ctx.env);const auth=await requireVxUser(ctx);if(auth.error)return auth.error;
  const url=new URL(ctx.request.url),params=url.searchParams,channelId=text(params.get('channel_id'),80),runId=text(params.get('run_id'),80),resource=text(params.get('resource'),20)||'overview';
  if(runId){const run=await ctx.env.DB.prepare(`SELECT r.*,c.name channel_name,c.channel_url,c.handle FROM tiktok_analysis_runs r JOIN tiktok_channels c ON c.id=r.channel_id WHERE r.id=? AND c.created_by=?`).bind(runId,auth.user.id).first();if(!run)return json({error:'ไม่พบรอบวิเคราะห์'},404,headers);const images=(await ctx.env.DB.prepare('SELECT id,file_name,mime_type,file_size,sort_order,object_key FROM tiktok_analysis_images WHERE run_id=? ORDER BY sort_order').bind(runId).all()).results||[];return json({run:{...run,result:parse(run.result_json),images:images.map(x=>({...x,url:'/api/media/'+x.object_key}))}},200,headers)}
  if(channelId){
    const channel=await ctx.env.DB.prepare('SELECT c.*,(SELECT t.scopes FROM tiktok_connections t WHERE t.channel_id=c.id AND t.user_id=c.created_by AND t.status=\'active\' ORDER BY t.updated_at DESC LIMIT 1) tiktok_scopes,(SELECT b.slot_id FROM tiktok_browser_profile_bindings b WHERE b.user_id=c.created_by AND b.channel_id=c.id LIMIT 1) browser_profile_slot_id,(SELECT b.profile_kind FROM tiktok_browser_profile_bindings b WHERE b.user_id=c.created_by AND b.channel_id=c.id LIMIT 1) browser_profile_kind FROM tiktok_channels c WHERE c.id=? AND c.created_by=? AND c.archived_at IS NULL').bind(channelId,auth.user.id).first();if(!channel)return json({error:'ไม่พบช่อง'},404,headers);
    channel.tiktok_connected=tikTokCapabilities(channel.tiktok_scopes).basic;
    channel.reconnect_required=!channel.tiktok_connected;
    if(resource==='channel')return json({channel},200,headers);
    if(['inventory','products','events'].includes(resource))return json(await inventoryPage(ctx.env.DB,channelId,params,resource),200,headers);
    if(resource!=='overview'&&resource!=='runs')return json({error:'resource ไม่ถูกต้อง'},400,headers);
    const runLimit=pageLimit(params.get('run_limit')||params.get('limit')),runCursor=pageCursor(params.get('run_cursor')),runWhere=['channel_id=?'],runBindings=[channelId];if(runCursor){runWhere.push('(created_at<? OR (created_at=? AND id<?))');runBindings.push(runCursor.at,runCursor.at,runCursor.id)}
    const runRows=(await ctx.env.DB.prepare(`SELECT id,title,date_range,strategy,status,result_json,provider,model,created_at FROM tiktok_analysis_runs WHERE ${runWhere.join(' AND ')} ORDER BY created_at DESC,id DESC LIMIT ?`).bind(...runBindings,runLimit+1).all()).results||[],runPage=pageResult(runRows,runLimit,'created_at'),runs=runPage.items.map(x=>({...x,result:parse(x.result_json)}));
    if(resource==='runs')return json({runs,pagination:{runs:runPage.pagination}},200,headers);
    const inventory=await inventoryPage(ctx.env.DB,channelId,params,'inventory');
    return json({channel,...inventory,runs,pagination:{...inventory.pagination,runs:runPage.pagination}},200,headers)
  }
  const channelLimit=pageLimit(params.get('limit')),channelCursor=pageCursor(params.get('cursor')),channelWhere=channelCursor?'WHERE (sort_at<? OR (sort_at=? AND id<?))':'',channelBindings=channelCursor?[auth.user.id,channelCursor.at,channelCursor.at,channelCursor.id,channelLimit+1]:[auth.user.id,channelLimit+1],channelRows=(await ctx.env.DB.prepare(`WITH scoped AS (SELECT c.*,(SELECT t.scopes FROM tiktok_connections t WHERE t.channel_id=c.id AND t.user_id=c.created_by AND t.status='active' ORDER BY t.updated_at DESC LIMIT 1) tiktok_scopes,(SELECT b.slot_id FROM tiktok_browser_profile_bindings b WHERE b.user_id=c.created_by AND b.channel_id=c.id LIMIT 1) browser_profile_slot_id,(SELECT b.profile_kind FROM tiktok_browser_profile_bindings b WHERE b.user_id=c.created_by AND b.channel_id=c.id LIMIT 1) browser_profile_kind,(SELECT COUNT(*) FROM tiktok_analysis_runs r WHERE r.channel_id=c.id) analysis_count,(SELECT result_json FROM tiktok_analysis_runs r WHERE r.channel_id=c.id ORDER BY r.created_at DESC LIMIT 1) latest_result,(SELECT created_at FROM tiktok_analysis_runs r WHERE r.channel_id=c.id ORDER BY r.created_at DESC LIMIT 1) latest_analysis_at,(SELECT avatar_url FROM tiktok_connections t WHERE t.channel_id=c.id AND t.user_id=c.created_by AND t.status='active' ORDER BY t.updated_at DESC LIMIT 1) avatar_url,(SELECT follower_count FROM tiktok_connections t WHERE t.channel_id=c.id AND t.user_id=c.created_by AND t.status='active' ORDER BY t.updated_at DESC LIMIT 1) follower_count,(SELECT likes_count FROM tiktok_connections t WHERE t.channel_id=c.id AND t.user_id=c.created_by AND t.status='active' ORDER BY t.updated_at DESC LIMIT 1) likes_count,(SELECT video_count FROM tiktok_connections t WHERE t.channel_id=c.id AND t.user_id=c.created_by AND t.status='active' ORDER BY t.updated_at DESC LIMIT 1) video_count,COALESCE((SELECT created_at FROM tiktok_analysis_runs r WHERE r.channel_id=c.id ORDER BY r.created_at DESC LIMIT 1),c.updated_at) sort_at FROM tiktok_channels c WHERE c.archived_at IS NULL AND c.created_by=?) SELECT * FROM scoped ${channelWhere} ORDER BY sort_at DESC,id DESC LIMIT ?`).bind(...channelBindings).all()).results||[],channelPage=pageResult(channelRows,channelLimit,'sort_at');
  return json({channels:channelPage.items.map(channelView),pagination:channelPage.pagination,provider_configured:Boolean(selectTikTokProvider(ctx.env))},200,headers);
}

export async function onRequestPost(ctx){
  await ensureDatabase(ctx.env);const form=await ctx.request.clone().formData(),action=text(form.get('action'),40),name=text(form.get('channel_name'),120),channelUrl=text(form.get('channel_url'),500),existingId=text(form.get('channel_id'),80);
  const localActions=new Set(['sync_sold_product_grades','fail_c_product','retest_f_product','set_product_c','set_product_inventory','delete_channel','save_channel']);
  const auth=await requireVxUser(ctx,{bootstrap:localActions.has(action)});if(auth.error)return auth.error;
  if(!localActions.has(action)){const blocked=await requireD1DataFetchAvailable(ctx,'tiktok_ai_analysis');if(blocked)return blocked}
  await ensureTikTokAnalyzerSchema(ctx.env);
  if(action==='sync_sold_product_grades'){
    if(!existingId)return json({error:'ไม่พบช่อง'},400,headers);const channel=await ctx.env.DB.prepare('SELECT id FROM tiktok_channels WHERE id=? AND created_by=? AND archived_at IS NULL').bind(existingId,auth.user.id).first();if(!channel)return json({error:'ไม่พบช่องหรือไม่มีสิทธิ์แก้ไข'},404,headers);
    let updates=[];try{updates=JSON.parse(String(form.get('sales_grades')||'[]'))}catch{return json({error:'ข้อมูลเกรดไม่ถูกต้อง'},400,headers)}
    const statements=[];for(const item of updates.slice(0,200)){const productName=text(item?.name,500),grade=productType(item?.grade,'D'),sales=Math.max(0,Number(item?.sales)||0),expected=sales>=30?'A':sales>=16?'B':sales>0?'C':'D';if(!productName||grade!==expected)continue;statements.push(ctx.env.DB.prepare("UPDATE tiktok_channel_products SET product_type=?,evidence=?,review_cycle_days=?,review_status='scheduled',next_review_at=datetime('now',?),last_seen_at=CURRENT_TIMESTAMP WHERE channel_id=? AND name=? AND source_kind='sold_product_selection' AND inventory_status='kept'").bind(expected,`ยอดขาย 30 วัน ${sales} ออเดอร์ · เกรด ${expected}`,expected==='D'?3:30,expected==='D'?'+3 days':'+30 days',existingId,productName))}
    if(statements.length)await ctx.env.DB.batch(statements);return json({ok:true,updated:statements.length},200,headers);
  }
  if(action==='fail_c_product'){
    const productName=text(form.get('product_name'),500);if(!existingId||!productName)return json({error:'ข้อมูลสินค้าไม่ครบ'},400,headers);
    const channel=await ctx.env.DB.prepare('SELECT id FROM tiktok_channels WHERE id=? AND created_by=? AND archived_at IS NULL').bind(existingId,auth.user.id).first();if(!channel)return json({error:'ไม่พบช่องหรือไม่มีสิทธิ์แก้ไข'},404,headers);
    const product=await ctx.env.DB.prepare('SELECT product_type FROM tiktok_channel_products WHERE channel_id=? AND name=?').bind(existingId,productName).first();if(!product)return json({error:'ไม่พบสินค้าในช่องนี้'},404,headers);if(product.product_type!=='D')return json({error:'ปุ่มไม่ผ่านใช้ได้เฉพาะสินค้าทดสอบ D'},409,headers);
    await ctx.env.DB.batch([ctx.env.DB.prepare("UPDATE tiktok_channel_products SET product_type='F',inventory_status='discarded',decided_at=CURRENT_TIMESTAMP,next_review_at=NULL,review_cycle_days=0,review_status='failed',last_seen_at=CURRENT_TIMESTAMP WHERE channel_id=? AND name=? AND product_type='D'").bind(existingId,productName),ctx.env.DB.prepare("INSERT INTO tiktok_product_events(id,channel_id,product_name,event_type,product_type,inventory_status,detail) VALUES(?,?,?,'manual_fail','F','discarded','ผู้ใช้กดไม่ผ่านสินค้าทดสอบ D จึงเปลี่ยนเป็น F')").bind(crypto.randomUUID(),existingId,productName)]);
    return json({ok:true,product_name:productName,product_type:'F',inventory_status:'discarded'},200,headers);
  }
  if(action==='retest_f_product'){
    const productName=text(form.get('product_name'),500);if(!existingId||!productName)return json({error:'ข้อมูลสินค้าไม่ครบ'},400,headers);
    const channel=await ctx.env.DB.prepare('SELECT id FROM tiktok_channels WHERE id=? AND created_by=? AND archived_at IS NULL').bind(existingId,auth.user.id).first();if(!channel)return json({error:'ไม่พบช่องหรือไม่มีสิทธิ์แก้ไข'},404,headers);
    const product=await ctx.env.DB.prepare('SELECT product_type FROM tiktok_channel_products WHERE channel_id=? AND name=?').bind(existingId,productName).first();if(!product)return json({error:'ไม่พบสินค้าในช่องนี้'},404,headers);if(product.product_type!=='F')return json({error:'ทดสอบใหม่ได้เฉพาะสินค้า F'},409,headers);
    await ctx.env.DB.batch([ctx.env.DB.prepare("UPDATE tiktok_channel_products SET product_type='D',inventory_status='kept',decided_at=CURRENT_TIMESTAMP,review_started_at=CURRENT_TIMESTAMP,next_review_at=datetime('now','+3 days'),review_cycle_days=3,review_status='scheduled',last_seen_at=CURRENT_TIMESTAMP WHERE channel_id=? AND name=? AND product_type='F'").bind(existingId,productName),ctx.env.DB.prepare("INSERT INTO tiktok_product_events(id,channel_id,product_name,event_type,product_type,inventory_status,detail) VALUES(?,?,?,'manual_retest','D','kept','สินค้านี้เคยถูกคัดออก ผู้ใช้เลือกนำกลับมาทดสอบเป็น D')").bind(crypto.randomUUID(),existingId,productName)]);
    return json({ok:true,product_name:productName,product_type:'D',inventory_status:'kept',previously_tested:true},200,headers);
  }
  if(action==='set_product_c'){
    let productName=text(form.get('product_name'),500);const scoreValue=form.get('score'),score=Number.isFinite(Number(scoreValue))?Math.max(0,Math.min(100,Number(scoreValue))):0,evidence=text(form.get('evidence'),2000),productUrl=safeUrl(form.get('product_url')),requestedSourceKind=text(form.get('source_kind'),40),sourceKind=['marketplace_selection','sold_product_selection'].includes(requestedSourceKind)?requestedSourceKind:'manual_selection',requestedGrade=productType(form.get('requested_grade'),'D'),savedGrade=sourceKind==='sold_product_selection'&&['A','B','C'].includes(requestedGrade)?requestedGrade:'D',reviewDays=savedGrade==='D'?3:30;
    if(!existingId||!productName)return json({error:'กรุณาระบุช่องและชื่อสินค้า'},400,headers);
    const channel=await ctx.env.DB.prepare('SELECT id FROM tiktok_channels WHERE id=? AND created_by=? AND archived_at IS NULL').bind(existingId,auth.user.id).first();if(!channel)return json({error:'ไม่พบช่องหรือไม่มีสิทธิ์แก้ไข'},404,headers);
    const existing=await findMatchingProduct(ctx.env.DB,existingId,productName);if(existing?.inventory_status==='kept'&&sourceKind!=='sold_product_selection')return json({ok:true,already_exists:true,product_name:existing.name,product_type:existing.product_type,inventory_status:'kept'},200,headers);if(existing)productName=existing.name;
    const sourceDetail=sourceKind==='marketplace_selection'?'เพิ่มจาก TikTok Open Collaboration เข้าลิสต์คัดสินค้าเป็น D และเริ่มติดตามผลรอบ 3 วัน':sourceKind==='sold_product_selection'?`เพิ่มจากตารางสินค้าที่ขายได้ด้วยเกรด ${savedGrade} ตามยอดขายจริง 30 วัน`:'ผู้ใช้เลือกสินค้าเป็น D เองและเริ่มติดตามผลรอบ 3 วัน';
    await ctx.env.DB.batch([ctx.env.DB.prepare(`INSERT INTO tiktok_channel_products(id,channel_id,name,name_key,product_url,product_type,source_kind,score,evidence,inventory_status,decided_at,review_started_at,next_review_at,review_cycle_days,review_status) VALUES(?,?,?,?,?,?,?,?,?,'kept',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,datetime('now',?),?,'scheduled') ON CONFLICT(channel_id,name) DO UPDATE SET name_key=excluded.name_key,product_url=CASE WHEN excluded.product_url<>'' THEN excluded.product_url ELSE tiktok_channel_products.product_url END,product_type=excluded.product_type,source_kind=excluded.source_kind,score=CASE WHEN excluded.score>0 THEN excluded.score ELSE tiktok_channel_products.score END,evidence=CASE WHEN excluded.evidence<>'' THEN excluded.evidence ELSE tiktok_channel_products.evidence END,inventory_status='kept',decided_at=CURRENT_TIMESTAMP,review_started_at=CURRENT_TIMESTAMP,next_review_at=excluded.next_review_at,review_cycle_days=excluded.review_cycle_days,review_status='scheduled',last_seen_at=CURRENT_TIMESTAMP`).bind(crypto.randomUUID(),existingId,productName,productKey(productName),productUrl,savedGrade,sourceKind,score,evidence,`+${reviewDays} days`,reviewDays),ctx.env.DB.prepare("INSERT INTO tiktok_product_events(id,channel_id,product_name,event_type,product_type,inventory_status,detail) VALUES(?,?,?,'manual_c',?,'kept',?)").bind(crypto.randomUUID(),existingId,productName,savedGrade,sourceDetail)]);
    return json({ok:true,already_exists:Boolean(existing?.inventory_status==='kept'),product_name:productName,product_type:savedGrade,inventory_status:'kept'},200,headers);
  }
  if(action==='set_product_inventory'){
    let productName=text(form.get('product_name'),500);const status=text(form.get('inventory_status'),20),type=productType(form.get('product_type'),'C'),scoreValue=form.get('score'),score=Number.isFinite(Number(scoreValue))?Math.max(0,Math.min(100,Number(scoreValue))):0;
    if(!existingId||!productName||!['kept','discarded'].includes(status))return json({error:'ข้อมูลสินค้าหรือสถานะไม่ครบ'},400,headers);
    const channel=await ctx.env.DB.prepare('SELECT id FROM tiktok_channels WHERE id=? AND created_by=? AND archived_at IS NULL').bind(existingId,auth.user.id).first();if(!channel)return json({error:'ไม่พบช่องหรือไม่มีสิทธิ์แก้ไข'},404,headers);
    const existing=await findMatchingProduct(ctx.env.DB,existingId,productName);if(existing?.inventory_status===status)return json({ok:true,already_exists:true,product_name:existing.name,inventory_status:status},200,headers);if(existing)productName=existing.name;
    await ctx.env.DB.batch([ctx.env.DB.prepare(`INSERT INTO tiktok_channel_products(id,channel_id,name,name_key,product_type,source_kind,score,evidence,inventory_status,decided_at) VALUES(?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(channel_id,name) DO UPDATE SET name_key=excluded.name_key,product_type=excluded.product_type,score=CASE WHEN excluded.score>0 THEN excluded.score ELSE tiktok_channel_products.score END,evidence=CASE WHEN excluded.evidence<>'' THEN excluded.evidence ELSE tiktok_channel_products.evidence END,inventory_status=excluded.inventory_status,decided_at=CURRENT_TIMESTAMP,last_seen_at=CURRENT_TIMESTAMP`).bind(crypto.randomUUID(),existingId,productName,productKey(productName),type,'analysis_selection',score,text(form.get('evidence'),2000),status),ctx.env.DB.prepare('INSERT INTO tiktok_product_events(id,channel_id,product_name,event_type,product_type,inventory_status,detail) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),existingId,productName,status==='kept'?'kept':'discarded',type,status,status==='kept'?'เก็บเข้าลิสต์คัดสินค้า':'คัดออกจากลิสต์สินค้า')]);
    const reviewDays=status==='kept'?(type==='D'?3:['A','B','C'].includes(type)?30:0):0;if(reviewDays)await ctx.env.DB.prepare("UPDATE tiktok_channel_products SET review_started_at=CURRENT_TIMESTAMP,next_review_at=datetime('now',?),review_cycle_days=?,review_status='scheduled' WHERE channel_id=? AND name=?").bind(`+${reviewDays} days`,reviewDays,existingId,productName).run();else await ctx.env.DB.prepare("UPDATE tiktok_channel_products SET next_review_at=NULL,review_cycle_days=0,review_status='not_scheduled' WHERE channel_id=? AND name=?").bind(existingId,productName).run();
    return json({ok:true,product_name:productName,inventory_status:status},200,headers);
  }
  if(action==='delete_channel'){
    if(!existingId)return json({error:'ไม่พบช่องที่ต้องการลบ'},400,headers);
    const channel=await ctx.env.DB.prepare('SELECT id FROM tiktok_channels WHERE id=? AND created_by=?').bind(existingId,auth.user.id).first();if(!channel)return json({error:'ไม่พบช่องหรือไม่มีสิทธิ์ลบ'},404,headers);
    await ctx.env.DB.prepare('UPDATE tiktok_channels SET archived_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND created_by=?').bind(existingId,auth.user.id).run();return json({ok:true,deleted_channel_id:existingId,recoverable:true},200,headers);
  }
  if(!auth.vx.admin && (action==='save_channel'||!existingId)) return json({error:'เพิ่มช่องด้วยปุ่ม + ช่องใหม่และล็อกอิน TikTok เท่านั้น'},400,headers);
  if(!name&&!channelUrl)return json({error:'กรุณาใส่ชื่อช่องหรือลิงก์ช่อง TikTok'},400,headers);
  if(action==='save_channel'){
    let saved=existingId?await ctx.env.DB.prepare('SELECT * FROM tiktok_channels WHERE id=? AND created_by=?').bind(existingId,auth.user.id).first():null;if(!saved&&channelUrl)saved=await ctx.env.DB.prepare('SELECT * FROM tiktok_channels WHERE channel_url=? AND created_by=?').bind(channelUrl,auth.user.id).first();
    const id=saved?.id||crypto.randomUUID(),savedName=name||saved?.name||channelUrl.replace(/\/$/,'').split('/').pop()||'ช่อง TikTok';
    if(saved)await ctx.env.DB.prepare('UPDATE tiktok_channels SET name=?,channel_url=?,direction=?,archived_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(savedName,channelUrl||saved.channel_url||'',text(form.get('strategy'),100),id).run();else await ctx.env.DB.prepare('INSERT INTO tiktok_channels(id,name,channel_url,direction,created_by) VALUES(?,?,?,?,?)').bind(id,savedName,channelUrl,text(form.get('strategy'),100),auth.user.id).run();
    return json({ok:true,channel_id:id,saved_only:true},201,headers);
  }
  const files=form.getAll('screenshots').filter(x=>x instanceof File&&x.size);if(files.length>30)return json({error:'อัปโหลดภาพได้ไม่เกิน 30 รูปต่อรอบ'},400,headers);
  let total=0;for(const file of files){total+=file.size;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)return json({error:'แต่ละรูปต้องเป็น JPG, PNG หรือ WEBP ไม่เกิน 5 MB'},400,headers)}if(total>25*1024*1024)return json({error:'รูปทั้งหมดรวมกันต้องไม่เกิน 25 MB'},400,headers);
  const notes=text(form.get('notes'),8000),shopApiConnection=existingId?await ctx.env.DB.prepare("SELECT id,last_synced_at FROM tiktok_shop_creator_connections WHERE user_id=? AND channel_id=? AND status='active' ORDER BY updated_at DESC LIMIT 1").bind(auth.user.id,existingId).first():null;if(!files.length&&!notes&&!shopApiConnection)return json({error:'กรุณาใส่ภาพหน้าจอหรือข้อมูลประกอบ หรือเชื่อม TikTok Shop API'},400,headers);
  let channel=existingId?await ctx.env.DB.prepare('SELECT * FROM tiktok_channels WHERE id=? AND created_by=? AND archived_at IS NULL').bind(existingId,auth.user.id).first():null;
  if(existingId&&!channel)return json({error:'ไม่พบช่องหรือไม่มีสิทธิ์วิเคราะห์'},404,headers);
  if(!channel&&channelUrl)channel=await ctx.env.DB.prepare('SELECT * FROM tiktok_channels WHERE channel_url=? AND created_by=? AND archived_at IS NULL').bind(channelUrl,auth.user.id).first();
  const channelId=channel?.id||crypto.randomUUID(),channelName=name||channel?.name||channelUrl.replace(/\/$/,'').split('/').pop()||'ช่อง TikTok';
  const images=[];for(const file of files)images.push({file,type:file.type,base64:base64(await file.arrayBuffer())});
  const provider=selectTikTokProvider(ctx.env);if(!provider)return json({error:'ยังไม่ได้ตั้งค่า AI สำหรับวิเคราะห์ภาพ TikTok',code:'AI_NOT_CONFIGURED'},503,headers);
  const lookbackDays=[7,14,30,60,90].includes(Number(form.get('lookback_days')))?Number(form.get('lookback_days')):30,attachmentPeriodDays=[3,7,30].includes(Number(form.get('attachment_period_days')))?Number(form.get('attachment_period_days')):30,clipsPerDay=[10,20,30].includes(Number(form.get('clips_per_day')))?Number(form.get('clips_per_day')):30;
  let officialContext='';const linked=await ctx.env.DB.prepare("SELECT id,scopes,display_name,bio,follower_count,following_count,likes_count,video_count,last_synced_at FROM tiktok_connections WHERE user_id=? AND channel_id=? AND status='active' ORDER BY updated_at DESC LIMIT 1").bind(auth.user.id,channelId).first();
  if(linked&&tikTokCapabilities(linked.scopes).basic){const videos=tikTokCapabilities(linked.scopes).videos?(await ctx.env.DB.prepare('SELECT title,description,create_time,duration,view_count,like_count,comment_count,share_count FROM tiktok_connection_videos WHERE connection_id=? AND create_time>=unixepoch(\'now\')-(?*86400) ORDER BY create_time DESC LIMIT 100').bind(linked.id,lookbackDays).all()).results||[]:[];officialContext=`\nข้อมูลทางการจาก TikTok API (ซิงก์ ${linked.last_synced_at||'-'}): ${JSON.stringify({profile:tikTokVisibleProfile({display_name:linked.display_name,bio:linked.bio,follower_count:linked.follower_count,following_count:linked.following_count,likes_count:linked.likes_count,video_count:linked.video_count,scopes:linked.scopes}),videos})}`}
  if(shopApiConnection){const shopProducts=(await ctx.env.DB.prepare('SELECT product_id,name,product_url,product_grade,commission_json,synced_at FROM tiktok_shop_showcase_products WHERE connection_id=? ORDER BY sort_order LIMIT 200').bind(shopApiConnection.id).all()).results||[],shopOrders=(await ctx.env.DB.prepare("SELECT order_id,create_time,product_ids,status,gmv_json,commission_json FROM tiktok_shop_affiliate_orders WHERE connection_id=? AND create_time>=unixepoch('now')-(30*86400) ORDER BY create_time DESC LIMIT 1000").bind(shopApiConnection.id).all()).results||[];officialContext+=`\nข้อมูลทางการจาก TikTok Shop API (ซิงก์ ${shopApiConnection.last_synced_at||'-'}): ${JSON.stringify({showcase_products:shopProducts,orders_last_30_days:shopOrders})}`}
  const historicalFailed=(await ctx.env.DB.prepare("SELECT name,evidence,last_seen_at FROM tiktok_channel_products WHERE channel_id=? AND product_type='F' ORDER BY last_seen_at DESC LIMIT 200").bind(channelId).all()).results||[];if(historicalFailed.length)officialContext+=`\nประวัติสินค้า F ของช่องที่ต้องเก็บไว้และแจ้งเตือนหากนำกลับมาทดสอบเป็น D: ${JSON.stringify(historicalFailed)}`;
  let result;try{result=await analyzeTikTok(provider,{channel:{name:channelName,channel_url:channelUrl||channel?.channel_url||''},notes:notes+officialContext,candidates:text(form.get('candidate_products'),3000),strategy:text(form.get('strategy'),100),dateRange:text(form.get('date_range'),100),lookbackDays,attachmentPeriodDays,clipsPerDay,images})}catch(error){const code=String(error?.message||error).slice(0,120);console.error('TIKTOK_ANALYZER_FAILED',{code,provider:provider.name,model:provider.model,image_count:images.length,total_image_bytes:files.reduce((sum,file)=>sum+file.size,0)});return json({error:'วิเคราะห์ภาพไม่สำเร็จ กรุณาลองใหม่',code},502,headers)}
  const runId=crypto.randomUUID(),statements=[];
  if(channel)statements.push(ctx.env.DB.prepare('UPDATE tiktok_channels SET name=?,channel_url=?,direction=?,homework=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND created_by=?').bind(channelName,channelUrl||channel.channel_url||'',text(form.get('strategy'),100),JSON.stringify(result.homework||[]),channelId,auth.user.id));else statements.push(ctx.env.DB.prepare('INSERT INTO tiktok_channels(id,name,channel_url,direction,homework,created_by) VALUES(?,?,?,?,?,?)').bind(channelId,channelName,channelUrl,text(form.get('strategy'),100),JSON.stringify(result.homework||[]),auth.user.id));
  statements.push(ctx.env.DB.prepare('INSERT INTO tiktok_analysis_runs(id,channel_id,title,date_range,strategy,notes,candidate_products,result_json,provider,model,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(runId,channelId,text(form.get('title'),160)||`วิเคราะห์ ${channelName}`,text(form.get('date_range'),100),text(form.get('strategy'),100),notes,text(form.get('candidate_products'),3000),JSON.stringify(result),provider.name,provider.model,auth.user.id));
  const rankedProducts=(Array.isArray(result.daily_product_list)?result.daily_product_list:[]).map(item=>({item:{...item,name:item?.product,evidence:item?.ranking_reason,score:item?.ranking_score},fallback:'E',kind:'daily_ranking',score:item?.ranking_score}));
  const classified=[...(Array.isArray(result.winner_products)?result.winner_products:[]).map(item=>({item,fallback:'A',kind:'winner',score:item?.score})),...(Array.isArray(result.next_product_candidates)?result.next_product_candidates:[]).map(item=>({item,fallback:'B',kind:'candidate',score:item?.fit_score})),...(Array.isArray(result.avoid_products)?result.avoid_products:[]).map(item=>({item,fallback:'E',kind:'avoid',score:item?.score})),...rankedProducts].slice(0,140);
  const eventProducts=new Set();for(const entry of classified){const item=entry.item,productName=text(item?.name,500);if(!productName)continue;const nameKey=productKey(productName);if(!nameKey)continue;const evidence=text(item?.evidence||(Array.isArray(item?.reasons)?item.reasons.join(' · '):'')||(Array.isArray(item?.risks)?item.risks.join(' · '):''),2000),gender=text(item?.customer_gender,100)||'ยังระบุไม่ได้',ageRange=text(item?.customer_age_range,100)||'ยังระบุไม่ได้',hasScore=entry.score!==null&&entry.score!==undefined&&entry.score!==''&&Number.isFinite(Number(entry.score)),score=Math.max(0,Math.min(100,Number(entry.score)||0)),rawType=String(item?.product_type||'').toUpperCase(),type=rawType==='F'||rawType===''?'':productType(rawType,entry.fallback),cycle=type==='C'?3:['A','B'].includes(type)?7:0,modifier=cycle?`+${cycle} days`:null,status=cycle?'scheduled':'not_scheduled';statements.push(ctx.env.DB.prepare(`INSERT INTO tiktok_channel_products(id,channel_id,name,name_key,product_url,product_type,source_kind,customer_gender,customer_age_range,score,evidence,source_run_id,review_started_at,next_review_at,review_cycle_days,review_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CASE WHEN ? IS NULL THEN NULL ELSE datetime('now',?) END,?,?) ON CONFLICT(channel_id,name) DO UPDATE SET name_key=excluded.name_key,product_url=CASE WHEN excluded.product_url<>'' THEN excluded.product_url ELSE tiktok_channel_products.product_url END,product_type=CASE WHEN tiktok_channel_products.inventory_status='discarded' THEN 'F' ELSE excluded.product_type END,source_kind=excluded.source_kind,customer_gender=excluded.customer_gender,customer_age_range=excluded.customer_age_range,score=excluded.score,evidence=excluded.evidence,source_run_id=excluded.source_run_id,review_started_at=CURRENT_TIMESTAMP,next_review_at=excluded.next_review_at,review_cycle_days=excluded.review_cycle_days,review_status=excluded.review_status,last_seen_at=CURRENT_TIMESTAMP`).bind(crypto.randomUUID(),channelId,productName,nameKey,safeUrl(item?.product_url),type,entry.kind,gender,ageRange,score,evidence,runId,modifier,modifier,cycle,status));if(!eventProducts.has(nameKey)){eventProducts.add(nameKey);statements.push(ctx.env.DB.prepare('INSERT INTO tiktok_product_events(id,channel_id,product_name,event_type,product_type,inventory_status,detail,source_run_id) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),channelId,productName,cycle?'review_scheduled':'analyzed',type,'analyzed',cycle?`วิเคราะห์จากรูปและนัดตรวจอีก ${cycle} วัน`:'วิเคราะห์จากรูปแล้ว',runId))}}
  const stored=[];for(let i=0;i<images.length;i++){const item=images[i],key=`tiktok-analyzer/${channelId}/${runId}-${i+1}.${ext(item.type)}`;await ctx.env.FILES.put(key,await item.file.arrayBuffer(),{httpMetadata:{contentType:item.type}});stored.push(key);statements.push(ctx.env.DB.prepare('INSERT INTO tiktok_analysis_images(id,run_id,object_key,file_name,mime_type,file_size,sort_order) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),runId,key,text(item.file.name,200),item.type,item.file.size,i))}
  try{await ctx.env.DB.batch(statements);await ctx.env.DB.batch([ctx.env.DB.prepare("UPDATE tiktok_channel_products SET review_cycle_days=3,next_review_at=datetime(COALESCE(review_started_at,CURRENT_TIMESTAMP),'+3 days'),review_status='scheduled' WHERE channel_id=? AND product_type='D' AND inventory_status='kept'").bind(channelId),ctx.env.DB.prepare("UPDATE tiktok_channel_products SET review_cycle_days=30,next_review_at=datetime(COALESCE(review_started_at,CURRENT_TIMESTAMP),'+30 days'),review_status='scheduled' WHERE channel_id=? AND product_type IN ('A','B','C') AND inventory_status='kept'").bind(channelId)])}catch(error){await Promise.all(stored.map(key=>ctx.env.FILES.delete(key)));return json({error:'บันทึกผลวิเคราะห์ไม่สำเร็จ'},500,headers)}
  return json({ok:true,channel_id:channelId,run_id:runId,result},201,headers);
}
