import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=file=>fs.readFileSync(file,'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.235');
const route=read('functions/s/[slug].js'),ui=read('public/sales-page-public.js'),css=read('public/sales-page-public.css'),center=read('public/sales-page-center.js'),protocol=read('VISIOND-SALES-PAGE-PROTOCOL.md'),roadmap=read('VISIOND-ROADMAP.md');
for(const token of["page_type='ad_shortcut'","status='published'",'p.robots_index=0',"p.status='published'",'p.deleted_at IS NULL',"COALESCE(p.product_kind,'product')='product'",'promotionPrice','x-robots-tag','noindex, nofollow','safeJson'])assert.ok(route.includes(token),token);
assert.match(route,/สินค้าหน้านี้ยังไม่พร้อมขาย[\s\S]*,410\)/);
for(const token of['vd_cart','data-cart-count','AddToCart',"location.href='/cart'",'เลือกสินค้าได้สูงสุดรวม 30 ชิ้น'])assert.ok(ui.includes(token),token);
assert.match(css,/@media\(max-width:760px\)/);
for(const token of['publicSalesPageLink','/s/${encodeURIComponent(detail.page.slug)}','published'])assert.ok(center.includes(token),token);
for(const token of['Ad Shortcut','noindex','สินค้าร่าง','Public Renderer'])assert.ok(protocol.includes(token)||roadmap.includes(token),token);
console.log('v0.14.235 public Ad Shortcut renderer published product gate noindex cart and checkout path: PASS');
