import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {buildRuleSalesInsight,classifySalesTurn,salesPlaybookPrompt} from '../functions/_visiond-sales-playbook.js';
import {captionKnowledgePrompt} from '../functions/_v12-page-captions.js';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const [version,index,admin,page,assistant,line,captions]=await Promise.all([read('VERSION.txt'),read('public/index.html'),read('public/admin.html'),read('public/v12-connect.html'),read('functions/api/admin/v12-sales-assistant.js'),read('functions/_veasy_line_ai.js'),read('functions/_v12-page-captions.js')]);
assert.equal(version.trim(),'v0.14.251');assert.match(index,/WEB v0\.14\.251/);assert.match(admin,/ADMIN v0\.14\.251/);assert.match(page,/v0\.14\.251/);assert.match(page,/build 014251/);
assert.equal(classifySalesTurn('จ่ายแล้วแต่เข้าเรียนไม่ได้').needs_human,true);assert.equal(classifySalesTurn('มีใบงานเด็ก 5 ขวบไหม').topic,'digital_product');assert.equal(classifySalesTurn('อยากเปิดคอร์ส').topic,'course');
const urgent=buildRuleSalesInsight([{role:'user',content:'จ่ายแล้วแต่เข้าเรียนไม่ได้'}]);assert.equal(urgent.stage,'follow_up');assert.match(urgent.next_action,/เจ้าหน้าที่/);assert.match(urgent.suggested_reply,/ส่งต่อ/);
const course=buildRuleSalesInsight([{role:'user',content:'เปิดคอร์สราคาเท่าไหร่'}]);assert.match(course.intent,/คอร์ส/);assert.match(course.suggested_reply,/กี่คอร์ส/);
assert.match(salesPlaybookPrompt(),/ถามคำถามคัดกรองเพียงหนึ่งข้อ/);assert.match(captionKnowledgePrompt(['เริ่มขายคอร์สได้แล้ว']),/ห้ามถือว่าราคา\/โปรเก่ายังใช้ได้/);
for(const token of['loadV12PageCaptions','captionKnowledgePrompt','page_knowledge','SALES_PLAYBOOK_VERSION'])assert.ok(assistant.includes(token),token);
for(const token of['classifySalesTurn','needs_human',"mode='human'",'salesPlaybookPrompt','captionKnowledgePrompt'])assert.ok(line.includes(token),token);
for(const token of['/posts?','fields:\'id,message,created_time\'','authorization:`Bearer ${token}`','META_CAPTIONS_'])assert.ok(captions.includes(token),token);
assert.doesNotMatch(captions,/return \{[^}]*token/);console.log('v0.14.251 VisionD sales playbook and Meta caption knowledge: PASS');
