import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.332');
assert.match(read('public/index.html'),/WEB v0\.14\.332/);
assert.match(read('public/admin.html'),/ADMIN v0\.14\.332/);
const html=read('public/course-basket-edit.html'),js=read('public/course-basket-edit.js');
assert.match(html,/วิดีโอ MP4\/WEBM ไม่เกิน 2 GB/);
assert.doesNotMatch(html,/วิดีโอ MP4\/WEBM ไม่เกิน 200 MB/);
assert.match(html,/name="video_quality"/);
assert.match(js,/lesson-video-multipart\/init/);
assert.match(js,/lesson-video-multipart\/part\?/);
assert.match(js,/lesson-video-multipart\/complete/);
assert.match(js,/lesson-video-multipart\/abort/);
assert.match(js,/lessonData\.delete\("video"\)/);
assert.match(js,/file\.slice\(offset, end\)/);
assert.match(js,/2 \* 1024 \* 1024 \* 1024/);
assert.match(read('functions/_course_rules.js'),/MAX_COURSE_VIDEO_BYTES\s*=\s*2 \* 1024 \* 1024 \* 1024/);
assert.match(read('functions/api/course-seller/[id]/lessons.js'),/ไฟล์ประกอบแต่ละไฟล์ต้องไม่เกิน 200 MB/);
console.log('PASS v0.14.332 basket edit uses 2 GB multipart video upload');
