import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.330');
assert.match(read('public/index.html'),/WEB v0\.14\.330/);
assert.match(read('public/admin.html'),/ADMIN v0\.14\.330/);
const active=read('JARVIS-PATCH-PROTOCOL.md'),start=read('START-HERE.md'),history=read('work-history/visiond/protocols/JARVIS-PATCH-PROTOCOL.md');
for(const heading of ['ลำดับอำนาจ','ALWAYS','WHEN-TOUCHING','REFERENCE','Definition of Done'])assert.match(active,new RegExp(heading));
assert.match(active,/กฎถาวร 10 ข้อ/);
assert.match(active,/DISCOVERED/);
assert.match(active,/ห้ามอัปเดต Marketing Plan/);
assert.match(active,/\.pnpm-store/);
assert.ok(active.split(/\r?\n/).length<100,'Active Protocol ต้องสั้นกว่า 100 บรรทัด');
assert.match(start,/กติกา Active: `JARVIS-PATCH-PROTOCOL\.md`/);
assert.match(start,/WHEN-TOUCHING/);
assert.doesNotMatch(start,/กติกาแพต: `work-history\/visiond\/protocols/);
assert.ok(history.length>active.length,'ฉบับละเอียดเดิมต้องยังอยู่เป็น Reference');
assert.match(history,/Guest identity rule/);
assert.match(history,/Course plan single-source rule/);
console.log('PASS v0.14.330 lean active protocol and conditional routing');
