import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.336');
assert.match(read('public/index.html'),/WEB v0\.14\.336/);
assert.match(read('public/admin.html'),/ADMIN v0\.14\.336/);
const map=read('FEATURE-MAP.md'),widget=read('public/elon-chat.js');
for(const token of ['ELON-CHAT-001','functions/api/elon/chat.js','functions/api/elon/public-chat.js','functions/_elon-provider.js','functions/_elon-member-store.js','elon_web_conversations','ELON_MAX_MESSAGE_LENGTH','retention 60 วัน','data-feature="ELON-CHAT-001"']) assert.ok(map.includes(token),token);
assert.match(widget,/root\.dataset\.feature = 'ELON-CHAT-001'/);
assert.match(widget,/const FRONTEND_SURFACES = new Set/);
assert.match(widget,/const chatApi = \(\) => authenticated \? API : PUBLIC_API/);
console.log('PASS v0.14.336 ELON Chat feature map and runtime identifier');
