import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const read=p=>readFile(new URL(`../${p}`,import.meta.url),'utf8');
const [version,index,admin,page,hook,roadmap]=await Promise.all([read('VERSION.txt'),read('public/index.html'),read('public/admin.html'),read('public/v12-connect.html'),read('functions/hooks/v12/facebook.js'),read('VISIOND-ROADMAP.md')]);
assert.equal(version.trim(),'v0.14.199');
assert.match(index,/WEB v0\.14\.199/);
assert.match(admin,/ADMIN v0\.14\.199/);
assert.match(page,/v0\.14\.199/);
assert.match(page,/v=014199/);
assert.doesNotMatch(hook,/ensureDatabase|ensureV12Schema/);
assert.match(hook,/hub\.verify_token/);
assert.match(hook,/decryptChannelValue/);
assert.match(roadmap,/v0\.14\.199[\s\S]*Fast Meta Webhook Verification/);
console.log('v0.14.199 fast Meta webhook verification: PASS');
