import assert from 'node:assert/strict';import fs from 'node:fs';
const read=file=>fs.readFileSync(file,'utf8'),checks=[];const check=(name,fn)=>{try{fn();checks.push(true);console.log(`PASS ${name}`)}catch(error){checks.push(false);console.error(`FAIL ${name}: ${error.message}`)}};
check('version',()=>{const match=read('VERSION.txt').trim().match(/^v0\.14\.(\d+)$/);assert.ok(match&&Number(match[1])>=65)});
check('one key one shop database rule',()=>{const sql=read('migrations/0027_veasy_shop_binding.sql');assert.match(sql,/license_id TEXT NOT NULL UNIQUE/);assert.match(sql,/FOREIGN KEY\(license_id\)/)});
check('one page one shop database rule',()=>assert.match(read('migrations/0027_veasy_shop_binding.sql'),/meta_page_id TEXT NOT NULL UNIQUE/));
check('complete owner chain index',()=>assert.match(read('migrations/0027_veasy_shop_binding.sql'),/\(id,user_id,license_id,meta_page_id\)/));
check('binding requires VisionD session',()=>assert.match(read('functions/api/vision7/shops/bind.js'),/requireVision7User/));
check('license lookup scoped to owner and V Easy',()=>{const core=read('functions/_veasy_shop.js');assert.match(core,/l\.key_hash=\? AND l\.user_id=\?/);assert.match(core,/p\.platform_type='veasy'/)});
check('second shop is blocked',()=>{const api=read('functions/api/vision7/shops/bind.js');assert.match(api,/VEASY_KEY_ALREADY_BOUND/);assert.match(api,/ร้านที่สอง/)});
check('page reuse is blocked',()=>assert.match(read('functions/api/vision7/shops/bind.js'),/VEASY_PAGE_ALREADY_BOUND/));
check('binding uses atomic D1 batch',()=>{const api=read('functions/api/vision7/shops/bind.js');assert.match(api,/DB\.batch/);assert.match(api,/binding_state='bound'/);assert.match(api,/binding_state='unbound'/)});
check('idempotent same binding',()=>{const api=read('functions/api/vision7/shops/bind.js');assert.match(api,/already_bound:true/);assert.match(api,/existing\.meta_page_id===pageId/)});
check('shop list scoped to session owner',()=>{const api=read('functions/api/vision7/shops/index.js');assert.match(api,/s\.user_id=\?/);assert.match(api,/l\.user_id=s\.user_id/)});
check('only shop requirements closed',()=>{const historical=JSON.parse(read('requirements-history/v0.14.65.json'));assert.equal(historical.requirements.find(x=>x.id==='VE-LICENSE-001').status,'DONE-VERIFIED');assert.equal(historical.requirements.find(x=>x.id==='VE-SHOP-001').status,'DONE-VERIFIED');assert.equal(historical.requirements.find(x=>x.id==='VE-RUNTIME-001').status,'PENDING')});
check('migration sequence',()=>{const files=fs.readdirSync('migrations').filter(x=>/^\d{4}_.*\.sql$/.test(x)).sort();assert.ok(Number(files.at(-1).slice(0,4))>=27)});
const failed=checks.filter(x=>!x).length;console.log(`v0.14.65 RESULT: total=${checks.length} passed=${checks.length-failed} failed=${failed}`);if(failed)process.exit(1);
