import assert from 'node:assert/strict';import fs from 'node:fs';
const read=file=>fs.readFileSync(file,'utf8'),checks=[];const check=(name,fn)=>{try{fn();checks.push(true);console.log(`PASS ${name}`)}catch(error){checks.push(false);console.error(`FAIL ${name}: ${error.message}`)}};
check('version',()=>{const match=read('VERSION.txt').trim().match(/^v0\.14\.(\d+)$/);assert.ok(match&&Number(match[1])>=66)});
check('one runtime per shop',()=>{const sql=read('migrations/0028_veasy_runtime_guards.sql');assert.match(sql,/veasy_runtime_leases/);assert.match(sql,/shop_id TEXT PRIMARY KEY/)});
check('one worker per conversation',()=>{const sql=read('migrations/0028_veasy_runtime_guards.sql');assert.match(sql,/veasy_conversation_leases/);assert.match(sql,/PRIMARY KEY\(shop_id,conversation_id\)/)});
check('lease tokens stored hashed',()=>{const core=read('functions/_veasy_runtime.js');assert.match(core,/hash=await sha256\(raw\)/);assert.match(core,/lease_token_hash/);assert.doesNotMatch(read('migrations/0028_veasy_runtime_guards.sql'),/lease_token TEXT/)});
check('expired runtime can be reclaimed',()=>assert.match(read('functions/_veasy_runtime.js'),/DELETE FROM veasy_runtime_leases WHERE shop_id=\? AND expires_at<=CURRENT_TIMESTAMP/));
check('second machine blocked',()=>assert.match(read('functions/_veasy_runtime.js'),/VEASY_SHOP_ALREADY_RUNNING/));
check('lease session and device scoped',()=>{const core=read('functions/_veasy_runtime.js');assert.match(core,/r\.app_session_id=\?/);assert.match(core,/r\.device_hash=\?/)});
check('conversation requires active runtime',()=>{const core=read('functions/_veasy_runtime.js');assert.match(core,/JOIN veasy_runtime_leases r/);assert.match(core,/r\.expires_at>CURRENT_TIMESTAMP/)});
check('message idempotency primary key',()=>assert.match(read('migrations/0028_veasy_runtime_guards.sql'),/PRIMARY KEY\(shop_id,platform_message_id\)/));
check('order idempotency primary key',()=>assert.match(read('migrations/0028_veasy_runtime_guards.sql'),/PRIMARY KEY\(shop_id,idempotency_key\)/));
check('message claim requires conversation lease',()=>{const api=read('functions/api/vision7/runtime/message-claim.js');assert.match(api,/verifyConversationLease/);assert.match(api,/INSERT OR IGNORE INTO veasy_message_claims/);assert.match(api,/duplicate:true/)});
check('order claim requires conversation lease',()=>{const api=read('functions/api/vision7/runtime/order-claim.js');assert.match(api,/verifyConversationLease/);assert.match(api,/INSERT OR IGNORE INTO veasy_order_claims/);assert.match(api,/duplicate:true/)});
check('account switch context',()=>{const api=read('functions/api/vision7/auth/context.js');assert.match(api,/account_scope_id/);assert.match(api,/clear_local_state_when_scope_changes:true/);assert.match(api,/WHERE user_id=\?/)});
check('logout clears local scopes',()=>{const api=read('functions/api/vision7/auth/logout.js');assert.match(api,/clear_local_state:true/);assert.match(api,/conversation/);assert.match(api,/orders/)});
check('all V Easy requirements verified',()=>{const ledger=JSON.parse(read('requirements-ledger.json'));for(const id of ['VE-KEYCENTER-001','VE-AUTH-001','VE-LICENSE-001','VE-SHOP-001','VE-RUNTIME-001','VE-IDEMPOTENCY-001','VE-ISOLATION-001'])assert.equal(ledger.requirements.find(x=>x.id===id).status,'DONE-VERIFIED')});
check('migration sequence',()=>{const files=fs.readdirSync('migrations').filter(x=>/^\d{4}_.*\.sql$/.test(x)).sort();assert.ok(Number(files.at(-1).slice(0,4))>=28)});
const failed=checks.filter(x=>!x).length;console.log(`v0.14.66 RESULT: total=${checks.length} passed=${checks.length-failed} failed=${failed}`);if(failed)process.exit(1);
