import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {decryptPartnerData,encryptPartnerData} from '../functions/_partner_crypto.js';
import {cleanScopes} from '../functions/_partner_api.js';
import {cleanId,forbiddenDataPath,idempotencyKey,payloadHash} from '../functions/_partner_sync.js';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const paths=['VERSION.txt','public/index.html','public/admin.html','public/partner-api.html','public/partner-api.js','public/partner-api.css','functions/api/partner/v1/customers/sync.js','functions/api/partner/v1/orders/sync.js','functions/api/admin/partner-websites/[id]/data.js','migrations/0047_partner_customer_sales_sync.sql','VISIOND-PARTNER-API-PROTOCOL.md','VISIOND-ROADMAP.md'];
const [version,index,admin,page,ui,css,customers,orders,adminData,migration,protocol,roadmap]=await Promise.all(paths.map(read));
assert.equal(version.trim(),'v0.14.216');assert.match(index,/WEB v0\.14\.216/);assert.match(admin,/ADMIN v0\.14\.216/);assert.match(page,/v0\.14\.216/);
assert.deepEqual(cleanScopes(['products:read','customers:write','orders:write','bad']),['products:read','customers:write','orders:write']);
const env={VISIOND_PARTNER_ENCRYPTION_KEY:'test-only-partner-key-32-bytes-minimum-12345'},profile=JSON.stringify({name:'ลูกค้าทดสอบ',email:'test@example.com'}),cipher=await encryptPartnerData(env,profile);assert.match(cipher,/^vdpd1:/);assert.equal(await decryptPartnerData(env,cipher),profile);assert.equal(cipher.includes('test@example.com'),false);
for(const field of['password','access_token','refresh_token','api_key','client_secret','card_number','cvv','bank_account','iban'])assert.ok(forbiddenDataPath({nested:{[field]:'forbidden'}}),field);assert.equal(forbiddenDataPath({external_customer_id:'CUS-1',payment_status:'paid'}),'');
assert.equal(await payloadHash({b:2,a:{d:4,c:3}}),await payloadHash({a:{c:3,d:4},b:2}));assert.notEqual(await payloadHash({a:1}),await payloadHash({a:2}));assert.equal(cleanId('ORDER-001'),'ORDER-001');assert.equal(cleanId('bad id'),'');
assert.equal(idempotencyKey(new Request('https://test.invalid',{headers:{'Idempotency-Key':'order-0001'}})),'order-0001');assert.equal(idempotencyKey(new Request('https://test.invalid')),'');
for(const token of['partner_customers','partner_orders','partner_order_items','partner_refunds','partner_idempotency','UNIQUE(website_id,external_customer_id)','UNIQUE(website_id,external_order_id)','PRIMARY KEY(website_id,idempotency_key)'])assert.ok(migration.includes(token),token);
for(const token of["requirePartnerScope(ctx,'customers:write')",'IDEMPOTENCY_KEY_REQUIRED','FORBIDDEN_SENSITIVE_FIELD','encryptPartnerData','external_customer_id'])assert.ok(customers.includes(token),token);
for(const token of["requirePartnerScope(ctx,'orders:write')",'IDEMPOTENCY_KEY_REQUIRED','ORDER_STATUS_TRANSITION_INVALID','REFUND_EXCEEDS_ORDER_TOTAL','ORDER_SUBTOTAL_MISMATCH','external_order_id','external_refund_id'])assert.ok(orders.includes(token),token);
for(const source of[customers,orders])assert.ok(source.indexOf('forbiddenDataPath(body)')<source.indexOf('ctx.env.DB.batch'), 'reject forbidden data before writes');
assert.match(adminData,/requireBoss/);assert.match(adminData,/decryptPartnerData/);assert.doesNotMatch(adminData,/profile_ciphertext:row/);
for(const token of['customers:write','orders:write','ดูลูกค้าและยอดขาย','ลูกค้าล่าสุด','ออเดอร์ล่าสุด'])assert.ok((page+ui).includes(token),token);assert.match(css,/partner-table/);assert.match(css,/@media\(max-width:700px\)/);
for(const token of['Idempotency-Key','External ID','ห้ามรับหรือเก็บ','AES-GCM','ศูนย์ควบคุมเว็บพาร์ทเนอร์'])assert.ok(protocol.includes(token),token);assert.match(roadmap,/Partner API Phase 2 Customer and Sales Sync/);
console.log('v0.14.216 Partner API phase 2 customer order sales payment cancellation refund idempotency security: PASS');
