import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{COURSE_PLANS,courseRevenue}from'../functions/_course_plans.js';
const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
assert.deepEqual(Object.values(COURSE_PLANS).sort((a,b)=>a.number-b.number).map(x=>[x.number,x.code]),[[1,'rights'],[2,'free'],[3,'partner']]);
assert.equal(COURSE_PLANS.free.maxCourses,3);assert.equal(COURSE_PLANS.free.maxEpisodes,5);assert.equal(COURSE_PLANS.partner.paymentOwner,'visiond');
assert.deepEqual(courseRevenue('partner',99900),{teacher:49850,visiond:49950,apiFee:100});assert.deepEqual(courseRevenue('rights',49900),{teacher:49900,visiond:0,apiFee:0});
const [version,index,admin,html,seller,api,lessons,publish,orders,slip,schema]=await Promise.all(['VERSION.txt','public/index.html','public/admin.html','public/course-seller.html','public/course-seller.js','functions/api/course-seller/index.js','functions/api/course-seller/[id]/lessons.js','functions/api/course-seller/[id]/publish.js','functions/api/orders/index.js','functions/api/orders/[id]/slip.js','functions/_schema.js'].map(read));
assert.ok(Number(version.trim().split('.').pop())>=252);assert.match(index,/WEB v0\.14\.\d+/);assert.match(admin,/ADMIN v0\.14\.\d+/);
for(const token of['1 · ซื้อสิทธิ์ 499 บาท','2 · เริ่มขายฟรี','3 · พาร์ตเนอร์ 50/50'])assert.ok(html.includes(token),token);
assert.ok(seller.indexOf('1 · ซื้อสิทธิ์')<seller.indexOf('2 · เริ่มขายฟรี'));assert.ok(seller.indexOf('2 · เริ่มขายฟรี')<seller.indexOf('3 · พาร์ตเนอร์ 50/50'));
for(const token of["course_plan","free_course_count","selectedPlan.requiresCredit","selectedPlan.maxCourses"])assert.ok(api.includes(token),token);
assert.match(lessons,/เริ่มขายฟรี เพิ่มได้ไม่เกิน 5 EP/);assert.match(publish,/course\.course_plan!=='partner'/);assert.match(orders,/courseRevenue/);assert.match(orders,/partnerCourse/);assert.match(slip,/partnerCourse/);assert.match(schema,/teacher_revenue/);
assert.match(api,/CASE WHEN o\.course_plan='partner' THEN o\.teacher_revenue ELSE o\.total END/);assert.match(slip,/PARTNER_BOSS_REVIEW/);
console.log('v0.14.252 course plans: PASS');
