import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=path=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.293');
const html=read('public/course-center.html');
const ui=read('public/course-center.js');
const api=read('functions/api/course-seller/sales.js');
assert.match(html,/id="ownedCourseList"/);
assert.match(html,/id="courseSalesFilter"/);
assert.match(html,/ย้อนหลังได้อิสระ ครั้งละไม่เกิน 60 วัน/);
assert.match(ui,/\/course-basket-edit\?id=/);
assert.match(ui,/fetch\("\/api\/course-seller", \{ cache: "no-store" \}\)/);
assert.match(ui,/ต้องแก้ไขและส่งตรวจใหม่/);
assert.match(ui,/\/api\/course-seller\/sales\?/);
assert.match(ui,/สมาชิกที่ซื้อ/);
assert.match(api,/course_owner_user_id=\?/);
assert.match(api,/o\.status='paid'/);
assert.match(api,/days > 60/);
assert.match(api,/date\(o\.updated_at,'\+7 hours'\) BETWEEN \? AND \?/);
assert.match(api,/COUNT\(DISTINCT o\.user_id\) buyers/);
assert.doesNotMatch(api,/u\.email|u\.phone|password|token/i);
console.log('v0.14.293 course sales dashboard and owned baskets: PASS');
