import assert from "node:assert/strict";
import fs from "node:fs";
const read=(file)=>fs.readFileSync(file,"utf8");
const version=read("VERSION.txt").trim();
const html=read("public/course-seller.html");
const js=read("public/course-seller.js");
const css=read("public/course-seller.css");
const api=read("functions/api/courses/index.js");
const courses=read("public/courses.js");
const home=read("public/home-course-catalog.js");
const detail=read("public/course-detail.js");
assert.equal(version,"v0.14.275");
assert.match(html,/name="course_plan" type="hidden" value="rights"/);
assert.doesNotMatch(html,/<select name="course_plan"/);
assert.doesNotMatch(html,/<option value="free">/);
assert.match(js,/const planPanels = new Set/);
assert.match(js,/if \(!planPanels\.has\(section\)\) section\.remove\(\)/);
for(const label of ["ตรวจเครดิต","ข้อมูลคอร์ส","เนื้อหา EP","ตั้งค่ารับเงิน","ตรวจสลิป","ตรวจความพร้อม","ส่งตรวจ"]) assert.ok(js.includes(label),label);
for(const step of ['sellerLessonManager.dataset.step = "3"','paymentProfilePanel.dataset.step = "4"','slipApiPanel.dataset.step = "5"','publishPanel.dataset.step = "7"']) assert.ok(js.includes(step),step);
assert.match(css,/\.course-rights-stepper/);
assert.match(css,/\.course-rights-readiness/);
assert.match(api,/c\.course_plan/);
for(const source of [courses,home,detail]) {
  assert.match(source,/course-plan-public/);
  assert.match(source,/แบบ 1 · ผู้สอนรับ 100%/);
  assert.match(source,/แบบ 2 · เริ่มขายฟรี/);
  assert.match(source,/แบบ 3 · พาร์ตเนอร์ 50\/50/);
}
assert.doesNotMatch(js,/499 บท/);
console.log("v0.14.275 course plan 1 seven-step page and public plan badges: PASS");
