import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=(path)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
assert.equal(read('VERSION.txt').trim(),'v0.14.288');
const rules=read('functions/_course_rules.js');
assert.match(rules,/MIN_COURSE_PRICE_BAHT = 499/);
assert.match(rules,/MAX_COURSE_VIDEO_BYTES = 2 \* 1024 \* 1024 \* 1024/);
assert.match(rules,/COURSE_VIDEO_CHUNK_BYTES = 25 \* 1024 \* 1024/);
for(const file of ['functions/api/course-seller/index.js','functions/api/course-seller/[id].js','functions/api/course-seller/[id]/publish.js'])assert.match(read(file),/MIN_COURSE_PRICE_SATANG/);
const html=read('public/course-seller.html');
assert.equal((html.match(/min="499"/g)||[]).length,2);
assert.match(html,/สูงสุด 2 GB/);
assert.match(html,/name="video_quality"/);
const client=read('public/course-seller.js');
assert.match(client,/async function uploadLessonVideo/);
assert.match(client,/lesson-video-multipart\/init/);
assert.match(client,/lesson-video-multipart\/part/);
assert.match(client,/lesson-video-multipart\/complete/);
assert.match(client,/video_upload_pending/);
for(const endpoint of ['init','part','complete','abort'])assert.match(read(`functions/api/course-seller/[id]/lesson-video-multipart/${endpoint}.js`),/requireUser/);
console.log('v0.14.288 large course upload and minimum price contracts: PASS');
